### ISSUE TITLE
Android high battery consumption

### ISSUE THREAD

**Issue by ochakov** [christocracy/cordova-plugin-background-geolocation#100]
Hi,

I have implemented the plugin in an app running on both iOS and Android. While iOS performs very well, on Android I always see very high battery usage when the location tracking is enabled. It is mostly noticeable inside a building (no GPS), as it tries to get GPS coordinates for about 60 seconds each time. BTW, no reporting is performed inside a building (event not coarse).
I would suggest adding options for less accurate location tracking, using low power and low accuracy. Also, location detection timeout can be decreased and add getting coarse location if GPS not found within X seconds.

Thanks and great job!

**Comment by christocracy** [comment]
Android refactored in Premium Version.  Battery performance has been vastly improved.

http://christocracy.github.io/cordova-background-geolocation/
