### ISSUE TITLE
window.plugins.backgroundGeoLocation Not found

### ISSUE THREAD

**Issue by digitalhuman** [christocracy/cordova-plugin-background-geolocation#102]
Hi,

i just installed this plugin, that went well. But when i start the app i check:
//Background geoLoaction
if(window.plugins && window.plugins.backgroundGeoLocation){
    var bgGeo = window.plugins.backgroundGeoLocation;
}else{
alert('Not found');
}

I get 'Not Found' alert.......... do i need to include some JS files or what?

**Comment by Microzone** [comment]
Hello Chris, can i please have your email
