### ISSUE TITLE
Android?

### ISSUE THREAD

**Issue by countrdd** [christocracy/cordova-plugin-background-geolocation#104]
What is teh format that is sent to the server and can be be customized? 

My server looks for this format and names
{
              "device_id": uuid,
              "username": user._id,
              "loc": {
                  "type": "Point",
                  "coordinates": [coords.longitude, coords.latitude]
              },
              "speed": coords.speed,
              "accuracy": coords.accuracy,
              "heading": coords.heading

```
      }
```

**Comment by christocracy** [comment]
Android refactored, FYI
http://christocracy.github.io/cordova-background-geolocation/

- No more in-plugin HTTP -- calls your javascript callback now, just like ios.
- Vastly improved battery performance.
