### ISSUE TITLE
changePace function visibility

### ISSUE THREAD

**Issue by geezmo** [christocracy/cordova-plugin-background-geolocation#107]
Hello Chris, and thanks for your terrific work on this plugin - it really helped me a lot.

The function changePace(...) is a precious one. In my case (but i'm pretty sure it's a common issue) starting the background tracking and then wait indeterminately for a cell switch was simply unacceptable, although when out of the stationary circle the plugin worked great. I needed to force the "moving" state, and when i stumbled upon that function in the source code i thought "it can't be so easy". But it was. So, my question is: why that function is not even mentioned in the doc? It could be really helpful, imho.

**Comment by christocracy** [comment]
Android now has ```#changePace``` in Premium Version
http://christocracy.github.io/cordova-background-geolocation/
