### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by KyleBrost** [christocracy/cordova-plugin-background-geolocation#108]
Hello,

I'm having troubles with the application and making it work.  I have programmed it to AJAX POST the reported location off to a server and save it in a database.  When the app first starts up the background process it posts the data.  When I put the app into background mode, it updates once.  I then drive around 1.5 km and it sends no more updates.  I have played with the configuration but I can't seem to get it to report changes in location when in background mode.

These are my configuration options.

```
                desiredAccuracy: 10,
                activityType: "AutomotiveNavigation",
                debug: true
```

I am using an iPhone IOS7.1.  Can someone offer some insight in how I can test the background feature within my small house?  Is there additional debug info besides the noise notifications?

Thanks!

**Comment by sandipishi** [comment]
i have same issue my code is

configureBackgroundGeoLocation: function() {
			// alert("configureBackgroundGeoLocation")
			/**
			* This would be your own callback for Ajax-requests after POSTing background geolocation to your server.
			*/
			// var yourAjaxCallback = function(response) {
				// backgroundGeoLocation.finish();
			// };
			$scope.FromDate = $rootScope.getDateTime();	
			
			/**
			   This is background-geolocation function start call
			*/
			var callbackFn = function(location) {
				
			var dateforinsert = $rootScope.getDateTime();
				var formData = {authToken:"aa56493sAafazxhaseafaovnappvaneioj",createdAt:$rootScope.getDateTime(),lat:location.latitude,lon:location.longitude};	
					console.log(formData)
					
					
					$.ajax({
						url: "http://---IP address----/geoloc/save",
						dataType: 'json',
						type: "GET",
						crossDomain: true,
						data:formData,
						success: function(data){
							console.log(data);
							console.log(data['status'])
						},
						error: function(err){
							console.log(err);
						}
					});
					
					
					$rootScope.db.transaction(function(tx){
						tx.executeSql("INSERT INTO Tbl_BackgroundGeolocation(latitude, longitude,Created_Date) VALUES (?,?,?)",[location.latitude,location.longitude,dateforinsert],function(tx,res){
							
						});
					});	
					
					
				
			};

			var failureFn = function(err) {
				// window.alert('BackgroundGeoLocation err: ' + JSON.stringify(err));
				console.log('BackgroundGeoLocation err: ' + JSON.stringify(err));
			};
			
			// BackgroundGeoLocation is highly configurable with location provider.
			backgroundGeoLocation.configure(callbackFn, failureFn, {
				desiredAccuracy: 10,
				stationaryRadius: 10,
				distanceFilter: 30,
				debug: true, //  enable this hear sounds for background-geolocation life-cycle.
				stopOnTerminate: false
		});
			
			// Turn ON the background-geolocation system.  The user will be tracked whenever they suspend the app.
			var settings = ENV.settings;

			if (settings.enabled == 'true') {
				app.startTracking();
				if (settings.aggressive == 'true') {
					backgroundGeoLocation.changePace(true);
				}
			}
		}

**Comment by christocracy** [comment]
Please see the README of this repo for important announcement of this plugin.
