### ISSUE TITLE
Android Location Info

### ISSUE THREAD

**Issue by lkaragol** [christocracy/cordova-plugin-background-geolocation#117]
I understand that "url" in "configure" function is being called and "params" posted to server for Android. "callbackFn" function with location param is never called on Android. I can pass custom info with params to my server. But at the moment, how can I know what the current location is? There is no "location" variable at this moment?

bgGeo.configure(callbackFn, failureFn, {
        url: 'http://www.xyz.com/',
        params: {
            foo: 'bar',
            currentLocation: ???
        },
        desiredAccuracy: 10,
        stationaryRadius: 20,
        distanceFilter: 30,
        debug: true
    });

**Comment by lkaragol** [comment]
Thank you.

**Comment by christocracy** [comment]
Android refactored in Premium Version -- Android now calls your javascript callback, just like iOS (along with significant battery performance improvement)

http://christocracy.github.io/cordova-background-geolocation/
