### ISSUE TITLE
Make a POST request to REST api to submit data with android app

### ISSUE THREAD

**Issue by stoskoverflowcomunity** [christocracy/cordova-plugin-background-geolocation#120]
I have REST api on backend created with php (slim php micro framework). So code is: INDEX.php

`$app->post('/coords', 'authenticate', function() use ($app) {
            $response = array();
            //$jsonData = $app->request->post('podaci');
            $jsonData = @file_get_contents('php://input');

$aData = json_decode($jsonData);
$latitude = $aData->location->latitude;
$longitude = $aData->location->longitude;

$podaci = $latitude.' ddd '.$longitude;

            global $user_id;
            $db = new DbHandler();

            // creating new task
            $coords_id = $db->createCoords($user_id, $podaci);

            if ($coords_id != NULL) {
                $response["error"] = false;
                $response["message"] = "Coords insert successfully";

                echoRespnse(201, $response);
            } else {
                $response["error"] = true;
                $response["message"] = "Coords not inserted";
                echoRespnse(200, $response);
            }            
        });`
I also have DBhandler file , code (function createCoords):

public function createCoords($user_id, $podaci) {
        $stmt = $this->conn->prepare("INSERT INTO coords(podaci) VALUES(?)");
        $stmt->bind_param("s", $podaci);
        $result = $stmt->execute();
        $stmt->close();

    }
I try this REST api with sample data with ajax request and work well, but now I need to POST data from phonegap app to server and I write:

// BackgroundGeoLocation is highly configurable.
        bgGeo.configure(callbackFn, failureFn, {
            url: 'http://agroagro.com/agroMobile/v1/coords', // <-- Android ONLY:  your server url to send locations to
            params: {
                Auth: 'df6017abde2d2re560896b63a0ee1039',    //  <-- Android ONLY:  HTTP POST params sent to your server when persisting locations.
                foo: 'bar'                              //  <-- Android ONLY:  HTTP POST params sent to your server when persisting locations.
            },
            desiredAccuracy: 0,
            stationaryRadius: 50,
            distanceFilter: 50,
            notificationTitle: 'Background tracking', // <-- android only, customize the title of the notification
            notificationText: 'ENABLED', // <-- android only, customize the text of the notification
            activityType: 'AutomotiveNavigation',
            debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
            stopOnTerminate: false // <-- enable this to clear background location settings when the app terminates
        });
I read here how to make php file to get INPUT data: https://github.com/christocracy/cordova-plugin-background-geolocation/issues/79

as you can see from my index.php code I write everything fine but what can be problem? This just dont work when I test on my android phone.

**Comment by LuisMRibeiro** [comment]
@stoskoverflowcomunity it would be nice if you could share the solution.

**Comment by christocracy** [comment]
Android has been refactored.
- plugin no longer handles http; calls js callback (just like ios)
- much improved battery efficiency.
- no more foreground service

http://christocracy.github.io/cordova-background-geolocation/

**Comment by firaskudsy** [comment]
"plugin no longer handles http; calls js callback (just like ios)" is this for the free vesion ?

**Comment by christocracy** [comment]
No.  That's a statement about the Premium Version.  However, that statement is dated; I reimplemented an optional HTTP layer for both iOS & Android.
