### ISSUE TITLE
Location to Restful backend 

### ISSUE THREAD

**Issue by SiddharthaRRamesh** [christocracy/cordova-plugin-background-geolocation#127]
The calls to backend URL is successful.  But how do I obtain the `location` json in the backend. We use java for backend. 

Consider this php example : 
```php
<?php
	$data = file_get_contents('php://input');
	echo $data;
        echo JSON_decode($data, true);
?>
```
This file is hosted at : http://www.madzz.co.in/loc.php

the url in my options is set the the above value. 

Can someone please help me how do I obtain the location json posted to this url. When I run my app I do get all the beep sounds and toast notifications.

**Comment by SiddharthaRRamesh** [comment]
Any answers for this?

**Comment by christocracy** [comment]
You could try inspecting the raw http request to observe the nature of the
data sent.

Since you understand Java, you should have no problem understanding the
nature of the HTTP POST.

https://github.com/christocracy/cordova-plugin-background-geolocation/blob/master/src/android/LocationUpdateService.java#L654

The entire request body IS the JSON.

http://stackoverflow.com/questions/5999359/how-to-add-json-to-the-body-of-an-http-post-in-java

On Tue, Jan 13, 2015 at 12:16 AM, SiddharthaRRamesh <
notifications@github.com> wrote:

> Any answers for this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/127#issuecomment-69696821>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by SiddharthaRRamesh** [comment]
So, what you are saying is whenever the app makes that beep sounds, it will add the json to the body of the url listed?

**Comment by christocracy** [comment]
An url does not have a body.

An HTTP Request HAS_A body.
An HTTP Request HAS_A url.

when you hear beep, that means “I recorded a GeoLocation” and stored the
location in a Queue within plugin.

If your device happens to have a network connection at that point in time,
the Queue will be synced to your configured url, one location-at-a-time.

The nature of the HTTP POST is Content-Type: application/json

Why don’t you keep an eye on the request log of your HTTP server and see
the exact data it receives?

On Tue, Jan 13, 2015 at 12:36 AM, SiddharthaRRamesh <
notifications@github.com> wrote:

> So, what you are saying is whenever the app makes that beep sounds, it
> will add the json to the body of the url listed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/127#issuecomment-69697995>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by SiddharthaRRamesh** [comment]
I know that I typed it in the wrong way I guess !
I am looking at the log, all it does it log the url that the application calls. Thats it. 
So the request which is a post request is being sent. But I am not able to get any data from the request body. Why is that happening?

**Comment by christocracy** [comment]
Your question is “In Java, how do retrieve the raw JSON body of an HTTP
response”.

The data is there, it’s up to you fetch it.  I’m not concerned with how any
particular platform retrieves the data data, be it PHP, Java, C# or Ruby.

On Tue, Jan 13, 2015 at 12:59 AM, SiddharthaRRamesh <
notifications@github.com> wrote:

> I know that I typed it in the wrong way I guess !
> I am looking at the log, all it does it log the url that the application
> calls. Thats it.
> So the request which is a post request is being sent. But I am not able to
> get any data from the request body. Why is that happening?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/127#issuecomment-69699371>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by SiddharthaRRamesh** [comment]
Ok! Calm  down.

**Comment by christocracy** [comment]
I’m calm as a clam.

On Tue, Jan 13, 2015 at 1:07 AM, SiddharthaRRamesh <notifications@github.com
> wrote:

> Ok! Calm down.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/127#issuecomment-69699813>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by SiddharthaRRamesh** [comment]
Ok i figured it out. Thanks for your guidance.

**Comment by christocracy** [comment]
Android has been refactored.
- significant improvement to battery performance.
- plugin no longer does HTTP -- calls javascript callback, just like ios.

http://christocracy.github.io/cordova-background-geolocation/
