### ISSUE TITLE
Android changePace()

### ISSUE THREAD

**Issue by geezmo** [christocracy/cordova-plugin-background-geolocation#128]
Hello Chris,
is anyway possible for me to force the plugin in moving mode on Android? I need my app to immediately entering moving mode when put in background - on iOs i can use changePace() (which i documented some weeks ago in the README file), but i know this is an ios only feature. Is there any way to achieve this on Android without modifying the code?
Thanks again for you work. :-)

**Comment by christocracy** [comment]
Shouldn't be difficult to do with Android.  I haven't touched Android code
in months though.

On Friday, January 16, 2015, Alberto Pirovano <notifications@github.com>
wrote:

> Hello Chris,
> is anyway possible for me to force the plugin in moving mode on Android? I
> need my app to immediately entering moving mode when put in background - on
> iOs i can use changePace() (which i documented some weeks ago in README),
> but i know this is an ios only feature. Is there any way to achieve this on
> Android without modifying the code?
> Thanks again for you work. :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/128>
> .
>


-- 
Snet from Gmail Mobile

**Comment by geezmo** [comment]
Yes, i was just wondering if there was something undocumented. I'll implement that. Thank you.

**Comment by geezmo** [comment]
I wrote the code today for the Android changePace() - i'm doing some testing, after which i'll make the pull request. Everything seems to work, but I have a couple of questions:

1. Is there any particular reason why you chose to extend the Service class and not IntentService?
2. I used the same Intent object you used for starting the background service in the BackgroundGpsPlugin execute() function. The onStartCommand() hook inside the activity hosts the logic which recognize the 2 differents Intent objects and acts accordingly. I'm not an Android guru, and this seemed to me the most reasonable way to communicate with the running service. In case there was another better way to accomplish the same thing please let me know. :-)

I do apologize if I wasn't able to explain clearly, just wanted your opinion before opening a pull request.

**Comment by christocracy** [comment]
Android has been refactored.
- plugin no longer handles http; calls js callback (just like ios)
- much improved battery efficiency.
- no more foreground service

http://christocracy.github.io/cordova-background-geolocation/
