### ISSUE TITLE
Android / IOS Different Foreground Behavior

### ISSUE THREAD

**Issue by lkaragol** [christocracy/cordova-plugin-background-geolocation#129]
I know, this is an background geoocation plugin and it works only in background mode. I can perform any operation with standard cordova geolocation platform in foreground mode, that's ok.

But I realized that Android continues to call the bgGeo.url in foreground mode but IOS not. Is this a bug? Or is there any option to disable Android foreground calls?

**Comment by christocracy** [comment]
Android has been refactored.
- plugin no longer handles http; calls js callback (just like ios)
- much improved battery efficiency.
- no more foreground service

http://christocracy.github.io/cordova-background-geolocation/
