### ISSUE TITLE
IllegalstateException

### ISSUE THREAD

**Issue by bardiakhosravi** [christocracy/cordova-plugin-background-geolocation#13]
Hi,

Thank you for this library. I was about to write one myself but then I found this library.

I am getting this exception, which I assume it is because I have not set a url: 

03-30 12:04:10.323: W/LocationUpdateService(13978): Exception posting location: java.lang.IllegalStateException: Target host must not be null, or set in parameters. scheme=null, host=null, path=BackgroundGeoLocation_url

how can I disable saving the location? I just like to receive the data for now and analyze it before sending it. Is that the purpose of the url parameter?

This is my configuration:

```
    bgGeo.configure(function() {
        console.log("bgGeo configure success");
    }, function() {
        console.log("bgGeo configure failure");
    }, {
        desiredAccuracy: 50,
        stationaryRadius: 0,
        distanceFilter: 0,
        debug: true // <-- enable this hear sounds for background-geolocation life-cycle.
    });
```

Thanks

**Comment by christocracy** [comment]
FYI Android has been completely refactored
- No more in-plugin HTTP -- plugin now executes your Javascript callback, just like iOS
- Significantly improved battery performance

http://christocracy.github.io/cordova-background-geolocation/
