### ISSUE TITLE
Geo monitoring foreground service killed when app is closed

### ISSUE THREAD

**Issue by reloaded** [christocracy/cordova-plugin-background-geolocation#130]
I noticed that when the app process is killed via the process manager the foreground service is removed from the android notification drawer. Is there a configuration setting that will allow the foreground service to run even if the main activity is killed?

**Comment by christocracy** [comment]
That's a good question

On Sunday, January 18, 2015, reloaded <notifications@github.com> wrote:

> I noticed that when the app process is killed via the process manager the
> foreground service is removed from the android notification drawer. Is
> there a configuration setting that will allow the foreground service to run
> even if the main activity is killed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/130>
> .
>


-- 
Snet from Gmail Mobile

**Comment by reloaded** [comment]
So is this something you're going to look into?

**Comment by christocracy** [comment]
I haven’t been inside the Android code in months, way too busy on other
projects.

I accept pull-requests if you care to dive in.

On Sun, Jan 18, 2015 at 11:38 PM, reloaded <notifications@github.com> wrote:

> So is this something you're going to look into?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/130#issuecomment-70445688>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
Android has been refactored.
- plugin no longer handles http; calls js callback (just like ios)
- much improved battery efficiency.
- no more foreground service

http://christocracy.github.io/cordova-background-geolocation/
