### ISSUE TITLE
Updated just one time

### ISSUE THREAD

**Issue by chrigu89** [christocracy/cordova-plugin-background-geolocation#131]
Hello there.

I got some issue and I looked in every topic in found.
My problem is that the app just send's one time the position throguh the URL (Android) - but i get the sound everytime with no update. I thought its of the bgGeo.finish() function, but in the callbackFn which is not loaded in adroid, correct?

So how can i fix this issue?

var callbackFn = function(location) {
	var token = window.localStorage.getItem("final_token");
	$.ajax({
		type: 'GET',
		url: 'MYURL',
		data:  { os: '', token: token, lat: location.latitude, long: location.longitude },
		crossDomain: true,
		cache: false,
		success: function(response) {
		}
	});
	
	console.log('BackgroundGeoLocation success');
	bgGeo.finish();
}

bgGeo.configure(callbackFn, failureFn, {
	url: 'MYURL', // <-- Android ONLY: your server url to send locations to
	params: {
		token: token,
		os: 'test'
	},
	desiredAccuracy: 0,
	stationaryRadius: 50,
	distanceFilter: 50,
	notificationTitle: 'Background tracking', // <-- android only, customize the title of the notification
	notificationText: 'ENABLED', // <-- android only, customize the text of the notification
	activityType: 'AutomotiveNavigation',
	debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
	stopOnTerminate: false // <-- enable this to clear background location settings when the app terminates
});

**Comment by christocracy** [comment]
bgGeo.configure(callbackFn, failureFn, {
url: 'MYURL', // <-- Android ONLY: your server url to send locations to


On Monday, January 19, 2015, chrigu89 <notifications@github.com> wrote:

> Hello there.
>
> I got some issue and I looked in every topic in found.
> My problem is that the app just send's one time the position throguh the
> URL (Android) - but i get the sound everytime with no update. I thought its
> of the bgGeo.finish() function, but in the callbackFn which is not loaded
> in adroid, correct?
>
> So how can i fix this issue?
>
> var callbackFn = function(location) {
> var token = window.localStorage.getItem("final_token");
> $.ajax({
> type: 'GET',
> url: 'MYURL',
> data: { os: '', token: token, lat: location.latitude, long:
> location.longitude },
> crossDomain: true,
> cache: false,
> success: function(response) {
> }
> });
>
> console.log('BackgroundGeoLocation success');
> bgGeo.finish();
>
> }
>
> bgGeo.configure(callbackFn, failureFn, {
> url: 'MYURL', // <-- Android ONLY: your server url to send locations to
> params: {
> token: token,
> os: 'test'
> },
> desiredAccuracy: 0,
> stationaryRadius: 50,
> distanceFilter: 50,
> notificationTitle: 'Background tracking', // <-- android only, customize
> the title of the notification
> notificationText: 'ENABLED', // <-- android only, customize the text of
> the notification
> activityType: 'AutomotiveNavigation',
> debug: true, // <-- enable this hear sounds for background-geolocation
> life-cycle.
> stopOnTerminate: false // <-- enable this to clear background location
> settings when the app terminates
> });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/131>
> .
>


-- 
Snet from Gmail Mobile

**Comment by chrigu89** [comment]
I use the URL correct. The location will be inserted in the database ONE time. After that, nothing more happens.

**Comment by chrigu89** [comment]
Beim iPad zeigt der "Outstanding bg-task was force-killed" an. Kann es damit zusammenhängen?

Lieben Dank!

**Comment by christocracy** [comment]
That is of no consequence.

On Mon, Jan 19, 2015 at 11:37 AM, chrigu89 <notifications@github.com> wrote:

> Beim iPad zeigt der "Outstanding bg-task was force-killed" an. Kann es
> damit zusammenhängen?
>
> Lieben Dank!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/131#issuecomment-70522766>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by chrigu89** [comment]
Hm do you have an idea about just sending one time?
Is my "bgGeo.finish(); correct?

**Comment by christocracy** [comment]
For Android, I would be checking my server /endpoint to ensure it returns
HTTP 200 — if it doesn’t, my plugin will keep the locations stored in an
internal SQLITE db and keep sending & sending & sending to your configured
URL until the server returns 200.

On Mon, Jan 19, 2015 at 11:20 AM, chrigu89 <notifications@github.com> wrote:

> I use the URL correct. The location will be inserted in the database ONE
> time. After that, nothing more happens.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/131#issuecomment-70520031>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
I’m confused:  is your issue with Android or iOS?

On Mon, Jan 19, 2015 at 11:49 AM, chrigu89 <notifications@github.com> wrote:

> Hm do you have an idea about just sending one time?
> Is my "bgGeo.finish(); correct?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/131#issuecomment-70524763>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by chrigu89** [comment]
Its the Android Problem, iOS will be on my todo, after i fixed android.
So i don't end my script with retun false;?
Should i use? exit(header("Status: 200 OK"));

**Comment by christocracy** [comment]
For Android, your HTTP response MUST return 200 or my plugin assumes the
HTTP request failed.

This plugin was designed for a disaster-response application, where users
may not have a network connection, thus, the plugin caches all geolocation
internally and continuously attempts to sync the cache to your configured
URL, until that URL returns 200.

The Javascript #finish method is for ios-only.  You *must* ensure you call
#finish, regardless of whether your Ajax request is success or failure.

On Mon, Jan 19, 2015 at 11:53 AM, chrigu89 <notifications@github.com> wrote:

> Its the Android Problem, iOS will be on my todo, after i fixed android.
> So i don't end my script with retun false;?
> Should i use? exit(header("Status: 200 OK"));
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/131#issuecomment-70525471>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by chrigu89** [comment]
Hm both problems are not solved.
For Android: I send the Status in different ways, but nothing happens.
For iOS:
This is my complete CB Function

	var callbackFn = function(location) {
		var token = window.localStorage.getItem("final_token");
		$.ajax({
			type: 'GET',
			url: 'http://mywebsite.de/ios/api.php?rquest=set_device_geo',
			data:  { os: '', token: token, lat: location.latitude, long: location.longitude },
			crossDomain: true,
			cache: false,
			success: function(response) {
			}
		});
		
		console.log('BackgroundGeoLocation success');
		bgGeo.finish();
		
	};

**Comment by christocracy** [comment]
you want to call #finish *within* your Ajax callback.  the ios callbackFn
is running in an ios background-thread — once you call #finish, the
background-thread will be popped like a balloon.  Do you understand that
you are calling #finish *before* your Ajax request has completed, due to
the nature of asynchronous actions?  ios is probably "popping your balloon"
before your server has had a chance to respond.

For Android, tail your server’s request log.

On Mon, Jan 19, 2015 at 12:06 PM, chrigu89 <notifications@github.com> wrote:

> Hm both problems are not solved.
> For Android: I send the Status in different ways, but nothing happens.
> For iOS:
> This is my complete CB Function
>
> var callbackFn = function(location) {
>     var token = window.localStorage.getItem("final_token");
>     $.ajax({
>         type: 'GET',
>         url: 'http://mywebsite.de/ios/api.php?rquest=set_device_geo',
>         data:  { os: '', token: token, lat: location.latitude, long: location.longitude },
>         crossDomain: true,
>         cache: false,
>         success: function(response) {
>         }
>     });
>
>     console.log('BackgroundGeoLocation success');
>     bgGeo.finish();
>
> };
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/131#issuecomment-70527394>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
Have you tried using my plugins SampleApp (@see example/SampleApp)
<https://github.com/christocracy/cordova-plugin-background-geolocation/tree/master/example/SampleApp>?
See plugin README for directions
<https://github.com/christocracy/cordova-plugin-background-geolocation#example-application>
.



On Mon, Jan 19, 2015 at 12:13 PM, Chris Scott <christocracy@gmail.com>
wrote:

> you want to call #finish *within* your Ajax callback.  the ios callbackFn
> is running in an ios background-thread — once you call #finish, the
> background-thread will be popped like a balloon.  Do you understand that
> you are calling #finish *before* your Ajax request has completed, due to
> the nature of asynchronous actions?  ios is probably "popping your balloon"
> before your server has had a chance to respond.
>
> For Android, tail your server’s request log.
>
> On Mon, Jan 19, 2015 at 12:06 PM, chrigu89 <notifications@github.com>
> wrote:
>
>> Hm both problems are not solved.
>> For Android: I send the Status in different ways, but nothing happens.
>> For iOS:
>> This is my complete CB Function
>>
>> var callbackFn = function(location) {
>>     var token = window.localStorage.getItem("final_token");
>>     $.ajax({
>>         type: 'GET',
>>         url: 'http://mywebsite.de/ios/api.php?rquest=set_device_geo',
>>         data:  { os: '', token: token, lat: location.latitude, long: location.longitude },
>>         crossDomain: true,
>>         cache: false,
>>         success: function(response) {
>>         }
>>     });
>>
>>     console.log('BackgroundGeoLocation success');
>>     bgGeo.finish();
>>
>> };
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/131#issuecomment-70527394>
>> .
>>
>
>
>
> --
> Chris Scott
> Transistor Software <http://www.transistorsoft.com>
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by chrigu89** [comment]
I didn't use. For iOS - is it ok like this?
I found many way's to write the callback and mosttimes it was also marked as comment so i'm not sure.

	var yourAjaxCallback = function(response) {
		bgGeo.finish();
	}; 
	
	var callbackFn = function(location) {
		var token = window.localStorage.getItem("final_token");
		$.ajax({
			type: 'GET',
			url: 'http://ada-nrw.de/ios/api.php?rquest=set_device_geo',
			data:  { os: '', token: token, lat: location.latitude, long: location.longitude },
			crossDomain: true,
			cache: false,
			success: function(response) {
			}
		});
		
		console.log('BackgroundGeoLocation success');
		yourAjaxCallback.call(this);
		
	};

**Comment by chrigu89** [comment]
For Android, here is my Log:
46.115.18.58 - - [19/Jan/2015:17:40:06 +0100] "POST /ios/api.php?rquest=update_device_geo HTTP/1.1" 200 210 "-" "Apache-HttpClient/UNAVAILABLE (java 1.4) [55:3021:0]" ada-nrw.de

**Comment by christocracy** [comment]
No.

var callbackFn = function(location) {
    var token = window.localStorage.getItem("final_token");
    $.ajax({
        type: 'GET',
        url: 'http://ada-nrw.de/ios/api.php?rquest=set_device_geo',
        data:  { os: '', token: token, lat: location.latitude, long:
location.longitude },
        crossDomain: true,
        cache: false,
        success: function(response) {  // <— THIS is yourAjaxCallback

            bgGeo.finish()  // <— call #finish IN youAjaxCallback,
when you are DONE
        }
    });

    console.log('BackgroundGeoLocation success');
    yourAjaxCallback.call(this);  // <— NO, NOT HERE.  This is NOT
yourAjaxCallback




};


On Mon, Jan 19, 2015 at 12:22 PM, chrigu89 <notifications@github.com> wrote:

> I didn't use. For iOS - is it ok like this?
> I found many way's to write the callback and mosttimes it was also marked
> as comment so i'm not sure.
>
> var yourAjaxCallback = function(response) {
>     bgGeo.finish();
> };
>
> var callbackFn = function(location) {
>     var token = window.localStorage.getItem("final_token");
>     $.ajax({
>         type: 'GET',
>         url: 'http://ada-nrw.de/ios/api.php?rquest=set_device_geo',
>         data:  { os: '', token: token, lat: location.latitude, long: location.longitude },
>         crossDomain: true,
>         cache: false,
>         success: function(response) {
>         }
>     });
>
>     console.log('BackgroundGeoLocation success');
>     yourAjaxCallback.call(this);
>
> };
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/131#issuecomment-70529809>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by chrigu89** [comment]
iOS: Ah ok - I way a bit confused, because i thought a long time, Android need a finish(), too. I made the changed but on iOS i get the error "Outstanding bg-task was force-killed" again.

**Comment by christocracy** [comment]
Don’t worry about "Outstanding bg-task was force-killed”.

Ensure that #finish is always called, whether your server returns 200, 404,
500, whatever.

On Mon, Jan 19, 2015 at 12:47 PM, chrigu89 <notifications@github.com> wrote:

> iOS: Ah ok - I way a bit confused, because i thought a long time, Android
> need a finish(), too. I made the changed but on iOS i get the error
> "Outstanding bg-task was force-killed" again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/131#issuecomment-70533432>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by chrigu89** [comment]
Thanks, I'll go for iOS and give a feedback soon.
So what's about Android: Did you saw the log? Is everything good withit?

**Comment by christocracy** [comment]
Android log look like it’s returning http 200.  Go for a walk, leave your
server tailing.  you should see many HTTP requests from my plugin.

On Mon, Jan 19, 2015 at 1:01 PM, chrigu89 <notifications@github.com> wrote:

> Thanks, I'll go for iOS and give a feedback soon.
> So what's about Android: Did you saw the log? Is everything good withit?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/131#issuecomment-70535538>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by chrigu89** [comment]
Correct, i saw many requests. So do i actually need to move to get a request or do you also send the current location as well? Because Android still has the same problem.

**Comment by christocracy** [comment]
The plugin uses a #distanceFilter (e.g.: 20 meters).  That is, the device
must physically move #distanceFilter meters away from the last recorded
location UNTIL another geoLocation even is recorded.

If you’re trying to test my plugin by sitting in your office, you will
fail.  You must get out in the field and move.

On Mon, Jan 19, 2015 at 1:06 PM, chrigu89 <notifications@github.com> wrote:

> Correct, i saw many requests. So do i actually need to move to get a
> request or do you also send the current location as well? Because Android
> still has the same problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/131#issuecomment-70536138>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by chrigu89** [comment]
Thanks for advice. I'll try, thanks a lot!

**Comment by huttj** [comment]
> For Android, your HTTP response MUST return 200 or my plugin assumes the
HTTP request failed.

That would be a very good thing to highlight in the docs. I am currently using the plugin in an app, and, in the case where authentication fails for the plugin's request, I send back a standard 403 response. In my server logs, I saw a long list of "not authenticated" requests, coming from the plugin. When my session expired, the plugin continued dutifully submitting geolocation updates, regardless of the response.

I think it should stop sending updates if a 403 is received. In my case, it would be ideal to trigger the app and try to reauthenticate, but I am not sure if you would want to go that far. I could certainly accomplish this through a push notification.

On a similar note (though it might be a separate issue), I left my app running on my nightstand all night, and I saw a ton of these failed requests, each with a `recorded_at` value within a few minutes of the next. I am not sure if this is a result of the 403 response, or a different misuse of the plugin, but it is not the desired behavior.

**Comment by christocracy** [comment]
Why are you using http sessions for a mobile app?

Also, in your JS code, be sure to execute #stop on my plugin when http 403
is received.  Are you polling your server at some regular interval in
javascript?  That will help, however your Javascript is not guaranteed to
keep bg-running on Android.

My plugin could prob use some better intelligence in its http
response-handling.

On Tuesday, January 20, 2015, Joshua Hutt <notifications@github.com> wrote:

> For Android, your HTTP response MUST return 200 or my plugin assumes the
> HTTP request failed.
>
> That would be a very good thing to highlight in the docs. I am currently
> using the plugin in an app, and, in the case where authentication fails for
> the plugin's request, I send back a standard 403 response. In my server
> logs, I saw a long list of "not authenticated" requests, coming from the
> plugin. When my session expired, the plugin continued dutifully submitting
> geolocation updates, regardless of the response.
>
> I think it should stop sending updates if a 403 is received. In my case,
> it would be ideal to trigger the app and try to reauthenticate, but I am
> not sure if you would want to go that far. I could certainly accomplish
> this through a push notification.
>
> On a similar note (though it might be a separate issue), I left my app
> running on my nightstand all night, and I saw a ton of these failed
> requests, each with a recorded_at value within a few minutes of the next.
> I am not sure if this is a result of the 403 response, or a different
> misuse of the plugin, but it is not the desired behavior.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/131#issuecomment-70670243>
> .
>


-- 
Snet from Gmail Mobile

**Comment by huttj** [comment]
I'm just using a session key to authenticate requests. It seems like a better practice than sending the user's password with each request.

Can you explain how I could listen for and handle the 403 response? I thought the Android version of the plugin doesn't support JS callbacks. The 403 response is being sent to the plugin's request, not to my app. So, I am not sure how I would detect it, unless I used push notifications.

I do not have a polling interval; I'm using SocketIO. The connection should be closed when the app is in the background, so there would't be a reliable way for me to inform the app of the failed request. It would be nice to have the plugin pass data back to the app, or have the option to open the app if it had been terminated.

**Comment by christocracy** [comment]
re: sessions:  this is really off-topic, but you don’t have to send user’s
password with each request — after successful user login, server generates
and returns a unique token.  User send that token with each request to
server.

https://auth0.com/blog/2014/01/15/auth-with-socket-io/

Android does not support js callback (since js isn’t guaranteed to keep
alive on Android) but I’m not talking about my plugin, I’m talking about *your
app-code.*  When the user opens your app, your javascript comes alive.  At
this point, I presume you contact your server for fresh data (via HTTP or
Socket) — if your server sends 403, ensure in *your* app-code to tell my
plugin to #stop.

On Tue, Jan 20, 2015 at 11:52 AM, Joshua Hutt <notifications@github.com>
wrote:

> I'm just using a session key to authenticate requests. It seems like a
> better practice than sending the user's password with each request.
>
> Can you explain how I could listen for and handle the 403 response? I
> thought the Android version of the plugin doesn't support JS callbacks. The
> 403 response is being sent to the plugin's request, not to my app. So, I am
> not sure how I would detect it, unless I used push notifications.
>
> I do not have a polling interval; I'm using SocketIO. The connection
> should be closed when the app is in the background, so there would't be a
> reliable way for me to inform the app of the failed request. It would be
> nice to have the plugin pass data back to the app, or have the option to
> open the app if it had been terminated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/131#issuecomment-70688580>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
Further, IMO, the reason we use session-based authentication is that
traditionally computers tend to be less private (e.g.: a public computer at
a library or a workstation in a cubicle farm).  You don’t want to be logged
into a web-app, like your online-banking app, without session-based auth.

A mobile device, however, is very personal.  You don’t have to worry about
the guy in the cubicle next to you checking out your phone when you’re at
lunch — your phone is always with and secured with a pass-code.

Never use session-based auth for mobile apps.

On Tue, Jan 20, 2015 at 12:06 PM, Chris Scott <christocracy@gmail.com>
wrote:

> re: sessions:  this is really off-topic, but you don’t have to send user’s
> password with each request — after successful user login, server generates
> and returns a unique token.  User send that token with each request to
> server.
>
> https://auth0.com/blog/2014/01/15/auth-with-socket-io/
>
> Android does not support js callback (since js isn’t guaranteed to keep
> alive on Android) but I’m not talking about my plugin, I’m talking about *your
> app-code.*  When the user opens your app, your javascript comes alive.
> At this point, I presume you contact your server for fresh data (via HTTP
> or Socket) — if your server sends 403, ensure in *your* app-code to tell
> my plugin to #stop.
>
> On Tue, Jan 20, 2015 at 11:52 AM, Joshua Hutt <notifications@github.com>
> wrote:
>
>> I'm just using a session key to authenticate requests. It seems like a
>> better practice than sending the user's password with each request.
>>
>> Can you explain how I could listen for and handle the 403 response? I
>> thought the Android version of the plugin doesn't support JS callbacks. The
>> 403 response is being sent to the plugin's request, not to my app. So, I am
>> not sure how I would detect it, unless I used push notifications.
>>
>> I do not have a polling interval; I'm using SocketIO. The connection
>> should be closed when the app is in the background, so there would't be a
>> reliable way for me to inform the app of the failed request. It would be
>> nice to have the plugin pass data back to the app, or have the option to
>> open the app if it had been terminated.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/131#issuecomment-70688580>
>> .
>>
>
>
>
> --
> Chris Scott
> Transistor Software <http://www.transistorsoft.com>
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by huttj** [comment]
I actually am using token-based auth. I just used the wrong terminology. I realize that they are fundamentally different methods.

The issue is in the token longevity. I (naively, I suppose) implemented token expiration on the server side, making it possible for the plugin to be sending requests with an invalidated token for as long as the user keeps the app running in the background, without opening the app.

If they open it, the client authenticates, requiring login, if necessary. At that point, the plugin should be re-configured with the new token. So, no problem there. The problem is if their token expires whole the app is in the background. There is no way to get the plugin to stop sending requests, except by  re-opening the app (either by making the user do it, or through a push notification).

That is what my issue is. I want a way to, at the very least, kill the task, if the response is 403 (and maybe   for other codes, as well). It would be great to also be able to re-open the app in such an event, but I'm not sure if that is feasible.

As a side note, I can stop expiring my tokens, or greatly extend the time they are valid, but that won't fully eliminate the problem. Because of the nature of my app, a user is only allowed to sign in from one client at a time. A second login **must** invalidate the existing token, to ensure that the new client is the only active connection for that user.

So, I really need a way to the the plugin off if authentication fails, and I can't count on the user opening the app in a timely manner. Would you be amiable to adding such functionality? I could try to tackle it myself, if that would help.

**Comment by christocracy** [comment]
I've been refactoring Android significantly where I dispense with having plugin do the http, instead executing the JS callback just like ios.

So your request would be moot.  You'd receive the Location in the js callback and take care of HTTP yourself.

This refactor implements the more battery-efficient Location API from Google Play Services.
https://developer.android.com/google/play-services/location.html

This API has an "activity recognition" system which uses the accelerometer/gyroscope for movement detection.

I'm not yet sure if I'm going to publish this code free though.  Is it worth $500?

**Comment by huttj** [comment]
That sounds pretty useful. Depending on how you did it, that could be preferable to the HTTP method, especially if it makes the Android and iOS APIs more isomorphic.

My team and I were a little frustrated with the battery performance of the plugin on Android devices, so I forked it and used the Play Services API, as well. It performs much better, mostly because it allows the phone to sleep, only waking it up periodically, rather than keeping a wakelock for the life of the service.

I think if your updated code matches the iOS version in terms of API and battery life, it is definitely worth the money. Unfortunately, because the product I am working on is self-funded, we aren't in the market for paid plugins just yet. However, when we have validated our model and are ready to tighten up our implementation, well, I know exactly where to find you. :smile:

In the mean time, if you would like to review my admittedly hacky revision, you can find it [here](https://github.com/huttj/cordova-plugin-background-geolocation).

**Comment by christocracy** [comment]
Mine is much cleaner, about half the code and I've implemented the
ActivityRecognition API for movement/stop detection.  And no more HTTP in
the plugin.

On Sunday, February 22, 2015, Joshua Hutt <notifications@github.com> wrote:

> That sounds pretty useful. Depending on how you did it, that could be
> preferable to the HTTP method, especially if it makes the Android and iOS
> APIs more isomorphic.
>
> My team and I were a little frustrated with the battery performance of the
> plugin on Android devices, so I forked it and used the Play Services API,
> as well. It performs much better, mostly because it allows the phone to
> sleep, only waking it up periodically, rather than keeping a wakelock for
> the life of the service.
>
> I think if your updated code matches the iOS version in terms of API and
> battery life, it is definitely worth the money. Unfortunately, because the
> product I am working on is self-funded, we aren't in the market for paid
> plugins just yet. However, when we have validated our model and are ready
> to tighten up our implementation, well, I know exactly where to find you. [image:
> :smile:]
>
> In the mean time, if you would like to review my admittedly hacky
> revision, you can find it here
> <https://github.com/huttj/cordova-plugin-background-geolocation>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/131#issuecomment-75438401>
> .
>


-- 
Snet from Gmail Mobile

**Comment by christocracy** [comment]
Btw, here's link to new premium version http://christocracy.github.io/cordova-background-geolocation/
