### ISSUE TITLE
iOS App Store Rejection - Need to remove persistent geolocation and only use the significant changes API

### ISSUE THREAD

**Issue by cacardinal** [christocracy/cordova-plugin-background-geolocation#132]
I've been in a back and forth with the App Store Review team and they will not allow our application into the app store if it is using persistent geolocation tracking. I've explained to them the behavior of this plugin with no avail. 

Apple said that they now only approve which use persistent tracking for directions and mapping applications and that the Significant Changes API will allow us to achieve the functionality we're looking for.

Our app needs to grab the users location sporadically to check the weather around them for use in a headache risk calculation. We would also like to have the accuracy high enough that we could infer establishments which they are visiting.

Is it possible to only use the Significant Changes API / significant-change location service with this plugin without having to declare support for location in the UIBackgroundModes key / persistent geolocation tracking?

Does anyone have any suggestions on how to achieve this?

**Comment by christocracy** [comment]
If you want to use only sig.changes api, simply disable Location Updates
from Background Modes.

https://www.dropbox.com/s/pvvsrn9pb2gmih2/Screenshot%202015-01-20%2016.14.44.png?dl=0

the plugin will continue to operate with sig.changes only.

On Tue, Jan 20, 2015 at 4:00 PM, cacardinal <notifications@github.com>
wrote:

> I've been in a back and forth with the App Store Review team and they will
> not allow our application into the app store if it is using persistent
> geolocation tracking. I've explained to them the behavior of this plugin
> with no avail.
>
> Apple said that they now only approve which use persistent tracking for
> directions and mapping applications and that the Significant Changes API
> will allow us to achieve the functionality we're looking for.
>
> Our app needs to grab the users location sporadically to check the weather
> around them for use in a headache risk calculation. We would also like to
> have the accuracy high enough that we could infer establishments which they
> are visiting.
>
> Is it possible to only use the Significant Changes API /
> significant-change location service with this plugin without having to
> declare support for location in the UIBackgroundModes key / persistent
> geolocation tracking?
>
> Does anyone have any suggestions on how to achieve this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/132>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
Your app should def. be rejected for your use-case.  sig.changes only will
be adequate.

On Tue, Jan 20, 2015 at 4:00 PM, cacardinal <notifications@github.com>
wrote:

> I've been in a back and forth with the App Store Review team and they will
> not allow our application into the app store if it is using persistent
> geolocation tracking. I've explained to them the behavior of this plugin
> with no avail.
>
> Apple said that they now only approve which use persistent tracking for
> directions and mapping applications and that the Significant Changes API
> will allow us to achieve the functionality we're looking for.
>
> Our app needs to grab the users location sporadically to check the weather
> around them for use in a headache risk calculation. We would also like to
> have the accuracy high enough that we could infer establishments which they
> are visiting.
>
> Is it possible to only use the Significant Changes API /
> significant-change location service with this plugin without having to
> declare support for location in the UIBackgroundModes key / persistent
> geolocation tracking?
>
> Does anyone have any suggestions on how to achieve this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/132>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by cacardinal** [comment]
Thanks for the quick response @christocracy 

We already had disabled Location Updates from Background Modes prior to our submission in order to attempt to resolve this issue. Looking back at the code we submitted, I now see that we didn't remove the declaration of support for location in the UIBackgroundModes key in our Info.plist

However, I've found that when I build cordova, the UIBackgroundModes key is reinserted into our Info.plist, which is likely triggering Apple's rejection. Is it ok to just delete this?

**Comment by christocracy** [comment]
When you submit, ensure that UIBackgroundModes does not contain location.

Apple will be happy

On Tuesday, January 20, 2015, cacardinal <notifications@github.com> wrote:

> Thanks for the quick response @christocracy
> <https://github.com/christocracy>
>
> We already had disabled Location Updates from Background Modes prior to
> our submission in order to attempt to resolve this issue. Looking back at
> the code we submitted, I now see that we didn't remove the declaration of
> support for location in the UIBackgroundModes key in our Info.plist
>
> However, I've found that when I build cordova, the UIBackgroundModes key
> is reinserted into our Info.plist, which is likely triggering Apple's
> rejection. Is it ok to just delete this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/132#issuecomment-70739369>
> .
>


-- 
Snet from Gmail Mobile

**Comment by cacardinal** [comment]
Sounds good. We'll be resubmitting today. Thanks for the great plugin!

**Comment by chemerisuk** [comment]
Hi @christocracy. Going to buy the premium version, but need to clarify on iOS part first. I had the same rejection last week related to having location in `UIBackgroundModes`. I understand that I can remove it manually but what will be the impact of that? Will it increase the battery usage?

**Comment by christocracy** [comment]
If you remove location from bg-modes, it will prevent aggressive GPS
tracking, *decreasing* battery usage.

You will continue to receive bg geolocation updates from the low-power
"sig.chaanges" system (typically every few blocks).  This is what apps like
4-Square use.

I suggest you enable debug mode after removing "location" then do some
field-testing.

On Monday, March 23, 2015, Maksim Chemerisuk <notifications@github.com>
wrote:

> Hi @christocracy <https://github.com/christocracy>. Going to buy the
> premium version, but need to clarify on iOS part first. I had the same
> rejection last week related to having location in UIBackgroundModes. I
> understand that I can remove it manually but what will be the impact of
> that? Will it increase the battery usage?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/132#issuecomment-84938327>
> .
>


-- 
Snet from Gmail Mobile

**Comment by chemerisuk** [comment]
@christocracy thanks for quick response Chris. I will do testing as you suggested, but afaiu without that permission location updates will be less granular, right? I read in the internet a bit about significant changes API, and people say different things. From your personal experience, what is typical granularity for that API? Is it enough for a transportation app (say Uber-like) to detect user/car position on a map in realtime, and potentially calculate a route price in real-time?

Ideally 10 meters is the target accuracy, but it might be acceptable a less accurate values I guess.

**Comment by christocracy** [comment]
I explained the granularity of sig.changes in previous msg:

"You will continue to receive bg geolocation updates from the low-power
"sig.chaanges" system (***typically every few blocks***). "

No it is not enough to calculate route in realtime, like Uber.  If you're
making a transportation app like this, you have nothing to fear from
Apple by using "location" in bg- modes.


On Monday, March 23, 2015, Maksim Chemerisuk <notifications@github.com>
wrote:

> @christocracy <https://github.com/christocracy> thanks for quick response
> Chris. I will do testing as you suggested, but afaiu without that
> permission location updates will be less granular, right? I read in the
> internet a bit about significant changes API, and people say different
> things. From your personal experience, what is typical granularity for that
> API? Is it enough for a transportation app (say Uber-like) to detect
> user/car position on a map in realtime, and potentially calculate a route
> price in real-time?
>
> Ideally 10 meters is the target accuracy, but it might be acceptable a
> less accurate values I guess.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/132#issuecomment-84962165>
> .
>


-- 
Snet from Gmail Mobile

**Comment by chemerisuk** [comment]
@christocracy It looks like Apple is not satisfied still:

> Your app declares support for location in the UIBackgroundModes key in your Info.plist file but does not declare any features that require persistent location. Apps that declare support for location in the UIBackgroundModes key in your Info.plist file must have features that require persistent location.

How can I pass this? Your plugin adds `location` mode, but it doesn't touch any API right? Or did I miss something?

**Comment by christocracy** [comment]
What is the nature of your app?

On Monday, March 23, 2015, Maksim Chemerisuk <notifications@github.com>
wrote:

> @christocracy <https://github.com/christocracy> It looks like Apple is
> not satisfied still:
>
> Your app declares support for location in the UIBackgroundModes key in
> your Info.plist file but does not declare any features that require
> persistent location. Apps that declare support for location in the
> UIBackgroundModes key in your Info.plist file must have features that
> require persistent location.
>
> How can I pass this? Your plugin adds location mode, but it doesn't touch
> any API right? Or did I miss something?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/132#issuecomment-84969136>
> .
>


-- 
Snet from Gmail Mobile

**Comment by chemerisuk** [comment]
@christocracy it's an Uber-like app for booking taxi online. I use cordova to enhance web application with a missing capabilities.

**Comment by DipakMakwana1** [comment]
Hello @ christocracy 

My app is rejected due to following reason.
"2.16 Details

Your app declares support for location in the UIBackgroundModes key in your Info.plist file but does not declare any features that require persistent location. Apps that declare support for location in the UIBackgroundModes key in your Info.plist file must have features that require persistent location.

Next Steps

Please revise your app to include features that require the persistent use of real-time location updates while the app is in the background. Please also add the following battery use disclaimer in your Application Description:
"Continued use of GPS running in the background can dramatically decrease battery life."

If your app does not require persistent real-time location updates, please remove the "location" setting from the UIBackgroundModes key. You may wish to use the significant-change location service or the region monitoring location service if persistent real-time location updates are not required for your app features."

But my application is require "location updates " and "Background fetch" in as background modes.("UIBackgroundModes") 
So can you please help me to re-solve this issue and my app pass out from the apple review cycle with       these features.

**Comment by christocracy** [comment]
Seems pretty clear to me what you have to do.

"Please revise your app to include features that require the persistent use
of real-time location updates while the app is in the background. Please
also add the following battery use disclaimer in your Application
Description:

"Continued use of GPS running in the background can dramatically decrease
battery life."


On Friday, July 10, 2015, DipakMakwana1 <notifications@github.com> wrote:

> Hello @ christocracy
>
> My app is rejected due to following reason.
> "2.16 Details
>
> Your app declares support for location in the UIBackgroundModes key in
> your Info.plist file but does not declare any features that require
> persistent location. Apps that declare support for location in the
> UIBackgroundModes key in your Info.plist file must have features that
> require persistent location.
>
> Next Steps
>
> Please revise your app to include features that require the persistent use
> of real-time location updates while the app is in the background. Please
> also add the following battery use disclaimer in your Application
> Description:
> "Continued use of GPS running in the background can dramatically decrease
> battery life."
>
> If your app does not require persistent real-time location updates, please
> remove the "location" setting from the UIBackgroundModes key. You may wish
> to use the significant-change location service or the region monitoring
> location service if persistent real-time location updates are not required
> for your app features."
>
> But my application is require "location updates " and "Background fetch"
> in as background modes.("UIBackgroundModes")
> So can you please help me to re-solve this issue and my app pass out from
> the apple review cycle with these features.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/132#issuecomment-120238021>
> .
>


-- 
Snet from Gmail Mobile

**Comment by ScottieR** [comment]
I am also trying to use your plugin using only the significant changes API.   Everything works fine when background location permissions are on but when I then remove them from the plist file, I get an exception and the app crashes.  Changing that background permission is the only change, and this can be demonstrated to break the Sample App (try removing the plist background modes and emulating).  I'm using xCode7 and ios9, which could be the culprit?  Any help would be very appreciated!  Here's the console log when removing the permission from the SampleApp:

```
2015-10-20 15:07:44.912 BG Geo[57806:1757291] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///Users/scottie/Library/Developer/CoreSimulator/Devices/7901ABC6-2ACC-4DFA-90EA-B1EA3DDE6C03/data/Containers/Data/Application/F4D00B91-FD91-4912-8202-DB854810BAFE/Library/Cookies/com.transistorsoft.backgroundgeolocation.ionic.binarycookies
2015-10-20 15:07:45.024 BG Geo[57806:1757291] Apache Cordova native platform version 3.9.1 is starting.
2015-10-20 15:07:45.026 BG Geo[57806:1757291] Multi-tasking -> Device: YES, App: YES
2015-10-20 15:07:45.032 BG Geo[57806:1757291] Unlimited access to network resources
2015-10-20 15:07:45.132 BG Geo[57806:1757291] [CDVTimer][keyboard] 0.142992ms
2015-10-20 15:07:45.378 BG Geo[57806:1757291] [CDVTimer][splashscreen] 245.315015ms
2015-10-20 15:07:45.378 BG Geo[57806:1757291] [CDVTimer][TotalPluginStartup] 245.988965ms
2015-10-20 15:07:45.527 BG Geo[57806:1757291] Resetting plugins due to page load.
2015-10-20 15:07:46.681 BG Geo[57806:1757291] [ts-locationmanager] CDVBackgroundGeoLocation configure {
    activityRecognitionInterval = 10000;
    activityType = Other;
    autoSync = true;
    batchSync = false;
    debug = true;
    desiredAccuracy = 0;
    disableElasticity = false;
    distanceFilter = 20;
    fastestLocationUpdateInterval = 1000;
    forceReloadOnGeofence = false;
    forceReloadOnLocationChange = false;
    forceReloadOnMotionChange = false;
    locationUpdateInterval = 5000;
    method = POST;
    params =     {
        device =         {
            available = 1;
            cordova = "3.9.1";
            manufacturer = Apple;
            model = "x86_64";
            platform = iOS;
            uuid = "5ACB9EFC-0019-407C-BD7D-FCFC36F944D0";
            version = "9.0";
        };
    };
    startOnBoot = false;
    stationaryRadius = 20;
    stopDetectionDelay = 0;
    stopOnTerminate = true;
    stopTimeout = 1;
    triggerActivities = "in_vehicle, on_bicycle, running, walking, on_foot";
    url = "http://posttestserver.com/post.php?dir=ionic-cordova-background-geolocation";
}
2015-10-20 15:07:46.682 BG Geo[57806:1757291] - TSLocationManager create database
2015-10-20 15:07:46.689 BG Geo[57806:1757291] [ts-locationmanager] - start location updates
2015-10-20 15:07:46.690 BG Geo[57806:1757291] *** Assertion failure in -[CLLocationManager setAllowsBackgroundLocationUpdates:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreLocationFramework_Sim/CoreLocation-1861.0.9/Framework/CoreLocation/CLLocationManager.m:604
2015-10-20 15:07:46.692 BG Geo[57806:1757291] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: !stayUp || CLClientIsBackgroundable(internal->fClient)'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010ae97f65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010d7dbdeb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ae97dca +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x000000010d429ae2 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	4   CoreLocation                        0x000000010dc1cfe3 CLClientGetCapabilities + 8270
	5   BG Geo                              0x000000010ac72fe4 -[TSLocationManager startUpdatingLocation] + 135
	6   BG Geo                              0x000000010ac6e03a -[TSLocationManager updateCurrentPosition:] + 1041
	7   BG Geo                              0x000000010ac48187 -[CDVBackgroundGeolocation getCurrentPosition:] + 423
	8   BG Geo                              0x000000010ac62cea -[CDVCommandQueue execute:] + 874
	9   BG Geo                              0x000000010ac62559 -[CDVCommandQueue executePending] + 841
	10  Foundation                          0x000000010d3c6129 __NSFireDelayedPerform + 402
	11  CoreFoundation                      0x000000010adf8364 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	12  CoreFoundation                      0x000000010adf7f11 __CFRunLoopDoTimer + 1089
	13  CoreFoundation                      0x000000010adb98b1 __CFRunLoopRun + 1937
	14  CoreFoundation                      0x000000010adb8e98 CFRunLoopRunSpecific + 488
	15  GraphicsServices                    0x000000010f3a2ad2 GSEventRunModal + 161
	16  UIKit                               0x000000010b244676 UIApplicationMain + 171
	17  BG Geo                              0x000000010ac3ee41 main + 65
	18  libdyld.dylib                       0x000000010e32b92d start + 1
	19  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by christocracy** [comment]
Ill check it out

On Tuesday, October 20, 2015, ScottieR <notifications@github.com> wrote:

> I am also trying to use your plugin using only the significant changes
> API. Everything works fine when background location permissions are on but
> when I then remove them from the plist file, I get an exception and the app
> crashes. Changing that background permission is the only change, and this
> can be demonstrated to break the Sample App (try removing the plist
> background modes and emulating). I'm using xCode7 and ios9, which could be
> the culprit? Any help would be very appreciated! Here's the console log
> when removing the permission from the SampleApp:
>
> 2015-10-20 15:07:44.912 BG Geo[57806:1757291] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///Users/scottie/Library/Developer/CoreSimulator/Devices/7901ABC6-2ACC-4DFA-90EA-B1EA3DDE6C03/data/Containers/Data/Application/F4D00B91-FD91-4912-8202-DB854810BAFE/Library/Cookies/com.transistorsoft.backgroundgeolocation.ionic.binarycookies
> 2015-10-20 15:07:45.024 BG Geo[57806:1757291] Apache Cordova native platform version 3.9.1 is starting.
> 2015-10-20 15:07:45.026 BG Geo[57806:1757291] Multi-tasking -> Device: YES, App: YES
> 2015-10-20 15:07:45.032 BG Geo[57806:1757291] Unlimited access to network resources
> 2015-10-20 15:07:45.132 BG Geo[57806:1757291] [CDVTimer][keyboard] 0.142992ms
> 2015-10-20 15:07:45.378 BG Geo[57806:1757291] [CDVTimer][splashscreen] 245.315015ms
> 2015-10-20 15:07:45.378 BG Geo[57806:1757291] [CDVTimer][TotalPluginStartup] 245.988965ms
> 2015-10-20 15:07:45.527 BG Geo[57806:1757291] Resetting plugins due to page load.
> 2015-10-20 15:07:46.681 BG Geo[57806:1757291] [ts-locationmanager] CDVBackgroundGeoLocation configure {
>     activityRecognitionInterval = 10000;
>     activityType = Other;
>     autoSync = true;
>     batchSync = false;
>     debug = true;
>     desiredAccuracy = 0;
>     disableElasticity = false;
>     distanceFilter = 20;
>     fastestLocationUpdateInterval = 1000;
>     forceReloadOnGeofence = false;
>     forceReloadOnLocationChange = false;
>     forceReloadOnMotionChange = false;
>     locationUpdateInterval = 5000;
>     method = POST;
>     params =     {
>         device =         {
>             available = 1;
>             cordova = "3.9.1";
>             manufacturer = Apple;
>             model = "x86_64";
>             platform = iOS;
>             uuid = "5ACB9EFC-0019-407C-BD7D-FCFC36F944D0";
>             version = "9.0";
>         };
>     };
>     startOnBoot = false;
>     stationaryRadius = 20;
>     stopDetectionDelay = 0;
>     stopOnTerminate = true;
>     stopTimeout = 1;
>     triggerActivities = "in_vehicle, on_bicycle, running, walking, on_foot";
>     url = "http://posttestserver.com/post.php?dir=ionic-cordova-background-geolocation";
> }
> 2015-10-20 15:07:46.682 BG Geo[57806:1757291] - TSLocationManager create database
> 2015-10-20 15:07:46.689 BG Geo[57806:1757291] [ts-locationmanager] - start location updates
> 2015-10-20 15:07:46.690 BG Geo[57806:1757291] *** Assertion failure in -[CLLocationManager setAllowsBackgroundLocationUpdates:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreLocationFramework_Sim/CoreLocation-1861.0.9/Framework/CoreLocation/CLLocationManager.m:604
> 2015-10-20 15:07:46.692 BG Geo[57806:1757291] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: !stayUp || CLClientIsBackgroundable(internal->fClient)'
> *** First throw call stack:
> (
>     0   CoreFoundation                      0x000000010ae97f65 __exceptionPreprocess + 165
>     1   libobjc.A.dylib                     0x000000010d7dbdeb objc_exception_throw + 48
>     2   CoreFoundation                      0x000000010ae97dca +[NSException raise:format:arguments:] + 106
>     3   Foundation                          0x000000010d429ae2 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
>     4   CoreLocation                        0x000000010dc1cfe3 CLClientGetCapabilities + 8270
>     5   BG Geo                              0x000000010ac72fe4 -[TSLocationManager startUpdatingLocation] + 135
>     6   BG Geo                              0x000000010ac6e03a -[TSLocationManager updateCurrentPosition:] + 1041
>     7   BG Geo                              0x000000010ac48187 -[CDVBackgroundGeolocation getCurrentPosition:] + 423
>     8   BG Geo                              0x000000010ac62cea -[CDVCommandQueue execute:] + 874
>     9   BG Geo                              0x000000010ac62559 -[CDVCommandQueue executePending] + 841
>     10  Foundation                          0x000000010d3c6129 __NSFireDelayedPerform + 402
>     11  CoreFoundation                      0x000000010adf8364 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
>     12  CoreFoundation                      0x000000010adf7f11 __CFRunLoopDoTimer + 1089
>     13  CoreFoundation                      0x000000010adb98b1 __CFRunLoopRun + 1937
>     14  CoreFoundation                      0x000000010adb8e98 CFRunLoopRunSpecific + 488
>     15  GraphicsServices                    0x000000010f3a2ad2 GSEventRunModal + 161
>     16  UIKit                               0x000000010b244676 UIApplicationMain + 171
>     17  BG Geo                              0x000000010ac3ee41 main + 65
>     18  libdyld.dylib                       0x000000010e32b92d start + 1
>     19  ???                                 0x0000000000000001 0x0 + 1
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/132#issuecomment-149724270>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
You’re not setting the config param `useSignificantChangesOnly: true`

Set that and it’ll work.

On Tue, Oct 20, 2015 at 6:48 PM, ScottieR <notifications@github.com> wrote:

> I am also trying to use your plugin using only the significant changes
> API. Everything works fine when background location permissions are on but
> when I then remove them from the plist file, I get an exception and the app
> crashes. Changing that background permission is the only change, and this
> can be demonstrated to break the Sample App (try removing the plist
> background modes and emulating). I'm using xCode7 and ios9, which could be
> the culprit? Any help would be very appreciated! Here's the console log
> when removing the permission from the SampleApp:
>
> 2015-10-20 15:07:44.912 BG Geo[57806:1757291] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///Users/scottie/Library/Developer/CoreSimulator/Devices/7901ABC6-2ACC-4DFA-90EA-B1EA3DDE6C03/data/Containers/Data/Application/F4D00B91-FD91-4912-8202-DB854810BAFE/Library/Cookies/com.transistorsoft.backgroundgeolocation.ionic.binarycookies
> 2015-10-20 15:07:45.024 BG Geo[57806:1757291] Apache Cordova native platform version 3.9.1 is starting.
> 2015-10-20 15:07:45.026 BG Geo[57806:1757291] Multi-tasking -> Device: YES, App: YES
> 2015-10-20 15:07:45.032 BG Geo[57806:1757291] Unlimited access to network resources
> 2015-10-20 15:07:45.132 BG Geo[57806:1757291] [CDVTimer][keyboard] 0.142992ms
> 2015-10-20 15:07:45.378 BG Geo[57806:1757291] [CDVTimer][splashscreen] 245.315015ms
> 2015-10-20 15:07:45.378 BG Geo[57806:1757291] [CDVTimer][TotalPluginStartup] 245.988965ms
> 2015-10-20 15:07:45.527 BG Geo[57806:1757291] Resetting plugins due to page load.
> 2015-10-20 15:07:46.681 BG Geo[57806:1757291] [ts-locationmanager] CDVBackgroundGeoLocation configure {
>     activityRecognitionInterval = 10000;
>     activityType = Other;
>     autoSync = true;
>     batchSync = false;
>     debug = true;
>     desiredAccuracy = 0;
>     disableElasticity = false;
>     distanceFilter = 20;
>     fastestLocationUpdateInterval = 1000;
>     forceReloadOnGeofence = false;
>     forceReloadOnLocationChange = false;
>     forceReloadOnMotionChange = false;
>     locationUpdateInterval = 5000;
>     method = POST;
>     params =     {
>         device =         {
>             available = 1;
>             cordova = "3.9.1";
>             manufacturer = Apple;
>             model = "x86_64";
>             platform = iOS;
>             uuid = "5ACB9EFC-0019-407C-BD7D-FCFC36F944D0";
>             version = "9.0";
>         };
>     };
>     startOnBoot = false;
>     stationaryRadius = 20;
>     stopDetectionDelay = 0;
>     stopOnTerminate = true;
>     stopTimeout = 1;
>     triggerActivities = "in_vehicle, on_bicycle, running, walking, on_foot";
>     url = "http://posttestserver.com/post.php?dir=ionic-cordova-background-geolocation";
> }
> 2015-10-20 15:07:46.682 BG Geo[57806:1757291] - TSLocationManager create database
> 2015-10-20 15:07:46.689 BG Geo[57806:1757291] [ts-locationmanager] - start location updates
> 2015-10-20 15:07:46.690 BG Geo[57806:1757291] *** Assertion failure in -[CLLocationManager setAllowsBackgroundLocationUpdates:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreLocationFramework_Sim/CoreLocation-1861.0.9/Framework/CoreLocation/CLLocationManager.m:604
> 2015-10-20 15:07:46.692 BG Geo[57806:1757291] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: !stayUp || CLClientIsBackgroundable(internal->fClient)'
> *** First throw call stack:
> (
>     0   CoreFoundation                      0x000000010ae97f65 __exceptionPreprocess + 165
>     1   libobjc.A.dylib                     0x000000010d7dbdeb objc_exception_throw + 48
>     2   CoreFoundation                      0x000000010ae97dca +[NSException raise:format:arguments:] + 106
>     3   Foundation                          0x000000010d429ae2 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
>     4   CoreLocation                        0x000000010dc1cfe3 CLClientGetCapabilities + 8270
>     5   BG Geo                              0x000000010ac72fe4 -[TSLocationManager startUpdatingLocation] + 135
>     6   BG Geo                              0x000000010ac6e03a -[TSLocationManager updateCurrentPosition:] + 1041
>     7   BG Geo                              0x000000010ac48187 -[CDVBackgroundGeolocation getCurrentPosition:] + 423
>     8   BG Geo                              0x000000010ac62cea -[CDVCommandQueue execute:] + 874
>     9   BG Geo                              0x000000010ac62559 -[CDVCommandQueue executePending] + 841
>     10  Foundation                          0x000000010d3c6129 __NSFireDelayedPerform + 402
>     11  CoreFoundation                      0x000000010adf8364 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
>     12  CoreFoundation                      0x000000010adf7f11 __CFRunLoopDoTimer + 1089
>     13  CoreFoundation                      0x000000010adb98b1 __CFRunLoopRun + 1937
>     14  CoreFoundation                      0x000000010adb8e98 CFRunLoopRunSpecific + 488
>     15  GraphicsServices                    0x000000010f3a2ad2 GSEventRunModal + 161
>     16  UIKit                               0x000000010b244676 UIApplicationMain + 171
>     17  BG Geo                              0x000000010ac3ee41 main + 65
>     18  libdyld.dylib                       0x000000010e32b92d start + 1
>     19  ???                                 0x0000000000000001 0x0 + 1
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/132#issuecomment-149724270>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by kevin-smets** [comment]
@christocracy where do you set this param? Been looking around where this config is located but can't seem to find it..

**Comment by christocracy** [comment]
Sorry, I didn't realize I was commenting on my **old & deprecated** repo.  

This project has moved [here](https://github.com/transistorsoft/cordova-background-geolocation-lt).

**Comment by christocracy** [comment]
And to answer your question specifically, at the new repo:  [useSignificantChangesOnly](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/api.md#param-boolean-usesignificantchangesonly-false)

**Comment by jimmont** [comment]
To prevent the key+value UIBackgroundModes + location being reinserted into the app is it appropriate to **remove** the following from `plugin.xml` (near line 80, [or line 39 in the new -it repo](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/plugin.xml#L39))?

```
        <config-file target="*-Info.plist" parent="UIBackgroundModes">
            <array>
                <string>location</string>
            </array>
        </config-file>
```

**Comment by christocracy** [comment]
This version of the plugin is no longer supported.  It has moved [here](https://github.com/transistorsoft/cordova-background-geolocation-lt)

**Comment by supriya-mobantica** [comment]
@christocracy, My App too was rejected due to location tracking in background Mode. I used Significant location change and removed background location capability. However, after field testing, i found that there were no location updates received on server, which I used to get when background location was on. Kindly help me understand what I am missing here?

**Comment by christocracy** [comment]
This plugin is no longer supported.  See README for redirection

On Monday, May 23, 2016, supriya-mobantica notifications@github.com wrote:

> @christocracy https://github.com/christocracy, My App too was rejected
> due to location tracking in background Mode. I used Significant location
> change and removed background location capability. However, after field
> testing, i found that there were no location updates received on server,
> which I used to get when background location was on. Kindly help me
> understand what I am missing here?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/132#issuecomment-220892862

## 

Snet form Gmail Mobile

**Comment by KirtiKumari5** [comment]
@christocracy  , I am working on iOS plugin.There i need to get location in case of app is terminated.I know how to do this in iOS app.But when i use the same concept for ios plugin in phonegap,it doesn't work.The concept that i am using is to start location tracking again on getting notification via UIApplicationDidFinishLaunchingNotification when app launches in background on location update by method startSignificantLocationChangesMonitering().But notification method is not calling, where i have restarted location tracking. Do you have any idea, how things work when we use iOS plugin in phoneGap?

**Comment by christocracy** [comment]
This version is no longer supported.  See readme for link to new version.
