### ISSUE TITLE
After restart of the phone, background geolocation is off

### ISSUE THREAD

**Issue by tvonbomhard** [christocracy/cordova-plugin-background-geolocation#133]
Is it possible that the background geolocation service is off after I restart the phone?

**Comment by christocracy** [comment]
which platform:  ios, Android or WP?

On Wed, Jan 21, 2015 at 11:56 AM, TvB <notifications@github.com> wrote:

> Is it possible that the background geolocation service is off after I
> restart the my phone?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/133>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by tvonbomhard** [comment]
Sorry, I've tested it on the android (version 4.4.4)

**Comment by christocracy** [comment]
I don’t think the geoLocation will re-start after device reboot on Android.

I think this is the relevant question.
http://stackoverflow.com/questions/14385231/android-broadcastreceiver-auto-run-service-after-reboot-of-device

On Wed, Jan 21, 2015 at 12:00 PM, TvB <notifications@github.com> wrote:

> Sorry, I've tested it on the android (version 4.4.4)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/133#issuecomment-70876046>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
