### ISSUE TITLE
Use local store and chached position

### ISSUE THREAD

**Issue by pklNarvik** [christocracy/cordova-plugin-background-geolocation#138]
Hi Chris, looks like it is a good package that you have created, but i have a few questions.
Have you example of a function with the Ajax Callback for iOS with auth_token and how it can work?

Can you save the token in local shop or do not work, it is possible from the background?
What happens when the phone lacks coverage and can not send position to server, you lose them or they are cached?

**Comment by christocracy** [comment]
Come back after you've read *every* word in the README,

On Wednesday, January 28, 2015, pklNarvik <notifications@github.com> wrote:

> Hi Chris, looks like it is a good package that you have created, but i
> have a few questions.
> Have you example of a function with the Ajax Callback for iOS with
> auth_token and how it can work?
>
> Can you save the token in local shop or do not work, it is possible from
> the background?
> What happens when the phone lacks coverage and can not send position to
> server, you lose them or they are cached?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/138>
> .
>


-- 
Snet from Gmail Mobile
