### ISSUE TITLE
Can i trigger the callback when there is no movement?

### ISSUE THREAD

**Issue by eladsof** [christocracy/cordova-plugin-background-geolocation#139]
I have an event that the user can trigger based on specific GPS location and would like to implement a "snooze" option so the user will get the same notification if he is still in the same position,
It would be super simple for me to put a timer that programatically triggers the callback. Is that possible?
I know i can put a timer that calls the call back, but i fear this gets me into dealing with different Async issues.

**Comment by christocracy** [comment]
It's called geo-fencing and I have an experimental plugin for defining
arbitrary geofences (alert on ENTER or EXIT).

What would you pay for such a plugin?

On Thursday, January 29, 2015, eladsof <notifications@github.com> wrote:

> I have an event that the user can trigger based on specific GPS location
> and would like to implement a "snooze" option so the user will get the same
> notification if he is still in the same position,
> It would be super simple for me to put a timer that programatically
> triggers the callback. Is that possible?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/139>
> .
>


-- 
Snet from Gmail Mobile

**Comment by eladsof** [comment]
Thanks for the quick reply.
I actually decided to completely decouple the updating of the location and the that actually does something with it, it fits my problem just fine.
Thanks again.
