### ISSUE TITLE
Samsung S4 jellyBean

### ISSUE THREAD

**Issue by drkhannah** [christocracy/cordova-plugin-background-geolocation#14]
testing with samsung s4 jellybean, positions are miles off, positions are also tracked less frequently, went the same route with htc one 4.4 and a 4.0 android and those were fine, s4 is the only buggy one

**Comment by christocracy** [comment]
FYI Android has been completely refactored
- No more in-plugin HTTP -- plugin now executes your Javascript callback, just like iOS
- Significantly improved battery performance

http://christocracy.github.io/cordova-background-geolocation/
