### ISSUE TITLE
After kill app background Service not working (Android - 4.4.0)

### ISSUE THREAD

**Issue by LokeshPatel** [christocracy/cordova-plugin-background-geolocation#140]
Hi,
App kill and service track location in background close. please help me how to handle .
i need service active after app kill .

Thanks

**Comment by christocracy** [comment]
It's possible but I have no time to implement this any time in near future,
sorry.

Feel free to implement it yourself and send me a PR.

On Thursday, January 29, 2015, Lokesh Patel <notifications@github.com>
wrote:

> Hi,
>
> App kill then background service track location close. please help me how
> to handle .
>
> i need service active after app kill .
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/140>
> .
>


-- 
Snet from Gmail Mobile

**Comment by samrat-shekhar** [comment]
add a startService call at the end of onDestroy as shown below.

@Override
    public void onDestroy() {
        Log.w(LOG_TAG, "------------------------------------------ Destroyed Location update Service");
        cleanUp();
        super.onDestroy();
		startService(new Intent(this, LocationUpdateService.class)); // add this line
    }

But, watch out for null-pointer exceptions as you are not passing any extra data through intent.

What I did was hard-code the data passed by intent in 'onStartCommand'

**Comment by christocracy** [comment]
Do you really think this is wise?

Have you thought of the implications of this?

What if the user actually wishes to destroy the service because it's
killing their battery -- you're just going to start it up again?

On Monday, February 16, 2015, samrat-shekhar <notifications@github.com>
wrote:

> add a startService call at the end of onDestroy as shown below.
>
> @Override <https://github.com/Override>
> public void onDestroy() {
> Log.w(LOG_TAG, "------------------------------------------ Destroyed
> Location update Service");
> cleanUp();
> super.onDestroy();
> startService(new Intent(this, LocationUpdateService.class)); // add this
> line
> }
>
> But, watch out for null-pointer exceptions as you are not passing any
> extra data through intent.
>
> What I did was hard-code the data passed by intent in 'onStartCommand'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/140#issuecomment-74494631>
> .
>


-- 
Snet from Gmail Mobile

**Comment by samrat-shekhar** [comment]
I agree. But the above tweaking depends on your desperation ;)

My use case is to track the user no matter what as long he is logged in to my app.

The re-starting of the service is governed by user-defaults which indicates whether the user is logged-in or not.

So, once the user loges out, the service can then be killed.

**Comment by uriva** [comment]
How is this implemented on other apps?
Shouldn't the background service be independent from the app itself?

**Comment by aperfectsquare** [comment]
+ 1 for this feature too. Maybe even better is to schedule the service to run once every hour

**Comment by uriva** [comment]
(It also stops working when restarting of course)

**Comment by christocracy** [comment]
Android has been refactored.
- plugin no longer handles http; calls js callback (just like ios)
- much improved battery efficiency.
- no more foreground service

http://christocracy.github.io/cordova-background-geolocation/

**Comment by As-k** [comment]
Hi,
I want code for make a service, it's run in background even app kill or forcefully closed. 

Thaks
Ashish

**Comment by christocracy** [comment]
Yes, that’s what this plugin does.
