### ISSUE TITLE
In Android how to stop the tracking from the server?

### ISSUE THREAD

**Issue by VapiSoft** [christocracy/cordova-plugin-background-geolocation#141]
In Android how to stop the tracking from the server?
I have the termination hour as one of the parameters, but I don;t have a way to terminate it so I will keep getting it forever.

**Comment by christocracy** [comment]
Send a "silent" push notification (one with no message, just a json-body.)

Eg {
  extra: {
    "bg-geo": {enabled: false}
}

You have to decode that logic yourself in push callback.

On Friday, January 30, 2015, VapiSoft <notifications@github.com> wrote:

> In Android how to stop the tracking from the server?
> I have the termination hour as one of the parameters, but I don;t have a
> way to terminate it so I will keep getting it forever.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/141>
> .
>


-- 
Snet from Gmail Mobile

**Comment by VapiSoft** [comment]
Hi Chris,

Thanks for your reply.
I didn't understand your answer.
What callback?
As I understand, in Android, you do not call the callback (only in ios),
but only the script (URL).
I also understand, that even if the App is out of memory you continue to
send the location if the stopOnTerminate is false.
So what can I do (in my PHP script) to stop it?

Also, currently when I tried it, it looks like it only send one location
and then stops.
Do I need to "echo" something to continue it?

Thanks,
Shlomo;





Shlomo Aran
http://www.mobile-gap.com
054-7399-340

**Comment by christocracy** [comment]
I've been refactoring Android significantly where I dispense with having plugin do the http, instead executing the JS callback just like ios.

This refactor implements the more battery-efficient Location API from Google Play Services.
https://developer.android.com/google/play-services/location.html

This API has an "activity recognition" system which uses the accelerometer/gyroscope for movement detection.

I'm not yet sure if I'm going to publish this code free though.  Is it worth $500 to you?

**Comment by VapiSoft** [comment]
Hi Chris,
Currently I am not making any money from my App, so I cannot afford to pay
anything, and it is also not my problem with the iOS. My problem with the
iOS notification is that the application is not being launched (like in
Android) when it is not in the background, and therefore, I cannot set the
"badge" number, and the users miss all the notifications.
This is a major drawback compare to Android.
Thanks,
Shlomo;




Shlomo Aran
http://www.mobile-gap.com
054-7399-340

**Comment by christocracy** [comment]
Why should my **background-geolocation** plugin be concerned with
notifications and badges??

On Sun, Feb 22, 2015 at 9:12 AM, VapiSoft <notifications@github.com> wrote:

> Hi Chris,
> Currently I am not making any money from my App, so I cannot afford to pay
> anything, and it is also not my problem with the iOS. My problem with the
> iOS notification is that the application is not being launched (like in
> Android) when it is not in the background, and therefore, I cannot set the
> "badge" number, and the users miss all the notifications.
> This is a major drawback compare to Android.
> Thanks,
> Shlomo;
>
>
>
>
> Shlomo Aran
> http://www.mobile-gap.com
> 054-7399-340
>
>
>
> On Sun, Feb 22, 2015 at 4:05 PM, Chris Scott <notifications@github.com>
> wrote:
>
> > I've been refactoring Android significantly where I dispense with having
> > plugin do the http, instead executing the JS callback just like ios.
> >
> > This refactor implements the more battery-efficient Location API from
> > Google Play Services.
> > https://developer.android.com/google/play-services/location.html
> >
> > This API has an "activity recognition" system which uses the
> > accelerometer/gyroscope for movement detection.
> >
> > I'm not yet sure if I'm going to publish this code free though. Is it
> > worth $500 to you?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/141#issuecomment-75436861
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/141#issuecomment-75437183>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by VapiSoft** [comment]
Oops,
Sorry, I was referring to another plugin (Notifications).
My problem with the iOS  Background-geolocation is that not like Android
that works directly with the server, and therefore is not affected when
there is no Internet connection, the iOS directly works with the callback
and when there is no Internet it fails (am I right?).
In any case, I really thank you very much for the plugin.

Thanks,
Shlomo

Shlomo Aran
http://www.mobile-gap.com
054-7399-340

**Comment by christocracy** [comment]
In fact, in the apps I create, I always assume no internet connection and
post ALL content to a Queue persisted in localStorage.

I have a task which periodically syncs my Queue to server.

On Sunday, February 22, 2015, Chris Scott <christocracy@gmail.com> wrote:

> On ios, when there's no internet connection, why don't you do what I do,
> and put the locations into localStorage?
>
> On Sunday, February 22, 2015, VapiSoft <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Oops,
>> Sorry, I was referring to another plugin (Notifications).
>> My problem with the iOS Background-geolocation is that not like Android
>> that works directly with the server, and therefore is not affected when
>> there is no Internet connection, the iOS directly works with the callback
>> and when there is no Internet it fails (am I right?).
>> In any case, I really thank you very much for the plugin.
>>
>> Thanks,
>> Shlomo
>>
>> Shlomo Aran
>> http://www.mobile-gap.com
>> 054-7399-340
>>
>>
>>
>> On Sun, Feb 22, 2015 at 4:17 PM, Chris Scott <notifications@github.com>
>> wrote:
>>
>> > Why should my **background-geolocation** plugin be concerned with
>> > notifications and badges??
>> >
>> >
>> > On Sun, Feb 22, 2015 at 9:12 AM, VapiSoft <notifications@github.com>
>> > wrote:
>> >
>> > > Hi Chris,
>> > > Currently I am not making any money from my App, so I cannot afford to
>> > pay
>> > > anything, and it is also not my problem with the iOS. My problem with
>> the
>> > > iOS notification is that the application is not being launched (like
>> in
>> > > Android) when it is not in the background, and therefore, I cannot set
>> > the
>> > > "badge" number, and the users miss all the notifications.
>> > > This is a major drawback compare to Android.
>> > > Thanks,
>> > > Shlomo;
>> > >
>> > >
>> > >
>> > >
>> > > Shlomo Aran
>> > > http://www.mobile-gap.com
>> > > 054-7399-340
>> > >
>> > >
>> > >
>> > > On Sun, Feb 22, 2015 at 4:05 PM, Chris Scott <
>> notifications@github.com>
>> > > wrote:
>> > >
>> > > > I've been refactoring Android significantly where I dispense with
>> > having
>> > > > plugin do the http, instead executing the JS callback just like ios.
>> > > >
>> > > > This refactor implements the more battery-efficient Location API
>> from
>> > > > Google Play Services.
>> > > > https://developer.android.com/google/play-services/location.html
>> > > >
>> > > > This API has an "activity recognition" system which uses the
>> > > > accelerometer/gyroscope for movement detection.
>> > > >
>> > > > I'm not yet sure if I'm going to publish this code free though. Is
>> it
>> > > > worth $500 to you?
>> > > >
>> > > > —
>> > > > Reply to this email directly or view it on GitHub
>> > > > <
>> > >
>> >
>> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/141#issuecomment-75436861
>> > > >
>> > >
>> > > > .
>> > > >
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <
>> >
>> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/141#issuecomment-75437183
>> > >
>> > > .
>> > >
>> >
>> >
>> >
>> > --
>> > Chris Scott
>> > Transistor Software <http://www.transistorsoft.com>
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/141#issuecomment-75437357
>> >
>> > .
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/141#issuecomment-75447255>
>> .
>>
>
>
> --
> Snet from Gmail Mobile
>


-- 
Snet from Gmail Mobile

**Comment by VapiSoft** [comment]
OK, now I understand what I should do.
Thank you very much.


Shlomo Aran
http://www.mobile-gap.com
054-7399-340
