### ISSUE TITLE
Lock Screen vs. Home Button on iOS

### ISSUE THREAD

**Issue by scgrant327** [christocracy/cordova-plugin-background-geolocation#142]
When hitting the lock button, the background service does not run.

When hitting the home button, the background services runs fine.

Is there any way to make the Lock behave the same as the Home?

**Comment by scgrant327** [comment]
IOS 6.1.6 by the way...

**Comment by christocracy** [comment]
I built this thing on ios 7.  ios 6 isn’t supported.

On Mon, Feb 2, 2015 at 4:25 PM, scgrant327 <notifications@github.com> wrote:

> IOS 6.1.6 by the way...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/142#issuecomment-72540964>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by scgrant327** [comment]
Ok, thanks.

**Comment by michaelkrog** [comment]
@christocracy This could be close I think!
