### ISSUE TITLE
No GPS recording in Android

### ISSUE THREAD

**Issue by VapiSoft** [christocracy/cordova-plugin-background-geolocation#143]
In one Android cell I get one gps recording, and in another cell I get no GPS recording at all.
When I start to walk I get a beep and a black rectangle with somthing that looks like a domain.

**Comment by christocracy** [comment]
I've been refactoring Android significantly where I dispense with having plugin do the http, instead executing the JS callback just like ios.

This refactor implements the more battery-efficient Location API from Google Play Services.
https://developer.android.com/google/play-services/location.html

This API has an "activity recognition" system which uses the accelerometer/gyroscope for movement detection.

I'm not yet sure if I'm going to publish this code free though.  Is it worth $500 to you?

**Comment by christocracy** [comment]
Android has been refactored.
- plugin no longer handles http; calls js callback (just like ios)
- much improved battery efficiency.
- no more foreground service

http://christocracy.github.io/cordova-background-geolocation/
