### ISSUE TITLE
iOS 8

### ISSUE THREAD

**Issue by scgrant327** [christocracy/cordova-plugin-background-geolocation#144]
When backgrounding the app in iOS 8, the background process does not run...and gets killed by the OS.

**Comment by christocracy** [comment]
Are you sure you "location" enabled in background-modes?  Works fine here

On Thursday, February 12, 2015, scgrant327 <notifications@github.com> wrote:

> When backgrounding the app in iOS 8, the background process does not
> run...and gets killed by the OS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/144>
> .
>


-- 
Snet from Gmail Mobile

**Comment by scgrant327** [comment]
Works fine on iOS 6.1.6...

Using this with Cordova via the Intel XDK dev system.

**Comment by christocracy** [comment]
Try the SampleApp in repo.  See README

On Thursday, February 12, 2015, scgrant327 <notifications@github.com> wrote:

> Works fine on iOS 6.1.6...
>
> Using this with Cordova via the Intel XDK dev system.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/144#issuecomment-74154611>
> .
>


-- 
Snet from Gmail Mobile
