### ISSUE TITLE
iOS locations

### ISSUE THREAD

**Issue by scgrant327** [christocracy/cordova-plugin-background-geolocation#145]
Is there any way to make the iOS version start updating sooner than:

"The plugin uses iOS Significant Changes API, and starts triggering  callbackFn  only *when a cell-tower switch is detected* (i.e. the device exits stationary radius). "

**Comment by christocracy** [comment]
See my SampleApp's usage of the #setPace method (via [Aggressive] button)

On Friday, February 13, 2015, scgrant327 <notifications@github.com> wrote:

> Is there any way to make the iOS version start updating sooner than:
>
> "The plugin uses iOS Significant Changes API, and starts triggering
> callbackFn only *when a cell-tower switch is detected* (i.e. the device
> exits stationary radius). "
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/145>
> .
>


-- 
Snet from Gmail Mobile
