### ISSUE TITLE
Continuous tracking icon after the second location upload

### ISSUE THREAD

**Issue by SeKra24** [christocracy/cordova-plugin-background-geolocation#147]
Hey Christocracy,

nice work on this one! But I have an issue with your plugin on Android: After the second upload through the background it says: "onLocationChanged: lat, long, accuracy: 30.0, isMoving: true, speed: 0.0" & "setPace: true" and the GPS icon in the top bar won't go away after the upload (In addition: After the first upload the GPS icon goes away). In this situation the battery goes down rapidly. 

These are my settings:
desiredAccuracy: 30,
stationaryRadius: 40,
distanceFilter: 50, 
notificationTitle: 'Title',
notificationText: 'Text',
activityType: 'AutomotiveNavigation',
debug: false

Thank you for your response.

SeKra24

**Comment by christocracy** [comment]
I've refactored the Android plugin to be much more battery-efficient and it
now executes the javascript callback rather than doing http in-plugin.

It's for sale at $500.

http://christocracy.github.io/cordova-background-geolocation/

On Monday, February 23, 2015, SeKra24 <notifications@github.com> wrote:

> Hey Christocracy,
>
> nice work on this one! But I have an issue with your plugin on Android:
> After the second upload through the background it says: "onLocationChanged:
> lat, long, accuracy: 30.0, isMoving: true, speed: 0.0" & "setPace: true"
> and the GPS icon in the top bar won't go away after the upload (In
> addition: After the first upload the GPS icon goes away). In this situation
> the battery goes down rapidly.
>
> These are my settings:
> desiredAccuracy: 30,
> stationaryRadius: 40,
> distanceFilter: 50,
> notificationTitle: 'Title',
> notificationText: 'Text',
> activityType: 'AutomotiveNavigation',
> debug: false
>
> Thank you for your response.
>
> SeKra24
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/147>
> .
>


-- 
Snet from Gmail Mobile

**Comment by SeKra24** [comment]
Thank you for your response but I'm a student and I can't afford it ;)

Can you tell me if it is normal that the GPS Icon is shown the hole time?

Thank you!

**Comment by christocracy** [comment]
Email me chris@transistorsoft.com


On Monday, February 23, 2015, SeKra24 <notifications@github.com> wrote:

> Thank you for your response but I'm a student and I can't afford it ;)
>
> Can you tell me if it is normal that the GPS Icon is shown the hole time?
>
> Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/147#issuecomment-75666491>
> .
>


-- 
Snet from Gmail Mobile
