### ISSUE TITLE
Future of this plugin

### ISSUE THREAD

**Issue by dbaq** [christocracy/cordova-plugin-background-geolocation#148]
Hey Chris,

I am using your plugin for an iOS/android app (it is a side project where I don't make any money at all).

I've read your last comments about the new version of your android code and we have to pay $500 to get it. It is great for you if some guys working for companies are willing to pay for it, I am sure you put a crazy amount of time and effort in this plugin. But I bet there is also a lot of guys/students developing free apps without real business model and no intention of making any money.

So I would like to know, what is your official position? no more updates without paying?

Thanks

**Comment by christocracy** [comment]
So far, I'm thinking:  ios is free.  Android;  $500.

On Monday, February 23, 2015, Didier Baquier <notifications@github.com>
wrote:

> Hey Chris,
>
> I am using your plugin for an iOS/android app (it is a side project where
> I don't make any money at all).
>
> I've read your last comments about the new version of your android code
> and we have to pay $500 to get it. It is great for you if some guys working
> for companies are willing to pay for it, I am sure you put a crazy amount
> of time and effort in this plugin. But I bet there is also a lot of
> guys/students developing free apps without real business model and no
> intention of making any money.
>
> So I would like to know, what is your official position? no more updates
> without paying?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/148>
> .
>


-- 
Snet from Gmail Mobile

**Comment by dbaq** [comment]
What about the updates for iOS? no more updates neither?

**Comment by christocracy** [comment]
I'll update ios.

On Tuesday, February 24, 2015, Didier Baquier <notifications@github.com>
wrote:

> What about the updates for iOS? no more updates neither?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/148#issuecomment-75707016>
> .
>


-- 
Snet from Gmail Mobile
