### ISSUE TITLE
WinPhone background mode active forever

### ISSUE THREAD

**Issue by jojo69256** [christocracy/cordova-plugin-background-geolocation#149]
Good day,
from my testing it seems, that WinPhone has backgroud mode active, even without runing 'start'.
Doesn't matter if I run 'start', 'stop', 'finish', or nothing.
I just need to add this plugin in config.xml and background mode is already active, so I have no control.

Also it seems, that event 'pause' is not working when plugin has been added in config.xml.

Thank you for your help

**Comment by jojo69256** [comment]
If there is any information I should provide to help with troubleshooting, please let me know.
Thnak you

**Comment by christocracy** [comment]
Sorry, I have nothing to do with WP.  The WP implementation came from a
pull-request from https://github.com/keesschollaart81




On Wed, Feb 25, 2015 at 2:51 PM, jojo69256 <notifications@github.com> wrote:

> If there is any information I should provide to help with troubleshooting,
> please let me know.
> Thnak you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/149#issuecomment-76041749>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
