### ISSUE TITLE
Awsome plugin, but need clarification on setting

### ISSUE THREAD

**Issue by adde-wik** [christocracy/cordova-plugin-background-geolocation#150]
Hi

First of all, love your plugin, appreciate all the hard work you've put into it. Considering buying your premium version to show my appreciation, although I need to get my app accepted first.

Apple has rejected my app for the same reason as for a few others I've read about, where Apple doesn't like the use of background location and wants the app to only use the significant Changes.

I've read your reply the closed issue https://github.com/christocracy/cordova-plugin-background-geolocation/issues/132 , where the user got the same reply from Apple.

If I simple disable Location Updates from Background Modes your plugin will work as normal (getting coordinates, callback and all), but without it entering the aggressive background mode? Would this also mean that the app only get's coordinates at cell tower switch or does it take the region monitoring in consideration?

If Apple doesn't approve my current settings using this plugin, I'm looking for the possibility to use this plugin for some kind of region monitoring, where I only get new coordinates if the user moves out of the 1000m radius, and if that happens, setting a new 1000m radius to monitor.

**Comment by christocracy** [comment]
> If I simple disable Location Updates from Background Modes your plugin
> will work as normal (getting coordinates, callback and all), but without it
> entering the aggressive background mode?
>
> Correct.  A ping about every 3 blocks, I've found is typical in sig.change
events.

>  Would this also mean that the app only get's coordinates at cell tower
> switch or does't it take the region monitoring in consideration?
>
A monitored-region is checked only after a location-update event, and a
location-update event is fired only after a sig.change event.

You can have a monitored stationaryRadius:10, but ios won't compare that
until you've moved ~3 blocks away.

The new premium Android plugin has a better system, ActivityRecognition
API.  Android can detect movement from stationary without
region-monitoring.  Typically 10 meters (but depends on
configured sample-rate of activity-recognition).  Too bad Apple couldn't figure
out how to do this without the A7 chip.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/150>
> .
>


-- 
Snet from Gmail Mobile

**Comment by adde-wik** [comment]
Thanks for the quick reply man!

Would this also mean that the plugin doesn't use much battery at all until the cell tower change is detected?

Will do an Android version as well if I somehow can workout this problem with the app (and Apple), sounds like the premium version will be great for the Android version.

**Comment by christocracy** [comment]
>
>
> Would this also mean that the plugin doesn't use much battery at all until
> the cell tower change is detected?
>

Correct.  Ios has your app completely suspended until a sig.change event.
No power consumed until then.  30s of bg running when it does fire

> Will do an Android version as well if I somehow can workout this problem
> with the app (and Apple), sounds like the premium version will be great for
> the Android version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/150#issuecomment-76148432>
> .
>


-- 
Snet from Gmail Mobile

**Comment by adde-wik** [comment]
One more minute of your precious time if I may,
If I disable Location Updates from Background Modes, what mode under location settings in iOS will the user have to accept for the app? "always" or "while using"?

**Comment by christocracy** [comment]
I'm not sure about that.

On Thursday, February 26, 2015, adde-wik <notifications@github.com> wrote:

> One more minute of your precious time if I may,
> If I disable Location Updates from Background Modes, what mode under
> location settings in iOS will the user have to accept for the app? "always"
> or "while using"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/150#issuecomment-76149176>
> .
>


-- 
Snet from Gmail Mobile

**Comment by adde-wik** [comment]
I'll give it a try on my next build and post the result, in case it's of intereset to someone else.

Thanks for your replies, will get back to you when it's time for the Android version!

**Comment by adde-wik** [comment]
The user will have to set location settings in iOS to "Always on" for the app to receive updates, as discussed above. Case closed.
