### ISSUE TITLE
Store location in database when no internet connection on Android

### ISSUE THREAD

**Issue by dfabreguette-ap** [christocracy/cordova-plugin-background-geolocation#151]
As there is no js callback when position is recorded on Android devices, is there a way to store location in  application sqlite database (for later sent) ? (Using sqlitePlugin from cordova)

**Comment by christocracy** [comment]
If you're serious about Android, the premium version now executes JS
callback and has vastly superior battery performance.

http://christocracy.github.io/cordova-background-geolocation/

On Friday, February 27, 2015, David Fabreguette <notifications@github.com>
wrote:

> As there is no js callback when position is recorded on Android devices,
> is there a way to store location in application sqlite database (for later
> sent) ? (Using sqlitePlugin from cordova)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/151>
> .
>


-- 
Snet from Gmail Mobile

**Comment by dfabreguette-ap** [comment]
Alright, didn't know there was a premium version ! Cool !
Do you know where I can have a full premium features “list" ? 
Basically, what can do much more the premium version ?

**Comment by dfabreguette-ap** [comment]
Sorry, I just saw plugin's README page :

Premium Version
A new Premium Version is available for $500.00

Implements the latest Android Fused GeoLocation and ActivityRecognition APIs for much-improved battery performance.
Android no longer handles HTTP -- It now executes your callback just like iOS!
50% less code -- much easier to extend!

:+1:

**Comment by christocracy** [comment]
Premium is new as of last week.

Only Android is different:

- js callback is executed (plugin no longer does http, just like ios)

- Android now uses more advanced And efficient Fused Location Provider from
Google Play Services

- Android uses ActivityRecognition API to detect movement (no more
stationaryRadius necessary)

Much more to come now that I'm using Google Play Services APIs.

Android plugin might have a slight edge in performance over ios now.

On Friday, February 27, 2015, David Fabreguette <notifications@github.com>
wrote:

> Alright, didn't know there was a premium version ! Cool !
> Do you know where I can have a full premium features “list" ?
> Basically, what can do much more the premium version ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/151#issuecomment-76393150>
> .
>


-- 
Snet from Gmail Mobile

**Comment by dfabreguette-ap** [comment]
Good stuff ! Might give it a try !

**Comment by dfabreguette-ap** [comment]
Hi !
Looking at source code - it looks like when no network is available, you store in cache locations and send them when you have back network through that method :

```
    private class PostLocationTask extends AsyncTask<Object, Integer, Boolean> {

        @Override
        protected Boolean doInBackground(Object...objects) {
            Log.d(TAG, "Executing PostLocationTask#doInBackground");
            LocationDAO locationDAO = DAOFactory.createLocationDAO(LocationUpdateService.this.getApplicationContext());
            for (com.tenforwardconsulting.cordova.bgloc.data.Location savedLocation : locationDAO.getAllLocations()) {
                Log.d(TAG, "Posting saved location");
                if (postLocation(savedLocation, locationDAO)) {
                    locationDAO.deleteLocation(savedLocation);
                }
            }
            return true;
        }
        @Override
        protected void onPostExecute(Boolean result) {
            Log.d(TAG, "PostLocationTask#onPostExecture");
        }
    }
```

Can you confirm that "locationDAO.getAllLocations()" gets all locations, including the ones stored in cache previously ?

**Comment by christocracy** [comment]
I have a new premium version where Android now executes the JS callback and
no longer does http for you.  In addition to vastly superior battery
efficiency.

http://christocracy.github.io/cordova-background-geolocation/

On Monday, March 2, 2015, David Fabreguette <notifications@github.com>
wrote:

> Reopened #151
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/151>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/151#event-244247142>
> .
>


-- 
Snet from Gmail Mobile

**Comment by dfabreguette-ap** [comment]
Yes I know that thank you ! :)
Unfortunately, it seems too expensive for our budget for now. Plus, battery efficiency isn't our main focus for now - but can be in the future months of our development.
For now, we just need to make sure user is tracked even when he has no network connection available and that location points will be sent to server later on. 
Sources shows to me that this is what is done, but I just wanted a confirmation as there's no mention of that in readme file.

**Comment by christocracy** [comment]
The public Android plugin is no longer supported.

$500 is too expensive?  That's 1/2 the cost of an iPhone 6.  This is a
liberal license with no restrictions on users or apps.

On Monday, March 2, 2015, David Fabreguette <notifications@github.com>
wrote:

> Yes I know that thank you ! :)
> Unfortunately, it seems too expensive for our budget for now. Plus,
> battery efficiency isn't our main focus for now - but can be in the future
> months of our development.
> For now, we just need to make sure user is tracked even when he has no
> network connection available and that location points will be sent to
> server later on.
> Sources shows to me that this is what is done, but I just wanted a
> confirmation as there's no mention of that in readme file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/151#issuecomment-76689212>
> .
>


-- 
Snet from Gmail Mobile

**Comment by christocracy** [comment]
Are you not supporting ios?  If so, how do you handle no network case in
ios?

On Monday, March 2, 2015, Chris Scott <christocracy@gmail.com> wrote:

> The public Android plugin is no longer supported.
>
> $500 is too expensive?  That's 1/2 the cost of an iPhone 6.  This is a
> liberal license with no restrictions on users or apps.
>
> On Monday, March 2, 2015, David Fabreguette <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Yes I know that thank you ! :)
>> Unfortunately, it seems too expensive for our budget for now. Plus,
>> battery efficiency isn't our main focus for now - but can be in the future
>> months of our development.
>> For now, we just need to make sure user is tracked even when he has no
>> network connection available and that location points will be sent to
>> server later on.
>> Sources shows to me that this is what is done, but I just wanted a
>> confirmation as there's no mention of that in readme file.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/151#issuecomment-76689212>
>> .
>>
>
>
> --
> Snet from Gmail Mobile
>


-- 
Snet from Gmail Mobile

**Comment by dfabreguette-ap** [comment]
Alright, does this licence has any time expiracy ? Does it include any support ? $500 isn't expensive for what it is, we agree with that, it's just that it's out of our budget that's all. 
In ios, I just store the location in database if any http post error is triggered - using js callback.

**Comment by christocracy** [comment]
>In ios, I just store the location in database if any http post error is
triggered

You mean localStorage, I presume?  Since Android & ios now both exec js
callback, im considering adding a localStorage-based queue to cache
locations when no network is detected.

The $500 is like an admission fee -- you get access to the private repo
where you may post issues as you're doing now.

I will support specific questions clearly related to my plugin.

If you want a new feature, like popcorn at the movies, you'd have to pay
for that.

The price will go up to $1000 before spring is over.

On Monday, March 2, 2015, DavFabreguette <notifications@github.com> wrote:

> Alright, does this licence has any time expiracy ? Does it include any
> support ? $500 isn't expensive for what it is, we agree with that, it's
> just that it's out of our budget that's all.
> In ios, I just store the location in database if any http post error is
> triggered - using js callback.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/151#issuecomment-76690776>
> .
>


-- 
Snet from Gmail Mobile

**Comment by dfabreguette-ap** [comment]
> You mean localStorage, I presume? 
Yes localStorage using cordova sqlitePlugin. 

> im considering adding a localStorage-based queue to cache
> locations when no network is detected
In Android platforms, aren't you already storing location through the "persistLocation" method (LocationUpdateService:704) ? And then sending them in the "PostLocationTask" using "getAllLocations()" method (SQLiteLocationDAO.java:28) ?

**Comment by christocracy** [comment]
No, I've scrapped the persistence layer entirely in premium version. The
plugin behaves Exactly like ios now.  If you've built a persistence layer
to handle ios, the new Android version will be compatible with that.

Btw, if I implemented a queue, I wouldn't use some SQLite plugin  After
all, under the hood, localStorage uses SQLite.  There is a way to easily
manage this by json-encoding each geolocation into a prefixed-key in std
localStorage.  You use another localStorage item to track the list-of-keys.

{
  "location-ids": "1,2",
  "location-1": "{lat: 73.3737, ...}",
  "location-2": "{lat: 73.3737, ...}"
}

Id probably use location timestamp as the "location id"


On Monday, March 2, 2015, David Fabreguette <notifications@github.com>
wrote:

> You mean localStorage, I presume?
> Yes localStorage using cordova sqlitePlugin.
>
> im considering adding a localStorage-based queue to cache
> locations when no network is detected
> In Android platforms, aren't you already storing location through the
> "persistLocation" method (LocationUpdateService:704) ? And then sending
> them in the "PostLocationTask" using "getAllLocations()" method
> (SQLiteLocationDAO.java:28) ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/151#issuecomment-76694948>
> .
>


-- 
Snet from Gmail Mobile

**Comment by dfabreguette-ap** [comment]
> No, I've scrapped the persistence layer entirely in premium version. The
plugin behaves Exactly like ios now.  If you've built a persistence layer
to handle ios, the new Android version will be compatible with that.

You mean in the new premium version or even in the current free version ? 

>Btw, if I implemented a queue, I wouldn't use some SQLite plugin  After
all, under the hood, localStorage uses SQLite.  There is a way to easily
manage this by json-encoding each geolocation into a prefixed-key in std
localStorage.  You use another localStorage item to track the list-of-keys.
{
  "location-ids": "1,2",
  "location-1": "{lat: 73.3737, ...}",
  "location-2": "{lat: 73.3737, ...}"
}
Id probably use location timestamp as the "location id"

Alright, this would be awesome !

Concerning the premium version, does the price include a limit of time and support for it ? Would we have access to plugin source code ?

**Comment by christocracy** [comment]
I believe I've answered all your questions in previous posts in this
thread.  Please go re-read.

$500 is admission fee to my private repo.  Support is exactly the same as
now, via github issues.  No different really.

On Monday, March 2, 2015, David Fabreguette <notifications@github.com>
wrote:

> No, I've scrapped the persistence layer entirely in premium version. The
> plugin behaves Exactly like ios now. If you've built a persistence layer
> to handle ios, the new Android version will be compatible with that.
>
> You mean in the new premium version or even in the current free version ?
>
> Btw, if I implemented a queue, I wouldn't use some SQLite plugin After
> all, under the hood, localStorage uses SQLite. There is a way to easily
> manage this by json-encoding each geolocation into a prefixed-key in std
> localStorage. You use another localStorage item to track the list-of-keys.
> {
> "location-ids": "1,2",
> "location-1": "{lat: 73.3737, ...}",
> "location-2": "{lat: 73.3737, ...}"
> }
> Id probably use location timestamp as the "location id"
>
> Alright, this would be awesome !
>
> Concerning the premium version, does the price include a limit of time and
> support for it ? Would we have access to plugin source code ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/151#issuecomment-76701470>
> .
>


-- 
Snet from Gmail Mobile

**Comment by scgrant327** [comment]
@dfabreguette-ap ~ contact me. I may have a solution for you. samuelgrant327@gmail.com

**Comment by christocracy** [comment]
Scgrant:  I won't allow solicitations on my own project

**Comment by scgrant327** [comment]
Just trying to offer an alternative to the sqlLite DB option. Sorry.

**Comment by christocracy** [comment]
@scgrant post a gist.

I plan to create a localStorage-based queue in the js side of the plugin.

On Monday, March 2, 2015, scgrant327 <notifications@github.com> wrote:

> Just trying to offer an alternative to the sqlLite DB option. Sorry.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/151#issuecomment-76743917>
> .
>


-- 
Snet from Gmail Mobile

**Comment by scgrant327** [comment]
Got it. I modified both the Android & iOS version to allow for creating/posting data to a local text file.

**Comment by christocracy** [comment]
You modified native code or js?

On Monday, March 2, 2015, scgrant327 <notifications@github.com> wrote:

> Got it. I modified both the Android & iOS version to allow for
> creating/posting data to a local text file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/151#issuecomment-76758913>
> .
>


-- 
Snet from Gmail Mobile

**Comment by scgrant327** [comment]
Native code on both platforms.

**Comment by christocracy** [comment]
Android was already doing that with SQLite.

It would be best to implement it in js since that's common to all platforms.

localStorage IS a SQLite db.

On Monday, March 2, 2015, scgrant327 <notifications@github.com> wrote:

> Native code on both platforms.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/151#issuecomment-76762265>
> .
>


-- 
Snet from Gmail Mobile

**Comment by scgrant327** [comment]
My app records data to a text file while running in the foreground (no HTTP upload)....and I wanted to be able to do the same while in the background.

**Comment by christocracy** [comment]
Are you aware I've created a new premium Android version which executes the
js callback now?

There is no more http layer in Android.

On Monday, March 2, 2015, scgrant327 <notifications@github.com> wrote:

> My app records data to a text file while running in the foreground (no
> HTTP upload)....and I wanted to be able to do the same while in the
> background.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/151#issuecomment-76763617>
> .
>


-- 
Snet from Gmail Mobile

**Comment by scgrant327** [comment]
Yes, I am aware. For now, $500 is way to much for me...as my app is virtually free.

**Comment by dfabreguette-ap** [comment]
Storing it to sqlite, through localStorage looks like to me the best solution - and I guess the best idea is to make it in JS to make it cross platform, as it should be the exact same thing, unless it makes the tasks killable by any the OS - but I'm not experienced enougth in android / ios development to tell about that so that's why I wondering if the current free version of the plugin was doing that or not.

And I guess @christocracy responded to me well, which is, it does for now only for the android platform but it doesn't in the premium version which can now execute JS callback and allow to implement it by our own (as I already did with IOS).

@scgrant327 From what I understand, you made an ios / android development to store locations in cache to a local file to send them later on to server through HTTP posts queries. If that's the case that's great but I think that's pretty much the same from what's working now in android platform and I got the ios part working the same in JS - but thank you very much for the help :+1: 

@christocracy localStorage seems a great way to start, I can share my sqlitePlugin code as a gist if that can help in any case (but I guess the tricky part is more about the queueing thing)

**Comment by christocracy** [comment]
What I would do, is basically what SenchTouch's LocalStorageProxy does (as
I explained earlier), where each record is serialized into one key.
Another key holds the list-of-ids.


On Monday, March 2, 2015, David Fabreguette <notifications@github.com>
wrote:

> Storing it to sqlite, through localStorage looks like to me the best
> solution - and I guess the best idea is to make it in JS to make it cross
> platform, as it should be the exact same thing, unless it makes the tasks
> killable by any the OS - but I'm not experienced enougth in android / ios
> development to tell about that so that's why I wondering if the current
> free version of the plugin was doing that or not.
>
> And I guess @christocracy <https://github.com/christocracy> responded to
> me well, which is, it does for now only for the android platform but it
> doesn't in the premium version which can now execute JS callback and allow
> to implement it by our own (as I already did with IOS).
>
> @scgrant327 <https://github.com/scgrant327> From what I understand, you
> made an ios / android development to store locations in cache to a local
> file to send them later on to server through HTTP posts queries. If that's
> the case that's great but I think that's pretty much the same from what's
> working now in android platform and I got the ios part working the same in
> JS - but thank you very much for the help [image: :+1:]
>
> @christocracy <https://github.com/christocracy> localStorage seems a
> great way to start, I can share my sqlitePlugin code as a gist if that can
> help in any case (but I guess the tricky part is more about the queueing
> thing)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/151#issuecomment-76813526>
> .
>


-- 
Snet from Gmail Mobile

**Comment by dfabreguette-ap** [comment]
Alright, this would be great !
