### ISSUE TITLE
Watch Position

### ISSUE THREAD

**Issue by tomardern** [christocracy/cordova-plugin-background-geolocation#152]
Hi,

I'm currently developing a app that constantly monitors a user location. 

Is there a way to set a timeout for geolocation rather than distance? 

Great plugin btw.

Thanks,

**Comment by christocracy** [comment]
Yes.  With my premium version.

http://christocracy.github.io/cordova-background-geolocation/

On Friday, February 27, 2015, Tom <notifications@github.com> wrote:

> Hi,
>
> I'm currently developing a app that constantly monitors a user location.
>
> Is there a way to set a timeout for geolocation rather than distance?
>
> Great plugin btw.
>
> Thanks,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/152>
> .
>


-- 
Snet from Gmail Mobile
