### ISSUE TITLE
Plugin selectively working on iOS

### ISSUE THREAD

**Issue by MartinGryner** [christocracy/cordova-plugin-background-geolocation#153]
Hi,

I have an issue with the plugin. Namely, it does not work sometimes and I have not been able to figure out the exact condition when it doesn't. 

I've tested the application on iPad Air 2, iPhone 5c and iPhone 4s. 
The issue rarely appears on Air 2 and 4s, but happens 90% of times on iPhone 5c. 

When the plugin won't send the location, all I see in the log are:

- CDVBackgroundGeoLocation finish
2015-03-03 16:40:26.009 huntloc[526:176996] - CDVBackgroundGeoLocation stopBackgroundTask (remaining t: 9.977656)

Or 

2015-03-03 15:34:15.354 huntloc[462:155671] - CDVBackgroundGeoLocation stopBackgroundTask (remaining t: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000)

The value of "t" is always either 9.9n or this huge number. 

It's usually the first few times I send the application to the background, at some point it usually starts (but won't keep) working.

My implementation is:

In the "pause" event callback:
```javascript
  if ( !this._bgGeo ) { 	
  	this._bgGeo = window.plugins.backgroundGeoLocation;
  }
  		
	this._bgGeo.configure(this.handleLocationUpdate(), function(){
  	console.log('FAILURE! Can\'t start backgound geolocation');
	}, {
      desiredAccuracy: 0,
      stationaryRadius: 0,
      distanceFilter: 0,
      activityType: 'Fitness',
      debug: true,
      stopOnTerminate: true 
  });

  this._bgGeo.start();
  this._bgGeo.changePace(true);
```

In the "resume" event callback:
```javascript
if ( this._bgGeo ) { 	  
    console.log('Stopping background task');
  	this._bgGeo.stop();
  	this._bgGeo = null;
  }
```

**Comment by christocracy** [comment]
Try my sample app in the repo.  See readme for details.  I have no issues
here.

On Tuesday, March 3, 2015, MartinGryner <notifications@github.com> wrote:

> Hi,
>
> I have an issue with the plugin. Namely, it does not work sometimes and I
> have not been able to figure out the exact condition when it doesn't.
>
> I've tested the application on iPad Air 2, iPhone 5c and iPhone 4s.
> The issue rarely appears on Air 2 and 4s, but happens 90% of times on
> iPhone 5c.
>
> When the plugin won't send the location, all I see in the log are:
>
>    - CDVBackgroundGeoLocation finish 2015-03-03 16:40:26.009
>    huntloc[526:176996] - CDVBackgroundGeoLocation stopBackgroundTask
>    (remaining t: 9.977656)
>
> Or
>
> 2015-03-03 15:34:15.354 huntloc[462:155671] - CDVBackgroundGeoLocation
> stopBackgroundTask (remaining t:
> 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000)
>
> The value of "t" is always either 9.9n or this huge number.
>
> It's usually the first few times I send the application to the background,
> at some point it usually starts (but won't keep) working.
>
> My implementation is:
>
> In the "pause" event callback:
>
>   if ( !this._bgGeo ) {
>     this._bgGeo = window.plugins.backgroundGeoLocation;
>   }
>
>     this._bgGeo.configure(this.handleLocationUpdate(), function(){
>     console.log('FAILURE! Can\'t start backgound geolocation');
>     }, {
>       desiredAccuracy: 0,
>       stationaryRadius: 0,
>       distanceFilter: 0,
>       activityType: 'Fitness',
>       debug: true,
>       stopOnTerminate: true
>   });
>
>   this._bgGeo.start();
>   this._bgGeo.changePace(true);
>
> In the "resume" event callback:
>
> if ( this._bgGeo ) {
>     console.log('Stopping background task');
>     this._bgGeo.stop();
>     this._bgGeo = null;
>   }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/153>
> .
>


-- 
Snet from Gmail Mobile
