### ISSUE TITLE
Detect stationary mode

### ISSUE THREAD

**Issue by MaliciousMustard** [christocracy/cordova-plugin-background-geolocation#154]
Hi,

Let me start by saying that your plugin is really awesome and thank you so much for all your hard work. I'm also considering if my app goes well to get the premium Android version (since now I'm only using it for iOS).

I was wondering if there is any way to detect whether the device is in `STATIONARY` mode or not? 
I checked the JSON object that is passed to the callback function and I don't see any fields regarding the mode. I thought for a second to use the `speed` property to determine whether the user is moving or not, but there were times where the mode was `MOVING` (in the debug messages) but the speed was `-1`.

Thank you for your help.

Best regards,
Alex

**Comment by christocracy** [comment]
In premium Android version, yes.
- STILL
- IN_VEHICLE
- BICYCLE
- RUNNING

There's a few more.

As for ios, I've been investigating implementing accelerometer api.  You
might be able to use core cordova accelerometer api yourself, independent
of my plugin.

On Wednesday, March 11, 2015, MaliciousMustard <notifications@github.com>
wrote:

> Hi,
>
> Let me start by saying that your plugin is really awesome and thank you so
> much for all your hard work. I'm also considering if my app goes well to
> get the premium Android version (since now I'm only using it for iOS).
>
> I was wondering if there is any way to detect whether the device is in
> STATIONARY mode or not?
> I checked the JSON object that is passed to the callback function and I
> don't see any fields regarding the mode. I thought for a second to use the
> speed property to determine whether the user is moving or not, but there
> were times where the mode was MOVING (in the debug messages) but the
> speed was -1.
>
> Thank you for your help.
>
> Best regards,
> Alex
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/154>
> .
>


-- 
Snet from Gmail Mobile

**Comment by christocracy** [comment]
I think the premium Android performance is better than ios (and I'm really
satisfied with ios performance).

Android is much more responsive at detecting when device is moving,
typically within 10 meters.  It can detect stationary very quickly
(configurable sample-rate; typically 10-30 seconds).

This sort of "activity detection" api is only possible on ios with M7
coprocessor (5s+).

For Android, it works great on my relatively old Nexus 4.

On Wednesday, March 11, 2015, MaliciousMustard <notifications@github.com>
wrote:

> Hi,
>
> Let me start by saying that your plugin is really awesome and thank you so
> much for all your hard work. I'm also considering if my app goes well to
> get the premium Android version (since now I'm only using it for iOS).
>
> I was wondering if there is any way to detect whether the device is in
> STATIONARY mode or not?
> I checked the JSON object that is passed to the callback function and I
> don't see any fields regarding the mode. I thought for a second to use the
> speed property to determine whether the user is moving or not, but there
> were times where the mode was MOVING (in the debug messages) but the
> speed was -1.
>
> Thank you for your help.
>
> Best regards,
> Alex
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/154>
> .
>


-- 
Snet from Gmail Mobile

**Comment by MaliciousMustard** [comment]
Thanks for the quick reply!
Hmm, I think I wasn't very clear on the description of the problem. I'm quite happy with the frequency of the updates for iOS. But what I was asking is if it's possible for a specific location update to also get the mode.
For example, if I enable `debug`, then I can see notifications like:
```
Location update: STATIONARY
SPD: -1 | DF: 15 | ACY: 65
```
or if moving:
```
Location update: MOVING
SPD: 1 | DF: 15 | ACY: 65
```

So it looks like the plugin can recognize if it's `STATIONARY` or `MOVING`. In the code I have a function like:
```
var callbackFn = function (location) {
    ....
}
```
I was wondering whether I can get the mode for a specific location update (if it's another argument I can pass in my callback function or some kind of configuration).

**Comment by christocracy** [comment]
The plugin has 2 modes: stationary & moving.

When stationary, plugin has setup a geofence and goes to sleep.  That's
stationary.  When you break out of geofence, aggressive tracking is engaged
and your app is awakened from suspended-mode, MOVING.

It's just an on/off switch.  The issue then is transmitting that state as
meta-data to callback.  Possible.  I'll have a look.

On Wednesday, March 11, 2015, MaliciousMustard <notifications@github.com>
wrote:

> Thanks for the quick reply!
> Hmm, I think I wasn't very clear on the description of the problem. I'm
> quite happy with the frequency of the updates for iOS. But what I was
> asking is if it's possible for a specific location update to also get the
> mode.
> For example, if I enable debug, then I can see notifications like:
>
> Location update: STATIONARY
> SPD: -1 | DF: 15 | ACY: 65
>
> or if moving:
>
> Location update: MOVING
> SPD: 1 | DF: 15 | ACY: 65
>
> So it looks like the plugin can recognize if it's STATIONARY or MOVING.
> In the code I have a function like:
>
> var callbackFn = function (location) {
>     ....
> }
>
> I was wondering whether I can get the mode for a specific location update
> (if it's another argument I can pass in my callback function or some kind
> of configuration).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/154#issuecomment-78390961>
> .
>


-- 
Snet from Gmail Mobile

**Comment by christocracy** [comment]
Have you tried out my SampleApp?  There's an undocumented, ios-only method
#onStationary, which is executed when the stationary geofence is created.
That might help you.

Search SampleApp for usage

On Wednesday, March 11, 2015, Chris Scott <christocracy@gmail.com> wrote:

> The plugin has 2 modes: stationary & moving.
>
> When stationary, plugin has setup a geofence and goes to sleep.  That's
> stationary.  When you break out of geofence, aggressive tracking is engaged
> and your app is awakened from suspended-mode, MOVING.
>
> It's just an on/off switch.  The issue then is transmitting that state as
> meta-data to callback.  Possible.  I'll have a look.
>
> On Wednesday, March 11, 2015, MaliciousMustard <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Thanks for the quick reply!
>> Hmm, I think I wasn't very clear on the description of the problem. I'm
>> quite happy with the frequency of the updates for iOS. But what I was
>> asking is if it's possible for a specific location update to also get the
>> mode.
>> For example, if I enable debug, then I can see notifications like:
>>
>> Location update: STATIONARY
>> SPD: -1 | DF: 15 | ACY: 65
>>
>> or if moving:
>>
>> Location update: MOVING
>> SPD: 1 | DF: 15 | ACY: 65
>>
>> So it looks like the plugin can recognize if it's STATIONARY or MOVING.
>> In the code I have a function like:
>>
>> var callbackFn = function (location) {
>>     ....
>> }
>>
>> I was wondering whether I can get the mode for a specific location update
>> (if it's another argument I can pass in my callback function or some kind
>> of configuration).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/154#issuecomment-78390961>
>> .
>>
>
>
> --
> Snet from Gmail Mobile
>


-- 
Snet from Gmail Mobile

**Comment by MaliciousMustard** [comment]
Oh you mean [this one](https://github.com/christocracy/cordova-plugin-background-geolocation/blob/master/example/SampleApp/www/js/index.js#L166-L180).
It looks exactly what I was looking for! I'll give it a try and get back to you.

Many thanks for your help. Keep up the great work!

**Comment by christocracy** [comment]
That's the one.

On Wednesday, March 11, 2015, MaliciousMustard <notifications@github.com>
wrote:

> Oh you mean this one
> <https://github.com/christocracy/cordova-plugin-background-geolocation/blob/master/example/SampleApp/www/js/index.js#L166-L180>
> .
> It looks exactly what I was looking for! I'll give it a try and get back
> to you.
>
> Many thanks for your help. Keep up the great work!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/154#issuecomment-78397304>
> .
>


-- 
Snet from Gmail Mobile

**Comment by MaliciousMustard** [comment]
Just tried it out and it works fine! So I could use the stationary callback to detect when a user entered in stationary mode and the normal success callback for moving. And as for Android, this feature is supported in the premium version.
I'll close this issue.
Thank you again for your help!

**Comment by christocracy** [comment]
Don't wait too long to send $ --  I'm going to double the price ;)

On Wednesday, March 11, 2015, MaliciousMustard <notifications@github.com>
wrote:

> Just tried it out and it works fine! So I could use the stationary
> callback to detect when a user entered in stationary mode and the normal
> success callback for moving. And as for Android, this feature is supported
> in the premium version.
> I'll close this issue.
> Thank you again for your help!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/154#issuecomment-78400146>
> .
>


-- 
Snet from Gmail Mobile
