### ISSUE TITLE
Android: generates huge number of API calls >1/second

### ISSUE THREAD

**Issue by mrtomhoward** [christocracy/cordova-plugin-background-geolocation#155]
Hey there,

Very happy with the plugin - thanks!  And will likely buy the premium version very soon - this week if I can make the client happy enough with the existing app to be willing to pay for it.

But I'm experiencing this issue and I guess I need to know whether it's my config or if it's something in the plugin (free version), or something else - perhaps to do with the hardware device I'm using.  I haven't tested on a second device yet - but can do if you think it's likely to be the issue.

FYI I'm testing on a ONIX AAP4-215 (I think it's a rebadged HTC) with Android 4.4.2.

My configuration is:
```
        bgGeo.configure(callbackFn, failureFn, {
            url: ajaxUrl,
            params: ajaxParams,
            headers: ajaxHeaders,
            locationTimeout: 300,
            desiredAccuracy: 10,
            stationaryRadius: 20,
            distanceFilter: 30,
            activityType: "Other",
            debug: false,
            stopOnTerminate: false
        });
```

The process runs in background mode just fine, but generates around 1 API call per second, and continues to do so for several hours.  In a two hour session it logged well over 6000 API calls.

Each API call responded with a 201 status.

Appreciate any help/advice you can offer.

UPDATE: looking further at the details of the updates it's posting, it's posting location updates for locations that are a great distance away from my current location, all of which are locations the phone has been to in the past few days, but not in the last 20 minutes during which I've done the latest test (and during which time I've been completely stationary).  On this basis it looks like something wrong with the device's geolocation function, but let me know if you can see anything else that would explain it.

Many thanks,
Tom

**Comment by christocracy** [comment]
Not sure, but your issue is moot with premium version, since the new
version no longer handles http in-plugin, it calls the js callback just
like ios.

The Android code has been completely refactored in every way and simplified.

On Tue, Mar 17, 2015 at 8:58 AM, mrtomhoward <notifications@github.com>
wrote:

> Hey there,
>
> Very happy with the plugin - thanks! And will likely buy the premium
> version very soon - this week if I can make the client happy enough with
> the existing app to be willing to pay for it.
>
> But I'm experiencing this issue and I guess I need to know whether it's my
> config or if it's something in the plugin (free version), or something else
> - perhaps to do with the hardware device I'm using. I haven't tested on a
> second device yet - but can do if you think it's likely to be the issue.
>
> FYI I'm testing on a ONIX AAP4-215 (I think it's a rebadged HTC) with
> Android 4.4.2.
>
> My configuration is:
>
>         bgGeo.configure(callbackFn, failureFn, {
>             url: ajaxUrl,
>             params: ajaxParams,
>             headers: ajaxHeaders,
>             locationTimeout: 300,
>             desiredAccuracy: 10,
>             stationaryRadius: 20,
>             distanceFilter: 30,
>             activityType: "Other",
>             debug: false,
>             stopOnTerminate: false
>         });
>
> The process runs in background mode just fine, but generates around 1 API
> call per second, and continues to do so for several hours. In a two hour
> session it logged well over 6000 API calls.
>
> Each API call responded with a 201 status.
>
> Appreciate any help/advice you can offer.
>
> Many thanks,
> Tom
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/155>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
