### ISSUE TITLE
Wish to grab Premium Version. Little Clarification Required

### ISSUE THREAD

**Issue by riddhimcc** [christocracy/cordova-plugin-background-geolocation#156]
Hello Sir,
I want to buy your premium vr. but I am really keen to know how I will install the plugin after payment.
Secondly I want to know about the accuracy in android. Is it better than before? In this matter I want to inform you I am very new to mobile app development and workin for android app.

**Comment by christocracy** [comment]
You install the plugin as you do any cordova plugin:

cordova plugin add
https://github.com/christocracy/cordova-background-geolocation.git

The github repo above is private, of course, with access granted after
payment.

The accuracy in Android is as good as iOS.

However, most important for Android is the improved *battery performance*
(5-10 times better).

The new Android version is better than iOS in its ability to very quickly
determine when device is moving since it implements the Android
ActivityDetection API.  This low-power api constantly samples the device’s
accelerometer & gyroscope and outputs an answer such as “STILL”, “RUNNING”,
“BICYCLE”, “IN_VEHICLE”, “WALKING”.  The sample-rate of this system can be
configured (every second, 10s, 30s, etc).

With iOS, the device must move ~3 blocks beyond its stationary position
before it turns the GPS on.  With Android, it takes just several meters.
Similary for stop-detection, iOS takes exactly 15min to determine device
has stopped — Android can detect you’ve stopped within the sample-rate of
the ActivityDetection API (e.g, 10s, 30s, etc).


On Fri, Mar 20, 2015 at 10:12 AM, riddhimcc <notifications@github.com>
wrote:

> Hello Sir,
> I want to buy your premium vr. but I am really keen to know how I will
> install the plugin after payment.
> Secondly I want to know about the accuracy in android. Is it better than
> before? In this matter I want to inform you I am very new to mobile app
> development and workin for android app.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/156>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by devteamshippeo** [comment]
Thanks again for your reply,

Is it possible to do some background geolocalisation with your plugin when user force-close the application ?

On ios, «  privacy > location services » , I see « allow location access » set to « always » when I use your plugin. Does it means you handle geolocation refresh if app is force-closed (not in background) ?  
But I don’t see it in « general > background app refresh »  

Is there an equivalence on Android ?

—
David


--  
David Barré

**Comment by christocracy** [comment]
If user force-closes the app while the plugin is enabled, the app will be
auto-booted again.

>But I don’t see it in « general > background app refresh »

Background app refresh is a different thing
<http://www.scottyloveless.com/blog/2014/background-app-refresh-explained>,
nothing to do with geolocation.

I made a separate plugin
<https://github.com/christocracy/cordova-plugin-background-fetch>
implementing the “background refresh api”.

Background Refresh is an iso-only system that awakes your app about every
15min (this interval is modified by iOS automatically based upon the user’s
behaviour (e.g. when the user is presumed to be sleeping,
background-refresh interval might occur every hour instead).

With my background-fetch plugin, when a background-refresh event occurs, my
plugin will execute your configured javascript callback — you have exactly
30s of running time before iOS suspends your app again.

On Fri, Mar 20, 2015 at 12:38 PM, devteamshippeo <notifications@github.com>
wrote:

> Thanks again for your reply,
>
> Is it possible to do some background geolocalisation with your plugin when
> user force-close the application ?
>
> On ios, « privacy > location services » , I see « allow location access »
> set to « always » when I use your plugin. Does it means you handle
> geolocation refresh if app is force-closed (not in background) ?
> But I don’t see it in « general > background app refresh »
>
> Is there an equivalence on Android ?
>
> —
> David
>
>
> --
> David Barré
>
>
> Le vendredi 20 mars 2015 à 15:37, Chris Scott a écrit :
>
> > You install the plugin as you do any cordova plugin:
> >
> > cordova plugin add
> > https://github.com/christocracy/cordova-background-geolocation.git
> >
> > The github repo above is private, of course, with access granted after
> > payment.
> >
> > The accuracy in Android is as good as iOS.
> >
> > However, most important for Android is the improved *battery performance*
> > (5-10 times better).
> >
> > The new Android version is better than iOS in its ability to very quickly
> > determine when device is moving since it implements the Android
> > ActivityDetection API. This low-power api constantly samples the device’s
> > accelerometer & gyroscope and outputs an answer such as “STILL”,
> “RUNNING”,
> > “BICYCLE”, “IN_VEHICLE”, “WALKING”. The sample-rate of this system can be
> > configured (every second, 10s, 30s, etc).
> >
> > With iOS, the device must move ~3 blocks beyond its stationary position
> > before it turns the GPS on. With Android, it takes just several meters.
> > Similary for stop-detection, iOS takes exactly 15min to determine device
> > has stopped — Android can detect you’ve stopped within the sample-rate of
> > the ActivityDetection API (e.g, 10s, 30s, etc).
> >
> >
> > On Fri, Mar 20, 2015 at 10:12 AM, riddhimcc <notifications@github.com
> (mailto:notifications@github.com)>
> > wrote:
> >
> > > Hello Sir,
> > > I want to buy your premium vr. but I am really keen to know how I will
> > > install the plugin after payment.
> > > Secondly I want to know about the accuracy in android. Is it better
> than
> > > before? In this matter I want to inform you I am very new to mobile app
> > > development and workin for android app.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/156
> >
> > > .
> > >
> >
> >
> >
> > --
> > Chris Scott
> > Transistor Software <http://www.transistorsoft.com>
> >
> > —
> > Reply to this email directly or view it on GitHub (
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/156#issuecomment-84033366
> ).
>
> >
> >
> >
> >
> >
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/156#issuecomment-84064199>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by riddhimcc** [comment]
Before I buy would like to clear the following points:
 I have used your plugin (free vr.) to develop an android app to track user silently from background. 

	A. I find that when the device is stationary the app is returning co-ordinates which ideally it should not.
	B. Some times the co-ordinates returned by the app is fluctuating within a range of few Kms. Same thing is happening when the device is stationary.
	C. The frequency in wchich co-ordinates are being returned by the app is varrying drastically. SOme times in a minute I am getting 3 - 4 co ordinates and sometimes one co-ordinate in 15 minutes. Same thing is happening when the device is stationary or moving.
	D. I developed the app in Cordova 2.9.1. Is your Premium Vr. compatible with this cordova vr.?
	E. After buying Plugin, in case I face any problem, will I get Support from your end?
	F. I have free account in GitHub, will I still use your Premium Plugin after purchase?
	
	Please find below the code what I have  developed for my app. Kindly Suggest whether code is ok or I am missing out something due to which correct position are not being returned.

window.navigator.geolocation.getCurrentPosition(onFrontGeoSuccess, onFrontGeoFail);
		var bgGeo = window.plugins.backgroundGeoLocation;
		bgGeo.configure(onBackGeoSuccess, onBackGeoFail, {
			url: 'http://myurl/BackgroundLocationTrack.aspx',//''http://only.for.android.com/update_location.json', // <-- Android ONLY:  your server url to send locations to
	        params: {
	        	userId: localStorage.getItem("userId"),
	        	uuid: device.uuid    //  <-- Android ONLY:  HTTP POST params sent to your server when persisting locations.
	            //, foo: 'bar'                              //  <-- Android ONLY:  HTTP POST params sent to your server when persisting locations.
	        },
	        headers: {                                   // <-- Android ONLY:  Optional HTTP headers sent to your configured #url when persisting locations
	            "X-Foo": "BAR"
	        },
	        
	        desiredAccuracy: 0,
	        stationaryRadius: 20,
	        distanceFilter: 30,
			notificationTitle: 'Checking Background tracking', // <-- android only, customize the title of the notification
	        notificationText: 'ENABLED.....', // <-- android only, customize the text of the notification
			//activityType: 'AutomotiveNavigation',
			debug: false, // enable this hear sounds for background-geolocation life-cycle.
			stopOnTerminate: false // enable this to clear background location settings when the app terminates
		});
		var onBackGeoSuccess = function(location) {
			console.log('[js] BackgroundGeoLocation callback:  ' + location.latitude + ',' + location.longitude);
			// Do your HTTP request here to POST location to your server.
			//
			// Ajax Call
			//
			//ajaxCallback.call(this);
		};
		var onBackGeoFail = function(error) {
			//console.log('BackgroundGeoLocation error');
			//bgGeo.finish();
		}

		// Turn ON the background-geolocation system.  The user will be tracked whenever they suspend the app.
		bgGeo.start();
		
		// bgGeo.stop();

		function ajaxCallback(){
			// on Server update success or failure, run the following

			//bgGeo.finish();
		}

**Comment by christocracy** [comment]
> A. I find that when the device is stationary the app is returning co-ordinates which ideally it should not.
>
> Premium version has completely refactored Android.  When Android is
stationary it doesn’t sample the GPS anymore.  Premium version uses
ActivityRecognition API to determine when device is moving.
ActivityRecognition API uses accelerometer & gyroscope.  Problem solved.

> B. Some times the co-ordinates returned by the app is fluctuating within a range of few Kms. Same thing is happening when the device is stationary.
>
> Solved as in previous.

> C. The frequency in wchich co-ordinates are being returned by the app is varrying drastically. SOme times in a minute I am getting 3 - 4 co ordinates and sometimes one co-ordinate in 15 minutes. Same thing is happening when the device is stationary or moving.
>
> Android has been completely refactored to use Android
FusedLocationProvider
<http://www.kpbird.com/2013/06/fused-location-provider-example.html>from
Google Play Services, a more efficient and advanced LocationProvider than
in the free-version.

> D. I developed the app in Cordova 2.9.1. Is your Premium Vr. compatible with this cordova vr.?
>
> You need to upgrade to 3.x.  The new Cordova plugin system, upon which my
plugin is based, wasn’t released until 3.0.

> E. After buying Plugin, in case I face any problem, will I get Support from your end?
>
> You will have access to my private repo along with all the other paying
customers.  You may post issues as normal.

> F. I have free account in GitHub, will I still use your Premium Plugin after purchase?
>
> My checkout system, after completing the transaction, will *automatically*
add your *github* user to my private repo.

> Please find below the code what I have  developed for my app. Kindly Suggest whether code is ok or I am missing out something due to which correct position are not being returned.
>
> If you want me to look at code, please ensure it’s formatted properly.
Post a gist <https://gist.github.com> at least.

>  window.navigator.geolocation.getCurrentPosition(onFrontGeoSuccess,
> onFrontGeoFail);
> var bgGeo = window.plugins.backgroundGeoLocation;
> bgGeo.configure(onBackGeoSuccess, onBackGeoFail, {
> url: 'http://myurl/BackgroundLocationTrack.aspx',//''
> http://only.for.android.com/update_location.json', // <-- Android ONLY:
> your server url to send locations to
> params: {
> userId: localStorage.getItem("userId"),
> uuid: device.uuid // <-- Android ONLY: HTTP POST params sent to your
> server when persisting locations.
> //, foo: 'bar' // <-- Android ONLY: HTTP POST params sent to your server
> when persisting locations.
> },
> headers: { // <-- Android ONLY: Optional HTTP headers sent to your
> configured #url when persisting locations
> "X-Foo": "BAR"
> },
>
>         desiredAccuracy: 0,
>         stationaryRadius: 20,
>         distanceFilter: 30,
>         notificationTitle: 'Checking Background tracking', // <-- android only, customize the title of the notification
>         notificationText: 'ENABLED.....', // <-- android only, customize the text of the notification
>         //activityType: 'AutomotiveNavigation',
>         debug: false, // enable this hear sounds for background-geolocation life-cycle.
>         stopOnTerminate: false // enable this to clear background location settings when the app terminates
>     });
>     var onBackGeoSuccess = function(location) {
>         console.log('[js] BackgroundGeoLocation callback:  ' + location.latitude + ',' + location.longitude);
>         // Do your HTTP request here to POST location to your server.
>         //
>         // Ajax Call
>         //
>         //ajaxCallback.call(this);
>     };
>     var onBackGeoFail = function(error) {
>         //console.log('BackgroundGeoLocation error');
>         //bgGeo.finish();
>     }
>
>     // Turn ON the background-geolocation system.  The user will be tracked whenever they suspend the app.
>     bgGeo.start();
>
>     // bgGeo.stop();
>
>     function ajaxCallback(){
>         // on Server update success or failure, run the following
>
>         //bgGeo.finish();
>     }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/156#issuecomment-84263046>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
