### ISSUE TITLE
Automatic start on Android boot

### ISSUE THREAD

**Issue by anaibol** [christocracy/cordova-plugin-background-geolocation#157]
Hi, I would like to know if the service is started automatically on system startup on Android.
Thanks!

**Comment by christocracy** [comment]
No.

On Tue, Mar 24, 2015 at 7:18 PM, Juan Anibal Micheli <
notifications@github.com> wrote:

> Hi, I would like to know if the service is started automatically on system
> startup on Android.
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/157>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by anaibol** [comment]
Neither the premium one I suppose. Thanks.

**Comment by christocracy** [comment]
I’ll experiment a bit in Premium and see what I can do.  I’ll ping back
here if I make it work.

On Wed, Mar 25, 2015 at 1:44 PM, Juan Anibal Micheli <
notifications@github.com> wrote:

> Neither the premium one I suppose. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/157#issuecomment-86141056>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
Ok, I got my Android app to auto-boot in Premium version exactly as
described here
<http://stackoverflow.com/questions/4562734/android-starting-service-at-boot-time>



On Tue, Mar 24, 2015 at 7:18 PM, Juan Anibal Micheli <
notifications@github.com> wrote:

> Hi, I would like to know if the service is started automatically on system
> startup on Android.
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/157>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
The way I do it is to fire-up Android ActivityRecognition at device boot.
When the device is detected to be moving, the foreground Activity is
booted.  My plugin then begins sending geolocations to the javascript
callback.

It might be a bit unexpected for the user to see your application
auto-booted like this but it gets the Javascript running.

On Wed, Mar 25, 2015 at 9:23 PM, Chris Scott <christocracy@gmail.com> wrote:

> Ok, I got my Android app to auto-boot in Premium version exactly as
> described here
> <http://stackoverflow.com/questions/4562734/android-starting-service-at-boot-time>
>
>
>
> On Tue, Mar 24, 2015 at 7:18 PM, Juan Anibal Micheli <
> notifications@github.com> wrote:
>
>> Hi, I would like to know if the service is started automatically on
>> system startup on Android.
>> Thanks!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/157>
>> .
>>
>
>
>
> --
> Chris Scott
> Transistor Software <http://www.transistorsoft.com>
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by anaibol** [comment]
Mm I was not planning to open the cordova app on boot, but only this service or process to run in background. I have been investigating how Fousquare knows where I am each time I move without using the GPS. There is a cached process running in background since the device boots, but I don't know if it's that.

**Comment by christocracy** [comment]
It’s really easy to handle the BOOT event in Android and start whatever
kind of service you want.

On Thu, Mar 26, 2015 at 3:20 PM, Juan Anibal Micheli <
notifications@github.com> wrote:

> Mm I was not planning to open the cordova app on boot, but only this
> service or process to run in background. I have been investigating how
> Fousquare knows where I am each time I move without using the GPS. There is
> a cached process running in background since the device boots, but I don't
> know if it's that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/157#issuecomment-86679006>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
FYI auto-start on boot is implemented in [Premium Version](http://christocracy.github.io/cordova-background-geolocation/)
