### ISSUE TITLE
Good parameter for automotive geolocation ?

### ISSUE THREAD

**Issue by davidbarre** [christocracy/cordova-plugin-background-geolocation#158]
Hello, 

I have some difficulties to have a regular and good working geolocation.
(On ios, I remark geocation works very well when google maps is open and in front. 
OR when wifi is up and running )

I try to find good parameters to have an automotive track works regulary.
Can someone share this geoloc parameter with me ?
Actually I got geolocation very randomly in car in city

My actual configuration below : 
```javascript
	var geoloc_options = {
            url: api_adr + 'location', 
            headers: {                                  
                'token' : Session.token()
            },
            desiredAccuracy: 10,
            stationaryRadius: 10,
            distanceFilter: 300,
            notificationTitle: 'xxxxxxxx', 
            notificationText: 'xxxxxxxx', 
            activityType: 'AutomotiveNavigation',
            debug: false,
            stopOnTerminate: false, 
            locationTimeout: 10
    };
```
I saw you don't use "locationTimeout" parameter ?
So, I will try your demo-app's parameter and remove locationTimeout tonight

```javascript
configure(callbackFn, failureFn, {
(...)
            desiredAccuracy: 10,
            stationaryRadius: 20,
            distanceFilter: 30,
(...)
            activityType: "AutomotiveNavigation",       // <-- iOS-only
```

Thanks, Regards

--
David Barré

**Comment by christocracy** [comment]
I get flawless tracking on iOS in every city I’ve visited.  I see you
have #desiredAccuracy:
10 — set that to 0 for best accuracy.  Your distanceFilter: 300 is rather
high.  iOS has automatic elasticity, meaning it scales the distanceFilter
automatically based upon speed.  Set distanceFilter: 30

Eg:
https://github.com/christocracy/cordova-plugin-background-geolocation/blob/master/images/distance-filter-city.png

- track on left is me in a cab.
- track on right is me walking.
- that’s distanceFilter: 30, auto-scaled based upon speed.

Also, set debug: true

Where are you located?

On Mon, Mar 30, 2015 at 2:09 PM, davidbarre <notifications@github.com>
wrote:

> Hello,
>
> I have some difficulties to have a regular and good working geolocation.
> (On ios, I remark geocation works very well when google maps is open and
> in front.
> OR when wifi is up and running )
>
> I try to find good parameters to have an automotive track works regulary.
> Can someone share this geoloc parameter with me ?
> Actually I got geolocation very randomly in car in city
>
> My actual configuration below :
>
>     var geoloc_options = {
>             url: api_adr + 'location',
>             headers: {
>                 'token' : Session.token()
>             },
>             desiredAccuracy: 10,
>             stationaryRadius: 10,
>             distanceFilter: 300,
>             notificationTitle: 'xxxxxxxx',
>             notificationText: 'xxxxxxxx',
>             activityType: 'AutomotiveNavigation',
>             debug: false,
>             stopOnTerminate: false,
>             locationTimeout: 10
>     };
>
> I saw you don't use "locationTimeout" parameter ?
> So, I will try your demo-app's parameter and remove locationTimeout tonight
>
> configure(callbackFn, failureFn, {
> (...)
>             desiredAccuracy: 10,
>             stationaryRadius: 20,
>             distanceFilter: 30,
> (...)
>             activityType: "AutomotiveNavigation",       // <-- iOS-only
>
> Thanks, Regards
>
> David Barré
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/158>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by davidbarre** [comment]
I'm located in Paris, France

Thanks I try your parameter now

On this map, you can see my position (I don't follow the blue line)
https://imgur.com/fvi9pXS,ZZMxOiQ#1
I put a black arrow to the position where I turn down google maps on my iphone

On this map, I zoom on the end of my journey
https://imgur.com/fvi9pXS,ZZMxOiQ
I can't follow my ride anymore

I update you after my test

--
David

**Comment by christocracy** [comment]
- GPS is a radio.  It outputs a constant stream of data.
- Imagine is has a power-selector:  0, 10, 100, 1000.
- lower number = high-accuracy, high power;  high number:  low-accuracy,
low power.
- you’ve configured it for 10.

Now you turn on google-maps, which cranks up the accuracy to 0.

Even though you asked for accuracy: 10, another app cranked up the accuracy
to 0.  *All* apps will receive these increased accuracy readings now.






On Mon, Mar 30, 2015 at 2:32 PM, davidbarre <notifications@github.com>
wrote:

> I'm located in Paris, France
>
> Thanks I try your parameter now
>
> On this map, you can see my position (I don't follow the blue line)
> https://imgur.com/fvi9pXS,ZZMxOiQ#1
> I put a black arrow to the position where I turn down google maps on my
> iphone
>
> On this map, I zoom on the end of my journey
> https://imgur.com/fvi9pXS,ZZMxOiQ
> I can't follow my ride anymore
>
> I update you after my test
>
> David
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/158#issuecomment-87782374>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by davidbarre** [comment]
Back,

I tested parameters given earlier :

```javascript
	var geoloc_options = {
            url: api_adr + 'location', 
            params: { (...) },
            headers: { (...)},
            desiredAccuracy: 0,
            stationaryRadius: 20,
            distanceFilter: 30,
            notificationTitle: 'xxxx', 
            notificationText: 'xxxx', 
            activityType: 'AutomotiveNavigation',
            debug: false,
            stopOnTerminate: false, 
    		//  locationTimeout: 10
    };
```
Find below results of my test
I'm starting to walk ~1.5km in a mostly open sky area (green circle)
And after I take a cab and travel 9km
Phone was locked and app in backgroup

http://imgur.com/luEvQvX
Live gmaps here (http://tinyurl.com/o4rdq9f)

There are few points positions when walking and only the end of the car part.

--
David

**Comment by christocracy** [comment]
You should be using debug: true.

The plugin will emit sounds and show notifications.

Also, try booting my SampleApp in repo.  See README for details.

Show me how you're adding the plugin to your project.

On Monday, March 30, 2015, davidbarre <notifications@github.com> wrote:

> Back,
>
> I tested parameters given earlier :
>
>     var geoloc_options = {
>             url: api_adr + 'location',
>             params: { (...) },
>             headers: { (...)},
>             desiredAccuracy: 0,
>             stationaryRadius: 20,
>             distanceFilter: 30,
>             notificationTitle: 'xxxx',
>             notificationText: 'xxxx',
>             activityType: 'AutomotiveNavigation',
>             debug: false,
>             stopOnTerminate: false,
>             //  locationTimeout: 10
>     };
>
> Find below results of my test
> I'm starting to walk ~1.5km in a mostly open sky area (green circle)
> And after I take a cab and travel 9km
> Phone was locked and app in backgroup
>
> http://imgur.com/luEvQvX
> Live gmaps here (http://tinyurl.com/o4rdq9f)
>
> There are few points positions when walking and only the end of the car
> part.
>
> David
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/158#issuecomment-87847505>
> .
>


-- 
Snet from Gmail Mobile

**Comment by davidbarre** [comment]
I use phonegap build, so : 		
<gap:plugin name="org.transistorsoft.cordova.background-geolocation" version="0.3.5"  />

**Comment by christocracy** [comment]
Too bad for you.  PGB is so limiting.

Which version is being installed by PGB?

What ios version and phone model?

On Monday, March 30, 2015, davidbarre <notifications@github.com> wrote:

> I use phonegap build, so :
>
>  —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/158#issuecomment-87858841>
> .
>


-- 
Snet from Gmail Mobile

**Comment by davidbarre** [comment]
according to https://build.phonegap.com/plugins/1299
master/e99380c

iphone 5 
ios 8.1.2

can you tell me some restrictions of PGB ?

Thanks again

**Comment by christocracy** [comment]
Not the latest, dates back to November, but nothing significant has changed
since then.

Disadvantage is PGB only allows you to use plugins which have been
submitted to their server.  You cannot use my latest version from github
repo, for example.

Since my latest premium version, with much improved Android version, is
non-free, I no longer support PGB.

On Monday, March 30, 2015, davidbarre <notifications@github.com> wrote:

> according to https://build.phonegap.com/plugins/1299
> master/e99380c
>
> iphone 5
> ios 8.1.2
>
> can you tell me some restrictions of PGB ?
>
> Thanks again
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/158#issuecomment-87887355>
> .
>


-- 
Snet from Gmail Mobile
