### ISSUE TITLE
Android old version support

### ISSUE THREAD

**Issue by theofficeexpress** [christocracy/cordova-plugin-background-geolocation#160]
I am successfully running the plugin on iOS 8.1. The app is crashing on an old Android phone running ~2.3.6/Gingerbread. Before I go too far debugging, I was curious if this version was supported. What version would you expect to be supported?

Thanks!

**Comment by christocracy** [comment]
2.3.6?  Not a chance.  4.0.3+

My premium version might work better on old phones since it's much simpler
code.

On Thursday, April 2, 2015, theofficeexpress <notifications@github.com>
wrote:

> I am successfully running the plugin on iOS 8.1. The app is crashing on an
> old Android phone running ~2.3.6/Gingerbread. Before I go too far
> debugging, I was curious if this version was supported. What version would
> you expect to be supported?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/160>
> .
>


-- 
Snet from Gmail Mobile

**Comment by jvwelzen** [comment]
Maybe 500 dollars, is a bit to much for some people :-(

**Comment by christocracy** [comment]
What would you have me do?  You're free to explore the Android APIs and
perform exhaustive field-testing yourself for a year-and-a-half

On Sunday, May 10, 2015, jvwelzen <notifications@github.com> wrote:

> Maybe 500 dollars, is a bit to much for some people :-(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/160#issuecomment-100655492>
> .
>


-- 
Snet from Gmail Mobile
