### ISSUE TITLE
Why "only" background location?

### ISSUE THREAD

**Issue by stefanmdt** [christocracy/cordova-plugin-background-geolocation#161]
Hi! I've tested the sample app and it looks very promising! But one - perhaps silly - question came up: Why is the plugin limited to background tracking? Why not just tracking but with background ability? Then one could get rid of additional foreground tracking mechanism ...

**Comment by cezarboicu** [comment]
Hi. I have the same question. Is it mandatory to use the geolocation for the foreground ? As sometimes, the tracking just doesn't kick in. Do you have any idea what might be ? 
Thanx.

**Comment by christocracy** [comment]
Currently, you must use the standard cordova geolocation in the foreground.

I’m currently doing a bunch of refactoring in the Premium version and I
might expand the plugin to operate in the foreground as well.

On Mon, Apr 27, 2015 at 2:21 PM, cezarboicu <notifications@github.com>
wrote:

> Hi. I have the same question. Is it mandatory to use the geolocation for
> the foreground ? As sometimes, the tracking just doesn't kick in. Do you
> have any idea what might be ?
> Thanx.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/161#issuecomment-96769386>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by stefanmdt** [comment]
Thanks for your reply. I've implemented the hybrid approach like it is shown in the example and it works quite well. But pure foreground tracking is not as sophisticated as the background tracking of your plugin, I guess. So foreground tracking would be a nice feature ...

**Comment by christocracy** [comment]
Foreground tracking doesn't need to be sophisticated and mine probably
won't be either.  It needs to be accurate with a fast sample rate (ie: a small
distanceFilter of 5m perhaps)



On Tuesday, April 28, 2015, stefanmdt <notifications@github.com> wrote:

> Thanks for your reply. I've implemented the hybrid approach like it is
> shown in the example and it works quite well. But pure foreground tracking
> is not as sophisticated as the background tracking of your plugin, I guess.
> So foreground tracking would be a nice feature ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/161#issuecomment-96982310>
> .
>


-- 
Snet from Gmail Mobile

**Comment by cezarboicu** [comment]
Thanx for the quick reply then :). I implemented also the hybrid and it seems to be working now for all scenarious.

**Comment by christocracy** [comment]
The amount of time people interact with your app in foreground is *far *less
than the time it’s running in bg.  It’s ok to blast the GPS for that short
time in foreground.  It’s only those long hours in bg where we need to take
care with battery-usage.

On Tue, Apr 28, 2015 at 8:53 AM, cezarboicu <notifications@github.com>
wrote:

> Thanx for the quick reply then :). I implemented also the hybrid and it
> seems to be working now for all scenarious.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/161#issuecomment-97051707>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
