### ISSUE TITLE
Plugin not installed 

### ISSUE THREAD

**Issue by Ank333** [christocracy/cordova-plugin-background-geolocation#162]
Hi ,

I am trying this plugin and installing it via CL but it won't work.

I am running it in Mac.

Can you help me ?

Thanks

**Comment by christocracy** [comment]
That’s not a whole lot of information.

That’s like saying “Help, I’m on fire.  Please bring water” and I don’t
know where you live.

Show me exactly what you’re writing in console as well as error message.
Use gists and/or code-formatting or I won’t look at it.


On Mon, Apr 6, 2015 at 9:44 AM, Ank333 <notifications@github.com> wrote:

> Hi ,
>
> I am trying this plugin and installing it via CL but it won't work.
>
> I am running it in Mac.
>
> Can you help me ?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/162>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by Ank333** [comment]
I am simply adding the plugin 
 cordova plugin add https://github.com/christocracy/cordova-plugin-background-geolocation.git
Fetching plugin "https://github.com/christocracy/cordova-plugin-background-geolocation.git" via git clone
cp: dest file already exists: /Volumes/Work_Data/geobased/plugins/org.transistorsoft.cordova.background-geolocation/LICENSE

cp: dest file already exists: /Volumes/Work_Data/geobased/plugins/org.transistorsoft.cordova.background-geolocation/LICENSE
cp: dest file already exists: /Volumes/Work_Data/geobased/plugins/org.transistorsoft.cordova.background-geolocation/README.md

skipping existing file: README.md
skipping existing file: ic_launcher.png
skipping existing file: ic_launcher.png
skipping existing file: ic_launcher.png
skipping existing file: ic_launcher.png
skipping existing file: ic_launcher.png
skipping existing file: ic_launcher.png
skipping existing file: playstore-icon.png
skipping existing file: Contents.json
skipping existing file: Icon-40.png
skipping existing file: Icon-40@2x.png
skipping existing file: Icon-40@3x.png
skipping existing file: Icon-60.png
skipping existing file: Icon-60@2x.png
skipping existing file: Icon-60@3x.png
skipping existing file: Icon-72.png
skipping existing file: Icon-72@2x.png
skipping existing file: Icon-76.png
skipping existing file: Icon-76@2x.png
skipping existing file: Icon-Small-50.png
skipping existing file: Icon-Small-50@2x.png
skipping existing file: Icon-Small.png
skipping existing file: Icon-Small@2x.png
skipping existing file: Icon-Small@3x.png
skipping existing file: Icon.png
skipping existing file: Icon@2x.png
skipping existing file: iTunesArtwork.png
skipping existing file: iTunesArtwork@2x.png
skipping existing file: config.xml
skipping existing file: contributors.txt
skipping existing file: README.md
skipping existing file: resource_copier.js
skipping existing file: bootstrap-min.css
skipping existing file: index.css
skipping existing file: glyphicons-halflings-regular.eot
skipping existing file: glyphicons-halflings-regular.svg
skipping existing file: glyphicons-halflings-regular.ttf
skipping existing file: glyphicons-halflings-regular.woff
skipping existing file: logo.png
skipping existing file: still_blue.png
skipping existing file: index.html
skipping existing file: index.js
skipping existing file: jquery-2.1.1.js
skipping existing file: index.html
skipping existing file: index.js
skipping existing file: android-battery-detail.png
skipping existing file: android-battery.png
skipping existing file: android-sample-app.png
skipping existing file: distance-filter-city.png
skipping existing file: distance-filter-highway.png
skipping existing file: enable-background-audio.png
cp: dest file already exists: /Volumes/Work_Data/geobased/plugins/org.transistorsoft.cordova.background-geolocation/LICENSE
cp: dest file already exists: /Volumes/Work_Data/geobased/plugins/org.transistorsoft.cordova.background-geolocation/README.md
cp: dest file already exists: /Volumes/Work_Data/geobased/plugins/org.transistorsoft.cordova.background-geolocation/plugin.xml

skipping existing file: BackgroundGpsPlugin.java
skipping existing file: LocationUpdateService.java
skipping existing file: DAOFactory.java
skipping existing file: Location.java
skipping existing file: LocationDAO.java
skipping existing file: LocationOpenHelper.java
skipping existing file: SQLiteLocationDAO.java
skipping existing file: notification.png
skipping existing file: CDVBackgroundGeoLocation.h
skipping existing file: CDVBackgroundGeoLocation.m
skipping existing file: BackgroundGeoLocation.cs
skipping existing file: BackgroundGeoLocationOptions.cs
skipping existing file: DebugAudioNotifier.cs
skipping existing file: ExtensionMethods.cs
skipping existing file: IBackgroundGeoLocation.cs
skipping existing file: BackgroundGeoLocation.js
Installing "org.transistorsoft.cordova.background-geolocation" for android
Fetching plugin "org.apache.cordova.dialogs" via plugin registry
npm http GET http://cordova.iriscouch.com/registry/_design/app/_rewrite/org.apache.cordova.dialogs/-/org.apache.cordova.dialogs-0.3.0.tgz
npm http 200 http://cordova.iriscouch.com/registry/_design/app/_rewrite/org.apache.cordova.dialogs/-/org.apache.cordova.dialogs-0.3.0.tgz
Failed to install 'org.transistorsoft.cordova.background-geolocation':Error: shasum check failed for /var/folders/mt/t5vnln9155sg32pd261104s40000gn/T/npm-1942-g5yenBvU/1428328148315-0.8391071865335107/tmp.tgz
Expected: c53dea81ab54175162b00df9c295f5d688fb19b4
Actual:   4e1027a868e5b773cedde1020df1df2aadfb1c84
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/sha/index.js:32:8
    at ReadStream.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/sha/index.js:61:7)
    at ReadStream.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
Error: shasum check failed for /var/folders/mt/t5vnln9155sg32pd261104s40000gn/T/npm-1942-g5yenBvU/1428328148315-0.8391071865335107/tmp.tgz
Expected: c53dea81ab54175162b00df9c295f5d688fb19b4
Actual:   4e1027a868e5b773cedde1020df1df2aadfb1c84
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/sha/index.js:32:8
    at ReadStream.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/sha/index.js:61:7)
    at ReadStream.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by christocracy** [comment]
When in doubt, destroy the platform, remove the plugin, re-add the plugin.
 re build.

```
$ rm -rf platforms/android
$ rm -rf plugins/org.transistorsoft.cordova.background-geolocation
$ rm plugins/android.json

// now re-add the plugin
$ cordova plugin add
https://github.com/christocracy/cordova-plugin-background-geolocation.git
$ cordova platform add android
$ cordova build android

```

On Mon, Apr 6, 2015 at 9:54 AM, Ank333 <notifications@github.com> wrote:

> I am simply adding the plugin
> cordova plugin add
> https://github.com/christocracy/cordova-plugin-background-geolocation.git
> Fetching plugin "
> https://github.com/christocracy/cordova-plugin-background-geolocation.git"
> via git clone
> cp: dest file already exists:
> /Volumes/Work_Data/geobased/plugins/org.transistorsoft.cordova.background-geolocation/LICENSE
>
> cp: dest file already exists:
> /Volumes/Work_Data/geobased/plugins/org.transistorsoft.cordova.background-geolocation/LICENSE
> cp: dest file already exists:
> /Volumes/Work_Data/geobased/plugins/org.transistorsoft.cordova.background-geolocation/README.md
>
> skipping existing file: README.md
> skipping existing file: ic_launcher.png
> skipping existing file: ic_launcher.png
> skipping existing file: ic_launcher.png
> skipping existing file: ic_launcher.png
> skipping existing file: ic_launcher.png
> skipping existing file: ic_launcher.png
> skipping existing file: playstore-icon.png
> skipping existing file: Contents.json
> skipping existing file: Icon-40.png
> skipping existing file: Icon-40@2x.png
> skipping existing file: Icon-40@3x.png
> skipping existing file: Icon-60.png
> skipping existing file: Icon-60@2x.png
> skipping existing file: Icon-60@3x.png
> skipping existing file: Icon-72.png
> skipping existing file: Icon-72@2x.png
> skipping existing file: Icon-76.png
> skipping existing file: Icon-76@2x.png
> skipping existing file: Icon-Small-50.png
> skipping existing file: Icon-Small-50@2x.png
> skipping existing file: Icon-Small.png
> skipping existing file: Icon-Small@2x.png
> skipping existing file: Icon-Small@3x.png
> skipping existing file: Icon.png
> skipping existing file: Icon@2x.png
> skipping existing file: iTunesArtwork.png
> skipping existing file: iTunesArtwork@2x.png
> skipping existing file: config.xml
> skipping existing file: contributors.txt
> skipping existing file: README.md
> skipping existing file: resource_copier.js
> skipping existing file: bootstrap-min.css
> skipping existing file: index.css
> skipping existing file: glyphicons-halflings-regular.eot
> skipping existing file: glyphicons-halflings-regular.svg
> skipping existing file: glyphicons-halflings-regular.ttf
> skipping existing file: glyphicons-halflings-regular.woff
> skipping existing file: logo.png
> skipping existing file: still_blue.png
> skipping existing file: index.html
> skipping existing file: index.js
> skipping existing file: jquery-2.1.1.js
> skipping existing file: index.html
> skipping existing file: index.js
> skipping existing file: android-battery-detail.png
> skipping existing file: android-battery.png
> skipping existing file: android-sample-app.png
> skipping existing file: distance-filter-city.png
> skipping existing file: distance-filter-highway.png
> skipping existing file: enable-background-audio.png
> cp: dest file already exists:
> /Volumes/Work_Data/geobased/plugins/org.transistorsoft.cordova.background-geolocation/LICENSE
> cp: dest file already exists:
> /Volumes/Work_Data/geobased/plugins/org.transistorsoft.cordova.background-geolocation/README.md
> cp: dest file already exists:
> /Volumes/Work_Data/geobased/plugins/org.transistorsoft.cordova.background-geolocation/plugin.xml
>
> skipping existing file: BackgroundGpsPlugin.java
> skipping existing file: LocationUpdateService.java
> skipping existing file: DAOFactory.java
> skipping existing file: Location.java
> skipping existing file: LocationDAO.java
> skipping existing file: LocationOpenHelper.java
> skipping existing file: SQLiteLocationDAO.java
> skipping existing file: notification.png
> skipping existing file: CDVBackgroundGeoLocation.h
> skipping existing file: CDVBackgroundGeoLocation.m
> skipping existing file: BackgroundGeoLocation.cs
> skipping existing file: BackgroundGeoLocationOptions.cs
> skipping existing file: DebugAudioNotifier.cs
> skipping existing file: ExtensionMethods.cs
> skipping existing file: IBackgroundGeoLocation.cs
> skipping existing file: BackgroundGeoLocation.js
> Installing "org.transistorsoft.cordova.background-geolocation" for android
> Fetching plugin "org.apache.cordova.dialogs" via plugin registry
> npm http GET
> http://cordova.iriscouch.com/registry/_design/app/_rewrite/org.apache.cordova.dialogs/-/org.apache.cordova.dialogs-0.3.0.tgz
> npm http 200
> http://cordova.iriscouch.com/registry/_design/app/_rewrite/org.apache.cordova.dialogs/-/org.apache.cordova.dialogs-0.3.0.tgz
> Failed to install
> 'org.transistorsoft.cordova.background-geolocation':Error: shasum check
> failed for
> /var/folders/mt/t5vnln9155sg32pd261104s40000gn/T/npm-1942-g5yenBvU/1428328148315-0.8391071865335107/tmp.tgz
> Expected: c53dea81ab54175162b00df9c295f5d688fb19b4
> Actual: 4e1027a868e5b773cedde1020df1df2aadfb1c84
> at
> /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/sha/index.js:32:8
> at ReadStream.
> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/sha/index.js:61:7)
> at ReadStream.emit (events.js:129:20)
> at _stream_readable.js:908:16
> at process._tickCallback (node.js:355:11)
> Error: shasum check failed for
> /var/folders/mt/t5vnln9155sg32pd261104s40000gn/T/npm-1942-g5yenBvU/1428328148315-0.8391071865335107/tmp.tgz
> Expected: c53dea81ab54175162b00df9c295f5d688fb19b4
> Actual: 4e1027a868e5b773cedde1020df1df2aadfb1c84
> at
> /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/sha/index.js:32:8
> at ReadStream.
> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/sha/index.js:61:7)
> at ReadStream.emit (events.js:129:20)
> at _stream_readable.js:908:16
> at process._tickCallback (node.js:355:11)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/162#issuecomment-90071570>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by Ank333** [comment]
Ok Let me try it again

**Comment by Ank333** [comment]
Same Issue

**Comment by christocracy** [comment]
repeat everything again and **send me the log**

On Mon, Apr 6, 2015 at 10:06 AM, Ank333 <notifications@github.com> wrote:

> Same Issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/162#issuecomment-90076280>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by Ank333** [comment]
ok

**Comment by christocracy** [comment]
I’m 99.9% sure it’s not a problem with my plugin, more likely a problem on
your end.

On Mon, Apr 6, 2015 at 10:12 AM, Chris Scott <christocracy@gmail.com> wrote:

> repeat everything again and **send me the log**
>
> On Mon, Apr 6, 2015 at 10:06 AM, Ank333 <notifications@github.com> wrote:
>
>> Same Issue
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/162#issuecomment-90076280>
>> .
>>
>
>
>
> --
> Chris Scott
> Transistor Software <http://www.transistorsoft.com>
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by Ank333** [comment]
I have installed other plugins and they are installing correctly even I had tried to make different sample projects and installed your plugin but same issue appearing ,Though I am trying to follow your steps again.

**Comment by christocracy** [comment]
People rarely have issue installing my plugin.  Me, never.

Also, try booting my SampleApp.  see README for directions.

Copy the example/SampleApp out of the plugin to some other directory then
$ cd /path/to/where/you/put/SampleApp
$ cordova plugin add <my plugin url>
$ cordova platform add android
$ cordova build android


On Mon, Apr 6, 2015 at 10:15 AM, Ank333 <notifications@github.com> wrote:

> I have installed other plugins and they are installing correctly even I
> had tried to make different sample projects and installed your plugin but
> same issue appearing ,Though I am trying to follow your steps again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/162#issuecomment-90079292>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by Ank333** [comment]
Thanks Christocracy,don't know why this issue appear but anyway I have resolved and Many thanks to you helping me for the same.

Thanks

**Comment by Ginie76** [comment]
Hi Christocracy, I've the same problem, I tried to remove the platform as you said and reset everything, it still doesn't work. I tried on a brand new project, completely empty, still the same issue.
I also tried your sampleApp : this is the same result.

Here's the log :

Installing "org.transistorsoft.cordova.background-geolocation" for ios
Fetching plugin "cordova-plugin-geolocation" via plugin registry
npm http GET http://registry.cordova.io/cordova-plugin-geolocation
npm http 404 http://registry.cordova.io/cordova-plugin-geolocation
Failed to install 'org.transistorsoft.cordova.background-geolocation':Error: 404 Not Found: cordova-plugin-geolocation
    at RegClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:268:14)
    at Request.self.callback (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:148:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:876:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:827:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
Error: 404 Not Found: cordova-plugin-geolocation
    at RegClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:268:14)
    at Request.self.callback (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:148:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:876:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:827:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)

Can you help ?

**Comment by christocracy** [comment]
That's not your issue, this is

https://github.com/christocracy/cordova-plugin-background-geolocation/issues/175

On Friday, May 15, 2015, Ginie76 <notifications@github.com> wrote:

> Hi Christocracy, I've the same problem, I tried to remove the platform as
> you said and reset everything, it still doesn't work. I tried on a brand
> new project, completely empty, still the same issue.
> I also tried your sampleApp : this is the same result.
>
> Here's the log :
>
> Installing "org.transistorsoft.cordova.background-geolocation" for ios
> Fetching plugin "cordova-plugin-geolocation" via plugin registry
> npm http GET http://registry.cordova.io/cordova-plugin-geolocation
> npm http 404 http://registry.cordova.io/cordova-plugin-geolocation
> Failed to install
> 'org.transistorsoft.cordova.background-geolocation':Error: 404 Not Found:
> cordova-plugin-geolocation
> at RegClient.
> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:268:14)
> at Request.self.callback
> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:148:22)
> at Request.emit (events.js:98:17)
> at Request.
> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:876:14)
> at Request.emit (events.js:117:20)
> at IncomingMessage.
> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:827:12)
> at IncomingMessage.emit (events.js:117:20)
> at _stream_readable.js:943:16
> at process._tickCallback (node.js:419:13)
> Error: 404 Not Found: cordova-plugin-geolocation
> at RegClient.
> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:268:14)
> at Request.self.callback
> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:148:22)
> at Request.emit (events.js:98:17)
> at Request.
> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:876:14)
> at Request.emit (events.js:117:20)
> at IncomingMessage.
> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:827:12)
> at IncomingMessage.emit (events.js:117:20)
> at _stream_readable.js:943:16
> at process._tickCallback (node.js:419:13)
>
> Can you help ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/162#issuecomment-102351848>
> .
>


-- 
Snet from Gmail Mobile
