### ISSUE TITLE
Improvements in notifications and what they mean

### ISSUE THREAD

**Issue by jamiehutber** [christocracy/cordova-plugin-background-geolocation#163]
Hi there

First off thanks so much for making a plugin like this, and I'm getting very close to getting my company to pay up for this app. 

However I have to show them something first and current I'm not getting very far with being able to trouble shoot the app...

Would it be possible to get some better error messages? Or just an idea of what they mean?

Console logs won't work of course.

I don't expect you to troubleshoot my code however the following errors if we could get some documentation on them I think once I start having something show and how fast the battery gets eaten :)

**Errors**

``` javascript
1: mv:true,acy:22.832,v:0.0,df:30
2: mv:false,acy:24.0,v:0.0,df:30
3: mv:false,acy:27.0,v:0.0,df:30
4: Statopnary Exit in -17.648m (I assume this one is because the geolocation can't handle standing still?)
```

**My Code**
```
module.exports = function () {
	'use strict';

	var gps = {};

	gps.bgGeo = null;

	if (window.plugins && typeof window.plugins.backgroundGeoLocation !== typeof undefined) {
		gps.bgGeo = window.plugins.backgroundGeoLocation;
	}
	setTimeout(function(){
		if(!gps.bgGeo) {
			gps.bgGeo = window.plugins.backgroundGeoLocation;
		}
		//your code to be executed after 1 seconds
	},5000);

	gps.bgGeo.configure(gps.callbackFn, gps.failureFn, {
		authToken: 'hutber',
		desiredAccuracy: 10,
		stationaryRadius: 10,
		distanceFilter: 30,
		debug: true,
		url: RN.glb.url.ajax + 'api/location/takeGPS',
		notificationTitle: 'RNLI',
		notificationText: 'Tracking GPS Coordinates',
		activityType: 'AutomotiveNavigation',
		stopOnTerminate: false,
	//  locationTimeout: 10
	});


	gps.callbackFn = function(location){
		this.onBackgroundSuccess(location);
		console.log('[js] BackgroundGeoLocation callback:  ' + location.latitudue + ',' + location.longitude);
		$.ajax({
			url: RN.glb.url.api + 'location/takeGPS',
			type: 'POST',
			dataType: "json",
			data: {
				'lat': location.latitudue,
				'long': location.longitude
			},
			error: function (data) {
				c('unsuccess post');
			},
			success: function (data) {
				c('success post');
			}
		});
		gps.bgGeo.finish();
	};

	gps.failureFn = function(error){
		console.log('Geolocation Error');
		gps.bgGeo.finish();
	};

	gps.start = function(data){
		this.bgGeo.start();
},

	gps.stop = function (data) {
		this.bgGeo.stop();
	}

	gps.onBackgroundSuccess = function(cords){
		c(cords);
		c('GPS whayyyy');
	};

	return gps;
};
```

**Comment by christocracy** [comment]
What's with that setTimeout?

You're interacting with my code *within* the cordova deviceready event,
right?

*Errors*

> 1: mv:true,acy:22.832,v:0.0,df:302: mv:false,acy:24.0,v:0.0,df:303: mv:false,acy:27.0,v:0.0,df:30
>
> These are not "errors", they're status messages:

 "mv": moving
 "acy": accuracy
 "v": velocity
 "df" distanceFilter (distance-filter is "elastic", scaled up based upon
speed.  Imagine a distance-filter of 30m at highway speed -- that would be
a location recorded every second.)

>4: Statopnary Exit in -17.648m (I assume >this one is because the geolocation can't >handle standing still?)

No.  My plugin is all about standing still--that's its preferred
state.  Sleeping inside a geofence of stationaryRadius meters.
Distance calculations are not simple point-distances -- you have to
take the accuracy into account as well, basicly the distance between
the edges of two circles of radius defined by the accuracy of the
geolocation.

Test with desiredAccuracy: 0.  You'll get better accuracy locations.

Get rid of that setTimeout:  it's an error with your code causing that
necessity -- not mine.


*My Code*
>
> module.exports = function () {
>     'use strict';
>
>     var gps = {};
>
>     gps.bgGeo = null;
>
>     if (window.plugins && typeof window.plugins.backgroundGeoLocation !== typeof undefined) {
>         gps.bgGeo = window.plugins.backgroundGeoLocation;
>     }
>     setTimeout(function(){
>         if(!gps.bgGeo) {
>             gps.bgGeo = window.plugins.backgroundGeoLocation;
>         }
>         //your code to be executed after 1 seconds
>     },5000);
>
>     gps.bgGeo.configure(gps.callbackFn, gps.failureFn, {
>         authToken: 'hutber',
>         desiredAccuracy: 10,
>         stationaryRadius: 10,
>         distanceFilter: 30,
>         debug: true,
>         url: RN.glb.url.ajax + 'api/location/takeGPS',
>         notificationTitle: 'RNLI',
>         notificationText: 'Tracking GPS Coordinates',
>         activityType: 'AutomotiveNavigation',
>         stopOnTerminate: false,
>     //  locationTimeout: 10
>     });
>
>
>     gps.callbackFn = function(location){
>         this.onBackgroundSuccess(location);
>         console.log('[js] BackgroundGeoLocation callback:  ' + location.latitudue + ',' + location.longitude);
>         $.ajax({
>             url: RN.glb.url.api + 'location/takeGPS',
>             type: 'POST',
>             dataType: "json",
>             data: {
>                 'lat': location.latitudue,
>                 'long': location.longitude
>             },
>             error: function (data) {
>                 c('unsuccess post');
>             },
>             success: function (data) {
>                 c('success post');
>             }
>         });
>         gps.bgGeo.finish();
>     };
>
>     gps.failureFn = function(error){
>         console.log('Geolocation Error');
>         gps.bgGeo.finish();
>     };
>
>     gps.start = function(data){
>         this.bgGeo.start();
> },
>
>     gps.stop = function (data) {
>         this.bgGeo.stop();
>     }
>
>     gps.onBackgroundSuccess = function(cords){
>         c(cords);
>         c('GPS whayyyy');
>     };
>
>     return gps;
> };
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/163>
> .
>


-- 
Snet from Gmail Mobile

**Comment by jamiehutber** [comment]
Ye sorry, the timeout is redundant.

I am starting the tracking with bgGeo.start() once the plugin is ready.

I know the event is firing as I see the notifications on screen. I'm just
unsure what they mean.

I also use chrome to inspect the app over usb so I can fully see what's
going on. Although any console logs or network tasks don't show up on
chrome, I assume that's because any code run through the bgGeo are on a
background service.

Again thanks

**Comment by christocracy** [comment]
Have you tried installing the SampleApp in the repo?  Do that and go for a
walk.  The sample app writes a map-markers to a gmap.

Then try increasing desiredAccuracy to 10, 100, 1000 and note the
difference in accuracy.  Find out what's right for your app.

It's all about accuracy vs battery life

If the plugin is regularly pinging away, you don't need to worry so much
about what the debug noise is all about.

On Tuesday, April 7, 2015, Jamie Hutber <notifications@github.com> wrote:

> Ye sorry, the timeout is redundant.
>
> I am starting the tracking with bgGeo.start() once the plugin is ready.
>
> I know the event is firing as I see the notifications on screen. I'm just
> unsure what they mean.
>
> I also use chrome to inspect the app over usb so I can fully see what's
> going on. Although any console logs or network tasks don't show up on
> chrome, I assume that's because any code run through the bgGeo are on a
> background service.
>
> Again thanks
> On 7 Apr 2015 01:57, "Chris Scott" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > What's with that setTimeout?
> >
> > You're interacting with my code *within* the cordova deviceready event,
> > right?
> >
> > *Errors*
> >
> > > 1: mv:true,acy:22.832,v:0.0,df:302: mv:false,acy:24.0,v:0.0,df:303:
> > mv:false,acy:27.0,v:0.0,df:30
> > >
> > > These are not "errors", they're status messages:
> >
> > "mv": moving
> > "acy": accuracy
> > "v": velocity
> > "df" distanceFilter (distance-filter is "elastic", scaled up based upon
> > speed. Imagine a distance-filter of 30m at highway speed -- that would be
> > a location recorded every second.)
> >
> > >4: Statopnary Exit in -17.648m (I assume >this one is because the
> > geolocation can't >handle standing still?)
> >
> > No. My plugin is all about standing still--that's its preferred
> > state. Sleeping inside a geofence of stationaryRadius meters.
> > Distance calculations are not simple point-distances -- you have to
> > take the accuracy into account as well, basicly the distance between
> > the edges of two circles of radius defined by the accuracy of the
> > geolocation.
> >
> > Test with desiredAccuracy: 0. You'll get better accuracy locations.
> >
> > Get rid of that setTimeout: it's an error with your code causing that
> > necessity -- not mine.
> >
> >
> > *My Code*
> > >
> > > module.exports = function () {
> > > 'use strict';
> > >
> > > var gps = {};
> > >
> > > gps.bgGeo = null;
> > >
> > > if (window.plugins && typeof window.plugins.backgroundGeoLocation !==
> > typeof undefined) {
> > > gps.bgGeo = window.plugins.backgroundGeoLocation;
> > > }
> > > setTimeout(function(){
> > > if(!gps.bgGeo) {
> > > gps.bgGeo = window.plugins.backgroundGeoLocation;
> > > }
> > > //your code to be executed after 1 seconds
> > > },5000);
> > >
> > > gps.bgGeo.configure(gps.callbackFn, gps.failureFn, {
> > > authToken: 'hutber',
> > > desiredAccuracy: 10,
> > > stationaryRadius: 10,
> > > distanceFilter: 30,
> > > debug: true,
> > > url: RN.glb.url.ajax + 'api/location/takeGPS',
> > > notificationTitle: 'RNLI',
> > > notificationText: 'Tracking GPS Coordinates',
> > > activityType: 'AutomotiveNavigation',
> > > stopOnTerminate: false,
> > > // locationTimeout: 10
> > > });
> > >
> > >
> > > gps.callbackFn = function(location){
> > > this.onBackgroundSuccess(location);
> > > console.log('[js] BackgroundGeoLocation callback: ' +
> location.latitudue
> > + ',' + location.longitude);
> > > $.ajax({
> > > url: RN.glb.url.api + 'location/takeGPS',
> > > type: 'POST',
> > > dataType: "json",
> > > data: {
> > > 'lat': location.latitudue,
> > > 'long': location.longitude
> > > },
> > > error: function (data) {
> > > c('unsuccess post');
> > > },
> > > success: function (data) {
> > > c('success post');
> > > }
> > > });
> > > gps.bgGeo.finish();
> > > };
> > >
> > > gps.failureFn = function(error){
> > > console.log('Geolocation Error');
> > > gps.bgGeo.finish();
> > > };
> > >
> > > gps.start = function(data){
> > > this.bgGeo.start();
> > > },
> > >
> > > gps.stop = function (data) {
> > > this.bgGeo.stop();
> > > }
> > >
> > > gps.onBackgroundSuccess = function(cords){
> > > c(cords);
> > > c('GPS whayyyy');
> > > };
> > >
> > > return gps;
> > > };
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/163
> > >
> > > .
> > >
> >
> >
> > --
> > Snet from Gmail Mobile
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/163#issuecomment-90299608
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/163#issuecomment-90406108>
> .
>


-- 
Snet from Gmail Mobile

**Comment by jamiehutber** [comment]
Sound advice. The messages make sense, I wonder if its worth updating the documentation with that?

I have the SampleApp running and i can see my location coming up on the map sure enough.
I have changed the url to my servers and this is defiently not being hit.

``` javascript
bgGeo.configure(callbackFn, failureFn, {
            url: 'http://rnli.hutber.com/api/location/takeGPS', // <-- Android ONLY:  your server url to send locations to
            params: {
                auth_token: 'user_secret_auth_token',    //  <-- Android ONLY:  HTTP POST params sent to your server when persisting locations.
                foo: 'bar'                              //  <-- Android ONLY:  HTTP POST params sent to your server when persisting locations.
            },

Is this meant to be post'd to by the app, or do you handle all posting inside the callBackFn? I also find this a little confusing in the documentation :)

**Comment by christocracy** [comment]
Are you monitoring adb logcat for msgs from my plugin?  The HTTP layer is
quite verbose.

**Comment by jamiehutber** [comment]
Great idea. Are you by any chance added a name so I can filter out the other logcat things? 

So I have used your example of ```fgGeo.watchPosition``` and this is how I am using the plugin...

It seems a little odd that with both your example plugin and me using all of your code that ```yourAjaxCallback````never gets run, even when minimising the app. I see the location icon and also the gps notification in the header display, so its defiantly working. Below is a small amount of the logcat, just to show it is firing. 

```I/ActivityManager(  731): Start proc com.rnli.hutber.com:remote for service com.rnli.hutber.com/com.tenforwardconsulting.cordova.bgloc.LocationUpdateService: pid=13543 uid=10129 gids={50129, 9997, 3003} abi=armeabi-v7a```

```W/PluginManager(10508): THREAD WARNING: exec() call to BackgroundGeoLocation.start blocked the main thread for 27ms. Plugin should use CordovaInterface.getThreadPool().```

I appoligise again as this seems to me like you are having to troubleshoot my version of the app.

**Comment by christocracy** [comment]
-s LocationUpdateService

On Tue, Apr 7, 2015 at 10:10 AM, Jamie Hutber <notifications@github.com>
wrote:

> Great idea. Are you by any chance added a name so I can filter out the
> other logcat things?
>
> So I have used your example of fgGeo.watchPosition and this is how I am
> using the plugin...
>
> It seems a little odd that with both your example plugin and me using all
> of your code that yourAjaxCallback`never gets run, even when minimising
> the app. I see the location icon and also the gps notification in the
> header display, so its defiantly working. Below is a small amount of the
> logcat, just to show it is firing.
>
> I/ActivityManager( 731): Start proc com.rnli.hutber.com:remote for
> service
> com.rnli.hutber.com/com.tenforwardconsulting.cordova.bgloc.LocationUpdateService:
> pid=13543 uid=10129 gids={50129, 9997, 3003} abi=armeabi-v7a
>
> W/PluginManager(10508): THREAD WARNING: exec() call to
> BackgroundGeoLocation.start blocked the main thread for 27ms. Plugin should
> use CordovaInterface.getThreadPool().
>
> I appoligise again as this seems to me like you are having to troubleshoot
> my version of the app.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/163#issuecomment-90575628>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by jamiehutber** [comment]
Indeed, it is posting as you said.

Last thing then, according to my outputs its not actually posting anything but the log says it is, which I am sure it is:

``` cmd
I/LocationUpdateService(22763): Posting  native location update: com.tenforwardconsulting.cordova.bgloc.data.Location@1a97229
I/LocationUpdateService(22763): location: {"latitude":"51.6177222","longitude":"-0.1385892","accuracy":"23.0","speed":"0.0","bearing":"0.0","altitude":"0.0","recorded_at":"2015-04-07T15:28Z"}
D/LocationUpdateService(22763): Posting to http://rnli.hutber.com/api/location/takeGPS
I/LocationUpdateService(22763): Response received: HTTP/1.1 200 OK
```

Output

```` php
a:0:{}
```

**Comment by christocracy** [comment]
The data is there inside the JSON payload of the HTTP Request.

Analyze the raw request.  PHP people often have this problem finding the
data.

Rails seems to have no problem at all providing the JSON payload of the
POST.

On Tue, Apr 7, 2015 at 11:48 AM, Jamie Hutber <notifications@github.com>
wrote:

> Indeed, it is posting as you said.
>
> Last thing then, according to my outputs its not actually posting anything
> but the log says it is, which I am sure it is:
>
> I/LocationUpdateService(22763): Posting  native location update: com.tenforwardconsulting.cordova.bgloc.data.Location@1a97229
> I/LocationUpdateService(22763): location: {"latitude":"51.6177222","longitude":"-0.1385892","accuracy":"23.0","speed":"0.0","bearing":"0.0","altitude":"0.0","recorded_at":"2015-04-07T15:28Z"}
> D/LocationUpdateService(22763): Posting to http://rnli.hutber.com/api/location/takeGPS
> I/LocationUpdateService(22763) <http://rnli.hutber.com/api/location/takeGPSI/LocationUpdateService(22763)>: Response received: HTTP/1.1 200 OK
>
> Output
>
> a:0:{}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/163#issuecomment-90616317>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
Try posting to this test-server http://www.posttestserver.com/

Here’s an example of a POST from my plugin.
http://posttestserver.com/data/2015/04/03/transistor/10.47.39497581039

On Tue, Apr 7, 2015 at 11:50 AM, Chris Scott <christocracy@gmail.com> wrote:

> The data is there inside the JSON payload of the HTTP Request.
>
> Analyze the raw request.  PHP people often have this problem finding the
> data.
>
> Rails seems to have no problem at all providing the JSON payload of the
> POST.
>
> On Tue, Apr 7, 2015 at 11:48 AM, Jamie Hutber <notifications@github.com>
> wrote:
>
>> Indeed, it is posting as you said.
>>
>> Last thing then, according to my outputs its not actually posting
>> anything but the log says it is, which I am sure it is:
>>
>> I/LocationUpdateService(22763): Posting  native location update: com.tenforwardconsulting.cordova.bgloc.data.Location@1a97229
>> I/LocationUpdateService(22763): location: {"latitude":"51.6177222","longitude":"-0.1385892","accuracy":"23.0","speed":"0.0","bearing":"0.0","altitude":"0.0","recorded_at":"2015-04-07T15:28Z"}
>> D/LocationUpdateService(22763): Posting to http://rnli.hutber.com/api/location/takeGPS
>> I/LocationUpdateService(22763) <http://rnli.hutber.com/api/location/takeGPSI/LocationUpdateService(22763)>: Response received: HTTP/1.1 200 OK
>>
>> Output
>>
>> a:0:{}
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/163#issuecomment-90616317>
>> .
>>
>
>
>
> --
> Chris Scott
> Transistor Software <http://www.transistorsoft.com>
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by jamiehutber** [comment]
I'll follow up for sure.

Its never been a problem for me before either, but good to know its only
me. Of course I can't see the request's response through the app, so that
website will be helpful.

Thanks
Jamie

**Comment by christocracy** [comment]
put a ?dir=hutber on your url and it’ll place all requests into that folder.

On Tue, Apr 7, 2015 at 11:56 AM, Jamie Hutber <notifications@github.com>
wrote:

> I'll follow up for sure.
>
> Its never been a problem for me before either, but good to know its only
> me. Of course I can't see the request's response through the app, so that
> website will be helpful.
>
> Thanks
> Jamie
>
> On 7 April 2015 at 16:54, Chris Scott <notifications@github.com> wrote:
>
> > Try posting to this test-server http://www.posttestserver.com/
> >
> > Here’s an example of a POST from my plugin.
> > http://posttestserver.com/data/2015/04/03/transistor/10.47.39497581039
> >
> >
> > On Tue, Apr 7, 2015 at 11:50 AM, Chris Scott <christocracy@gmail.com>
> > wrote:
> >
> > > The data is there inside the JSON payload of the HTTP Request.
> > >
> > > Analyze the raw request. PHP people often have this problem finding the
> > > data.
> > >
> > > Rails seems to have no problem at all providing the JSON payload of the
> > > POST.
> > >
> > > On Tue, Apr 7, 2015 at 11:48 AM, Jamie Hutber <
> notifications@github.com>
> > > wrote:
> > >
> > >> Indeed, it is posting as you said.
> > >>
> > >> Last thing then, according to my outputs its not actually posting
> > >> anything but the log says it is, which I am sure it is:
> > >>
> > >> I/LocationUpdateService(22763): Posting native location update:
> > com.tenforwardconsulting.cordova.bgloc.data.Location@1a97229
> > >> I/LocationUpdateService(22763): location:
> >
> {"latitude":"51.6177222","longitude":"-0.1385892","accuracy":"23.0","speed":"0.0","bearing":"0.0","altitude":"0.0","recorded_at":"2015-04-07T15:28Z"}
> > >> D/LocationUpdateService(22763): Posting to
> > http://rnli.hutber.com/api/location/takeGPS
> > >> I/LocationUpdateService(22763) <
> >
> http://rnli.hutber.com/api/location/takeGPSI/LocationUpdateService(22763)
> >:
> > Response received: HTTP/1.1 200 OK
> > >>
> > >> Output
> > >>
> > >> a:0:{}
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <
> >
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/163#issuecomment-90616317
> > >
> > >> .
> > >>
> > >
> > >
> > >
> > > --
> > > Chris Scott
> > > Transistor Software <http://www.transistorsoft.com>
> > >
> >
> >
> >
> > --
> > Chris Scott
> > Transistor Software <http://www.transistorsoft.com>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/163#issuecomment-90618510
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/163#issuecomment-90619419>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
