### ISSUE TITLE
Background Tracking Enabled Notification

### ISSUE THREAD

**Issue by m-menon** [christocracy/cordova-plugin-background-geolocation#164]
hi,

Thanks a ton for this useful plugin. I have a small little issue. When I tap on the notification (in Android) which says "Background Tracking ENABLED", it does not activate the app if it's in the background. I was wondering if this feature is already built into the plugin or am I doing something wrongly or missing something.

Thanks a ton,
M&M

**Comment by christocracy** [comment]
Nobody has ever had an issue with this.

I see clearly that an Intent pointing to the foreground Activity class is
being created
<https://github.com/christocracy/cordova-plugin-background-geolocation/blob/master/src/android/LocationUpdateService.java#L185>
and
plugged into the Notification instance.
<https://github.com/christocracy/cordova-plugin-background-geolocation/blob/master/src/android/LocationUpdateService.java#L193>





On Tue, Apr 7, 2015 at 4:16 AM, m-menon <notifications@github.com> wrote:

> hi,
>
> Thanks a ton for this useful plugin. I have a small little issue. When I
> tap on the notification (in Android) which says "Background Tracking
> ENABLED", it does not activate the app if it's in the background. I was
> wondering if this feature is already built into the plugin or am I doing
> something wrongly or missing something.
>
> Thanks a ton,
> M&M
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/164>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by m-menon** [comment]
hi Chris,

Oke thanks. Lemme figure out where I messed up :-)

Thanks for the nice plugin though,

Cheers,
M&M

**Comment by christocracy** [comment]
You’re aware of the premium version?  Android battery-life and performance
is much improved.

iOS is the same in both free & premium.

On Tue, Apr 7, 2015 at 10:28 AM, m-menon <notifications@github.com> wrote:

> hi Chris,
>
> Oke thanks. Lemme figure out where I messed up :-)
>
> Thanks for the nice plugin though,
>
> Cheers,
> M&M
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/164#issuecomment-90585335>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by m-menon** [comment]
Actually yes and most probably i can persuade my boss to buy it at a later
time because for now even though we are creating a mobile app it's not
really a revenue generating thingy because initially we plan to offer it
for free. And we're planning only an Android version as the App might grow
in complexity in time to come.

**Comment by christocracy** [comment]
You’ll find the free Android plugin drains the battery *very* quickly.
Like when you wake up in the morning, your phone will be dead.  The Premium
Android plugin can run for days.

On Tue, Apr 7, 2015 at 10:43 AM, m-menon <notifications@github.com> wrote:

> Actually yes and most probably i can persuade my boss to buy it at a later
> time because for now even though we are creating a mobile app it's not
> really a revenue generating thingy because initially we plan to offer it
> for free. And we're planning only an Android version as the App might grow
> in complexity in time to come.
> On 7 Apr, 2015 10:34 pm, "Chris Scott" <notifications@github.com> wrote:
>
> > You’re aware of the premium version? Android battery-life and performance
> > is much improved.
> >
> > iOS is the same in both free & premium.
> >
> > On Tue, Apr 7, 2015 at 10:28 AM, m-menon <notifications@github.com>
> wrote:
> >
> > > hi Chris,
> > >
> > > Oke thanks. Lemme figure out where I messed up :-)
> > >
> > > Thanks for the nice plugin though,
> > >
> > > Cheers,
> > > M&M
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/164#issuecomment-90585335
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Chris Scott
> > Transistor Software <http://www.transistorsoft.com>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/164#issuecomment-90586546
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/164#issuecomment-90588957>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by m-menon** [comment]
I actually am quite inclined towards the premium version but i need to wait
a little while to convince my boss who thinks hes just experimenting for
now :-(

Actually the battery saving with the fusedlocation thingy impressed me
right from the beginning

**Comment by oibvua** [comment]
Hello,

I'm at the same issue. Nothing happens when pressing the notification. I'm currently on the free version. Do you have any suggestions?

**Comment by m-menon** [comment]
hi Chris,

Is there a chance that I can test the premium version of the background
geo-fencing plugin. We are at least couple of months away from publishing
an app on the play store. It would be great if I could experiment with it
and then purchase the premium version before we make our app available on
the App Store. I'd really want to check the advantages of using Android
Fused GeoLocation and ActivityRecognition. For now our app is still
experimental and it may only be on the store if it's a complete success.

Thanks,
M&M

**Comment by christocracy** [comment]
Sorry, no way I can let you test it without giving the src.  I'm going to
publish my SampleApp in App Store someday.

IOS is same in Premium, only Android differs.  Premium Android has superior
battery life over Free version.  Android premium doesn't do geofencing, it
uses ActivityRecognition instead (via accelerometer/gyro).  It detects
movement-states very quickly to engage/disengage GPS.  Premium Android
has "auto start on boot" feature as well, but that's not exactly something
that needs to be rigorously tested.  The quality of geolocation doesn't
differ with Fused provider.  It's really all about battery-life and the
advantage of premium in that regard is objectively superior.

Free Android will be sufficient for development.

On Friday, April 24, 2015, m-menon <notifications@github.com> wrote:

> hi Chris,
>
> Is there a chance that I can test the premium version of the background
> geo-fencing plugin. We are at least couple of months away from publishing
> an app on the play store. It would be great if I could experiment with it
> and then purchase the premium version before we make our app available on
> the App Store. I'd really want to check the advantages of using Android
> Fused GeoLocation and ActivityRecognition. For now our app is still
> experimental and it may only be on the store if it's a complete success.
>
> Thanks,
> M&M
>
> On Tue, Apr 7, 2015 at 10:47 PM, Chris Scott <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > You’ll find the free Android plugin drains the battery *very* quickly.
> > Like when you wake up in the morning, your phone will be dead. The
> Premium
> > Android plugin can run for days.
> >
> > On Tue, Apr 7, 2015 at 10:43 AM, m-menon <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > Actually yes and most probably i can persuade my boss to buy it at a
> > later
> > > time because for now even though we are creating a mobile app it's not
> > > really a revenue generating thingy because initially we plan to offer
> it
> > > for free. And we're planning only an Android version as the App might
> > grow
> > > in complexity in time to come.
> > > On 7 Apr, 2015 10:34 pm, "Chris Scott" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > >
> > > > You’re aware of the premium version? Android battery-life and
> > performance
> > > > is much improved.
> > > >
> > > > iOS is the same in both free & premium.
> > > >
> > > > On Tue, Apr 7, 2015 at 10:28 AM, m-menon <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > > wrote:
> > > >
> > > > > hi Chris,
> > > > >
> > > > > Oke thanks. Lemme figure out where I messed up :-)
> > > > >
> > > > > Thanks for the nice plugin though,
> > > > >
> > > > > Cheers,
> > > > > M&M
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > >
> > >
> >
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/164#issuecomment-90585335
> > > > >
> > > > > .
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Chris Scott
> > > > Transistor Software <http://www.transistorsoft.com>
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/164#issuecomment-90586546
> > > >
> > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/164#issuecomment-90588957
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Chris Scott
> > Transistor Software <http://www.transistorsoft.com>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/164#issuecomment-90590782
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/164#issuecomment-95828511>
> .
>


-- 
Snet from Gmail Mobile
