### ISSUE TITLE
pluginName: BackgroundGeoLocation does not exist.

### ISSUE THREAD

**Issue by vukhanhtruong** [christocracy/cordova-plugin-background-geolocation#165]
Hello Sir,

I am working on the project that using Ionic. I need using signification location change to track the path.
I found your plugin and installed it. Below is the error that I got from the system log.

-------

CDVPlugin class CDVBackgroundGeoLocation (pluginName: BackgroundGeoLocation) does not exist.

ERROR: Plugin 'BackgroundGeoLocation' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.

-[CDVCommandQueue executePending] [Line 159] FAILED pluginJSON = ["BackgroundGeoLocation1343263250","BackgroundGeoLocation","start",[]]

-------

Please help me fix this issue. Thanks in advance.

**Comment by christocracy** [comment]
how did you install the plugin?

On Wed, Apr 8, 2015 at 10:39 AM, Vu Khanh Truong <notifications@github.com>
wrote:

> Hello Sir,
>
> I am working on the project that using Ionic. I need using signification
> location change to track the path.
> I found your plugin and installed it. Below is the error that I got from
> the system log.
>
> CDVPlugin class CDVBackgroundGeoLocation (pluginName:
> BackgroundGeoLocation) does not exist.
>
> ERROR: Plugin 'BackgroundGeoLocation' not found, or is not a CDVPlugin.
> Check your plugin mapping in config.xml.
> -[CDVCommandQueue executePending] [Line 159] FAILED pluginJSON =
> ["BackgroundGeoLocation1343263250","BackgroundGeoLocation","start",[]]
>
> Please help me fix this issue. Thanks in advance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/165>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by vukhanhtruong** [comment]
I installed follow your instruction:
$ cordova plugin add https://github.com/christocracy/cordova-plugin-background-geolocation.git
$ cordova platform add ios
$ cordova build ios

**Comment by christocracy** [comment]
Works perfect here.  I just did a fresh install of my example/SampleApp and
booted without problem.

Problem is on your end, I’m afraid.  What version of cordova are you using?

On Wed, Apr 8, 2015 at 11:28 AM, Vu Khanh Truong <notifications@github.com>
wrote:

> I installed follow your instruction:
> $ cordova plugin add
> https://github.com/christocracy/cordova-plugin-background-geolocation.git
> $ cordova platform add ios
> $ cordova build ios
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/165#issuecomment-90950920>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by vukhanhtruong** [comment]
I am using cordova v4.3.0

**Comment by christocracy** [comment]
Have you tried booting my SampleApp?

see README.

On Wed, Apr 8, 2015 at 11:42 AM, Vu Khanh Truong <notifications@github.com>
wrote:

> I am using cordova v4.3.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/165#issuecomment-90955371>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by vukhanhtruong** [comment]
I can not boot your sampleApp. I got the following error http://pastebin.com/7vJXkYpQ
I really appreciate for your help. Thanks so much.

**Comment by christocracy** [comment]
Seems to be an issue with my SampleApp icons.  Are you on Mac or Linux?

$ rm /Users/brianvu/Developers/geo_example/SampleApp/hooks/before_prepare/
resource_copier.js

Then try again.

On Wed, Apr 8, 2015 at 12:02 PM, Vu Khanh Truong <notifications@github.com>
wrote:

> I can not boot your sampleApp. I got the following error
> http://pastebin.com/7vJXkYpQ
> I really appreciate for your help. Thanks so much.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/165#issuecomment-90960068>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by vukhanhtruong** [comment]
Hello,

I am using Mac. 
After delete that file, it work perfect on iOS 7 but iOS 8.
Sorry for late reply.

**Comment by vukhanhtruong** [comment]
Hello Sir,

Your example only work on iOS 7.
Could you please help me make it work on iOS 8?

Thanks & Regards,

**Comment by christocracy** [comment]
How do you expect me to help you?  You've provided no evidence to support
your statement and my experience contradicts your observation.

ios8 works for me.

On Thursday, April 9, 2015, Vu Khanh Truong <notifications@github.com>
wrote:

> Hello Sir,
>
> Your example only work on iOS 7.
> Could you please help me make it work on iOS 8?
>
> Thanks & Regards,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/165#issuecomment-91396772>
> .
>


-- 
Snet from Gmail Mobile

**Comment by vukhanhtruong** [comment]
Hi,

I'm sorry.I re-checked, your example work like charm. 
However, my app is still work on iOS 7.
Here is the error log when I run my app on iOS8 http://pastebin.com/2KhfnKcD

**Comment by christocracy** [comment]
I just installed booted my SampleApp from scratch on iOS8.2, Cordova 4.3.0,
iPhone 5 and it continues to work as expected.

My boot-log
https://gist.github.com/christocracy/0cfd4e87e4d72f0d2ded



On Thu, Apr 9, 2015 at 10:45 PM, Vu Khanh Truong <notifications@github.com>
wrote:

> Hi,
>
> I'm sorry.I re-checked, your example work like charm.
> However, my app is still work on iOS 7.
> Here is the error log when I run my app on iOS8
> http://pastebin.com/2KhfnKcD
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/165#issuecomment-91409230>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by vukhanhtruong** [comment]
Yes, I also boot your SampleApp work on iOS8.2, Cordova 4.3.0. 
But I can not make my app work as expected on iOS8.2, the callbackFn did not excute 
I get notifications on Simulator and I see one of the notification as Outstanding bg-task was force killed.

Anyway, thanks for your help.

**Comment by christocracy** [comment]
"Outstanding bg-task was force killed.” this is of no consequence.

On Fri, Apr 10, 2015 at 4:19 AM, Vu Khanh Truong <notifications@github.com>
wrote:

> Yes, I also boot your SampleApp work on iOS8.2, Cordova 4.3.0.
> But I can not make my app work as expected on iOS8.2, the callbackFn did
> not excute
> I get notifications on Simulator and I see one of the notification as
> Outstanding bg-task was force killed.
>
> Anyway, thanks for your help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/165#issuecomment-91474900>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
delete app from ios 8 device.  re-install.

On Fri, Apr 10, 2015 at 4:21 AM, Chris Scott <christocracy@gmail.com> wrote:

> "Outstanding bg-task was force killed.” this is of no consequence.
>
> On Fri, Apr 10, 2015 at 4:19 AM, Vu Khanh Truong <notifications@github.com
> > wrote:
>
>> Yes, I also boot your SampleApp work on iOS8.2, Cordova 4.3.0.
>> But I can not make my app work as expected on iOS8.2, the callbackFn did
>> not excute
>> I get notifications on Simulator and I see one of the notification as
>> Outstanding bg-task was force killed.
>>
>> Anyway, thanks for your help.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/165#issuecomment-91474900>
>> .
>>
>
>
>
> --
> Chris Scott
> Transistor Software <http://www.transistorsoft.com>
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by vukhanhtruong** [comment]
I did, but it still did not work. It meet the same error above.
Thanks for your help :)

**Comment by christocracy** [comment]
just installed iOS 8.3, still works without any issues.

On Fri, Apr 10, 2015 at 6:44 AM, Vu Khanh Truong <notifications@github.com>
wrote:

> I did, but it still did not work. It meet the same error above.
> Thanks for your help :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/165#issuecomment-91512782>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
Field test successful

On Friday, April 10, 2015, Chris Scott <christocracy@gmail.com> wrote:

> just installed iOS 8.3, still works without any issues.
>
> On Fri, Apr 10, 2015 at 6:44 AM, Vu Khanh Truong <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I did, but it still did not work. It meet the same error above.
>> Thanks for your help :)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/165#issuecomment-91512782>
>> .
>>
>
>
>
> --
> Chris Scott
> Transistor Software <http://www.transistorsoft.com>
>


-- 
Snet from Gmail Mobile

**Comment by vukhanhtruong** [comment]
Today, I update iOS 8.3 and It work great. Thanks so much for your support.
