### ISSUE TITLE
Status Bar Icon

### ISSUE THREAD

**Issue by codletech** [christocracy/cordova-plugin-background-geolocation#166]
Hi,
Many thanks for giving us this great plugin!!
How can I change the persistent status bar icon in an Android app?
Thanks in advance,
Dvir Cohen.

**Comment by christocracy** [comment]
I don’t think I made that easily configurable.  Surprised more people
haven’t asked about this.

It seems to be set here
<https://github.com/christocracy/cordova-plugin-background-geolocation/blob/master/src/android/LocationUpdateService.java#L192>

Btw, the premium version isn’t required to use a status-bar icon.

On Wed, Apr 8, 2015 at 11:00 AM, codletech <notifications@github.com> wrote:

> Hi,
> Many thanks for giving us this great plugin!!
> How can I change the persistent status bar icon in an Android app?
> Thanks in advance,
> Dvir Cohen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/166>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by codletech** [comment]
Thanks for the quick response.
Is it going to be configurable in the next updates?
It's very important for the product design.
Thanks again :)

**Comment by christocracy** [comment]
Development of free Android is dead.  All new development occurs only in
Premium Version (which is a complete refactor).

iOS is the same for both free & premium versions.

On Wed, Apr 8, 2015 at 11:07 AM, codletech <notifications@github.com> wrote:

> Thanks for the quick response.
> Is it going to be configurable in the next updates?
> It's very important for the product design.
> Thanks again :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/166#issuecomment-90944680>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by codletech** [comment]
Alright, Thanks!

**Comment by christocracy** [comment]
The battery consumption of premium version is vastly better than free
version.[image: Inline image 3][image: Inline image 1]

On Wed, Apr 8, 2015 at 11:12 AM, codletech <notifications@github.com> wrote:

> Alright, Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/166#issuecomment-90946375>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
