### ISSUE TITLE
Premium version and Phonegap Build

### ISSUE THREAD

**Issue by MaliciousMustard** [christocracy/cordova-plugin-background-geolocation#168]
Hi,

I'm considering buying the premium version and I wanted to verify whether it works with Phonegap Build.

At the moment I'm only using the config.xml for the plugins and Phonegap Build to build my application. 
Would the premium version work like that?

Best regards,
Alex

**Comment by christocracy** [comment]
PhoneGap now supports “private plugins
<http://stackoverflow.com/questions/18656810/how-to-make-a-custom-private-plugin-in-phonegap>
”

Yes, you can use Premium with Phonegap.

On Sat, Apr 18, 2015 at 4:40 PM, MaliciousMustard <notifications@github.com>
wrote:

> Hi,
>
> I'm considering buying the premium version and I wanted to verify whether
> it works with Phonegap Build.
>
> At the moment I'm only using the config.xml for the plugins and Phonegap
> Build to build my application.
> Would the premium version work like that?
>
> Best regards,
> Alex
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/168>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
btw, you made the “What are People Saying” section of my marketing page
<http://christocracy.github.io/cordova-background-geolocation/>:)

[image: Inline image 1]

On Sat, Apr 18, 2015 at 4:49 PM, Chris Scott <christocracy@gmail.com> wrote:

> PhoneGap now supports “private plugins
> <http://stackoverflow.com/questions/18656810/how-to-make-a-custom-private-plugin-in-phonegap>
> ”
>
> Yes, you can use Premium with Phonegap.
>
> On Sat, Apr 18, 2015 at 4:40 PM, MaliciousMustard <
> notifications@github.com> wrote:
>
>> Hi,
>>
>> I'm considering buying the premium version and I wanted to verify whether
>> it works with Phonegap Build.
>>
>> At the moment I'm only using the config.xml for the plugins and Phonegap
>> Build to build my application.
>> Would the premium version work like that?
>>
>> Best regards,
>> Alex
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/168>
>> .
>>
>
>
>
> --
> Chris Scott
> Transistor Software <http://www.transistorsoft.com>
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by MaliciousMustard** [comment]
Hehe, well it's true!!!! Definitely one of the most awesome, helpful and well supported phonegap plugins out there! ;)
