### ISSUE TITLE
Keeping background locations on after termination and restart

### ISSUE THREAD

**Issue by echojuno** [christocracy/cordova-plugin-background-geolocation#169]
Hi, 

I noticed that you are stopping the location updates after the app is terminated or restarted.

- (void)applicationWillTerminate:(UIApplication *)application {
    [locationManager stopMonitoringSignificantLocationChanges];

 Is there is a way to keep the location updates working even after the app is terminated or phone restarted.

**Comment by christocracy** [comment]
Hmm, yes.  I don’t think it should do that.  If the plugin is currently
monitoring user’s location, keeping sig.changes and startionary-region
monitoring might wake up the app after a restart.

I’ll test that out tonight.

On Mon, Apr 20, 2015 at 5:29 PM, echojuno <notifications@github.com> wrote:

> Hi,
>
> I noticed that you are stopping the location updates after the app is
> terminated or restarted.
>
>    -
>
>    (void)applicationWillTerminate:(UIApplication *)application {
>    [locationManager stopMonitoringSignificantLocationChanges];
>
>    Is there is a way to keep the location updates working even after the
>    app is terminated or phone restarted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/169>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
Confirmed:  by removing that code in applicationWillTerminate, iOS will
re-initialize monitoring of stationary-region and significant changes on
reboot.

Good catch.

On Mon, Apr 20, 2015 at 6:18 PM, Chris Scott <christocracy@gmail.com> wrote:

> Hmm, yes.  I don’t think it should do that.  If the plugin is currently
> monitoring user’s location, keeping sig.changes and startionary-region
> monitoring might wake up the app after a restart.
>
> I’ll test that out tonight.
>
> On Mon, Apr 20, 2015 at 5:29 PM, echojuno <notifications@github.com>
> wrote:
>
>> Hi,
>>
>> I noticed that you are stopping the location updates after the app is
>> terminated or restarted.
>>
>>    -
>>
>>    (void)applicationWillTerminate:(UIApplication *)application {
>>    [locationManager stopMonitoringSignificantLocationChanges];
>>
>>    Is there is a way to keep the location updates working even after the
>>    app is terminated or phone restarted.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/169>
>> .
>>
>
>
>
> --
> Chris Scott
> Transistor Software <http://www.transistorsoft.com>
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by ahujaravish** [comment]
Just curious, does this fix the similar Android issue too?

**Comment by christocracy** [comment]
I don't think free Android version operates as well in this regard.

The premium version definitely can auto-start after a reboot.

http://christocracy.github.io/cordova-background-geolocation/

On Wednesday, May 27, 2015, ahujaravish <notifications@github.com> wrote:

> Just curious, does this fix the similar Android issue too?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/169#issuecomment-106088726>
> .
>


-- 
Snet from Gmail Mobile

**Comment by ahujaravish** [comment]
OK, that makes sense. thanks
