### ISSUE TITLE
Benefit of payed version

### ISSUE THREAD

**Issue by t3rmin83r** [christocracy/cordova-plugin-background-geolocation#172]
Hi, I have seen your plugin and it works great. I have seen its payed version. I want to know what would be the benefit of payed version? I am using the plugin from your github repo. Is it illegal?

**Comment by christocracy** [comment]
The Permium (paid) version has a much better Android implementation with
superior battery performance vs free version in addition to some other
features.

The premium version exists within a private repo -- when you pay for it, I
give you access.

It's perfectly legal to use the free version.

On Saturday, April 25, 2015, Khawar <notifications@github.com> wrote:

> Hi, I have seen your plugin and it works great. I have seen its payed
> version. I want to know what would be the benefit of payed version? I am
> using the plugin from your github repo. Is it illegal?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/172>
> .
>


-- 
Snet from Gmail Mobile
