### ISSUE TITLE
Quiet time for stopOnTerminate: false

### ISSUE THREAD

**Issue by markarupert** [christocracy/cordova-plugin-background-geolocation#174]
I am building an app that requires a Clock In and Clock Out. I want to track the the user while clocked in only. I also want to be able to continue tracking even when the app is exited. I store the clockin time in SQLite so it will persist even when the app exits. Once the user clocks out I want the tracking to stop. I call bgGeo.stop(); when I clock out but it continues to run. I suspect it is because I am using stopOnTerminate: false. Is there another call I should make?

**Comment by christocracy** [comment]
T
