### ISSUE TITLE
How different is the Premium API - can I develop against 'Free' and migrate to Premium *easily*, later?

### ISSUE THREAD

**Issue by sixman9** [christocracy/cordova-plugin-background-geolocation#178]
Hi,
Following on from my subject, **is the Premium API a drop-in replacement for your free offering?** 

I'm mildly aware of the callback *not* working locally on Android in your free version, however, **I'd like to be able to develop against the free version of your code-base, at least far enough so I can later justify the $500 spend on my self-funded project**.

**If the 2 release versions are *not* API equivalent, how much additional work is necessary to migrate to the Premium version?**

As I'll be one-manning my project, I'm, ultimately, looking to avoid platform differences, hence my overall interest in Phonegap/Cordova/Ionic.

**Comment by christocracy** [comment]
Why not develop against iOS for now?

It's mostly a drop-in replacement.  You have to provide a few extra config
params.

The iOS code is mostly the same but with extra features, including HTTP &
SQLite persistence layers.

On Sunday, May 10, 2015, sixman9 <notifications@github.com> wrote:

> Hi,
> Following on from my subject, *is the Premium API a drop-in replacement
> for your free offering?*
>
> I'm mildly aware of the callback *not* working locally on Android in your
> free version, however, *I'd like to be able to develop against the free
> version of your code-base, at least far enough so I can later justify the
> $500 spend on my self-funded project*.
>
> *If the 2 release versions are not API equivalent, how much additional
> work is necessary to migrate to the Premium version?*
>
> As I'll be one-manning my project, I'm, ultimately, looking to avoid
> platform differences, hence my overall interest in Phonegap/Cordova/Ionic.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/178>
> .
>


-- 
Snet from Gmail Mobile
