### ISSUE TITLE
NSException occuring when firing start() again after stop().

### ISSUE THREAD

**Issue by danmatthews** [christocracy/cordova-plugin-background-geolocation#179]
In my application, when i log out, i call `.stop()` so that all background location tracking is stopped.

When you log in again, it calls `configure()` again, then `.start()`. this causes the folllowing error in the lldb console:

```
(lldb) 2015-05-12 14:09:52.681 My Pet My Vet[11612:1565365] - CDVBackgroundGeoLocation finish
2015-05-12 14:09:52.683 My Pet My Vet[11612:1565365] - CDVBackgroundGeoLocation stopBackgroundTask (remaining t: 1797693134862315708145274237317043567980705675258449965(lldb) 98917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0(lldb) 00000)
(lldb) 2015-05-12 14:09:52.712 My Pet My Vet[11612:1565382] -[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0x15645000
2015-05-12 14:09:52.713 My Pet My Vet[11612:1565382] *** Terminating app due to uncaught exception 'NSInvalidArgumentE(lldb) xception', reason: '-[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0x15645000'
*** First throw call stack:
(0x241b0fef 0x32724c8b 0x241b6409 0x241b4327 0x240e3e78 0x8174d 0x7efcb 0x7eb73 0x7c417 0x32c8f2e3 0x32c99381 0x32c9a3c3 (lldb) 0x32df6dc1 0x32df6b14)
(lldb) libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) Process 11612 stopped
* thread #5: tid = 0x17e2c6, 0x32d7adf0 libsystem_kernel.dylib`__pthread_kill + 8, queue = 'com.apple.root.default-qos', stop reason = signal SIGABRT
    frame #0: 0x32d7adf0 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x32d7adf0 <+8>:  blo    0x32d7ae08                ; <+32>
    0x32d7adf4 <+12>: ldr    r12, [pc, #0x4]           ; <+24>
    0x32d7adf8 <+16>: ldr    r12, [pc, r12]
    0x32d7adfc <+20>: b      0x32d7ae04                ; <+28>
(lldb)
```

**Comment by christocracy** [comment]
Thanks, I'll check that out asap.

Fix will go into #edge branch

On Tuesday, May 12, 2015, Dan Matthews <notifications@github.com> wrote:

> In my application, when i log out, i call .stop() so that all background
> location tracking is stopped.
>
> When you log in again, it calls configure() again, then .start(). this
> causes the folllowing error in the lldb console:
>
> (lldb) 2015-05-12 14:09:52.681 My Pet My Vet[11612:1565365] - CDVBackgroundGeoLocation finish
> 2015-05-12 14:09:52.683 My Pet My Vet[11612:1565365] - CDVBackgroundGeoLocation stopBackgroundTask (remaining t: 1797693134862315708145274237317043567980705675258449965(lldb) 98917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0(lldb) 00000)
> (lldb) 2015-05-12 14:09:52.712 My Pet My Vet[11612:1565382] -[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0x15645000
> 2015-05-12 14:09:52.713 My Pet My Vet[11612:1565382] *** Terminating app due to uncaught exception 'NSInvalidArgumentE(lldb) xception', reason: '-[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0x15645000'
> *** First throw call stack:
> (0x241b0fef 0x32724c8b 0x241b6409 0x241b4327 0x240e3e78 0x8174d 0x7efcb 0x7eb73 0x7c417 0x32c8f2e3 0x32c99381 0x32c9a3c3 (lldb) 0x32df6dc1 0x32df6b14)
> (lldb) libc++abi.dylib: terminating with uncaught exception of type NSException
> (lldb) Process 11612 stopped
> * thread #5: tid = 0x17e2c6, 0x32d7adf0 libsystem_kernel.dylib`__pthread_kill + 8, queue = 'com.apple.root.default-qos', stop reason = signal SIGABRT
>     frame #0: 0x32d7adf0 libsystem_kernel.dylib`__pthread_kill + 8
> libsystem_kernel.dylib`__pthread_kill:
> ->  0x32d7adf0 <+8>:  blo    0x32d7ae08                ; <+32>
>     0x32d7adf4 <+12>: ldr    r12, [pc, #0x4]           ; <+24>
>     0x32d7adf8 <+16>: ldr    r12, [pc, r12]
>     0x32d7adfc <+20>: b      0x32d7ae04                ; <+28>
> (lldb)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/179>
> .
>


-- 
Snet from Gmail Mobile

**Comment by danmatthews** [comment]
Thanks!

**Comment by christocracy** [comment]
Which branch were you using?  #master or #edge?

On Tue, May 12, 2015 at 9:19 AM, Dan Matthews <notifications@github.com>
wrote:

> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/179#issuecomment-101272017>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by danmatthews** [comment]
Master I would guess, whichever one pulls from the Cordova plugin add command.

**Comment by christocracy** [comment]
Use edge.  Append #edge to your plugin URL:

$ cordova plugin add <URL>#edge

On Tuesday, May 12, 2015, Dan Matthews <notifications@github.com> wrote:

> Master I would guess, whichever one pulls from the Cordova plugin add
> command.
>
> Sent from my iPhone
>
> > On 12 May 2015, at 19:55, Chris Scott <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > Which branch were you using? #master or #edge?
> >
> > On Tue, May 12, 2015 at 9:19 AM, Dan Matthews <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > Thanks!
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/179#issuecomment-101272017
> >
> > > .
> > >
> >
> >
> >
> > --
> > Chris Scott
> > Transistor Software <http://www.transistorsoft.com>
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/179#issuecomment-101410523>
> .
>


-- 
Snet from Gmail Mobile
