### ISSUE TITLE
Getting the geolocation value periodically

### ISSUE THREAD

**Issue by deepak014** [christocracy/cordova-plugin-background-geolocation#180]
Hi Chris,

This is an awesome plugin. works great. just wondering about a small issue that I am facing with my app. I see that the plugin records the geolocation based on the distance calculation.
(round(speed, 5))^2 + distanceFilter

I understand this is to save the battery but my requirement is to catch the location coords after every 20 minutes (user stationary or moving does not matter). Is it possible in this plugin somehow. Is there a workaround to achieve this with your code.

P.S. : I am pretty new to cordova and I am just consuming you plugin through js code. No idea regarding any changes in the java classes.

Thanks in Advance,

Cheers,
Deepak

**Comment by christocracy** [comment]
The premium version has a config disableElasticity.

No you cannot update the location every 20 minutes.  Geolocation APIs don't
work on timers -- they work on distance travelled.

If you want to know where someone is every 20 min, your server can send a
silent push notification to them.

On Wednesday, May 13, 2015, deepak014 <notifications@github.com> wrote:

> Hi Chris,
>
> This is an awesome plugin. works great. just wondering about a small issue
> that I am facing with my app. I see that the plugin records the geolocation
> based on the distance calculation.
> (round(speed, 5))^2 + distanceFilter
>
> I understand this is to save the battery but my requirement is to catch
> the location coords after every 20 minutes (user stationary or moving does
> not matter). Is it possible in this plugin somehow. Is there a workaround
> to achieve this with your code.
>
> P.S. : I am pretty new to cordova and I am just consuming you plugin
> through js code. No idea regarding any changes in the java classes.
>
> Thanks in Advance,
>
> Cheers,
> Deepak
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/180>
> .
>


-- 
Snet from Gmail Mobile

**Comment by deepak014** [comment]
Thanks:)
will try the same and let you know 

Regards,
Deepak
