### ISSUE TITLE
WP8 bgGeo.configure()  issue

### ISSUE THREAD

**Issue by ftaddei** [christocracy/cordova-plugin-background-geolocation#181]
Thanks for a great plugin - However I need your assistance with the wp8 bgGeo.configure() - very strange behaviour in only wp8 where the failureFn callback gets triggered with "Invalid value for stationaryRadius:" - this continues even when I hard code the values;

Android app works 100% ( understanding that Android will call the url directly and not the callbackFn)

Code below 
bgGeo.configure(callbackFn, failureFn, {
				url: 'http://www.rassys.co.za/retraceLIVE/api/GeoLocation', 
				headers: {                                   
					"X-Dep-No" : localStorage.getItem("depno"),
					"X-Device-ID" : device.uuid
				},
				clientId : clientID,
				depNo : localStorage.getItem("depno"),
				deviceId : device.uuid,
				desiredAccuracy: 10,
				stationaryRadius: 20,
				distanceFilter: 30,
				notificationTitle: 'Retrace Tracking', 
				notificationText: 'Enabled', 
				activityType: 'AutomotiveNavigation',
				debug: false, 
				stopOnTerminate: false 
			});

			bgGeo.start();

I have also tried a simpler 

bgGeo.configure(callbackFn, failureFn, {
					desiredAccuracy: 10,
					stationaryRadius: 20,
					distanceFilter: 30,
					activityType: 'AutomotiveNavigation',
					debug: false, 
					stopOnTerminate: false 
				} );
Even this gives the same issue 

Many thanks for your assistance - this has been driving me nuts for hours :-)

**Comment by christocracy** [comment]
Can't help you with wp8, sorry.  I took thee wp8 plugin in as a
pull-request.  I don't personally support it.

Btw, the Premium version has a much better Android implementation which
does call your js callback among other new features

On Wednesday, May 13, 2015, ftaddei <notifications@github.com> wrote:

> Thanks for a great plugin - However I need your assistance with the wp8
> bgGeo.configure() - very strange behaviour in only wp8 where the failureFn
> callback gets triggered with "Invalid value for stationaryRadius:" - this
> continues even when I hard code the values;
>
> Android app works 100% ( understanding that Android will call the url
> directly and not the callbackFn)
>
> Code below
> bgGeo.configure(callbackFn, failureFn, {
> url: 'http://www.rassys.co.za/retraceLIVE/api/GeoLocation',
> headers: {
>
> "X-Dep-No" : localStorage.getItem("depno"),
> "X-Device-ID" : device.uuid
> },
> clientId : clientID,
> depNo : localStorage.getItem("depno"),
> deviceId : device.uuid,
> desiredAccuracy: 10,
> stationaryRadius: 20,
> distanceFilter: 30,
> notificationTitle: 'Retrace Tracking',
> notificationText: 'Enabled',
> activityType: 'AutomotiveNavigation',
> debug: false,
> stopOnTerminate: false
> });
>
>         bgGeo.start();
>
> I have also tried a simpler
>
> bgGeo.configure(callbackFn, failureFn, {
> desiredAccuracy: 10,
> stationaryRadius: 20,
> distanceFilter: 30,
> activityType: 'AutomotiveNavigation',
> debug: false,
> stopOnTerminate: false
> } );
> Even this gives the same issue
>
> Many thanks for your assistance - this has been driving me nuts for hours
> :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/181>
> .
>


-- 
Snet from Gmail Mobile
