### ISSUE TITLE
Configurations for city

### ISSUE THREAD

**Issue by JGuscins** [christocracy/cordova-plugin-background-geolocation#182]
Hi,

I have a problem - i am trying to track locations when (driving+walking+running) all in one. But problem is that it works good when i am driving, but not so good when i am walking. Sometimes when i walk, it doesn't track for 10-15 minutes.. I am almost sure problem is with my configurations.

I currently use this settings:

        bgGeo.configure(callbackFn, failureFn, {
            desiredAccuracy: 0,
            stationaryRadius: 25,
            distanceFilter: 25,
            activityType: "OtherNavigation",
            debug: true,
            stopOnTerminate: false,
            locationTimeout: 30,
        });

Maybe you can suggest better settings for city and all type of movement. I need as much location updates as possible (when target is moving) and it would be great if i could get real location (with accuracy +/- 50m)

p.s - Thanks for making this plugin :)

**Comment by christocracy** [comment]
which platform?

On Thu, May 14, 2015 at 9:57 AM, JGuscins <notifications@github.com> wrote:

> Hi,
>
> I have a problem - i am trying to track locations when
> (driving+walking+running) all in one. But problem is that it works good
> when i am driving, but not so good when i am walking. Sometimes when i
> walk, it doesn't track for 10-15 minutes.. I am almost sure problem is with
> my configurations.
>
> I currently use this settings:
>
>     bgGeo.configure(callbackFn, failureFn, {
>         desiredAccuracy: 0,
>         stationaryRadius: 25,
>         distanceFilter: 25,
>         activityType: "OtherNavigation",
>         debug: true,
>         stopOnTerminate: false,
>         locationTimeout: 30,
>     });
>
> Maybe you can suggest better settings for city and all type of movement. I
> need as much location updates as possible (when target is moving) and it
> would be great if i could get real location (with accuracy +/- 50m)
>
> p.s - Thanks for making this plugin :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/182>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by JGuscins** [comment]
ios

**Comment by christocracy** [comment]
It doesn’t matter if you’re walking or running or driving -- it tracks the
same.  When you’re moving, you’re moving.  A location-update will be
recorded every time the device moves *#distanceFilter* meters away from
previous location.

Note that tracking will not engage until you move about 2-3 blocks away
from your stationary-location, so if you’re walking, yes that could take
10-15 minutes of walking until tracking engages.  Once it’s engaged, you’ll
receive an update each *#distanceFilter* meters.

Note Behaviour
<https://github.com/christocracy/cordova-plugin-background-geolocation#behaviour>
section in README

" iOS has a nice system Significant Changes API
<https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/CLLocationManager/CLLocationManager.html#//apple_ref/occ/instm/CLLocationManager/startMonitoringSignificantLocationChanges>,
which allows the os to suspend your app until a cell-tower change is
detected *(typically 2-3 city-block change*) “



On Thu, May 14, 2015 at 9:57 AM, JGuscins <notifications@github.com> wrote:

> Hi,
>
> I have a problem - i am trying to track locations when
> (driving+walking+running) all in one. But problem is that it works good
> when i am driving, but not so good when i am walking. Sometimes when i
> walk, it doesn't track for 10-15 minutes.. I am almost sure problem is with
> my configurations.
>
> I currently use this settings:
>
>     bgGeo.configure(callbackFn, failureFn, {
>         desiredAccuracy: 0,
>         stationaryRadius: 25,
>         distanceFilter: 25,
>         activityType: "OtherNavigation",
>         debug: true,
>         stopOnTerminate: false,
>         locationTimeout: 30,
>     });
>
> Maybe you can suggest better settings for city and all type of movement. I
> need as much location updates as possible (when target is moving) and it
> would be great if i could get real location (with accuracy +/- 50m)
>
> p.s - Thanks for making this plugin :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/182>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
