### ISSUE TITLE
Store location values offline - Android version

### ISSUE THREAD

**Issue by deepak014** [christocracy/cordova-plugin-background-geolocation#184]
Hi chris,

Is it possible to store the location values in the free version for android? Do you do it on your side i.e check the connection and store the location coords in local storage?

**Comment by christocracy** [comment]
Free Android has always had a SQLite persistence layer.

On Monday, May 18, 2015, deepak014 <notifications@github.com> wrote:

> Hi chris,
>
> Is it possible to store the location values (in indexDB) in the free
> version for android? Do you do it on your side i.e check the connection and
> store the location coords in local storage?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/184>
> .
>


-- 
Snet from Gmail Mobile

**Comment by christocracy** [comment]
The [Premium Version](http://christocracy.github.io/cordova-background-geolocation/) has a more advanced SQLite persistence layer with a javascript API to fetch the stored-locations from database and optionally sync them to server (**for both iOS & Android**).
