### ISSUE TITLE
Android 4.1.2

### ISSUE THREAD

**Issue by mattgrande** [christocracy/cordova-plugin-background-geolocation#187]
Hi there, I'm running your plugin version 0.3.6. Just wondering if there are any known issues with old Android versions? One customer is reporting it's not working, and I thought I'd check here before I start digging too hard.

**Comment by christocracy** [comment]
4.1.2 should be fine.

However, the free Android is vastly inferior to the Premium version (though
not unreliable, just inefficient).

http://christocracy.github.io/cordova-background-geolocation/

On Thursday, May 21, 2015, Matt Grande <notifications@github.com> wrote:

> Hi there, I'm running your plugin version 0.3.6. Just wondering if there
> are any known issues with old Android versions? One customer is reporting
> it's not working, and I thought I'd check here before I start digging too
> hard.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/187>
> .
>


-- 
Snet from Gmail Mobile
