### ISSUE TITLE
Plugin stop working

### ISSUE THREAD

**Issue by truongces** [christocracy/cordova-plugin-background-geolocation#188]
Hi,

First, thanks for great plugin.
I installed your plugin and run it on iOS. 
However, it stop working and make another plugin down. But it work again, when I hit the home button twice and re-focus it
I am using Cordova 4.3.0. This is the log file http://pastebin.com/v6BpstLC
Please help me fix this issue.

Thanks & Regards

**Comment by christocracy** [comment]
What do you expect to happen?

On Mon, May 25, 2015 at 5:38 AM, truongces <notifications@github.com> wrote:

> Hi,
>
> First, thanks for great plugin.
> I installed your plugin and run it on iOS.
> However, it stop working and make another plugin down. But it work again,
> when I hit the home button twice and re-focus it
> I am using Cordova 4.3.0. This is the log file
> http://pastebin.com/v6BpstLC
> Please help me fix this issue.
>
> Thanks & Regards
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/188>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by truongces** [comment]
Everything work correct until I add your plugin into app. Do you have any suggestion?

**Comment by christocracy** [comment]
Do you have some evidence?  Your previous log shows everything is fine with
my plugin.

On Monday, May 25, 2015, truongces <notifications@github.com> wrote:

> Everything work correct until I add your plugin into app. Do you have any
> suggestion?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/188#issuecomment-105360691>
> .
>


-- 
Snet from Gmail Mobile

**Comment by truongces** [comment]
The log only show like that and stop. I have no more evidence.
Ok, I will try to review my app, I will let you know if I have any evidence.
I really appreciate for your support. Thanks.

**Comment by christocracy** [comment]
Are you telling me your app is "crashing"?

Are you sure you don't have a JavaScript error?



On Monday, May 25, 2015, truongces <notifications@github.com> wrote:

> The log only show like that and stop. I have no more evidence.
> Ok, I will try to review my app, I will let you know if I have any
> evidence.
> I really appreciate for your support. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/188#issuecomment-105367010>
> .
>


-- 
Snet from Gmail Mobile

**Comment by truongces** [comment]
I am sorry, it's not crash. When I get the log as I sent you, all cordova plugin stop working. It's strange.

**Comment by christocracy** [comment]
The log only show like that and stop.
>
> Like I asked before, what do you expect to see in the log instead of just
"stopping"

My plugin is clearly (and correctly) in stationary geofence mode.
Hibernating and conserving the device's battery until you move 2-3 city
blocks out of the "stationary geofence".
>
>
My plugin doesn't just constantly report a geolocation.  Read the README
very carefully, step out of the office and go for a walk or car ride.


-- 
Snet from Gmail Mobile

**Comment by christocracy** [comment]
I have never heard of this in 2 years.  You prob have a js error.

On Monday, May 25, 2015, truongces <notifications@github.com> wrote:

> I am sorry, it's not crash. When I get the log as I sent you, all cordova
> plugin stop working. It's strange.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/188#issuecomment-105369211>
> .
>


-- 
Snet from Gmail Mobile

**Comment by truongces** [comment]
Hi,

You right, I have a js error. Sorry for bothering you. Thanks.
