### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by sebrojas14** [christocracy/cordova-plugin-background-geolocation#189]
Hi Chris, this plugin will help to implement a notification feature based on geolocation? (I need notify all devices in a specific area). Thanks

**Comment by christocracy** [comment]
My plugin tracks a device's geolocation while in background, executing a JavaScript callback each time a location is recorded.  You would presumably want to send that geolocation to the server.  Your server would use that information to decide which device to send a push to.

**Comment by sebrojas14** [comment]
Ok. And what is the difference con the cordova plugin geolocation?

**Comment by christocracy** [comment]
The std Cordova geolocation plugin is meant to operate only in the
foreground.  My plugin has a significant amount of intelligence for running
long term in the background and conserving battery.

My plugin uses a geofencing around the device's "stationary region".  When
device moves beyond the "stationary geofence", it begins aggressively
tracking location.

When device is detected to have stopped, a new stationary geofence is
created.

You use both, not just mine or std Cordova plugin.  I use std Cordova
plugin in foreground for updating the user's location on map.  I use my
plugin to send location to server.

My plugin has significantly more configure options too.

On Monday, May 25, 2015, Sebastián Rojas Ricaurte <notifications@github.com>
wrote:

> Ok. And what is the difference con the cordova plugin geolocation?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/189#issuecomment-105370280>
> .
>


-- 
Snet from Gmail Mobile

**Comment by christocracy** [comment]
And the [Premium Version](http://christocracy.github.io/cordova-background-geolocation/) has significantly more options and intelligence than the free version you’re looking at here.  The Premium Android version is particularly better for battery performance.

**Comment by sebrojas14** [comment]
Thankyou

**Comment by fcavola** [comment]
Hi, your plugin work only in Background or even if the app is closed? For example when the user re-boot the phone?
Thank you.
Francesco

**Comment by christocracy** [comment]
For iOS, when you execute `#start` on my plugin, it does 2 things
- initiates iOS significant-changes system
- creates a "stationary geofence" (a geofence around the user's current location).

iOS will automatically boot the app when a geofence is running or a significant-change event is fired.

If the user reboots their phone then gets in their car to drive, the app will be awoken when they drive out of the "stationary-geofence".

So to answer your question, yes and yes.

**Comment by christocracy** [comment]
http://stackoverflow.com/questions/17174042/ios-corelocation-and-geofencing-while-app-is-closed

**Comment by fcavola** [comment]
Thank you Chris, and for Android ?
We use the plugin on Android but when app is closed service stops to work.I'm wrong? 
Maybe we have to manage the boot_completed event?
Thank you in advance.

**Comment by christocracy** [comment]
You'll have a much better time using the Premium version with ~10* better
battery efficiency.

http://christocracy.github.io/cordova-background-geolocation/



On Thursday, May 28, 2015, fcavola <notifications@github.com> wrote:

> Thank you Chris, and for Android ?
> We use the plugin on Android but when app is closed service stops to
> work.I'm wrong?
> Maybe we have to manage the boot_completed event?
> Thank you in advance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/189#issuecomment-106200872>
> .
>


-- 
Snet from Gmail Mobile
