### ISSUE TITLE
[android] Location callback

### ISSUE THREAD

**Issue by danilomendonca** [christocracy/cordova-plugin-background-geolocation#19]
The background geolocation works fine in Android 4.3 (Galaxy S3). It successfully POST data to the server, but so far I was unable to use the javascript callback to process the location and make some actions in my front end application (I have to update the  traveled distance using the location data). 

Can I really interact with my application using the callbackFn?

**Comment by christocracy** [comment]
FYI Android has been completely refactored
- No more in-plugin HTTP -- plugin now executes your Javascript callback, just like iOS
- Significantly improved battery performance

http://christocracy.github.io/cordova-background-geolocation/
