### ISSUE TITLE
Premium Version Demo App

### ISSUE THREAD

**Issue by charliecharlie** [christocracy/cordova-plugin-background-geolocation#191]
Could you post a demo app in order to test the operation and performance and subsequently purchase the license?

**Comment by christocracy** [comment]
I have an app under review in App store.

On Wed, May 27, 2015 at 10:54 PM, charliecharlie <notifications@github.com>
wrote:

> Could you post a demo app in order to test the operation and performance
> and subsequently purchase the license?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/191>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by charliecharlie** [comment]
Oh, that sounds great, I hope it to be released soon. What about an Android app demo?

**Comment by christocracy** [comment]
Have you tried the free version?

On Wed, May 27, 2015 at 11:12 PM, charliecharlie <notifications@github.com>
wrote:

> Oh, that sounds great, I hope it to be released soon. What about an
> Android app demo?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/191#issuecomment-106157638>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by charliecharlie** [comment]
Yes but I think the premium version is quite different because of the use of activity recognition and I would like to know how it works.

**Comment by christocracy** [comment]
it samples your current-activity at configurable sample-rate
(#activityRecognitionInterval), e.g.:  every 10s, 30s.

This API is low-power and runs constantly, spitting out an answer “STILL”,
“ON_FOOT”, “IN_VEHICLE”, “ON_BICYCLE”, “RUNNING”, etc.

When the plugin sees “STILL”, it turns off the location-updates (i.e.; GPS).
When the plugin see “IN_VEHICLE”, “ON_FOOT”, “ON_BICYCLE”, “RUNING”, it
turns on location-updates.

It’s very quick (depending on the configured #activityRecognitionInterval)
to pick up state-changes.  This system is much better than iOS.

Here’s a typical adb logcat

- requesting activity updates 10000
Activity detected:still, confidence:100
Activity detected:still, confidence:100
Activity detected:still, confidence:100



Activity detected:on_foot, confidence:81  <-- "on_foot" detected
- setPace: true   <-- turn on GPS
Location received: Location[fused 45.519265,-73.616908 acc=10
et=+23h20m44s778ms]
- INSERT, id: 67, timestamp: 2015-05-28T03:22:32Z   <-- location persisted
to SQLite
Locked 1 records <-- Record locked in preparation for POSTing to server.
POST batch (1 records) <-- HTTP POST to configured #url
RESPONSE received: HTTP/1.1 200 OK <-- Server responds with "OK"
- DELETE SUCCESS (1) <-- Location is deleted from SQLite db.
Activity detected:on_foot, confidence:46
Activity detected:still, confidence:100 <-- "still" detected
- setPace: false <-- Turning off GPS
Activity detected:still, confidence:100 <-- Back to low-power mode.
Activity detected:still, confidence:100
Activity detected:still, confidence:100



On Wed, May 27, 2015 at 11:18 PM, charliecharlie <notifications@github.com>
wrote:

> Yes but I think the premium version is quite different because of the use
> of activity recognition and I would like to know how it works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/191#issuecomment-106158092>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by charliecharlie** [comment]
Ok thank you, I think this android free version will become obsolete soon, I hope you can still improve it for the people that can't acquire a licence.

**Comment by christocracy** [comment]
Free Android is obsolete.  All work goes into the Premium version which is
completely refactored.

On Thu, May 28, 2015 at 12:18 AM, charliecharlie <notifications@github.com>
wrote:

> Ok thank you, I think this android free version will become obsolete soon,
> I hope you can still improve it for the people that can't acquire a licence.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/191#issuecomment-106165846>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
