### ISSUE TITLE
Stationary feature

### ISSUE THREAD

**Issue by espicone** [christocracy/cordova-plugin-background-geolocation#192]
Hi guys, congratulations, your plugin works great.
Is there any chance to send positions when the device is stationary? I have a case where I need to determine if the device is stationary more than X minutes so it would be useful that it sends positions when it is stationary, even at low frequency, for example 1 position every 10-15 minutes. Also It would be acceptable that these positions repeat the coordinates of the last GPS position.  
What do you think? Thanks!

**Comment by christocracy** [comment]
Impossible.  When iOS goes to stationary-mode, it turns of std
location-services.  When std location-services are switched off, iOS
automatically suspends the application.  When in the stationary-state,
there is no code running; the app is asleep.

On Mon, Jun 1, 2015 at 2:05 PM, Esteban Picone <notifications@github.com>
wrote:

> Hi guys, congratulations, your plugin works great.
> Is there any chance to send positions when the device is stationary? I
> have a case where I need to determine if the device is stationary more than
> X minutes so it would be useful that it sends positions when it is
> stationary, even at low frequency, for example 1 position every 10-15
> minutes. Also It would be acceptable that these positions repeat the
> coordinates of the last GPS position.
>
> What do you think? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/192>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by espicone** [comment]
Do you think that setting distanceFilter to a low value could help in my scenario?
Thanks

**Comment by christocracy** [comment]
#distanceFilter is only used while std. location-services have been
activated, after exiting stationary-mode.


On Mon, Jun 1, 2015 at 2:47 PM, Esteban Picone <notifications@github.com>
wrote:

> Do you think that setting distanceFilter to a low value could help in my
> scenario?
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/192#issuecomment-107668697>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
