### ISSUE TITLE
Does Android premium version still use foreground service?

### ISSUE THREAD

**Issue by msokk** [christocracy/cordova-plugin-background-geolocation#193]
Is there a persistent notification shown all the time or is it invisible?

**Comment by christocracy** [comment]
The notification is a requirement of an Androjd "foreground service".  It
is always visible.

The premium version does not run as a "fg service" so does not have this
notification requirement

On Wednesday, June 3, 2015, Mihkel Sokk <notifications@github.com> wrote:

> Is there a persistent notification shown all the time or is it invisible?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/193>
> .
>


-- 
Snet from Gmail Mobile

**Comment by msokk** [comment]
Great, thanks!
