### ISSUE TITLE
http post take more than 1 minute !?

### ISSUE THREAD

**Issue by firaskudsy** [christocracy/cordova-plugin-background-geolocation#194]
am using this plugin and set the url to point to my php page that read the post and insert it into mysql table, but i get 0 in latitude and longtitude !!? when i test the code on my ionic application it get the latitude and longtitude values and post them to the server but with delay like every 1 minute or around 800 m !! the setting am using in both my ionic app and on this application is the same

 desiredAccuracy: 0,
stationaryRadius: 30,
distanceFilter: 50,
stopTimeout:0,

any help ? how often the location post ? or how ? based on distance or time ?

**Comment by christocracy** [comment]
Have you tried running this repo's SampleApp?

**Comment by firaskudsy** [comment]
am using ionic , and iv installed the plugin for cordova 4.x and using the same example in the readme, and i cant see any big deferent between the code in the readme and the code in the sammple app  your advice ?

**Comment by christocracy** [comment]
Have you read the "Android Config" section of README and implemented *all*
the params listed there?

On Monday, June 15, 2015, firaskudsy <notifications@github.com> wrote:

> am using ionic , and iv installed the plugin for cordova 4.x and using the
> same example in the readme, and i cant see any big deferent between the
> code in the readme and the code in the sammple app your advice ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/194#issuecomment-111973288>
> .
>


-- 
Snet from Gmail Mobile

**Comment by firaskudsy** [comment]
yes . this is my code 

         $scope.bgGeo.configure(callbackFn, failureFn, {
     //                url: 'http://www.najaf-aacblock.com/drLocationSync.php', // <-- Android ONLY:  your server url to send locations to
     url: 'http://www.mytestserver.com/savelocation2.php', // <-- Android ONLY:  your server url to send locations to
     params: {
         driver_id: $scope.did
     },
     desiredAccuracy: 0,
     stationaryRadius:50,
     distanceFilter: 10,
     notificationTitle: 'خدمة تحديث موقع الدراجة', // <-- android only, customize the title of the notification
     notificationText: 'مفعلة',
     activityType: 'AutomotiveNavigation',
     debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
     stopOnTerminate: false // <-- enable this to clear background location settings when the app terminates
 });

**Comment by christocracy** [comment]
You're not interested in:

`@param {Integer} locationTimeout

The minimum time interval between location updates, in seconds. See Android
docs
<http://developer.android.com/reference/android/location/LocationManager.html#requestLocationUpdates(long,%20float,%20android.location.Criteria,%20android.app.PendingIntent)>
for
more information.

??

On Monday, June 15, 2015, firaskudsy <notifications@github.com> wrote:

> yes . this is my code
>
>      $scope.bgGeo.configure(callbackFn, failureFn, {
>  //                url: 'http://www.najaf-aacblock.com/drLocationSync.php', // <-- Android ONLY:  your server url to send locations to
>  url: 'http://www.mytestserver.com/savelocation2.php', // <-- Android ONLY:  your server url to send locations to
>  params: {
>      driver_id: $scope.did
>  },
>  desiredAccuracy: 0,
>  stationaryRadius:50,
>  distanceFilter: 10,
>  notificationTitle: 'خدمة تحديث موقع الدراجة', // <-- android only, customize the title of the notification
>  notificationText: 'مفعلة',
>  activityType: 'AutomotiveNavigation',
>  debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
>  stopOnTerminate: false // <-- enable this to clear background location settings when the app terminates
>
> });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/194#issuecomment-111974290>
> .
>


-- 
Snet from Gmail Mobile

**Comment by firaskudsy** [comment]
yes, this one fix the issue, many thanks
