### ISSUE TITLE
background location not sending data to my server

### ISSUE THREAD

**Issue by cissemy** [christocracy/cordova-plugin-background-geolocation#195]
For some reason my app is not sending back to the server my location.
I am using :

```
var courier = '0992';
var bgGeo;
function onDeviceReady() {
   if (window.plugins.backgroundGeoLocation) {
        configureBackgroundGeoLocation();
    }
}
configureBackgroundGeoLocation=function () {
    // Your app must execute AT LEAST ONE call for the current position via standard Cordova geolocation,
    //  in order to prompt the user for Location permission.
    window.navigator.geolocation.getCurrentPosition(function (position) {
        console.log('Location from Phonegap');
    });

     bgGeo = window.plugins.backgroundGeoLocation;

    /**
    * This would be your own callback for Ajax-requests after POSTing background geolocation to your server.
    */
    var yourAjaxCallback = function (response) {
      
        bgGeo.finish();
    };

    /**
    * This callback will be executed every time a geolocation is recorded in the background.
    */
    var callbackFn = function (position) {
        console.log('[js] BackgroundGeoLocation callback:  ' + position.latitudue + ',' + position.longitude);
        // Do your HTTP request here to POST location to your server.
        // this part is not working
         var url = "http://myserver/service1.asmx/Courier_GPS?CourierID=" + courier + "&Latitude=" + position.coords.latitude + "&Longitude=" + position.coords.longitude;
        $.ajax({
            type: "GET",
            url: url,
            dataType: "json",
            success: function (xml) {
                var p = JSON.stringify(xml.GPS);
                var v = JSON.parse(p);
                if (v[0].Warning === "") {
                    console.log('backgrd Gps successfuly'); // showToast('toast', 'backgrd Gps successfuly!', 'success');
                }
                else {
                    console.log('backgrd Gps error'); // showToast('toast', v[0].Warning, 'error');
                }
            },
            error: function (xml) {
                console.log('backgrd Gps error')//showToast('toast', 'Gps Error!', 'error');
            }
        });   
        yourAjaxCallback.call(this);
    };

    var failureFn = function (error) {
        console.log('BackgroundGeoLocation error');
    }

    // BackgroundGeoLocation is highly configurable.
    bgGeo.configure(callbackFn, failureFn, {
       
        desiredAccuracy: 10,
        stationaryRadius: 20,
        distanceFilter: 30,
       // notificationTitle: 'Background tracking',   // <-- android only, customize the title of the notification
        //notificationText: 'ENABLED',                // <-- android only, customize the text of the notification
        activityType: "AutomotiveNavigation",       // <-- iOS-only
        debug: true     // <-- enable this hear sounds for background-geolocation life-cycle.
    });

    // Turn ON the background-geolocation system.  The user will be tracked whenever they suspend the app.
    bgGeo.start();

    // If you wish to turn OFF background-tracking, call the #stop method.
    // bgGeo.stop()
}
```

Thanks

**Comment by christocracy** [comment]
See my comments prefixed with `CHRIS:`
https://gist.github.com/christocracy/74ffb8ad3b8e691abd61

**Comment by cissemy** [comment]
Hi Chris ,
I did get rid of
 var yourAjaxCallback = function (response) {  // <-- CHRIS:  GET RID OF THIS
 
        bgGeo.finish();
    };
and 
yourAjaxCallback.call(this);  // <-- CHRIS:  GET RID OF THIS.  You're sending a signal to the native code that your task is complete **BEFORE** you even execute your Ajax reques
but the app is still not sending data to my server.
My code now is : 
 configureBackgroundGeoLocation = function () {
    // Your app must execute AT LEAST ONE call for the current positiona via standard Cordova geolocation,
    //  in order to prompt the user for Location permission.
    window.navigator.geolocation.getCurrentPosition(function (position) {
        console.log('Location from Phonegap');
     });
    bgGeo = window.plugins.backgroundGeoLocation;

var callbackFn = function (position) {
    console.log('BackgroundGeoLocation:  ' + position.coords.latitude + ',' + position.coords.longitude);
    var url = "http://ws2.deluxedelivery.com/service1.asmx/Courier_GPS?CourierID=" + courier + "&Latitude=" + position.coords.latitude + "&Longitude=" + position.coords.longitude;
    $.ajax({
        type: "GET",
        url: url,
        dataType: "json",
        success: function (xml) {
            var p = JSON.stringify(xml.GPS);
            var v = JSON.parse(p);
            if (v[0].Warning === "") {
                console.log('backgrd Gps successfuly'); //showToast('toast', 'Gps successfuly!', 'success');
            }
            else {
                console.log('backgrd Gps error'); // showToast('toast', v[0].Warning, 'error');
            }
            bgGeo.finish();
        },
        error: function (xml) {
            console.log('backgrd Gps error'); //showToast('toast', 'Gps Error!', 'error');
        }
    });
};
var failureFn = function (error) {
    console.log('BackgroundGeoLocation error');
}
bgGeo.configure(callbackFn, failureFn, {

    desiredAccuracy: 10,
    stationaryRadius: 20,
    distanceFilter: 30,
    // notificationTitle: 'Background tracking',   // <-- android only, customize the title of the notification
    //notificationText: 'ENABLED',                // <-- android only, customize the text of the notification
    activityType: "AutomotiveNavigation",       // <-- iOS-only
    debug: true     // <-- enable this hear sounds for background-geolocation life-cycle.
});
 // Turn ON the background-geolocation system.  The user will be tracked whenever they suspend the app.
  bgGeo.start();
  } 
Thanks

**Comment by christocracy** [comment]
Have you tried the SampleApp?  see README for instructions.

**Comment by cissemy** [comment]
Yes. I did it.
My code is based on sampleApp.
Thanks

**Comment by cissemy** [comment]
Hi ,
Here is what my app shows  Location update  but  callbackFn not being executed otherwise i will get update to my server.
![bgeo](https://cloud.githubusercontent.com/assets/87177/8435544/c6c95662-1f1f-11e5-81ab-c55a58dfcab3.PNG)

**Comment by christocracy** [comment]
Are you monitoring the JavaScript web console?

On Tuesday, June 30, 2015, Mohamed Y. Cisse <notifications@github.com>
wrote:

> Hi ,
> Here is what my app shows Location update but callbackFn not being
> executed otherwise i will get update to my server.
> [image: bgeo]
> <https://cloud.githubusercontent.com/assets/87177/8435544/c6c95662-1f1f-11e5-81ab-c55a58dfcab3.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/195#issuecomment-117238809>
> .
>


-- 
Snet from Gmail Mobile

**Comment by cissemy** [comment]
Yes .
I do not get any message from javascript console.
Thanks

**Comment by christocracy** [comment]
Show me a screenshot of your web console.

**Comment by cissemy** [comment]
i cannot execute cordova.js from the browser.
i am not using phonegap/eclipse in am developing using devexpresss devextreme 
http://js.devexpress.com/MobileDevelopment/
and create ipa file using adobe phonegap build.
I have 
var callbackFn = function (position) {
        showToast('toast', 'In callbackFn!', 'success');
    console.log('BackgroundGeoLocation:  ' + position.coords.latitude + ',' + position.coords.longitude);
    var url = "http://myserver/Courier_GPS?CourierID=" + courier + "&Latitude=" + position.coords.latitude + "&Longitude=" + position.coords.longitude;
    $.ajax({
        type: "GET",
        url: url,
        dataType: "json",
        success: function (xml) {
            var p = JSON.stringify(xml.GPS);
            var v = JSON.parse(p);
            if (v[0].Warning === "") {
                console.log('backgrd Gps successfuly'); //showToast('toast', 'Gps successfuly!', 'success');
            }
            else {
                console.log('backgrd Gps error'); // showToast('toast', v[0].Warning, 'error');
            }
            bgGeo.finish();
        },
        error: function (xml) {
            console.log('backgrd Gps error'); //showToast('toast', 'Gps Error!', 'error');
        }
    });
};
If callbackFn is executed i should get the message 'In callbackFn!' on my phone screen.
Thanks

**Comment by christocracy** [comment]
Show me a screenshot of your JavaScript console.  If you cannot do that,
you have bigger problems.

You likely have a JavaScript error in your callback which is preventing
your Ajax request from running.

The callback is running.

On Tuesday, June 30, 2015, Mohamed Y. Cisse <notifications@github.com>
wrote:

> i cannot execute cordova.js from the browser.
> i am not using phonegap/eclipse in am developing using devexpresss
> devextreme
> http://js.devexpress.com/MobileDevelopment/
> and create ipa file using adobe phonegap build.
> I have
> var callbackFn = function (position) {
> showToast('toast', 'In callbackFn!', 'success');
> console.log('BackgroundGeoLocation: ' + position.coords.latitude + ',' +
> position.coords.longitude);
> var url = "http://myserver/Courier_GPS?CourierID=" + courier +
> "&Latitude=" + position.coords.latitude + "&Longitude=" +
> position.coords.longitude;
> $.ajax({
> type: "GET",
> url: url,
> dataType: "json",
> success: function (xml) {
> var p = JSON.stringify(xml.GPS);
> var v = JSON.parse(p);
> if (v[0].Warning === "") {
> console.log('backgrd Gps successfuly'); //showToast('toast', 'Gps
> successfuly!', 'success');
> }
> else {
> console.log('backgrd Gps error'); // showToast('toast', v[0].Warning,
> 'error');
> }
> bgGeo.finish();
> },
> error: function (xml) {
> console.log('backgrd Gps error'); //showToast('toast', 'Gps Error!',
> 'error');
> }
> });
> };
> If callbackFn is executed i should get the message 'In callbackFn!' on my
> phone screen.
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/195#issuecomment-117286972>
> .
>


-- 
Snet from Gmail Mobile

**Comment by cissemy** [comment]
do you mind if i email you my code full app code?

**Comment by christocracy** [comment]
Sorry, I’m not interested.  Have you booted the SampleApp provided in the
repo?  see README for details.

On Tue, Jun 30, 2015 at 5:17 PM, Mohamed Y. Cisse <notifications@github.com>
wrote:

> do you mind if i email you my code full app code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/195#issuecomment-117345094>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
I'm 100% sure that the problem is not related to my plugin -- you have a problem in your application code.

No offence, but I suspect you're new to Cordova / PhoneGap.  Your problem is you lack basic Cordova debugging skills.

When you're able to boot a web-console to debug your Javascript, you'll find the problem in no time.  Following is a screenshot of my Safari web-console.  Notice, for example, that my code is currently stopped at a `debugger` breakpoint.  This code in the console is running on my physical iPhone 5.  If you can't do this, you are debugging blind.

![Debugger](https://www.dropbox.com/s/ekw1crn4xyz52fi/Screenshot%202015-06-30%2017.29.11.png?dl=1)

**Comment by cissemy** [comment]
Hi,
It is ok.It is not an offence.
I am able to find error on web console i did fix one and the missing cordova.js is added when building the zip.I using google chrome.I am going to deploy on my iphone and i will let you know.
I appreciate your help.
Thanks
![error](https://cloud.githubusercontent.com/assets/87177/8442827/4ee5f210-1f4f-11e5-97f8-f9b05fc21458.PNG)

**Comment by cissemy** [comment]
Hi,
I think the background geolocation is working now.
Is it possible to send location every 5 minutes and disable the notification message on the screen like : "Location update : moving"
Thanks

**Comment by christocracy** [comment]
It is **not** possible to send location every x minutes.  Native geolocation apis are *distance-based", not "time-based".

The notifications are part of [debug mode](https://github.com/christocracy/cordova-plugin-background-geolocation#param-boolean-debug).  set `debug: false`

**Comment by cissemy** [comment]
In your foreground sample application you use watchposition with frequency:10000 and timeout:10000
Is that giving  me data every 10 seconds ?

**Comment by christocracy** [comment]
Yes, In the foreground you can do whatever you wish with the standard
Cordova geolocation.

In the foreground, it often makes sense to have time updates and update the
user’s current position on a map, for example.

Background geolocation is a completely different behaviour.  There will
never be time-based geolocation in the background.

On Wed, Jul 1, 2015 at 3:39 PM, Mohamed Y. Cisse <notifications@github.com>
wrote:

> In your foreground sample application you use watchposition with
> frequency:10000 and timeout:10000
> Is that giving me data every 10 seconds ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/195#issuecomment-117803103>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
If you want to know where a device is every x minutes, run a worker-thread on your server to send out Push requests every x minutes to the devices you wish to know the location of.  

iOS provides exactly 30s of background running-time when receiving a Push notification in the background.  You can use the standard Cordova Geolocation plugin to achieve this.  My plugin is not involved in that at all.

**Comment by christocracy** [comment]
I made an ios plugin for receiving Push notifications in the background and executing a callback.

https://github.com/christocracy/cordova-plugin-background-notification

**Comment by cissemy** [comment]
Great

**Comment by christocracy** [comment]
If you turn on a watchPosition in the foreground, be damn sure to stop it
when the app goes to background or kiss your battery goodbye.

On Wednesday, July 1, 2015, Mohamed Y. Cisse <notifications@github.com>
wrote:

> Great
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/195#issuecomment-117807470>
> .
>


-- 
Snet from Gmail Mobile

**Comment by cissemy** [comment]
for foreground  i am using : 
setInterval(function(){ myLocation() }, 300000); 'every 5 minutes
where 
function myLocation() {
      navigator.geolocation.getCurrentPosition(onSuccess, onError, { enableHighAccuracy: true });
}

**Comment by christocracy** [comment]
I'm not concerned with how you use any plugin but mine

On Wednesday, July 1, 2015, Mohamed Y. Cisse <notifications@github.com>
wrote:

> for foreground i am using :
> setInterval(function(){ myLocation() }, 300000); 'every 5 minutes
> where
> function myLocation() {
> navigator.geolocation.getCurrentPosition(onSuccess, onError, {
> enableHighAccuracy: true });
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/195#issuecomment-117812726>
> .
>


-- 
Snet from Gmail Mobile

**Comment by nesjett** [comment]
Im running on the same issue, seems like my callback function is not running.

I just have an alert('test'); on the very top of the callback function and it doesnt launch de alert.
The plugin is beign executed because I can start/stop the background geolocation, but even if I´m passing a url on the bg configuraction, no post is made, and no callback is called.

Any advice on that? I´m running on android

I´ve read that the post must be done on the callback function, through javascript, but then, why your plugin has http requests on the .java files? and the url configuration parameter?


Thanks

**Comment by christocracy** [comment]
This plugin is no longer supported (almost a year since).  See README for
link to new version.

On Friday, December 11, 2015, Néstor Sabater <notifications@github.com>
wrote:

> Im running on the same issue, seems like my callback function is not
> running.
>
> I just have an alert('test'); on the very top of the callback function and
> it doesnt launch de alert.
> The plugin is beign executed because I can start/stop the background
> geolocation, but even if I´m passing a url on the bg configuraction, no
> post is made, and no callback is called.
>
> Any advice on that? I´m running on android
>
> I´ve read that the post must be done on the callback function, through
> javascript, but then, why your plugin has http requests on the .java files?
> and the url configuration parameter?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/195#issuecomment-164058081>
> .
>


-- 
Snet form Gmail Mobile

**Comment by KirtiKumari5** [comment]
@christocracy ..Does OnDeviceReady function call when app launches in background for the first time by significant location API of iOS(remain in background only, does not come to foreground)?

**Comment by christocracy** [comment]
This version of plugin is no longer supported.  It has moved.  See [`README`](https://github.com/christocracy/cordova-plugin-background-geolocation)

**Comment by itsupportvspl** [comment]
hi ,

the below code is to get location and upload to server 

function configureBackgroundGeoLocation() {
bgGeo.on('location', callbackFn, failureFn);
   bgGeo.configure({
                  // Geolocation config
                  desiredAccuracy: 0,
                  distanceFilter: 20,

                  // Activity recognition config
                  activityRecognitionInterval: 10000,
                  stopTimeout: 1,	 // Stop-detection timeout minutes (wait x minutes to turn off tracking)

                  // Application config
                  debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
                  logLevel: bgGeo.LOG_LEVEL_VERBOSE,    // Verbose logging
                  stopOnTerminate: false,               // Don't stop tracking when user closes app.
                  startOnBoot: true,                    // Auto-start tracking on reboot
                  // HTTP / SQLite config
                  url: http://172.16.1.11:70/Service/Service.svc/RunStoredProcedureReturnsDataset?ConnectionString_Encrypted=FAICTranDBConnection&ProcedureName_Encrypted=Gpstrack&ParametersList_Encrypted=aswin|1.0.8(DEV)|FAiC|'+location.coords.latitude+'|'+location.coords.longitude,
                  batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
                  autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
                  maxDaysToPersist: 1,    // <-- Maximum days to persist a location in plugin's SQLite database when HTTP fails
              }, function(state) {
                // Plugin is configured and ready to use.
                if (!state.enabled) {
                  bgGeo.start();  // <-- start-tracking
                }
              });
     var callbackFn = function(location) {
              console.log('[js] BackgroundGeoLocation callback:  ' + location.coords.latitude + ',' + location.coords.longitude);
                myUpdatePositionOnMapMethod(location);
                var lat = location.coords.latitude;
                var lng = location.coords.longitude;

                setGlobalValue('RES_RECEIVED',"DAmmi"+location.coords.longitude+location.coords.latitude);

                 if (location.sample) {
                    console.log('- Ignore samples');
                    return;
                }
               
              };
     var failureFn = function(error) {
                     console.log('BackgroundGeoLocation error', error);
     }

          bgGeo.start();

}

**Comment by christocracy** [comment]
This version of the plugin is no longer supported for over 3 years now.  See the README (as I said above!)

**Comment by itsupportvspl** [comment]
please share that README link

**Comment by christocracy** [comment]
Look at the post right **ABOVE** yours.  You didn’t read *ANY* of the messages in this thread, did you?

**Comment by itsupportvspl** [comment]
hi ,

i am unable to upload the location to my db ,below is my log.
getting http failure: every time
╔═════════════════════════════════════════════
                                                                            ║ BackgroundGeolocation Settings
                                                                            ╠═════════════════════════════════════════════
                                                                            {
                                                                              "isMoving": false,
                                                                              "enabled": true,
                                                                              "odometer": 117.27817,
                                                                              "schedulerEnabled": false,
                                                                              "trackingMode": "location",
                                                                              "distanceFilter": 10,
                                                                              "desiredAccuracy": 0,
                                                                              "desiredOdometerAccuracy": 100,
                                                                              "locationUpdateInterval": 1000,
                                                                              "fastestLocationUpdateInterval": 10000,
                                                                              "locationTimeout": 60,
                                                                              "deferTime": 0,
                                                                              "disableElasticity": false,
                                                                              "elasticityMultiplier": 1,
                                                                              "activityRecognitionInterval": 30000,
                                                                              "minimumActivityRecognitionConfidence": 75,
                                                                              "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
                                                                              "disableStopDetection": false,
                                                                              "stationaryRadius": 25,
                                                                              "stopTimeout": 5,
                                                                              "stopOnStationary": false,
                                                                              "url": "http:\/\/myip\/Service\/Service.svc\/RunStoredProcedureReturnsDataset?ConnectionString_Encrypted=FAICTranDBConnection&ProcedureName_Encrypted=Gpstrack&ParametersList_Encrypted=aswin|1.0.8(DEV)|FAiC|12.22222|70.77777",
                                                                              "method": "POST",
                                                                              "autoSync": true,
                                                                              "autoSyncThreshold": 0,
                                                                              "batchSync": false,
                                                                              "maxBatchSize": -1,
                                                                              "params": {},
                                                                              "headers": {
                                                                                "ContentType": "application\/json",
                                                                                "DataType": "json",
                                                                                "ProcessData": "true"
                                                                              },
                                                                              "extras": {},
                                                                              "httpRootProperty": "location",
                                                                              "locationTemplate": "",
                                                                              "geofenceTemplate": "",
                                                                              "persist": true,
                                                                              "maxDaysToPersist": 3,
                                                                              "maxRecordsToPersist": -1,
                                                                              "locationsOrderDirection": "ASC",
                                                                              "httpTimeout": 60000,
                                                                              "geofenceProximityRadius": 1000,
                                                                              "geofenceInitialTriggerEntry": true,
                                                                              "stopOnTerminate": false,
                                                                              "startOnBoot": true,
                                                                              "heartbeatInterval": -1,
                                                                              "foregroundService": false,
                                                                              "notificationPriority": 0,
                                                                              "notificationTitle": "",
                                                                              "notificationText": "Location Service activated",
                                                                              "notificationColor": "",
                                                                              "notificationIcon": "",
                                                                              "notificationSmallIcon": "",
                                                                              "notificationLargeIcon": "",
                                                                              "forceReloadOnLocationChange": false,
                                                                              "forceReloadOnMotionChange": false,
                                                                              "forceReloadOnGeofence": false,
                                                                              "forceReloadOnBoot": false,
                                                                              "forceReloadOnHeartbeat": false,
                                                                              "forceReloadOnSchedule": false,
                                                                              "stopAfterElapsedMinutes": 0,
                                                                              "schedule": [],
                                                                              "configureUrl": "",
                                                                              "configureInterval": -1,
                                                                              "debug": true,
                                                                              "logLevel": 5,
                                                                              "logMaxDays": 3
                                                                            }╚═════════════════════════════════════════════

**Comment by christocracy** [comment]
Do you not understand that *THIS* repo is **DEAD**?  Why are you posting here?
