### ISSUE TITLE
GPS request always connected

### ISSUE THREAD

**Issue by wworley** [christocracy/cordova-plugin-background-geolocation#196]
So i'm not sure how this plugin saves battery as the GPS fix seems to always be constant(as shown by the location icon in the status bar on both android(nexus 5) and iOS(tested on iphone6 and ipadmini)), unless i use the getCurrentPosition in my onDeviceReady, but if i do that then the plugin will not run in the background and check for GPS changes, so the only way i was able to get the plugin to do the background checks was to use watchPosition in my onDeviceReady which does cause the GPS location to be updated but the GPD fix icon is always in the status bar on all devices which means the app is 100% more likely to get disapproved by the app markets for to much "location" demand and over usage of battery.

See screenshot below

![screenshot_2015-06-21-17-49-12](https://cloud.githubusercontent.com/assets/7535181/8273483/2ffe9f72-183e-11e5-84d3-56189004ce79.png)

This is the two calls

NOT WORKING (as the background refresh doesn't work)
navigator.geolocation.getCurrentPosition(onDPosSuccess, onDPosError,{maximumAge:0, timeout:5000, enableHighAccuracy:true});

WORKING (background refresh works but the GPs fix icon is always shown and battery usage is high)
navigator.geolocation.watchPosition(onDPosSuccess, onDPosError, {maximumAge:0, timeout:5000, frequency: 60000, enableHighAccuracy: true});

**Comment by christocracy** [comment]
The free Android version is horrible for battery life.

The premium version has been completely refactored to use google play
services and is excellent for battery life.

http://christocracy.github.io/cordova-background-geolocation/


On Sunday, June 21, 2015, wworley <notifications@github.com> wrote:

> So i'm not sure how this plugin saves battery as the GPS fix seems to
> always be constant(as shown by the location icon in the status bar on both
> android(nexus 5) and iOS(tested on iphone6 and ipadmini)), unless i use the
> getCurrentPosition in my onDeviceReady, but if i do that then the plugin
> will not run in the background and check for GPS changes, so the only way i
> was able to get the plugin to do the background checks was to use
> watchPosition in my onDeviceReady which does cause the GPS location to be
> updated but the GPD fix icon is always in the status bar on all devices
> which means the app is 100% more likely to get disapproved by the app
> markets for to much "location" demand and over usage of battery.
>
> See screenshot below
>
> [image: screenshot_2015-06-21-17-49-12]
> <https://cloud.githubusercontent.com/assets/7535181/8273483/2ffe9f72-183e-11e5-84d3-56189004ce79.png>
>
> This is the two calls
>
> NOT WORKING (as the background refresh doesn't work)
> navigator.geolocation.getCurrentPosition(onDPosSuccess,
> onDPosError,{maximumAge:0, timeout:5000, enableHighAccuracy:true});
>
> WORKING (background refresh works but the GPs fix icon is always shown and
> battery usage is high)
> navigator.geolocation.watchPosition(onDPosSuccess, onDPosError,
> {maximumAge:0, timeout:5000, frequency: 60000, enableHighAccuracy: true});
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/196>
> .
>


-- 
Snet from Gmail Mobile

**Comment by wworley** [comment]
Chris promoting your premium version seems like a moot point when your free version can't even do what it is supposed to do, so why would i spend $500+ to buy something that doesn't even work for free.

So again i will state that your free plugin WILL NOT work on iOS as a background service if you use getCurrentPosition so you are forced to use watchPosition which causes the GPS location icon to remain active all the time and drain massive amounts of battery.

Maybe you should try to show your solution fully working in all claimed cases including using getCurrentPosition as a permission request on iOS, then start asking me to open my wallet to you.

**Comment by christocracy** [comment]
If you're using watchPosition from std Cordova geolocation, you'd better
wire up a Cordova pause listener to turn it off; resume listener to turn it
back on.

Premium iOS doesn't require std Cordova geolocation at all.  It manages
asking permissions on its own now.  It has its own #getCurrentPosition as
well.  It operates all the time too, not just in bg.

Have you not tried booting up the SampleApp included in the repo?  I don't
fully understand your issues and I suspect you have some false assumption
and/or doing it wrong.  The free iOS version has existed largely in the
current state for nearly 2 years with hundreds of users and I've never
heard anyone say anything like what you're saying.

On Sunday, June 21, 2015, wworley <notifications@github.com> wrote:

> Chris promoting your premium version seems like a moot point when your
> free version can't even do what it is supposed to do, so why would i spend
> $500+ to buy something that doesn't even work for free.
>
> So again i will state that your free plugin WILL NOT work on iOS as a
> background service if you use getCurrentPosition so you are forced to use
> watchPosition which causes the GPS location icon to remain active all the
> time and drain massive amounts of battery.
>
> Maybe you should try to show your solution fully working in all claimed
> cases including using getCurrentPosition as a permission request on iOS,
> then start asking me to open my wallet to you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/196#issuecomment-113990601>
> .
>


-- 
Snet from Gmail Mobile

**Comment by wworley** [comment]
@christocracy Please don't get me wrong i'm not trying to be a pain in the butt here and i have no issue opening my wallet to you for the premium, i just want to see it working within my own app before spending that much on a plugin that i can't get to work.

I think you nailed the reason why it's not working as expected is i'm not pausing the watchPosition when your background operation takes over.

see code below from my app cleared of all app specific functions

    document.addEventListener("deviceready", onDeviceReady, false);

    var bgGeo = window.plugins.backgroundGeoLocation;

    function onDeviceReady() {
        //BELOW IS NOT WORKING AS THE BACKGROUND SERVICE NEVER STARTS WORKING
        //navigator.geolocation.getCurrentPosition(onDPosSuccess, onDPosError,{maximumAge:0, timeout:5000, enableHighAccuracy:true});

        //BELOW WORKS BUT SHOWS THE LOCATION ICON ALL THE TIME
        navigator.geolocation.watchPosition(onDPosSuccess, onDPosError, {maximumAge:0, timeout:5000, frequency: 60000, enableHighAccuracy: true});

        bgGeo.configure(onBPosSuccess, onBPosError, {
            desiredAccuracy: 10,
            stationaryRadius: 20,
            distanceFilter: 30
        });

        bgGeo.start();
    }

    function onDPosSuccess(){
        $.ajax({
            url: DOMAIN,
            data:data,
            dataType:'json',
            type:'POST',
            success: function(result) {},
            error: function(){}
        });

        bgGeo.finish();
    }

    function onDPosError(){
        alert('error');
    }

**Comment by christocracy** [comment]
Have you tried the SampleApp?

On Sunday, June 21, 2015, wworley <notifications@github.com> wrote:

> @christocracy <https://github.com/christocracy> Please don't get me wrong
> i'm not trying to be a pain in the butt here and i have no issue opening my
> wallet to you for the premium, i just want to see it working within my own
> app before spending that much on a plugin that i can't get to work.
>
> I think you nailed the reason why it's not working as expected is i'm not
> pausing the watchPosition when your background operation takes over.
>
> see code below from my app cleared of all app specific functions
>
> document.addEventListener("deviceready", onDeviceReady, false);
>
> var bgGeo = window.plugins.backgroundGeoLocation;
>
> function onDeviceReady() {
>     //BELOW IS NOT WORKING AS THE BACKGROUND SERVICE NEVER STARTS WORKING
>     //navigator.geolocation.getCurrentPosition(onDPosSuccess, onDPosError,{maximumAge:0, timeout:5000, enableHighAccuracy:true});
>
>     //BELOW WORKS BUT SHOWS THE LOCATION ICON ALL THE TIME
>     navigator.geolocation.watchPosition(onDPosSuccess, onDPosError, {maximumAge:0, timeout:5000, frequency: 60000, enableHighAccuracy: true});
>
>     bgGeo.configure(onBPosSuccess, onBPosError, {
>         desiredAccuracy: 10,
>         stationaryRadius: 20,
>         distanceFilter: 30
>     });
>
>     bgGeo.start();
> }
>
> function onDPosSuccess(){
>     $.ajax({
>         url: DOMAIN,
>         data:data,
>         dataType:'json',
>         type:'POST',
>         success: function(result) {},
>         error: function(){}
>     });
>
>     bgGeo.finish();
> }
>
> function onDPosError(){
>     alert('error');
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/196#issuecomment-113995030>
> .
>


-- 
Snet from Gmail Mobile

**Comment by wworley** [comment]
I have not tried the sample app but if it can't work with my basic example above then it's seems like a lot more effort.

I guess your just not understanding the problem or seeing why i'm having an issue with it.

It's very simple if i uncomment the line in my example code above for the getCurrentPosition and i comment out the watchPosition your background process never works, but it DOES work in the example code above when the watchPosition is used however the GPS usage is through the roof due to the watchPosition constantly running.

**Comment by christocracy** [comment]
I don't look at anyone's app code until they boot the sample app so we're
on the same page.

On Monday, June 22, 2015, wworley <notifications@github.com> wrote:

> I have not tried the sample app but if it can't work with my basic example
> above then it's seems like a lot more effort.
>
> I guess your just not understanding the problem or seeing why i'm having
> an issue with it.
>
> It's very simple if i uncomment the line in my example code above for the
> getCurrentPosition and i comment out the watchPosition your background
> process never works, but it DOES work in the example code above when the
> watchPosition is used however the GPS usage is through the roof due to the
> watchPosition constantly running.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/196#issuecomment-113996116>
> .
>


-- 
Snet from Gmail Mobile

**Comment by wworley** [comment]
Give me 5 minutes then.... I will install and run your sample app on a Phonegap build project

**Comment by christocracy** [comment]
Take as much time as you want, you're not paying me for this.

On Monday, June 22, 2015, wworley <notifications@github.com> wrote:

> Give me 5 minutes then.... I will install and run your sample app on a
> Phonegap build project
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/196#issuecomment-113996756>
> .
>


-- 
Snet from Gmail Mobile

**Comment by christocracy** [comment]
I no longer provide direct updates to the public PGB version of my plugin.

PGB users are advised to take advantage of PGB ability to add *private*
plugins, and upload the master branch of this repo.

On Monday, June 22, 2015, wworley <notifications@github.com> wrote:

> Give me 5 minutes then.... I will install and run your sample app on a
> Phonegap build project
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/196#issuecomment-113996756>
> .
>


-- 
Snet from Gmail Mobile

**Comment by wworley** [comment]
WOW dude your business sense/customer services seems lacking. I almost purchased your plugin earlier just to get some of the other benefits, but didn't because i wanted to get it working using basic stuff first but the way your treating me i'm kind of glad i didn't if that's any indication of how your customer service is going to be after purchase. But just to clear things up here your telling me if i go buy right now your going to provide support for my exact issue that is better or more polite then?

**Comment by christocracy** [comment]
I'm sure everything will be fine when you get the SampleApp booted.

On Monday, June 22, 2015, wworley <notifications@github.com> wrote:

> WOW dude your business sense/customer services seems lacking. I almost
> purchased your plugin earlier just to get some of the other benefits, but
> didn't because i wanted to get it working using basic stuff first but the
> way your treating me i'm kind of glad i didn't if that's any indication of
> how your customer service is going to be after purchase. But just to clear
> things up here your telling me if i go buy right now your going to provide
> support for my exact issue that is better or more polite then?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/196#issuecomment-113997382>
> .
>


-- 
Snet from Gmail Mobile

**Comment by wworley** [comment]
It's booted and does work correctly and works as expected and i see now why your sample app works as expected, but why not just throw a few comments in your sample code and say watchPosition will stay on unless paused..

**Comment by christocracy** [comment]
My plugin certainly *facillitated* the ability of a foreign plugin to kill
the battery by preventing the OS from suspending due to its application of
the appropriate permissions.

I haven't heard of anyone making that mistake before.  I'll add a note.

Happy field-testing.  Since you're using PGB, don't forget to add
manually the UIBackgroundMode of "audio" in your plist so you hear debug
sounds when app is in bg.  That's described as an Xcode button click in
README


On Monday, June 22, 2015, wworley <notifications@github.com> wrote:

> It's booted and does work correctly and works as expected and i see now
> why your sample app works as expected, but why not just throw a few
> comments in your sample code and say watchPosition will stay on unless
> paused..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/196#issuecomment-113997823>
> .
>


-- 
Snet from Gmail Mobile

**Comment by wworley** [comment]
Thanks i've already setup my provisioning profile to have the correct settings and deployed successfully to both iphone and ipads. So you mentioned in sections of README that with premium there are little changes needed to get the premium working but you also mentioned here that the premium doesn't use getCurrentPosition but i assume you pass through any calls to getCurrentPosition  and call your own functions?

**Comment by christocracy** [comment]
Yes, I meant to change that line about "little changes required".

I've made some fundamental changes to iOS over the past few months.

- no more Cordova geolocation required
- native iOS persistence & http
- #onStationary deprecated in favor of #onMotionChange (fires for both
start-moving & stop)

The API is significantly expanded but you #configure, #start & #stop it in
the same manner.  It can be your sole geolocation provider for both fg & bg.

On Monday, June 22, 2015, wworley <notifications@github.com> wrote:

> Thanks i've already setup my provisioning profile to have the correct
> settings and deployed successfully to both iphone and ipads. So you
> mentioned in sections of README that with premium there are little changes
> needed to get the premium working but you also mentioned here that the
> premium doesn't use getCurrentPosition but i assume you pass through any
> calls to getCurrentPosition and call your own functions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/196#issuecomment-114007668>
> .
>


-- 
Snet from Gmail Mobile

**Comment by wworley** [comment]
Ok great, thank you for the helpful comments now :+1: 

I'm trying to use your plugin to every 60 seconds hit my server through a function call which passes lat/lon and other user info to my server then the server returns a json list of messages which i then serve notifications on the lock screen or they slide down from the top on iOS and play a sound when the message is received so can i "ignore" whether the users location is changed enough to warrant the success function call?

**Comment by wworley** [comment]
BTW i'm going to purchase your premium version as soon as i change all my code and get it to work with the sample app code (i was really not wanting to take the time to do so but your sample app did work....)

**Comment by christocracy** [comment]
You're doing it wrong.  Native geolocation is *distance-based* not
*time-based*.

You will never be able to fetch the location every x minutes with my
plugin, nor do you want to.  When I'm stuck in traffic and move 50 meters
in 10min, a typical distanceFilter for me when field testing, why kill the
battery recording 10 pings inside 50 meters??  My plugin will record just 1.

"so can i "ignore" whether the users location is changed enough to warrant
the success function call?"

This is called @param {number} distanceFilter as seen in my docs.  One of
the most important config params.

You might want to try installing the premium Android SampleApp and do some
field testing.  It has a rich settings screen allowing you to tweak all the
config params in realtime so you can immediately see the effect of tweaking
distanceFilter / desiredAccuracy and more.

On Monday, June 22, 2015, wworley <notifications@github.com> wrote:

> Ok great, thank you for the helpful comments now [image: :+1:]
>
> I'm trying to use your plugin to every 60 seconds hit my server through a
> function call which passes lat/lon and other user info to my server then
> the server returns a json list of messages which i then serve notifications
> on the lock screen or they slide down from the top on iOS and play a sound
> when the message is received so can i "ignore" whether the users location
> is changed enough to warrant the success function call?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/196#issuecomment-114009616>
> .
>


-- 
Snet from Gmail Mobile

**Comment by christocracy** [comment]
https://play.google.com/store/apps/details?id=com.transistorsoft.background_geolocation.ionic



On Monday, June 22, 2015, Chris Scott <christocracy@gmail.com> wrote:

> You're doing it wrong.  Native geolocation is *distance-based* not
> *time-based*.
>
> You will never be able to fetch the location every x minutes with my
> plugin, nor do you want to.  When I'm stuck in traffic and move 50 meters
> in 10min, a typical distanceFilter for me when field testing, why kill the
> battery recording 10 pings inside 50 meters??  My plugin will record just 1.
>
> "so can i "ignore" whether the users location is changed enough to
> warrant the success function call?"
>
> This is called @param {number} distanceFilter as seen in my docs.  One of
> the most important config params.
>
> You might want to try installing the premium Android SampleApp and do some
> field testing.  It has a rich settings screen allowing you to tweak all the
> config params in realtime so you can immediately see the effect of tweaking
> distanceFilter / desiredAccuracy and more.
>
> On Monday, June 22, 2015, wworley <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Ok great, thank you for the helpful comments now [image: :+1:]
>>
>> I'm trying to use your plugin to every 60 seconds hit my server through a
>> function call which passes lat/lon and other user info to my server then
>> the server returns a json list of messages which i then serve notifications
>> on the lock screen or they slide down from the top on iOS and play a sound
>> when the message is received so can i "ignore" whether the users location
>> is changed enough to warrant the success function call?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/196#issuecomment-114009616>
>> .
>>
>
>
> --
> Snet from Gmail Mobile
>


-- 
Snet from Gmail Mobile

**Comment by wworley** [comment]
Emailed you.
