### ISSUE TITLE
AppStore Background compliance? 

### ISSUE THREAD

**Issue by clarklight** [christocracy/cordova-plugin-background-geolocation#197]
Hi 

   I am looking at your Premium addition, just want to make sure, it is 100% compile with AppStore and Playstore background requirement before i purchase. As i know Apple is a bit touchy on those background requirements. 

Thanks

**Comment by christocracy** [comment]
Google is fine I have my SampleApp available here:

http://christocracy.github.io/cordova-background-geolocation/

iOS is, as you say, more finicky, but I personally have a client with 4
apps accepted.  It depends what you're doing.  If, for example, you're
making a fleet-tracking, taxi app or jogging app, it's perfectly
acceptable.

If you're making an Alarm Clock app and hoping to use my plugin to keep iOS
from suspending your app just so can run JavaScript timers, you'll be
disappointed.

I built this plugin by closely following Apple's published guidelines for
bg tracking.
https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/LocationAwarenessPG/CoreLocation/CoreLocation.html


On Wednesday, June 24, 2015, clarklight <notifications@github.com> wrote:

> Hi
>
> I am looking at your Premium addition, just want to make sure, it is 100%
> compile with AppStore and Playstore background requirement before i
> purchase. As i know Apple is a bit touchy on those background requirements.
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/197>
> .
>


-- 
Snet from Gmail Mobile

**Comment by clarklight** [comment]
Thanks for the reply, yes i am making something in the area of the apps you mentioned fleet-tracking, taxi app or jogging app type. 

I will go over that Apple guideline link, thanks!
