### ISSUE TITLE
Android Auto Start At Boot Works Fine But Cant Restart Again After Crash

### ISSUE THREAD

**Issue by richot** [christocracy/cordova-plugin-background-geolocation#200]
Hello Chris, big hands for the great work. 
I do have a little challenge.

I have been able to make the service to automatically start at boot on Android and every thing is fine and it can run for several hours.
But the issue is that in very rare cases, the service crashes and it appears it wants to automatically trying to restart itself but crashes again then makes the second attempt, then it crashes as well. 

Then when I check the list of running services on the device, my app is listed with "...Restarting" as its status and nothing ever happens forever. The case is so for Android 3.s and 4.s

Many many thanks to you.

Here is the regular crash log: 

06-16 12:58:46.007: E/SqliteDatabaseCpp(11303): sqlite3_exec - Failed to set synchronous mode = 1(Normal) 
06-16 12:58:46.046: E/SQLiteDatabase(11303): Failed to open the database. closing it.
06-16 12:58:46.046: E/SQLiteDatabase(11303): android.database.sqlite.SQLiteDatabaseLockedException: database is locked
06-16 12:58:46.046: E/SQLiteDatabase(11303): 	at android.database.sqlite.SQLiteDatabase.dbopen(Native Method)
06-16 12:58:46.046: E/SQLiteDatabase(11303): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1123)
06-16 12:58:46.046: E/SQLiteDatabase(11303): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1074)
06-16 12:58:46.046: E/SQLiteDatabase(11303): 	at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1161)
06-16 12:58:46.046: E/SQLiteDatabase(11303): 	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:826)
06-16 12:58:46.046: E/SQLiteDatabase(11303): 	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:228)
06-16 12:58:46.046: E/SQLiteDatabase(11303): 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:157)
06-16 12:58:46.046: E/SQLiteDatabase(11303): 	at com.tenforwardconsulting.cordova.bgloc.data.sqlite.SQLiteLocationDAO.deleteLocation(SQLiteLocationDAO.java:69)
06-16 12:58:46.046: E/SQLiteDatabase(11303): 	at com.tenforwardconsulting.cordova.bgloc.LocationUpdateService$PostLocationTask.doInBackground(LocationUpdateService.java:937)
06-16 12:58:46.046: E/SQLiteDatabase(11303): 	at com.tenforwardconsulting.cordova.bgloc.LocationUpdateService$PostLocationTask.doInBackground(LocationUpdateService.java:1)
06-16 12:58:46.046: E/SQLiteDatabase(11303): 	at android.os.AsyncTask$2.call(AsyncTask.java:264)
06-16 12:58:46.046: E/SQLiteDatabase(11303): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
06-16 12:58:46.046: E/SQLiteDatabase(11303): 	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
06-16 12:58:46.046: E/SQLiteDatabase(11303): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
06-16 12:58:46.046: E/SQLiteDatabase(11303): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
06-16 12:58:46.046: E/SQLiteDatabase(11303): 	at java.lang.Thread.run(Thread.java:856)
06-16 12:58:46.062: E/AndroidRuntime(11303): FATAL EXCEPTION: AsyncTask #1
06-16 12:58:46.062: E/AndroidRuntime(11303): java.lang.RuntimeException: An error occured while executing doInBackground()
06-16 12:58:46.062: E/AndroidRuntime(11303): 	at android.os.AsyncTask$3.done(AsyncTask.java:278)
06-16 12:58:46.062: E/AndroidRuntime(11303): 	at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
06-16 12:58:46.062: E/AndroidRuntime(11303): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
06-16 12:58:46.062: E/AndroidRuntime(11303): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
06-16 12:58:46.062: E/AndroidRuntime(11303): 	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
06-16 12:58:46.062: E/AndroidRuntime(11303): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
06-16 12:58:46.062: E/AndroidRuntime(11303): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
06-16 12:58:46.062: E/AndroidRuntime(11303): 	at java.lang.Thread.run(Thread.java:856)
06-16 12:58:46.062: E/AndroidRuntime(11303): Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database is locked
06-16 12:58:46.062: E/AndroidRuntime(11303): 	at android.database.sqlite.SQLiteDatabase.dbopen(Native Method)
06-16 12:58:46.062: E/AndroidRuntime(11303): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1123)
06-16 12:58:46.062: E/AndroidRuntime(11303): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1074)
06-16 12:58:46.062: E/AndroidRuntime(11303): 	at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1161)
06-16 12:58:46.062: E/AndroidRuntime(11303): 	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:826)
06-16 12:58:46.062: E/AndroidRuntime(11303): 	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:228)
06-16 12:58:46.062: E/AndroidRuntime(11303): 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:157)
06-16 12:58:46.062: E/AndroidRuntime(11303): 	at com.tenforwardconsulting.cordova.bgloc.data.sqlite.SQLiteLocationDAO.deleteLocation(SQLiteLocationDAO.java:69)
06-16 12:58:46.062: E/AndroidRuntime(11303): 	at com.tenforwardconsulting.cordova.bgloc.LocationUpdateService$PostLocationTask.doInBackground(LocationUpdateService.java:937)
06-16 12:58:46.062: E/AndroidRuntime(11303): 	at com.tenforwardconsulting.cordova.bgloc.LocationUpdateService$PostLocationTask.doInBackground(LocationUpdateService.java:1)
06-16 12:58:46.062: E/AndroidRuntime(11303): 	at android.os.AsyncTask$2.call(AsyncTask.java:264)
06-16 12:58:46.062: E/AndroidRuntime(11303): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
06-16 12:58:46.062: E/AndroidRuntime(11303): 	... 4 more
06-16 12:59:06.296: E/AndroidRuntime(12194): FATAL EXCEPTION: main
06-16 12:59:06.296: E/AndroidRuntime(12194): java.lang.NullPointerException
06-16 12:59:06.296: E/AndroidRuntime(12194): 	at com.tenforwardconsulting.cordova.bgloc.LocationUpdateService.onLocationChanged(LocationUpdateService.java:409)
06-16 12:59:06.296: E/AndroidRuntime(12194): 	at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:234)
06-16 12:59:06.296: E/AndroidRuntime(12194): 	at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:167)
06-16 12:59:06.296: E/AndroidRuntime(12194): 	at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:183)
06-16 12:59:06.296: E/AndroidRuntime(12194): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-16 12:59:06.296: E/AndroidRuntime(12194): 	at android.os.Looper.loop(Looper.java:137)
06-16 12:59:06.296: E/AndroidRuntime(12194): 	at android.app.ActivityThread.main(ActivityThread.java:4514)
06-16 12:59:06.296: E/AndroidRuntime(12194): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-16 12:59:06.296: E/AndroidRuntime(12194): 	at java.lang.reflect.Method.invoke(Method.java:511)
06-16 12:59:06.296: E/AndroidRuntime(12194): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
06-16 12:59:06.296: E/AndroidRuntime(12194): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
06-16 12:59:06.296: E/AndroidRuntime(12194): 	at dalvik.system.NativeStart.main(Native Method)

NOTE: I am actually suspecting this lines in the above log but I have not been able to handle it:

06-16 12:59:06.296: E/AndroidRuntime(12194): FATAL EXCEPTION: main
06-16 12:59:06.296: E/AndroidRuntime(12194): java.lang.NullPointerException
06-16 12:59:06.296: E/AndroidRuntime(12194): 	at com.tenforwardconsulting.cordova.bgloc.LocationUpdateService.onLocationChanged(LocationUpdateService.java:409)

**Comment by christocracy** [comment]
What version of the plugin are you using?  I see references to classes
which don't exist anymore.

On Wednesday, July 1, 2015, richot <notifications@github.com> wrote:

> Hello Chris, big hands for the great work.
> I do have a little challenge.
>
> I have been able to make the service to automatically start at boot on
> Android and every thing is fine and it can run for several hours.
> But the issue is that in very rare cases, the service crashes and it
> appears it wants to automatically trying to restart itself but crashes
> again then makes the second attempt, then it crashes as well.
>
> Then when I check the list of running services on the device, my app is
> listed with "...Restarting" as its status and nothing ever happens forever.
> The case is so for Android 3.s and 4.s
>
> Many many thanks to you.
>
> Here is the regular crash log:
>
> 06-16 12:58:46.007: E/SqliteDatabaseCpp(11303): sqlite3_exec - Failed to
> set synchronous mode = 1(Normal)
> 06-16 12:58:46.046: E/SQLiteDatabase(11303): Failed to open the database.
> closing it.
> 06-16 12:58:46.046: E/SQLiteDatabase(11303):
> android.database.sqlite.SQLiteDatabaseLockedException: database is locked
> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
> android.database.sqlite.SQLiteDatabase.dbopen(Native Method)
> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
> android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1123)
> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
> android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1074)
> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
> android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1161)
> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
> android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:826)
> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
> android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:228)
> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
> android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:157)
> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
> com.tenforwardconsulting.cordova.bgloc.data.sqlite.SQLiteLocationDAO.deleteLocation(SQLiteLocationDAO.java:69)
> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
> com.tenforwardconsulting.cordova.bgloc.LocationUpdateService$PostLocationTask.doInBackground(LocationUpdateService.java:937)
> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
> com.tenforwardconsulting.cordova.bgloc.LocationUpdateService$PostLocationTask.doInBackground(LocationUpdateService.java:1)
> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
> android.os.AsyncTask$2.call(AsyncTask.java:264)
> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
> java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
> java.util.concurrent.FutureTask.run(FutureTask.java:137)
> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
> java.lang.Thread.run(Thread.java:856)
> 06-16 12:58:46.062: E/AndroidRuntime(11303): FATAL EXCEPTION: AsyncTask #1
> <https://github.com/christocracy/cordova-plugin-background-geolocation/pull/1>
> 06-16 12:58:46.062: E/AndroidRuntime(11303): java.lang.RuntimeException:
> An error occured while executing doInBackground()
> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
> android.os.AsyncTask$3.done(AsyncTask.java:278)
> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
> java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
> java.util.concurrent.FutureTask.setException(FutureTask.java:124)
> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
> java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
> java.util.concurrent.FutureTask.run(FutureTask.java:137)
> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
> java.lang.Thread.run(Thread.java:856)
> 06-16 12:58:46.062: E/AndroidRuntime(11303): Caused by:
> android.database.sqlite.SQLiteDatabaseLockedException: database is locked
> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
> android.database.sqlite.SQLiteDatabase.dbopen(Native Method)
> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
> android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1123)
> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
> android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1074)
> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
> android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1161)
> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
> android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:826)
> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
> android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:228)
> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
> android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:157)
> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
> com.tenforwardconsulting.cordova.bgloc.data.sqlite.SQLiteLocationDAO.deleteLocation(SQLiteLocationDAO.java:69)
> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
> com.tenforwardconsulting.cordova.bgloc.LocationUpdateService$PostLocationTask.doInBackground(LocationUpdateService.java:937)
> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
> com.tenforwardconsulting.cordova.bgloc.LocationUpdateService$PostLocationTask.doInBackground(LocationUpdateService.java:1)
> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
> android.os.AsyncTask$2.call(AsyncTask.java:264)
> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
> java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
> 06-16 12:58:46.062: E/AndroidRuntime(11303): ... 4 more
> 06-16 12:59:06.296: E/AndroidRuntime(12194): FATAL EXCEPTION: main
> 06-16 12:59:06.296: E/AndroidRuntime(12194): java.lang.NullPointerException
> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
> com.tenforwardconsulting.cordova.bgloc.LocationUpdateService.onLocationChanged(LocationUpdateService.java:409)
> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
> android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:234)
> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
> android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:167)
> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
> android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:183)
> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
> android.os.Handler.dispatchMessage(Handler.java:99)
> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
> android.os.Looper.loop(Looper.java:137)
> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
> android.app.ActivityThread.main(ActivityThread.java:4514)
> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
> java.lang.reflect.Method.invokeNative(Native Method)
> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
> java.lang.reflect.Method.invoke(Method.java:511)
> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
> com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
> dalvik.system.NativeStart.main(Native Method)
>
> NOTE: I am actually suspecting this lines in the above log but I have not
> been able to handle it:
>
> 06-16 12:59:06.296: E/AndroidRuntime(12194): FATAL EXCEPTION: main
> 06-16 12:59:06.296: E/AndroidRuntime(12194): java.lang.NullPointerException
> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
> com.tenforwardconsulting.cordova.bgloc.LocationUpdateService.onLocationChanged(LocationUpdateService.java:409)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/200>
> .
>


-- 
Snet from Gmail Mobile

**Comment by christocracy** [comment]
Oh, sorry.  Cancel that.  This is the free version

On Wednesday, July 1, 2015, Chris Scott <christocracy@gmail.com> wrote:

> What version of the plugin are you using?  I see references to classes
> which don't exist anymore.
>
> On Wednesday, July 1, 2015, richot <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Hello Chris, big hands for the great work.
>> I do have a little challenge.
>>
>> I have been able to make the service to automatically start at boot on
>> Android and every thing is fine and it can run for several hours.
>> But the issue is that in very rare cases, the service crashes and it
>> appears it wants to automatically trying to restart itself but crashes
>> again then makes the second attempt, then it crashes as well.
>>
>> Then when I check the list of running services on the device, my app is
>> listed with "...Restarting" as its status and nothing ever happens forever.
>> The case is so for Android 3.s and 4.s
>>
>> Many many thanks to you.
>>
>> Here is the regular crash log:
>>
>> 06-16 12:58:46.007: E/SqliteDatabaseCpp(11303): sqlite3_exec - Failed to
>> set synchronous mode = 1(Normal)
>> 06-16 12:58:46.046: E/SQLiteDatabase(11303): Failed to open the database.
>> closing it.
>> 06-16 12:58:46.046: E/SQLiteDatabase(11303):
>> android.database.sqlite.SQLiteDatabaseLockedException: database is locked
>> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
>> android.database.sqlite.SQLiteDatabase.dbopen(Native Method)
>> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
>> android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1123)
>> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
>> android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1074)
>> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
>> android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1161)
>> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
>> android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:826)
>> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
>> android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:228)
>> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
>> android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:157)
>> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
>> com.tenforwardconsulting.cordova.bgloc.data.sqlite.SQLiteLocationDAO.deleteLocation(SQLiteLocationDAO.java:69)
>> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
>> com.tenforwardconsulting.cordova.bgloc.LocationUpdateService$PostLocationTask.doInBackground(LocationUpdateService.java:937)
>> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
>> com.tenforwardconsulting.cordova.bgloc.LocationUpdateService$PostLocationTask.doInBackground(LocationUpdateService.java:1)
>> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
>> android.os.AsyncTask$2.call(AsyncTask.java:264)
>> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
>> java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
>> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
>> java.util.concurrent.FutureTask.run(FutureTask.java:137)
>> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
>> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
>> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
>> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
>> 06-16 12:58:46.046: E/SQLiteDatabase(11303): at
>> java.lang.Thread.run(Thread.java:856)
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): FATAL EXCEPTION: AsyncTask
>> #1
>> <https://github.com/christocracy/cordova-plugin-background-geolocation/pull/1>
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): java.lang.RuntimeException:
>> An error occured while executing doInBackground()
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
>> android.os.AsyncTask$3.done(AsyncTask.java:278)
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
>> java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
>> java.util.concurrent.FutureTask.setException(FutureTask.java:124)
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
>> java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
>> java.util.concurrent.FutureTask.run(FutureTask.java:137)
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
>> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
>> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
>> java.lang.Thread.run(Thread.java:856)
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): Caused by:
>> android.database.sqlite.SQLiteDatabaseLockedException: database is locked
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
>> android.database.sqlite.SQLiteDatabase.dbopen(Native Method)
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
>> android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1123)
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
>> android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1074)
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
>> android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1161)
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
>> android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:826)
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
>> android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:228)
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
>> android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:157)
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
>> com.tenforwardconsulting.cordova.bgloc.data.sqlite.SQLiteLocationDAO.deleteLocation(SQLiteLocationDAO.java:69)
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
>> com.tenforwardconsulting.cordova.bgloc.LocationUpdateService$PostLocationTask.doInBackground(LocationUpdateService.java:937)
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
>> com.tenforwardconsulting.cordova.bgloc.LocationUpdateService$PostLocationTask.doInBackground(LocationUpdateService.java:1)
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
>> android.os.AsyncTask$2.call(AsyncTask.java:264)
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): at
>> java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
>> 06-16 12:58:46.062: E/AndroidRuntime(11303): ... 4 more
>> 06-16 12:59:06.296: E/AndroidRuntime(12194): FATAL EXCEPTION: main
>> 06-16 12:59:06.296: E/AndroidRuntime(12194):
>> java.lang.NullPointerException
>> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
>> com.tenforwardconsulting.cordova.bgloc.LocationUpdateService.onLocationChanged(LocationUpdateService.java:409)
>> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
>> android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:234)
>> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
>> android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:167)
>> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
>> android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:183)
>> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
>> android.os.Handler.dispatchMessage(Handler.java:99)
>> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
>> android.os.Looper.loop(Looper.java:137)
>> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
>> android.app.ActivityThread.main(ActivityThread.java:4514)
>> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
>> java.lang.reflect.Method.invokeNative(Native Method)
>> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
>> java.lang.reflect.Method.invoke(Method.java:511)
>> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
>> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
>> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
>> com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
>> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
>> dalvik.system.NativeStart.main(Native Method)
>>
>> NOTE: I am actually suspecting this lines in the above log but I have not
>> been able to handle it:
>>
>> 06-16 12:59:06.296: E/AndroidRuntime(12194): FATAL EXCEPTION: main
>> 06-16 12:59:06.296: E/AndroidRuntime(12194):
>> java.lang.NullPointerException
>> 06-16 12:59:06.296: E/AndroidRuntime(12194): at
>> com.tenforwardconsulting.cordova.bgloc.LocationUpdateService.onLocationChanged(LocationUpdateService.java:409)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/200>
>> .
>>
>
>
> --
> Snet from Gmail Mobile
>


-- 
Snet from Gmail Mobile

**Comment by richot** [comment]
Thanks for the super timely response Chris. Yes it's the free version.

**Comment by richot** [comment]
Hello Chris. Please an hope on this problem. THANKS

**Comment by richot** [comment]
Hi Chris. Can you please help regarding this issue.
Regards.

**Comment by christocracy** [comment]
This version of the plugin has ben deprecated a long time.  Please see the new improved version [here](https://github.com/transistorsoft/cordova-background-geolocation-lt)
