### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by lamuertepeluda** [christocracy/cordova-plugin-background-geolocation#201]
Hi there,

any plan to support windows (not wp8, the universal app for 8.1 and 10, platform name 'windows') with its nice JavaScript system API?

Benefit you get:
the app can be installed on both Windows Store and Windows Phone Store.

Cheers

**Comment by christocracy** [comment]
Is Windows Phone Dead?
https://www.thurrott.com/mobile/windows-phone/4512/analysis-microsoft-is-scaling-back-on-windows-phone-dramatically


On Wednesday, July 1, 2015, Vito Macchia <notifications@github.com> wrote:

> Hi there,
>
> any plan to support windows (not wp8, the universal app for 8.1 and 10)
> with its nice JavaScript system API?
>
> Benefit you get:
> the app can be installed on both Windows Store and Windows Phone Store.
>
> Cheers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/201>
> .
>


-- 
Snet from Gmail Mobile

**Comment by lamuertepeluda** [comment]
ok yeah I agree... Windows Phone s..., I mean it isn't the most popular platform and sure it isn't the best. But think about windows tablet. The js api is just the same.

**Comment by christocracy** [comment]
If it doesn't have a GPS, my plugin isn't interested

On Saturday, July 11, 2015, Vito Macchia <notifications@github.com> wrote:

> ok yeah I agree... Windows Phone s..., I mean it isn't the most popular
> platform and sure it isn't the best. But think about windows tablet. The js
> api is just the same.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/201#issuecomment-120617690>
> .
>


-- 
Snet from Gmail Mobile

**Comment by lamuertepeluda** [comment]
yes they have. not all models probably, but most of the tablets have

http://apps.microsoft.com/windows/en-us/app/maps-pro/afe19081-5161-4399-8850-06c9a858a072
