### ISSUE TITLE
Ionic + ngCordova + background geolocation + DeviceReady issue

### ISSUE THREAD

**Issue by sahiltalwar88** [christocracy/cordova-plugin-background-geolocation#202]
Hey Chris, 

Please see my question here - http://stackoverflow.com/questions/31195046/ionic-ngcordova-background-geolocation-deviceready-issue. I'm really not sure why this is happening, and despite having worked on it for three days, can't seem to figure it out. 

Thanks!

**Comment by christocracy** [comment]
I'm not sure if it's related, but I've experienced something really wonky myself (albeit in the Premium Version).

For some reason, I found `window.plugins.backgroundGeoLocation` didn't exist _sometimes_

defined [Here](https://github.com/christocracy/cordova-plugin-background-geolocation/blob/master/plugin.xml#L20)

When I changed that to 
`<clobbers target="window.backgroundGeoLocation" />`

My problem went away.

**Comment by sahiltalwar88** [comment]
Interesting. I'll give that a shot, stay tuned...

**Comment by sahiltalwar88** [comment]
Nah, it didn't fix the issue...I hate to ask, but would you mind pulling down my public repo and seeing if you can repro the issue? (it's a blank screen; when you click the hamburger button it should take you to a page with a map. Then it should start tracking your location.) 

It worked perfectly the first time I installed it on my phone, but the second time, it never got to the map page - instead, it just didn't do anything. It's the same way on my production application, pressing the button for the page that uses deviceready doesn't do anything :(

Is there any alternative to using $ionicPlatform.ready or deviceready?

**Comment by christocracy** [comment]
Have you tried installing my plugin directly from teh repo rather than
through this Ionic wrapper?

$ cordova plugin add
https://github.com/christocracy/cordova-plugin-background-geolocation

This Ionic wrapper is not required.

On Thu, Jul 2, 2015 at 5:55 PM, Sahil Talwar <notifications@github.com>
wrote:

> Nah, it didn't fix the issue...I hate to ask, but would you mind pulling
> down my public repo and seeing if you can repro the issue? (it's a blank
> screen; when you click the hamburger button it should take you to a page
> with a map. Then it should start tracking your location.)
>
> It worked perfectly the first time I installed it on my phone, but the
> second time, it never got to the map page - instead, it just didn't do
> anything. It's the same way on my production application, pressing the
> button for the page that uses deviceready doesn't do anything :(
>
> Is there any alternative to using $ionicPlatform.ready or deviceready?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/202#issuecomment-118178872>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by sahiltalwar88** [comment]
Unfortunately, the app that I'm building is a full on ionic app - the sample app is just something I built to demonstrate the issues I'm having with the production app. That being said, I'm not sure if you mean something specific when you say "this Ionic wrapper" (other than the obvious, Ionic itself). I CAN say, though, that I installed your plugin exactly the way you suggested. 

Is there something else that I can do, or somewhere that I'm using Ionic that I don't need to?
My apologies for the lack of understanding.

**Comment by sahiltalwar88** [comment]
It occurs to me that the initialization code in my app.js may be relevant - am I configuring it wrong here, perhaps?
```javascript
.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
    // for form inputs)
    if(window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
    }
    if(window.StatusBar) {
      StatusBar.styleDefault();
    }

    if (window.cordova) {
      if (window.plugins && window.plugins.backgroundGeoLocation) {
        BackgroundGeolocation.configurePlugin(window.plugins.backgroundGeoLocation);
      }
    }
  });
})
```

**Comment by christocracy** [comment]
I don't understand...are you using the [Premium Version](http://christocracy.github.io/cordova-background-geolocation/)?

You're clearly quoting code there from my [Premium Version Sample App](https://github.com/christocracy/cordova-background-geolocation-SampleApp/blob/master/www/js/app.js#L127)

**Comment by sahiltalwar88** [comment]
You're absolutely right, that's from the sample app! I could not figure out what I was doing wrong, so I went hunting for more examples of correct usage, and put together what I could. 

However, I'm not using the premium version yet; this app is intended to be a prototype for a VC demo. Tech decisions are all being deferred until the startup receives funding :)

So, I take it from your comment that either I don't need the code or it's wrong - should I remove or alter it?

**Comment by christocracy** [comment]
You cannot use code from the premium SampleApp.

The free version hosts its own SampleApp.  See README for details.

Boot this SampleApp on your device.

On Friday, July 3, 2015, Sahil Talwar <notifications@github.com> wrote:

> You're absolutely right, that's from the sample app! I could not figure
> out what I was doing wrong, so I went hunting for more examples of correct
> usage, and put together what I could.
>
> However, I'm not using the premium version yet; this app is intended to be
> a prototype for a VC demo. Tech decisions are all being deferred until the
> startup receives funding :)
>
> So, I take it from your comment that either I don't need the code or it's
> wrong - should I remove or alter it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/202#issuecomment-118258429>
> .
>


-- 
Snet from Gmail Mobile

**Comment by sahiltalwar88** [comment]
Hey Chris, 

I understand that I can't use code from the premium app. However, the sample in your free app uses jQuery, not Ionic. Since my problem is specifically with the "deviceready" listener _on a device_, I can't see anything in the the sample app that's helpful to me - I'm sorry if I'm being thick or misunderstanding something. 

Could you please help me understand what I need to change in order to get this very simple demo app working? Thanks again for your time.

**Comment by christocracy** [comment]
Precisely.  I want you to boot the SampleApp completely isolated from your
application-code so we can confirm that everything works without Ionic
involved.

On Mon, Jul 6, 2015 at 11:23 AM, Sahil Talwar <notifications@github.com>
wrote:

> Hey Chris,
>
> I understand that I can't use code from the premium app. However, the
> sample in your free app uses jQuery, not Ionic. Since my problem is
> specifically with the "deviceready" listener *on a device*, I can't see
> anything in the the sample app that's helpful to me - I'm sorry if I'm
> being thick or misunderstanding something.
>
> Could you please help me understand what I need to change in order to get
> this very simple demo app working? Thanks again for your time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/202#issuecomment-118889734>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by sahiltalwar88** [comment]
Gotcha. Just to ensure that I understand - you're saying you'd like me to use PhoneGap to install the Sample App? Is that right?

**Comment by christocracy** [comment]
I’m not concerned how you install the SampleApp on your device.  I have
nothing to do with PhoneGap.

Personally, I’m on a mac, I have Xcode installed:

$ cordova build ios
$ cordova run ios —device


On Mon, Jul 6, 2015 at 12:01 PM, Sahil Talwar <notifications@github.com>
wrote:

> Gotcha. Just to ensure that I understand - you're saying you'd like me to
> use PhoneGap to install the Sample App? Is that right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/202#issuecomment-118909671>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by sahiltalwar88** [comment]
Got it. I installed it on two separate phones - a Droid Turbo and a Galaxy S2 - and walked around my office for a couple of minutes with both, on normal and aggressive mode. Neither did anything. 

At this point, it seems like perhaps there's something wrong with my installation of cordova - any ideas for what the issue may be?

**Comment by christocracy** [comment]
- what Android OS?
- devices require accelerometer, GPS and gyroscope.
- I built this plugin using a Nexus 4 (2012).

Enable developer mode on your androids, enable `usb debugging`.  with phone plugged into usb:

```
$ adb logcat -s TSLocationManager
W/TSLocationManager(19141): Activity detected:still, confidence:100
I/TSLocationManager(19141): - Activity received: still, confidence: 100
W/TSLocationManager(19141): Activity detected:still, confidence:100
I/TSLocationManager(19141): - Activity received: still, confidence: 100
W/TSLocationManager(19141): Activity detected:still, confidence:100
I/TSLocationManager(19141): - Activity received: still, confidence: 100
W/TSLocationManager(19141): Activity detected:still, confidence:100
I/TSLocationManager(19141): - Activity received: still, confidence: 100
W/TSLocationManager(19141): Activity detected:still, confidence:100
I/TSLocationManager(19141): - Activity received: still, confidence: 100
W/TSLocationManager(19141): Activity detected:still, confidence:100
I/TSLocationManager(19141): - Activity received: still, confidence: 100
W/TSLocationManager(19141): Activity detected:still, confidence:100
I/TSLocationManager(19141): - Activity received: still, confidence: 100
W/TSLocationManager(19141): Activity detected:still, confidence:100
I/TSLocationManager(19141): - Activity received: still, confidence: 100
W/TSLocationManager(19141): Activity detected:still, confidence:100
I/TSLocationManager(19141): - Activity received: still, confidence: 100
W/TSLocationManager(19141): Activity detected:still, confidence:100
I/TSLocationManager(19141): - Activity received: still, confidence: 100
```

You should see a stream of `Activity received` messages.  If you shake the phone vigorously (for a period of at least `activityRecognitionInterval` seconds) you should see:

```
W/TSLocationManager(23088): Activity detected:on_foot, confidence:100
I/TSLocationManager(23088): - Activity received: on_foot, confidence: 100
I/TSLocationManager(23088): - setPace: true
I/TSLocationManager(23088): Location received: Location[fused 45.519262,-73.616923 acc=30 et=+11d0h36m25s717ms]
I/TSLocationManager(23088): BUS Rx:Location[fused 45.519262,-73.616923 acc=30 et=+11d0h36m25s717ms]
D/TSLocationManager(23088): - INSERT, id: 706, timestamp: 2015-07-06T17:45:53Z

```

**Comment by christocracy** [comment]
Oh, cancel that.  That's the Premium Version.  I always get confused between Free & Premium questions :)

**Comment by christocracy** [comment]
Go for a long walk with Free version.  Go walk about 200 meters away.

**Comment by sahiltalwar88** [comment]
Haha no problem, I understand. Will try that. 
As for android OS + perms: Tried on Lollipop and Jellybean (don't have a KitKat device); will try giving explicit perms as well.

**Comment by christocracy** [comment]
You’ll save yourself a lot of pain if you use the Premium version.  It’s
completely different Android code and is at least 10 times more efficient
on the battery life.

On Mon, Jul 6, 2015 at 1:52 PM, Sahil Talwar <notifications@github.com>
wrote:

> Haha no problem, I understand. Will try that.
> As for android OS + perms: Tried on Lollipop and Jellybean (don't have a
> KitKat device); will try giving explicit perms as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/202#issuecomment-118938207>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by sahiltalwar88** [comment]
I added the following to the Android Manifest:
```xml
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-feature android:name="android.hardware.location.gps" android:required="true" />
    <uses-feature android:name="android.hardware.sensor.compass" android:required="true" />
    <uses-feature android:name="android.hardware.sensor.gyroscope" android:required="true" />
    <uses-feature android:name="android.hardware.sensor.accelerometer" android:required="true" />

Now, I saw that it was using the location services on the phone, but saw no change on the UI itself, which I think it means that it's still not working. I'm assuming that it's supposed to show lat/long or something on the list, right?

**Comment by sahiltalwar88** [comment]
I'd love to use the premium version, but as this is for a prototype and we haven't been authorized to expense the additional cost, I can't yet :(

If you provide temporary dev licenses (good for ~2 weeks or so), then I'd love to go that route.

**Comment by christocracy** [comment]
You shouldn’t need to add those permissions.  The plugin adds those
automatically.

https://github.com/christocracy/cordova-plugin-background-geolocation/blob/master/plugin.xml#L39

The SampleApp does not render a “list”.  it only adds locations and a blue
polyline to the map.

On Mon, Jul 6, 2015 at 2:33 PM, Sahil Talwar <notifications@github.com>
wrote:

> I added the following to the Android Manifest:
>
>     <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
>     <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
>     <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
>     <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
>     <uses-feature android:name="android.hardware.location.gps" android:required="true" />
>     <uses-feature android:name="android.hardware.sensor.compass" android:required="true" />
>     <uses-feature android:name="android.hardware.sensor.gyroscope" android:required="true" />
>     <uses-feature android:name="android.hardware.sensor.accelerometer" android:required="true" />
>
> Now, I saw that it was using the location services on the phone, but saw no change on the UI itself, which I think it means that it's still not working. I'm assuming that it's supposed to show lat/long or something on the list, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/202#issuecomment-118951056>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by sahiltalwar88** [comment]
Got it. Yeah, in that case, the map and locations / line don't show up at all - I've tried it on 3 phones now (2 running Lollipop, one running Jellybean). Please see attached image for what it looks like on the two phones running Lollipop - on the Jellybean phone, the lines that make it appear to be a list don't show up; other than that, it's identical. 

Is it possible that you were using an older version of android, and that the free version no longer works?

![screenshot_2015-07-06-12-36-36](https://cloud.githubusercontent.com/assets/2473487/8530319/4f09afcc-23ee-11e5-8a5b-182a80bd75cb.png)

**Comment by christocracy** [comment]
Are you connected to Internet?

On Monday, July 6, 2015, Sahil Talwar <notifications@github.com> wrote:

> Got it. Yeah, in that case, the map and locations / line don't show up at
> all - I've tried it on 3 phones now (2 running Lollipop, one running
> Jellybean). Please see attached image for what it looks like on the two
> phones running Lollipop - on the Jellybean phone, the lines that make it
> appear to be a list don't show up; other than that, it's identical.
>
> Is it possible that you were using an older version of android, and that
> the free version no longer works?
>
> [image: screenshot_2015-07-06-12-36-36]
> <https://cloud.githubusercontent.com/assets/2473487/8530319/4f09afcc-23ee-11e5-8a5b-182a80bd75cb.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/202#issuecomment-118956405>
> .
>


-- 
Snet from Gmail Mobile

**Comment by sahiltalwar88** [comment]
Yep, I tried both while indoors with WiFi and outdoors with normal 4G LTE data.

**Comment by christocracy** [comment]
Are you monitoring the JavaScript console because clearly there are
errors.  The google map failed to render.

Could be whitelist issues

On Monday, July 6, 2015, Sahil Talwar <notifications@github.com> wrote:

> Yep, I tried both while indoors with WiFi and outdoors with normal 4G LTE
> data.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/202#issuecomment-118958558>
> .
>


-- 
Snet from Gmail Mobile

**Comment by sahiltalwar88** [comment]
Unfortunately, I've never been able to get livereload working on the device via ionic, and I don't know how to get the logs without that. Could you show me how to get them?

**Comment by christocracy** [comment]
I cannot show you, sorry.  When you come here to ask questions, it's
assumed that you're able to debug on your own.

On Monday, July 6, 2015, Sahil Talwar <notifications@github.com> wrote:

> Unfortunately, I've never been able to get livereload working on the
> device via ionic, and I don't know how to get the logs without that. Could
> you show me how to get them?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/202#issuecomment-118967218>
> .
>


-- 
Snet from Gmail Mobile

**Comment by christocracy** [comment]
Being able to monitor the ha console of your Cordova app is crucial.  If
you cannot do that, stop what you're doing and don't return until you can
do so.

You're basically debugging like a blind person.

On Monday, July 6, 2015, Sahil Talwar <notifications@github.com> wrote:

> Unfortunately, I've never been able to get livereload working on the
> device via ionic, and I don't know how to get the logs without that. Could
> you show me how to get them?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/202#issuecomment-118967218>
> .
>


-- 
Snet from Gmail Mobile

**Comment by sahiltalwar88** [comment]
Okay, I'll go figure that out and come back shortly.

**Comment by christocracy** [comment]
And use this
https://chrome.google.com/webstore/detail/adb/dpngiggdglpdnjdoaefidgiigpemgage

On Monday, July 6, 2015, Sahil Talwar <notifications@github.com> wrote:

> Okay, I'll go figure that out and come back shortly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/202#issuecomment-118969053>
> .
>


-- 
Snet from Gmail Mobile

**Comment by sahiltalwar88** [comment]
Figured it out - actually just used a window.onerror() and found that plugins was null. Dug some more and found that apparently, cordova does not install missing plugins on build, and my colleague had added the plugins folder (reasonably assuming that they would be automatically downloaded). I unignored it, installed the plugins, and we're good :) 
Thank you for all your help!

**Comment by christocracy** [comment]
"alert debugging??".  You guys waste so much time debugging like blind people.

**Safari Develop Console**
[ios web inspector](https://www.dropbox.com/s/uo9c9t9i6gav1hh/Screenshot%202015-07-07%2014.27.38.png?dl=1)

**Android Developer Console**
[Android adb console](https://www.dropbox.com/s/xbfspy9ne8a9bp1/Screenshot%202015-07-07%2014.31.02.png?dl=1)

**Comment by sahiltalwar88** [comment]
Haha I realized that there must be an exception being thrown. As soon as I did that, we started down the right path :) Although if they do end up getting funded, I will absolutely use those - they look MUCH better, thank you for the tip!

**Comment by sahiltalwar88** [comment]
ADB is really helpful, thank you! Two additional questions: 

1. In the sample app, I found that the link to google maps doesn't resolve by using ADB; that's why I'm having the rendering problem. Here's the error: 
![bg sample app error](https://cloud.githubusercontent.com/assets/2473487/8659280/abbdea2e-2977-11e5-92d1-06548d498a07.png)

2. I have the following code, and if I call configure _without_ the callback and error functions, it works fine in Android. If I call it _with_ the callback and error functions, it doesn't work on Android or iOS, and throws no errors. Do you know what's going on? 

.run(function ($ionicPlatform, $location, $rootScope, $cordovaGeolocation, $cordovaBackgroundGeolocation, $cordovaDevice, $http) {
    alert('stop so I can inspect!');
  $ionicPlatform.ready(function() {
    if(window.StatusBar) {
      StatusBar.styleDefault();
    }
    
    $location.path('/app');
    $rootScope.$digest();

    $rootScope.deviceReady = false; 
    
    document.addEventListener('deviceready', function () {
        if(window.cordova && window.cordova.plugins && window.cordova.plugins.Keyboard) {
          window.cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
        }

        var bgGeo = $cordovaBackgroundGeolocation;
        var deviceId = $cordovaDevice.getUUID();
        var addVisitUrl = 'url-goes-here';
        
        $rootScope.deviceId = deviceId;
        $rootScope.deviceReady = true;

        var posOptions = { timeout: 5000, enableHighAccuracy: true, maximumAge: 5000 };
        $cordovaGeolocation.getCurrentPosition(posOptions)
            .then(function (location) {
                $rootScope.currentLat = location.coords.latitude;
                $rootScope.currentLong = location.coords.longitude;
        
                var yourAjaxCallback = function(response) {
                    bgGeo.finish();
                };
                
                var callbackFn = function(location) {
                    var data = {
                                    deviceId: deviceId,
                                    "location": {
                                        "latitude": location.latitude,
                                        "longitude": location.longitude
                                    }
                                };
                    $http.post(addVisitUrl, data);
                    yourAjaxCallback.call(this);
                };
                
                var failureFn = function(error) {
                    alert('Background Geolocation Error: ' + error);
                };
                
                bgGeo.configure(callbackFn, failureFn, {
                    url: addVisitUrl,
                    params: {
                        deviceId: deviceId,
                        "location": {
                            "latitude": $rootScope.currentLat,
                            "longitude": $rootScope.currentLong
                        }
                    },
                    desiredAccuracy: 10,
                    stationaryRadius: 10,
                    distanceFilter: 10,
                    activityType: 'OtherNavigation',
                    debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
                    stopOnTerminate: false // <-- enable this to clear background location settings when the app terminates
                });

                bgGeo.start(); // Sahil: Do we need this?? Configure calls start internally.
            });
        $rootScope.$digest();
    });
  });
})

PS. I'm happy to make a new issue if you prefer.

**Comment by rishantagarwal** [comment]
![image](https://cloud.githubusercontent.com/assets/2218422/12086667/9e139924-b30f-11e5-9aa6-c7346a7baff3.png)

Getting this error . I am unable to figure out what is causing the issue. 

here is my code 

```
angular.module('starter', ['ionic','ionic.service.core', 'starter.controllers', 'starter.services','ngCordova'])

.run(function ($ionicPlatform,  $rootScope, $cordovaGeolocation, $cordovaBackgroundGeolocation, $cordovaDevice, $http) {
    alert('stop so I can inspect!');
  $ionicPlatform.ready(function() {
    if(window.StatusBar) {
      StatusBar.styleDefault();
    }

   // $location.path('/app');
   /* $rootScope.$digest();

    $rootScope.deviceReady = false; */

  /*  document.addEventListener('deviceready', function () {
        if(window.cordova && window.cordova.plugins && window.cordova.plugins.Keyboard) {
          window.cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
        }
          
          */
         var bgGeo = window.backgroundGeoLocation;
         console.log(bgGeo);
    /**
    * This callback will be executed every time a geolocation is recorded in the background.
    */
    var callbackFn = function(location, taskId) {
        var coords = location.coords;
        var lat    = coords.latitude;
        var lng    = coords.longitude;

        // Simulate doing some extra work with a bogus setTimeout.  This could perhaps be an Ajax request to your server.
        // The point here is that you must execute bgGeo.finish after all asynchronous operations within the callback are complete.
        setTimeout(function() {
          bgGeo.finish(taskId); // <-- execute #finish when your work in callbackFn is complete
        }, 1000);
    };

    var failureFn = function(error) {
        console.log('BackgroundGeoLocation error');
    }

    // BackgroundGeoLocation is highly configurable.
    bgGeo.configure(callbackFn, failureFn, {
        // Geolocation config
        desiredAccuracy: 0,
        stationaryRadius: 50,
        distanceFilter: 50,
        disableElasticity: false, // <-- [iOS] Default is 'false'.  Set true to disable speed-based distanceFilter elasticity
        locationUpdateInterval: 5000,
        minimumActivityRecognitionConfidence: 80,   // 0-100%.  Minimum activity-confidence for a state-change 
        fastestLocationUpdateInterval: 5000,
        activityRecognitionInterval: 10000,
        stopDetectionDelay: 1,  // Wait x minutes to engage stop-detection system
        stopTimeout: 2,  // Wait x miutes to turn off location system after stop-detection
        activityType: 'AutomotiveNavigation',

        // Application config
        debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
        forceReloadOnLocationChange: false,  // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a new location is recorded (WARNING: possibly distruptive to user) 
        forceReloadOnMotionChange: false,    // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when device changes stationary-state (stationary->moving or vice-versa) --WARNING: possibly distruptive to user) 
        forceReloadOnGeofence: false,        // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a geofence crossing occurs --WARNING: possibly distruptive to user) 
        stopOnTerminate: false,              // <-- [Android] Allow the background-service to run headless when user closes the app.
        startOnBoot: true,                   // <-- [Android] Auto start background-service in headless mode when device is powered-up.

        // HTTP / SQLite config
        url: 'http://posttestserver.com/post.php?dir=cordova-background-geolocation',
        method: 'POST',
        batchSync: true,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
        autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
        maxDaysToPersist: 1,    // <-- Maximum days to persist a location in plugin's SQLite database when HTTP fails
        headers: {
            "X-FOO": "bar"
        },
        params: {
            "auth_token": "maybe_your_server_authenticates_via_token_YES?"
        }
    });

    // Turn ON the background-geolocation system.  The user will be tracked whenever they suspend the app.
    bgGeo.start();

    // If you wish to turn OFF background-tracking, call the #stop method.
    // bgGeo.stop()  
   
  });
})
```

**Comment by rishantagarwal** [comment]
![image](https://cloud.githubusercontent.com/assets/2218422/12087078/5944c35a-b313-11e5-9dd6-b44b8f106c95.png)

Getting above error , but unable to solve this.
Pasting my code and plugin.xml file along with it.

```
angular.module('starter', ['ionic','ionic.service.core', 'starter.controllers', 'starter.services','ngCordova'])

.run(function ($ionicPlatform,  $rootScope, $cordovaGeolocation, $cordovaBackgroundGeolocation, $cordovaDevice, $http) {
    alert('stop so I can inspect!');
  $ionicPlatform.ready(function() {
    if(window.StatusBar) {
      StatusBar.styleDefault();
    }

   // $location.path('/app');
   /* $rootScope.$digest();

    $rootScope.deviceReady = false; */

  /*  document.addEventListener('deviceready', function () {
        if(window.cordova && window.cordova.plugins && window.cordova.plugins.Keyboard) {
          window.cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
        }
          
          */
         var bgGeo = window.backgroundGeoLocation;
         console.log(bgGeo);
    /**
    * This callback will be executed every time a geolocation is recorded in the background.
    */
    var callbackFn = function(location, taskId) {
        var coords = location.coords;
        var lat    = coords.latitude;
        var lng    = coords.longitude;

        // Simulate doing some extra work with a bogus setTimeout.  This could perhaps be an Ajax request to your server.
        // The point here is that you must execute bgGeo.finish after all asynchronous operations within the callback are complete.
        setTimeout(function() {
          bgGeo.finish(taskId); // <-- execute #finish when your work in callbackFn is complete
        }, 1000);
    };

    var failureFn = function(error) {
        console.log('BackgroundGeoLocation error');
    }

    // BackgroundGeoLocation is highly configurable.
    bgGeo.configure(callbackFn, failureFn, {
        // Geolocation config
        desiredAccuracy: 0,
        stationaryRadius: 50,
        distanceFilter: 50,
        disableElasticity: false, // <-- [iOS] Default is 'false'.  Set true to disable speed-based distanceFilter elasticity
        locationUpdateInterval: 5000,
        minimumActivityRecognitionConfidence: 80,   // 0-100%.  Minimum activity-confidence for a state-change 
        fastestLocationUpdateInterval: 5000,
        activityRecognitionInterval: 10000,
        stopDetectionDelay: 1,  // Wait x minutes to engage stop-detection system
        stopTimeout: 2,  // Wait x miutes to turn off location system after stop-detection
        activityType: 'AutomotiveNavigation',

        // Application config
        debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
        forceReloadOnLocationChange: false,  // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a new location is recorded (WARNING: possibly distruptive to user) 
        forceReloadOnMotionChange: false,    // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when device changes stationary-state (stationary->moving or vice-versa) --WARNING: possibly distruptive to user) 
        forceReloadOnGeofence: false,        // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a geofence crossing occurs --WARNING: possibly distruptive to user) 
        stopOnTerminate: false,              // <-- [Android] Allow the background-service to run headless when user closes the app.
        startOnBoot: true,                   // <-- [Android] Auto start background-service in headless mode when device is powered-up.

        // HTTP / SQLite config
        url: 'http://posttestserver.com/post.php?dir=cordova-background-geolocation',
        method: 'POST',
        batchSync: true,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
        autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
        maxDaysToPersist: 1,    // <-- Maximum days to persist a location in plugin's SQLite database when HTTP fails
        headers: {
            "X-FOO": "bar"
        },
        params: {
            "auth_token": "maybe_your_server_authenticates_via_token_YES?"
        }
    });

    // Turn ON the background-geolocation system.  The user will be tracked whenever they suspend the app.
    bgGeo.start();
});
})

```

Plugin.xml file 

```
<?xml version="1.0" encoding="UTF-8"?>

<plugin xmlns="http://www.phonegap.com/ns/plugins/1.0"
    xmlns:android="http://schemas.android.com/apk/res/android"
    id="com.transistorsoft.cordova.background-geolocation"
    version="1.2.0">
    <name>BackgroundGeolocation</name>
    <description>Sophisticated, battery-efficient background-geolocation plugin for Cordova</description>
    <license>MIT</license>
    <keywords>cordova, phonegap, background geolocation</keywords>

    <engines>
        <engine name="cordova" version=">=3.0.0" />
    </engines>

    <!-- 
        Pre-Cordova 5, non-npm plugin reference.  Uncomment this if you're not using Cordova 5.
    <dependency id="org.apache.cordova.dialogs" />
    -->

    <!-- Cordova 5 npm-style plugin referernce.  Comment this out if you're not using Cordova 5 -->
    <dependency id="cordova-plugin-dialogs" />

    <js-module src="www/BackgroundGeolocation.js" name="backgroundGeoLocation">
        <clobbers target="window.backgroundGeoLocation" />
    </js-module>

    <!-- android available in Premium Version: http://transistorsoft.github.io/cordova-background-geolocation -->
    
     <platform name="ios">
        <!-- required background modes:  App registers for location updates -->
        
        <config-file target="*-Info.plist" parent="NSLocationAlwaysUsageDescription">
            <string>TSLocationManager requires background location tracking</string>
        </config-file>

        <config-file target="*-Info.plist" parent="UIBackgroundModes">
            <array>
                <string>location</string>
            </array>
        </config-file>

        <config-file target="config.xml" parent="/*">
            <feature name="backgroundGeolocation">
                <param name="ios-package" value="CDVBackgroundGeoLocation"/>
            </feature>
        </config-file>
        <framework src="SystemConfiguration.framework" weak="true" />
        <framework src="AudioToolbox.framework" weak="true" />
        <framework src="AVFoundation.framework" weak="true" />
        <framework src="libsqlite3.dylib" weak="true" />
        <framework src="src/ios/TSLocationManager.framework" custom="true" />
        <source-file src="src/ios/CDVBackgroundGeolocation.m" />
        <header-file src="src/ios/CDVBackgroundGeolocation.h" />
     </platform>          

</plugin>
```

**Comment by christocracy** [comment]
The plugin has moved here
https://github.com/transistorsoft/cordova-background-geolocation-lt

This version is no longer supported

**Comment by rishantagarwal** [comment]
Maybe I posted it in wrong thread but the issue is there. Please can you tell me how to fix it ?

**Comment by christocracy** [comment]
Please install the correct version and comment on the repo here
https://github.com/transistorsoft/cordova-background-geolocation-lt


On Mon, Jan 4, 2016 at 6:54 AM, Rishant Agarwal <notifications@github.com>
wrote:

> Maybe I posted it in wrong thread but the issue is there. Please can you
> tell me how to fix it ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/202#issuecomment-168656833>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
And start by installing the free iOS SampleApp
<https://github.com/transistorsoft/cordova-background-geolocation-SampleApp>

On Mon, Jan 4, 2016 at 1:54 PM, Chris Scott <christocracy@gmail.com> wrote:

> Please install the correct version and comment on the repo here
> https://github.com/transistorsoft/cordova-background-geolocation-lt
>
>
> On Mon, Jan 4, 2016 at 6:54 AM, Rishant Agarwal <notifications@github.com>
> wrote:
>
>> Maybe I posted it in wrong thread but the issue is there. Please can you
>> tell me how to fix it ?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/202#issuecomment-168656833>
>> .
>>
>
>
>
> --
> Chris Scott
> Transistor Software <http://www.transistorsoft.com>
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by vikasjson** [comment]
Hello Sir,
This Is My Code  I want to get Lat Long When App Is Minimised or in background position . When app is running its working fine , but when i minimized applcation it stops working . when controller comes in this method its print only first console ,console.log('Entering in geolocation'); after this nothing happen in this method, can anyone help me?

.controller('AppCtrl', function ($scope, $state,$interval, $ionicModal, $ionicPopover, $timeout, $http, $ionicPlatform, userFactory,$cordovaGeolocation,$filter) {

```
setInterval(function(){
  getLocation();

},50000);

function getLocation(){
  var posOptions = {timeout: 10000, enableHighAccuracy: false};
  console.log('Entering in geolocation');
  $cordovaGeolocation
    .getCurrentPosition(posOptions)
    .then(function (position)
    {
      console.log('Getting Location');
      var now = new Date();
      var nowdate = $filter('date')(now, 'yyyy-MM-dd');
      var nowtime = $filter('date')(now, 'HH:mm:ss');
      var userid = localStorage.jumboUserId;
      var lati =  position.coords.latitude;
      var longi =  position.coords.longitude;
      var date = nowdate;
      var time = nowtime;
      console.log('Getting Location');
      userFactory.trackUser(userid, lati, longi, date, time).then(function (data) {
        console.log('done');
        console.log('Location sending');
      });
    }, function (err) {
      // error
    });
}
```

});
