### ISSUE TITLE
Can't get the window.plugins.backgroundGeoLocation object

### ISSUE THREAD

**Issue by artu1000** [christocracy/cordova-plugin-background-geolocation#203]
Hi Chris,

I am looking for a solution to my problem and I've been searching in issues, stackoverflow and more, without finding a solution : 

I installed your plugin as it is explained here : https://github.com/christocracy/cordova-plugin-background-geolocation.
When deviceready event is received, I try to execute your code example in it but I encountered a few problems :
- first, window.navigator.geolocation was not found, I had to replace it by navigator.geolocation to get the first geolocation call.
- then, the window.plugins.backgroundGeoLocation object is not found too, it always returns null.

I tried with the solution you explain here : https://github.com/christocracy/cordova-plugin-background-geolocation/issues/202 (replacing 
```
<clobbers target="plugins.backgroundGeoLocation" />
```
by
```
<clobbers target="window.backgroundGeoLocation" />
``` 
in the plugins/org.transistorsoft.cordova.background-geolocation/plugins.xml file) but without the result is still null.

When I try to console the window.plugins object, it only returns me { insomnia: {} }.

I am quite confused, I don't know how to get your plugin object in order to get the geolocation work in background (I had no problem using the gelocation plugin but I need it to run it in background).

My version of phonegap : 5.1.1-0.29.0
My version of cordova : 5.1.1

Thank you by advance for your answer.
Hopping to read you soon !

**Comment by neotrode** [comment]
I am in the exact same situation.  Geolocation work fine but when I use this plugin I get the same error.
I am just using Cordova (not Phonegap) version 5.0.0 on Ubuntu 14.04 LTS.

**Comment by christocracy** [comment]
I may be experiencing something similar in the [Premium Version](http://christocracy.github.io/cordova-background-geolocation/)

Try this:  edit [plugin.xml](https://github.com/christocracy/cordova-plugin-background-geolocation/blob/master/plugin.xml#L20)

Change that to:
```
<clobbers target="window.backgroundGeoLocation" />
```

You'll have to access the plugin like so, of course
```
onDeviceReady = function() {
    var bgGeo = window.backgroundGeoLocation;
    .
    .
    .
};
```

**Comment by christocracy** [comment]
And make sure you destroy your platform then rebuild it when you try this

On Thursday, July 9, 2015, neotrode <notifications@github.com> wrote:

> I am in the exact same situation. Geolocation work fine but when I use
> this plugin I get the same error.
> I am just using Cordova (not Phonegap) version 5.0.0 on Ubuntu 14.04 LTS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/203#issuecomment-120212640>
> .
>


-- 
Snet from Gmail Mobile

**Comment by artu1000** [comment]
Thanks for your answer.

I tried your solution :
1) I replaced 
```xml
<clobbers target="plugins.backgroundGeoLocation" />
```
by
```xml
<clobbers target="window.backgroundGeoLocation" />
```

2) I destroyed my platforms with the command
```shell
phonegap platform remove <platform>
```

3) I added the ios platform again with a
```shell
phonegap platform add ios
```

4) I built it with
```shell
phonegap build ios
```

I got the following error :
```shell
Failed to install 'de.appplant.cordova.plugin.background-mode':Error: Expected plugin to have ID "org.apache.cordova.device" but got "cordova-plugin-device".
    at checkID (/Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:164:15)
    at /Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:148:9
    at _fulfilled (/Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:749:13)
    at /Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)

Error: Expected plugin to have ID "org.apache.cordova.device" but got "cordova-plugin-device".
    at checkID (/Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:164:15)
    at /Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:148:9
    at _fulfilled (/Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:749:13)
    at /Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
```

According to what I saw here : https://github.com/katzer/cordova-plugin-background-mode/issues/90
that was not so important and my platform has been installed anyway, so I tried.

I serve my phonegap app and do a
```javascript
console.log(window.backgroundGeoLocation);
```

This is still null...
Any idea of what I did wrong here ?

**Comment by christocracy** [comment]
We need to isolate the problem away from your app.

Please install the SampleApp in the repo and debug with that

On Friday, July 10, 2015, Arthur LORENT <notifications@github.com> wrote:

> Thanks for your answer.
>
> I tried your solution :
> 1) I replaced
>
> <clobbers target="plugins.backgroundGeoLocation" />
>
> by
>
> <clobbers target="window.backgroundGeoLocation" />
>
> 2) I destroyed my platforms with the command
>
> phonegap platform remove <platform>
>
> 3) I added the ios platform again with a
>
> phonegap platform add ios
>
> 4) I built it with
>
> phonegap build ios
>
> I got the following error :
>
> Failed to install 'de.appplant.cordova.plugin.background-mode':Error: Expected plugin to have ID "org.apache.cordova.device" but got "cordova-plugin-device".
>     at checkID (/Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:164:15)
>     at /Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:148:9
>     at _fulfilled (/Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:787:54)
>     at self.promiseDispatch.done (/Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:816:30)
>     at Promise.promise.promiseDispatch (/Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:749:13)
>     at /Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:557:44
>     at flush (/Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:108:17)
>     at process._tickCallback (node.js:355:11)
>
> Error: Expected plugin to have ID "org.apache.cordova.device" but got "cordova-plugin-device".
>     at checkID (/Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:164:15)
>     at /Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:148:9
>     at _fulfilled (/Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:787:54)
>     at self.promiseDispatch.done (/Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:816:30)
>     at Promise.promise.promiseDispatch (/Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:749:13)
>     at /Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:557:44
>     at flush (/Users/arthurlorent/.nvm/versions/node/v0.12.2/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:108:17)
>     at process._tickCallback (node.js:355:11)
>
> According to what I saw here : katzer/cordova-plugin-background-mode#90
> <https://github.com/katzer/cordova-plugin-background-mode/issues/90>
> that was not so important and my platform has been installed anyway, so I
> tried.
>
> I serve my phonegap app and do a
>
> console.log(window.backgroundGeoLocation);
>
> This is still null...
> Any idea of what I did wrong here ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/203#issuecomment-120301584>
> .
>


-- 
Snet from Gmail Mobile

**Comment by neotrode** [comment]
I updated the clobbers tag and now get bgGeo undefined.  If I nest the scripts onDeviceReady, as suggested, then I can not call any functions nested within the onDeviceReady block via a button tag's onclick routine.

Also note, I followed your suggestion for a baseline and downloaded the SampleApp, added a platform, and proceeded with a build.  I get the same error as noted in the beginning of this thread, "window.plugins.backgroundGeoLocation object is not found"

**Comment by neotrode** [comment]
Should I be using event trigger listeners in the javascript side rather than call a function from the html  button tags?

**Comment by christocracy** [comment]
If you update the clobbers tag to `window.backgroundGeoLocation`, there is no more `window.plugins.backgroundGeoLocation' -- it's `window.backgroundGeoLocation`.

"html button tags", what??

You're not doing this `<button onclick="someFunction()" />` ?

**Comment by neotrode** [comment]
yep and according to that response, I am admitting that embarrassingly.  Should I stick to the js side and listen for events instead?

**Comment by christocracy** [comment]
Yes

On Friday, July 10, 2015, Frank <notifications@github.com> wrote:

> yep and according to that response, I am admitting that embarrassingly.
> Should I stick to the js side and listen for events instead?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/203#issuecomment-120566072>
> .
>


-- 
Snet from Gmail Mobile

**Comment by neotrode** [comment]
You rock!  That did it.  So in summary, your initial suggestion to change the cobble tag to: <clobbers target="window.backgroundGeoLocation" /> took care of it once I re-arranged the code to nest within onDeviceReady.

My app is firing away and the background tracking icon is appearing. Now I just need to work on my code.

My apologies adding the monkey wrench with my logic of html triggering js.  I have some old habits.

Thanks again Chris.

**Comment by christocracy** [comment]
The premium version is 100* better

On Saturday, July 11, 2015, Frank <notifications@github.com> wrote:

> You rock! That did it. So in summary, your initial suggestion to change
> the cobble tag to: took care of it once I re-arranged the code to nest
> within onDeviceReady.
>
> My app is firing away and the background tracking icon is appearing. Now I
> just need to work on my code.
>
> My apologies adding the monkey wrench with my logic of html triggering js.
> I have some old habits.
>
> Thanks again Chris.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/203#issuecomment-120572361>
> .
>


-- 
Snet from Gmail Mobile

**Comment by neotrode** [comment]
I'm sure.  Once I have this going perfectly, I will gladly proceed to premium.

**Comment by christocracy** [comment]
Try out edge branch.  Moved `window.plugins.backgroundGeoLocation` -> `window.BackgroundGeolocation`.

**NOTE** There's a change in came-casing as well:  `backgroundGeoLocation` vs `BackgroundGeolocation`.

**Comment by artu1000** [comment]
After a few tests, here are the results :

I tried your sample example using only cordova on an android phone and surprise, it works without changing anything in the plugin.xml file.
I still have an error : google is not defined. It seems that the Google Map API call is not well handled, but I get the geolocation notifications.

Using phonegap seems to be quite different because you don't need to build the platform before rendering it on you mobile. I could use all the native cordova plugins (accessible via the navigator variable) but I couldn't make your plugin work (I can't access to your plugin).
This should be possible because I could use the insomnia plugin, which prevent the mobile from enter in sleeping mode.
Here is how the new Phonegap tool works if you want to know more about it : http://app.phonegap.com/

Let me now if you think that there is an existing solution for the phonegap use. If not, I will use cordova and will drop phonegap for my future developments.

**Comment by christocracy** [comment]
What version of Cordova are you using?  perhaps this is a
cordova-plugin-whitelist issue?
https://github.com/apache/cordova-plugin-whitelist

PhoneGap is very limiting.  There are more flexible build-services out
there, such as Cloud Five
https://www.cloudfiveapp.com/


On Tue, Jul 14, 2015 at 12:57 PM, Arthur LORENT <notifications@github.com>
wrote:

> After a few tests, here are the results :
>
> I tried your sample example using only cordova on an android phone and
> surprise, it works without changing anything in the plugin.xml file.
> I still have an error : google is not defined. It seems that the Google
> Map API call is not well handled, but I get the geolocation notifications.
>
> Using phonegap seems to be quite different because you don't need to build
> the platform before rendering it on you mobile. I could use all the native
> cordova plugins (accessible via the navigator variable) but I couldn't make
> your plugin work (I can't access to your plugin).
> This should be possible because I could use the insomnia plugin, which
> prevent the mobile from enter in sleeping mode.
> Here is how the new Phonegap tool works if you want to know more about it
> : http://app.phonegap.com/
>
> Let me now if you think that there is an existing solution for the
> phonegap use. If not, I will use cordova and will drop phonegap for my
> future developments.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/203#issuecomment-121307805>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
