### ISSUE TITLE
iOS not providing events after being Stationary

### ISSUE THREAD

**Issue by iconico** [christocracy/cordova-plugin-background-geolocation#204]
I've been testing your plugin (great documentation by the way) for the last few days and discovered a problem with the iOS version. I'm getting the callbacks from the plugin, and I can watch the notifications in debug mode. The problem I'm seeing is that after the plugin signals either a "stop detected" event or says it's "stationary" and then I leave the phone still for 20 minutes, if I then take the phone for a walk I'm no longer getting any notifications or events from the plugin.

I'm using PhoneGap Build with Cordova 3.7.

This is really holding me up, I specifically need the use case where the phone is stationary for an hour or so, and I want to detect if the phone has left a location, with the user driving away.

I'm using the free version right now, and will purchase if I can resolve this issue.

Thanks in advance for your help.

**Comment by christocracy** [comment]
When the plugin enters stationary mode, you must travel several blocks to
re-engage tracking.

On Monday, July 6, 2015, iconico <notifications@github.com> wrote:

> I've been testing your plugin (great documentation by the way) for the
> last few days and discovered a problem with the iOS version. I'm getting
> the callbacks from the plugin, and I can watch the notifications in debug
> mode. The problem I'm seeing is that after the plugin signals either a
> "stop detected" event or says it's "stationary" and then I leave the phone
> still for 20 minutes, if I then take the phone for a walk I'm no longer
> getting any notifications or events from the plugin.
>
> I'm using PhoneGap Build with Cordova 3.7.
>
> This is really holding me up, I specifically need the use case where the
> phone is stationary for an hour or so, and I want to detect if the phone
> has left a location, with the user driving away.
>
> I'm using the free version right now, and will purchase if I can resolve
> this issue.
>
> Thanks in advance for your help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/204>
> .
>


-- 
Snet from Gmail Mobile

**Comment by iconico** [comment]
I understand that, I've gone about half a mile on my bike and it's not coming back for me. I've tried a whole bunch of configuration values.

**Comment by christocracy** [comment]
Have you got wifi on?  Are you in a populated urban environment?

On Monday, July 6, 2015, iconico <notifications@github.com> wrote:

> I understand that, I've gone about half a mile on my bike and it's not
> coming back for me. I've tried a whole bunch of configuration values.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/204#issuecomment-118968220>
> .
>


-- 
Snet from Gmail Mobile

**Comment by christocracy** [comment]
DesiredAccuracy: 0 for best results

On Monday, July 6, 2015, iconico <notifications@github.com> wrote:

> I understand that, I've gone about half a mile on my bike and it's not
> coming back for me. I've tried a whole bunch of configuration values.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/204#issuecomment-118968220>
> .
>


-- 
Snet from Gmail Mobile

**Comment by iconico** [comment]
I'm in center city Philadelphia, so yes.
I do have wifi on.
I've tried DesiredAccuracy: 0

**Comment by christocracy** [comment]
You're not calling bgGeo.stop(), are you?



On Monday, July 6, 2015, iconico <notifications@github.com> wrote:

> I'm in center city Philadelphia, so yes.
> I do have wifi on.
> I've tried DesiredAccuracy: 0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/204#issuecomment-118969216>
> .
>


-- 
Snet from Gmail Mobile

**Comment by christocracy** [comment]
No crashes reported inxcode logs?

On Monday, July 6, 2015, Chris Scott <christocracy@gmail.com> wrote:

> You're not calling bgGeo.stop(), are you?
>
>
>
> On Monday, July 6, 2015, iconico <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I'm in center city Philadelphia, so yes.
>> I do have wifi on.
>> I've tried DesiredAccuracy: 0
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/204#issuecomment-118969216>
>> .
>>
>
>
> --
> Snet from Gmail Mobile
>


-- 
Snet from Gmail Mobile

**Comment by iconico** [comment]
no, not calling it

**Comment by iconico** [comment]
I'm running off a PC unfortunately, I just push the .ipa file over that PhoneGap Build makes.

**Comment by christocracy** [comment]
HAve you booted my SampleApp in repo in order to test the plugin isolation
from your app code?

On Monday, July 6, 2015, iconico <notifications@github.com> wrote:

> I'm running off a PC unfortunately, I just push the .ipa file over that
> PhoneGap Build makes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/204#issuecomment-118970883>
> .
>


-- 
Snet from Gmail Mobile

**Comment by iconico** [comment]
No, I guess that's the next step. So there's nothing that I normally no problem having the phone stationary for a number of hours. No settings I need to adjust?

**Comment by iconico** [comment]
Sample App is working.

Ok I think I figured it out. For some reason during development I didn't have the user permissions set properly and I was just updating the Javascript for my app off of the server. When I reinstalled my app I got the prompt to use location services in the background.
The plugin then showed a notification for "Authorization status changed 3" - which I'm sure is kCLAuthorizationStatusAuthorized. So for some reason the plugin must not have had the right permissions to run continuously in the background?

It would be cool if there was some kind of reporting of this in debug mode, or, even better, an event thrown so I could prompt users to fix any permissions problems if they're not set correctly.

I'm looking at the constants here, FYI:
https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/index.html#//apple_ref/c/econst/kCLAuthorizationStatusAuthorized

Another thing I've noticed is that I can go about 10 blocks through Center City Philadelphia without an exit of the stationary region being reported. However if I head the other way down towards the Delaware River I get an exit reported in 2 blocks.

**Comment by christocracy** [comment]
>
> Another thing I've noticed is that I can go about 10 blocks through Center
> City Philadelphia without an exit of the stationary region being reported.
> However if I head the other way down towards the Delaware River I get an
> exit reported in 2 blocks.
>

Stationary-monitoring is implemente with native iOS Geofence api which
relies upon cell-tower-change events to determine if device has exited
geofence.

You’re closer to the boundary of a cell-tower in one direction [Tower A] vs
the other [Tower B]

  | [Tower A]
  |  [Tower B]
/\   *[you]*                            /\



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by iconico** [comment]
Ok I'm still having issues, doing a lot of testing and it's intermittent, but sometimes I'll see the plugin enter into stationary mode, sometimes not. Sometimes it wakes up, sometimes not. Last night my app posted some "moving updates" at around 5am - which is crazy as I was sleeping at the time!
Seeing the same issues in the Sample app, I'm really wondering if it's iOS 8.3
I found that some people are having issues with that so I'm upgrading to iOS 8.4
http://apple.stackexchange.com/questions/180575/location-service-not-working-as-expected-in-ios-8-3

**Comment by iconico** [comment]
The release notes of iOS 8.4 state that:
	•	Fixes an issue that prevented GPS accessories from providing location data 

Here's hoping!

**Comment by christocracy** [comment]
I've never experienced anything like that in 2 years, extraneous stationary
exits while sleeping.

On Tuesday, July 7, 2015, iconico <notifications@github.com> wrote:

> The release notes of iOS 8.4 state that:
> • Fixes an issue that prevented GPS accessories from providing location
> data
>
> Here's hoping!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/204#issuecomment-119320647>
> .
>


-- 
Snet from Gmail Mobile

**Comment by iconico** [comment]
Looks like it was iOS 8.3 - it works fine this morning on iOS 8.4

**Comment by christocracy** [comment]
awesome.

On Wed, Jul 8, 2015 at 2:17 PM, iconico <notifications@github.com> wrote:

> Looks like it was iOS 8.3 - it works fine this morning on iOS 8.4
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/204#issuecomment-119684503>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
