### ISSUE TITLE
Premium Version and PhoneGap Build

### ISSUE THREAD

**Issue by iconico** [christocracy/cordova-plugin-background-geolocation#205]
In the demo version I can include the plugin by adding the following to my config.xml
`<gap:plugin name="org.transistorsoft.cordova.background-geolocation" \>`

Is there something similar for the premium version where I can simply include it?
I don't want to have to maintain the source code.

**Comment by christocracy** [comment]
Please use Premium repo's Issues for Premium questions.

**Comment by christocracy** [comment]
(This issue has been raised and answered several times in Premium repo's issues.)
