### ISSUE TITLE
Can Premium Version be shared on BitBucket?

### ISSUE THREAD

**Issue by iconico** [christocracy/cordova-plugin-background-geolocation#206]
When registering can we use our BitBucket ID, instead of GitHub?
Thanks

**Comment by christocracy** [comment]
I've been thinking of migrating to bit bucket but it's github only currently

On Wednesday, July 8, 2015, iconico <notifications@github.com> wrote:

> When registering can we use our BitBucket ID, instead of GitHub?
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/206>
> .
>


-- 
Snet from Gmail Mobile
