### ISSUE TITLE
When my app goes to background it's killing background service

### ISSUE THREAD

**Issue by KashifAhmed** [christocracy/cordova-plugin-background-geolocation#209]
Here is my Application
https://github.com/KashifAhmed/backgroundGeoLocaiton

**Comment by KashifAhmed** [comment]
I also ran the sampleApp but it's same when I suspend my app it's destroying background service do I need to add some thing in AndroidManifest or I need some thing to add on config.xml.

**Comment by christocracy** [comment]
This is not an issue with my plugin — it’s an issue with your device.

Did did not answer my question about the state of developer-options that
you don’t have “Don’t keep activities” set.

[image: Inline image 1]

On Sun, Jul 12, 2015 at 5:56 PM, Kashif Ahmed <notifications@github.com>
wrote:

> I also ran the sampleApp but it's same when I suspend my app it's
> destroying background service do I need to add some thing in
> AndroidManifest or I need some thing to add on config.xml.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/209#issuecomment-120766409>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by KashifAhmed** [comment]
I have checked the sampleApp both enable & disable "Don't keep activities".

**Comment by christocracy** [comment]
What device make/model OS version are you testing this on?  try it on
another Android device.



On Sun, Jul 12, 2015 at 6:12 PM, Kashif Ahmed <notifications@github.com>
wrote:

> I have checked the sampleApp both enable & disable "Don't keep activities".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/209#issuecomment-120768012>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by KashifAhmed** [comment]
The app which is on google play it works fine.on my mobile, I have Motorola Droid Razr M.

**Comment by KashifAhmed** [comment]
Same error on other devices I think I'm doing something wrong.

**Comment by christocracy** [comment]
- Remove my plugin
- In a simple Hello World app, set up a watchPosition using standard plugin `cordova-plugin-geolocation`.  Send the location to your server via Ajax.
- Does the problem still occur, where where the app dies when you "minimize"?
