### ISSUE TITLE
iOS not going to Background

### ISSUE THREAD

**Issue by markarupert** [christocracy/cordova-plugin-background-geolocation#213]
I have been testing my app on several iOS phones. It works on all of them except for one oddity. One of the iPhones never seems to go to the background. I am getting GPS updates but all from my foreground code. I realize if it never goes to the foreground that it only makes sense that you plugin won't kickin but I was wondering if you ever experienced this and had an idea why it does not go to the background.

**Comment by christocracy** [comment]
Have you tried with SampleApp?

https://github.com/christocracy/cordova-background-geolocation-SampleApp

On Saturday, July 18, 2015, markarupert <notifications@github.com> wrote:

> I have been testing my app on several iOS phones. It works on all of them
> except for one oddity. One of the iPhones never seems to go to the
> background. I am getting GPS updates but all from my foreground code. I
> realize if it never goes to the foreground that it only makes sense that
> you plugin won't kickin but I was wondering if you ever experienced this
> and had an idea why it does not go to the background.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/213>
> .
>


-- 
Snet from Gmail Mobile

**Comment by markarupert** [comment]
I'll give it a try and let you know.
