### ISSUE TITLE
Android: no background service after I kill the foreground app

### ISSUE THREAD

**Issue by gereko3d** [christocracy/cordova-plugin-background-geolocation#217]
I'm doing some experiments with this plugin. As far as I can see, when I kill the foreground app, also the background service is killed.
I can't see any more logs in adb logcat, neither beep or other sound notifications are produced anymore (I'm running the plugin with the boolean  *debug* at **true**).
Any idea??

**Comment by christocracy** [comment]
Show me your config

**Comment by gereko3d** [comment]
Here is my config (with just an extra line, for de device uuid).

var dev_uuid = $cordovaDevice.getUUID();
var bg_geoloc_opt = {
            url: 'http://demochat.europeconsulting.it/savebgposition',
            params: {
                dev_uuid: dev_uuid
            },
            debug: true
}

What I am seeing, now, is that the plugin looks working correctly with another device (with Android 4.1.2), but it still is not working with the main device (wich is 4.4.2). In the main device I also turned off de developer mode (in order to avoid some wrong config) without results.
I suppose there could be some issues based on Android version, don't you think?

**Comment by christocracy** [comment]
If you're basically letting the plugin apply default config, what's the
plugin reporting for config in adb logcat?  I don't recall what the plugin
uses as defaults.

Why are you stuck on such old Android versions?  Thé latest version for 4.4
is 4.4.4.

On Wednesday, July 22, 2015, gereko3d <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Here is my config (with just an extra line, for de device uuid).
>
> var dev_uuid = $cordovaDevice.getUUID();
> var bg_geoloc_opt = {
> url: 'http://demochat.europeconsulting.it/savebgposition',
> params: {
> dev_uuid: dev_uuid
> },
> debug: true
> }
>
> What I am seeing, now, is that the plugin looks working correctly with
> another device (with Android 4.1.2), but it still is not working with the
> main device (wich is 4.4.2). In the main device I also turned off de
> developer mode (in order to avoid some wrong config) without results.
> I suppose there could be some issues based on Android version, don't you
> think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/217#issuecomment-123693427>
> .
>


-- 
Snet from Gmail Mobile

**Comment by gereko3d** [comment]
As far as I can see in your Java code, those should be the default values:

```java
private String stationaryRadius = "30";
private String desiredAccuracy = "100";
private String distanceFilter = "30";
private String locationTimeout = "60";
private String isDebugging = "false";
private String notificationTitle = "Background tracking";
private String notificationText = "ENABLED";
private String stopOnTerminate = "false";
```

About the Android version of my testing device... the producer (Wiko Mobile) haven't released any other updates (so far). And I don't desire/time to spend for any home-made/self-made upgrade...

**Comment by gereko3d** [comment]
I'have gone a little bit deeper on this issue.
As I said, the plugin is correctly working on an old 4.1.2 device. 
I found that this is a known bug, which was introduced in 4.4.1 and affects 4.4.2 too.
You can find more informations [here](http://www.androidpolice.com/2014/03/07/bug-watch-stopping-apps-on-android-4-4-2-can-silently-kill-related-background-services-a-fix-is-on-the-way/).

The author of the post also suggested a solution (well, more of a **workaorund**). As far as I can see in your code (as I said I'm definitively not a Java expert), it seems like you are doing something similar, using the system AlarmManager...

I also tried a little change on your code, trying to comment **this.stopSelf();** in **onTaskRemoved** method. The method, now, apper:

```java
@TargetApi(Build.VERSION_CODES.ICE_CREAM_SANDWICH)
@Override
public void onTaskRemoved(Intent rootIntent) {
    // this.stopSelf();
    super.onTaskRemoved(rootIntent);
}
```

In this way the service is not killed anymore when I close/kill the application process.
But... It still is not working: I mean, the service is running, but no data are posted to my endpoint (nor can I hear any sound or see any **Toast notification**, using the debug mode).

At this point, do you have any suggestions? Thanks.

**Comment by christocracy** [comment]
Try installing the premium sample app from Google Play Store in your
problem devices.  I bet it has no problem.

http://christocracy.github.io/cordova-background-geolocation/

On Thursday, July 23, 2015, gereko3d <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> I'have gone a little bit deeper on this issue.
> As I said, the plugin is correctly working on an old 4.1.2 device.
> I found that this is a known bug, which was introduced in 4.4.1 and
> affects 4.4.2 too.
> You can find more informations here
> <http://www.androidpolice.com/2014/03/07/bug-watch-stopping-apps-on-android-4-4-2-can-silently-kill-related-background-services-a-fix-is-on-the-way/>
> .
>
> The author of the post also suggested a solution (well, more of a
> *workaorund*). As far as I can see in your code (as I said I'm
> definitively not a Java expert), it seems like you are doing something
> similar, using the system AlarmManager...
>
> I also tried a little change on your code, trying to comment
> *this.stopSelf();* in *onTaskRemoved* method. The method, now, apper:
>
> @TargetApi(Build.VERSION_CODES.ICE_CREAM_SANDWICH)
> @Overridepublic void onTaskRemoved(Intent rootIntent) {
>     // this.stopSelf();
>     super.onTaskRemoved(rootIntent);
> }
>
> In this way the service is not killed anymore when I close/kill the
> application process.
> But... It still is not working: I mean, the service is running, but no
> data are posted to my endpoint (nor can I hear any sound or see any *Toast
> notification*, using the debug mode).
>
> At this point, do you have any suggestions? Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/217#issuecomment-124059375>
> .
>


-- 
Snet from Gmail Mobile

**Comment by gereko3d** [comment]
Downloaded and tried. 
Is the same: as I kill the process, the service is killed too...

**Comment by christocracy** [comment]
Upgrade Android.  I can't fix this on my end

On Thursday, July 23, 2015, gereko3d <notifications@github.com> wrote:

> Downloaded and tried.
> Is the same: as I kill the process, the service is killed too...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/217#issuecomment-124067858>
> .
>


-- 
Snet from Gmail Mobile

**Comment by lucasalmeida92** [comment]
@gereko3d I noticed that too.. when i kill my app in foreground the service is killed too..
Although the plugin is working fine on my android(lolipop version)...

Maybe your distance configuration is too big and the service is not detecting your movement.
When i was testing i used this configuration to debug:

...
desiredAccuracy: 5,
stationaryRadius: 10,
distanceFilter: 10,
...

In wich file have you did this modification in onTaskRemoved method?

(sorry, my english is not so good ;x)

**Comment by gereko3d** [comment]
Directly in the source code (src/android/LocationUpdateService.java).
You have to rebuild it. The easiest way I found for this kind of experimentations:

- Remove your cordova plugin (**cordova plugin rm org.transistorsoft.cordova.background-geolocation**)
- Clone the repository in a separate folder (i.e. in a subfolder or your home) using git clone https://github.com/christocracy/cordova-plugin-background-geolocation.git /path/to/yourfolder
- Modify the Java source code
- Add back the plugin from your folder (cordova plugin add /path/to/yourfolder)

I don't know if there are easiest way to achieve the same goal.


For what concerning the config: as I said the same app (an the background geolocation) is perfectly working on another device, with an older version of Android. I also noticed (as I said in a precedent comment) that killing a spawned service by killing the foreground app is a known bug introduced with 4.4.0... So, I don't think it's a problem with the javascript config of the plugin...

**Comment by lucasalmeida92** [comment]
@gereko3d  Thanks for the explaining! I'll try it.

About the bug, i didnt know that... are u sure is it because of the version ? maybe its because of your device.

thanks \o

**Comment by gereko3d** [comment]
Let's have a look here: http://www.androidpolice.com/2014/03/07/bug-watch-stopping-apps-on-android-4-4-2-can-silently-kill-related-background-services-a-fix-is-on-the-way/

**Comment by lucasalmeida92** [comment]
I'll read! ;]  Thanks!

And the modification in java method also worked!

Another problem...In my device when service is starded a notification shows up and i cant swipe it off! Do you have this same problem?

I wish i could disable this notification, because is boring you know?

\o

**Comment by gereko3d** [comment]
Happy ti know I helped you.
For what concerning the notification, I don't think it could be swiped.

**Comment by christocracy** [comment]
You cannot disable the notification due to the nature of the Android
service.

The premium version does not have this notification, however.

On Monday, July 27, 2015, gereko3d <notifications@github.com> wrote:

> Happy ti know I helped you.
> For what concerning the notification, I don't think it could be swiped.
> On 27 Jul 2015 19:47, "Lucas Almeida" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > I'll read! ;] Thanks!
> >
> > And the modification in java method also worked!
> >
> > Another problem...In my device when service is starded a notification
> > shows up and i cant swipe it off! Do you have this same problem?
> >
> > I wish i could disable this notification, because is boring you know?
> >
> > \o
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/217#issuecomment-125284910
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/217#issuecomment-125285601>
> .
>


-- 
Snet from Gmail Mobile

**Comment by lucasalmeida92** [comment]
Hey @christocracy !

Are u sure it cant be disabled? So how apps like Swarm does it?

Thanks ;]

**Comment by christocracy** [comment]
This is my plugin.  I made it.  I'm telling you the free version use a type
of service which requires a notification message.  The premium version uses
a different device mechanism.  This cannot be changed

On Monday, July 27, 2015, Lucas Almeida <notifications@github.com> wrote:

> Hey @christocracy <https://github.com/christocracy> !
>
> Are u sure it cant be disabled? So how apps like Swarm does it?
>
> Thanks ;]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/217#issuecomment-125351631>
> .
>


-- 
Snet from Gmail Mobile
