### ISSUE TITLE
Error trying to run the sync

### ISSUE THREAD

**Issue by markarupert** [christocracy/cordova-plugin-background-geolocation#218]
I am getting the following error trying to implement the sync() function

       Error: undefined is not an object (evaluating 'bgGeo.sync')

This is what is in the plugin list
       com.transistorsoft.cordova.background-geolocation 0.5.2 "BackgroundGeolocation"

Is this a version issue or am I missing something else?

**Comment by christocracy** [comment]
Confused.  This is a question about the premium API on the free version's issues

**Comment by markarupert** [comment]
Reported in Premium section
