### ISSUE TITLE
Cannot read property 'backgroundGeoLocation' of undefined

### ISSUE THREAD

**Issue by meghalmodi12** [christocracy/cordova-plugin-background-geolocation#219]
Hello Chris,

I am using your plug-in in my application. I am using Telerik appbuilder with cordova 3.7. And when I run my application I get above mentioned error. I tried the same thing with cordova 4.0. Can you help me to solve thiis problem?

Thank You,
Meghal

**Comment by paweldziura** [comment]
1. what is the object where you're looking for 'backgroundGeoLocation' ?
It should be window.plugins.backgroundGeoLocation
2. Check if 'deviceready' event is fired before usage of plugin.

**Comment by christocracy** [comment]
Update?

**Comment by meghalmodi12** [comment]
Hello Chris,

I am extremely sorry, I couldn't get back to you. But thanks a lot for your
support the issue was resolved. I am still exploring the application. I
will let you know if I have any doubts.

Once again thanks a lot.

Regards,
Meghal Modi

**Comment by christocracy** [comment]
You'll be **100 times** happier using the [Premium Version](http://transistorsoft.github.io/cordova-background-geolocation/).  Android battery-efficiency is at least **10 times** greater.

The Premium version now adds **battery level & status** data to each recorded geolocation.  Here's what a recorded location looks like in **Premium Version**:

```
{
    "location": {
        "coords": {
            "latitude":   [Float],
            "longitude":  [Float]
            "accuracy":   [Float]
            "speed":      [Float],
            "heading":    [Float],
            "altitude":   [Float]
        },
        "activity": {                // <-- Android Only
            "type": [still | on_foot | walking | running | in_vehicle | on_bicycle],
            "confidence": [0-100%]
        },
        "battery": {              // <-- iOS & Android
            "level": [Float, 0-1],
            "is_charging": [Boolean]
        },
        "timestamp": [ISO-8601 UTC], // eg:  "2015-05-05T04:31:54Z"
        "is_moving": [Boolean]       // <-- The motion-state when location was recorded.
    }
}
```
