### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by houmanka** [christocracy/cordova-plugin-background-geolocation#220]
I am trying to install the free version to see if Client is happy with how it works then I purchase the full version however when try to install it I get the following error:

Installing "org.transistorsoft.cordova.background-geolocation" for android
Fetching plugin "cordova-plugin-dialogs" via npm
npm http GET https://registry.npmjs.org/cordova-plugin-dialogs
npm http GET https://registry.npmjs.org/cordova-plugin-dialogs
npm http GET https://registry.npmjs.org/cordova-plugin-dialogs
npm http GET https://registry.npmjs.org/cordova-plugin-dialogs/-/cordova-plugin-dialogs-1.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/cordova-plugin-dialogs/-/cordova-plugin-dialogs-1.1.1.tgz
npm http GET https://registry.npmjs.org/cordova-plugin-dialogs/-/cordova-plugin-dialogs-1.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/cordova-plugin-dialogs/-/cordova-plugin-dialogs-1.1.1.tgz
npm http GET https://registry.npmjs.org/cordova-plugin-dialogs/-/cordova-plugin-dialogs-1.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/cordova-plugin-dialogs/-/cordova-plugin-dialogs-1.1.1.tgz
Fetching from npm failed: read ECONNRESET
Failed to install 'org.transistorsoft.cordova.background-geolocation':Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)

At this stage, even if I can get the iOS running on the Client phone I will be happy. Thanks.

H.

**Comment by christocracy** [comment]
Are you using Cordova >= 4?

On Monday, July 27, 2015, Houman Kargaran <notifications@github.com> wrote:

> I am trying to install the free version to see if Client is happy with how
> it works then I purchase the full version however when try to install it I
> get the following error:
>
> Installing "org.transistorsoft.cordova.background-geolocation" for android
> Fetching plugin "cordova-plugin-dialogs" via npm
> npm http GET https://registry.npmjs.org/cordova-plugin-dialogs
> npm http GET https://registry.npmjs.org/cordova-plugin-dialogs
> npm http GET https://registry.npmjs.org/cordova-plugin-dialogs
> npm http GET
> https://registry.npmjs.org/cordova-plugin-dialogs/-/cordova-plugin-dialogs-1.1.1.tgz
> npm ERR! fetch failed
> https://registry.npmjs.org/cordova-plugin-dialogs/-/cordova-plugin-dialogs-1.1.1.tgz
> npm http GET
> https://registry.npmjs.org/cordova-plugin-dialogs/-/cordova-plugin-dialogs-1.1.1.tgz
> npm ERR! fetch failed
> https://registry.npmjs.org/cordova-plugin-dialogs/-/cordova-plugin-dialogs-1.1.1.tgz
> npm http GET
> https://registry.npmjs.org/cordova-plugin-dialogs/-/cordova-plugin-dialogs-1.1.1.tgz
> npm ERR! fetch failed
> https://registry.npmjs.org/cordova-plugin-dialogs/-/cordova-plugin-dialogs-1.1.1.tgz
> Fetching from npm failed: read ECONNRESET
> Failed to install
> 'org.transistorsoft.cordova.background-geolocation':Error: read ECONNRESET
> at exports._errnoException (util.js:746:11)
> at TCP.onread (net.js:559:26)
> Error: read ECONNRESET
> at exports._errnoException (util.js:746:11)
> at TCP.onread (net.js:559:26)
>
> At this stage, even if I can get the iOS running on the Client phone I
> will be happy. Thanks.
>
> H.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/220>
> .
>


-- 
Snet from Gmail Mobile

**Comment by christocracy** [comment]
Are you following the directions in README for SampleApp *exactly*?

On Monday, July 27, 2015, Houman Kargaran <notifications@github.com> wrote:

> I am trying to install the free version to see if Client is happy with how
> it works then I purchase the full version however when try to install it I
> get the following error:
>
> Installing "org.transistorsoft.cordova.background-geolocation" for android
> Fetching plugin "cordova-plugin-dialogs" via npm
> npm http GET https://registry.npmjs.org/cordova-plugin-dialogs
> npm http GET https://registry.npmjs.org/cordova-plugin-dialogs
> npm http GET https://registry.npmjs.org/cordova-plugin-dialogs
> npm http GET
> https://registry.npmjs.org/cordova-plugin-dialogs/-/cordova-plugin-dialogs-1.1.1.tgz
> npm ERR! fetch failed
> https://registry.npmjs.org/cordova-plugin-dialogs/-/cordova-plugin-dialogs-1.1.1.tgz
> npm http GET
> https://registry.npmjs.org/cordova-plugin-dialogs/-/cordova-plugin-dialogs-1.1.1.tgz
> npm ERR! fetch failed
> https://registry.npmjs.org/cordova-plugin-dialogs/-/cordova-plugin-dialogs-1.1.1.tgz
> npm http GET
> https://registry.npmjs.org/cordova-plugin-dialogs/-/cordova-plugin-dialogs-1.1.1.tgz
> npm ERR! fetch failed
> https://registry.npmjs.org/cordova-plugin-dialogs/-/cordova-plugin-dialogs-1.1.1.tgz
> Fetching from npm failed: read ECONNRESET
> Failed to install
> 'org.transistorsoft.cordova.background-geolocation':Error: read ECONNRESET
> at exports._errnoException (util.js:746:11)
> at TCP.onread (net.js:559:26)
> Error: read ECONNRESET
> at exports._errnoException (util.js:746:11)
> at TCP.onread (net.js:559:26)
>
> At this stage, even if I can get the iOS running on the Client phone I
> will be happy. Thanks.
>
> H.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/220>
> .
>


-- 
Snet from Gmail Mobile

**Comment by houmanka** [comment]
5.1.1

**Comment by christocracy** [comment]
I mean really *exactly*.  Like copying example/SampleApp out of the repo
into some other folder is important

On Monday, July 27, 2015, Houman Kargaran <notifications@github.com> wrote:

> 5.1.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/220#issuecomment-125408521>
> .
>


-- 
Snet from Gmail Mobile

**Comment by houmanka** [comment]
Can you please print the link to the Sample App? Thanks

**Comment by houmanka** [comment]
I was following what is in the https://github.com/christocracy/cordova-plugin-background-geolocation description

**Comment by houmanka** [comment]
Found it.

**Comment by houmanka** [comment]
Sample Application installs with no issue. So now how I incorporate it in my application as the instruction on the https://github.com/christocracy/cordova-plugin-background-geolocation didn't work, unless it is how the premium works only.

Can I incorporate this into Ionic framework? Will you have support for this if we purchase the premium version with premium support?

**Comment by christocracy** [comment]
Premium version has a more fully featured, ionic based SampleApp

https://github.com/christocracy/cordova-background-geolocation-SampleApp

On Monday, July 27, 2015, Houman Kargaran <notifications@github.com> wrote:

> Sample Application installs with no issue. So now how I incorporate it in
> my application as the instruction on the
> https://github.com/christocracy/cordova-plugin-background-geolocation
> didn't work, unless it is how the premium works only.
>
> Can I incorporate this into Ionic framework? Will you have support for
> this if we purchase the premium version with premium support?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/220#issuecomment-125415083>
> .
>


-- 
Snet from Gmail Mobile

**Comment by houmanka** [comment]
Cool. I need to purchase the premium version before I can test the sample. So before I pass this to Account Manager can you please answer the following so I can get the ball rolling?

1. Do you have or know any application that uses your plugin and now on the app store? ( Account Manager wants to know if this will pass the Apple review ) 

2. Will you be able to guide us through installation and setting this up in our application which is developing based on ionic framework? ( we dont need you to code anything just so we can get the plugin installs and operates )
FYI: we will use your Sample App as a guide anyway.

Thanks again.
PS: my question now: if user turn off the location service app is not going to work correct? So it is safe to say this is the only limitation this plugin would have.

**Comment by christocracy** [comment]
>
>    1.
>
>    Do you have or know any application that uses your plugin and now on
>    the app store?
>
>
> My client has 3.  It all depends upon if you're making an app that
deserves bg tracking (eg fleet-tracking, taxi App, fitness App).  The free
version has existed for over 2 years and many others have sucEssfuuly
submitted apps.

>
>    1.
>
>    Will you be able to guide us through installation and setting this up
>    in our application which is developing based on ionic framework? ( we dont
>    need you to code anything just so we can get the plugin installs and
>    operates )
>
> I'm not interested in your app code at all.  If you have an issue getting
the sample app to run, post an issue and I'll respond.   I'm not
responsible for PhoneGap issues (if you're using that).

> PS: my question now: if user turn off the location service app is not
> going to work correct? So it is safe to say this is the only limitation
> this plugin would have.
>
If user "closes" app before you exec #stop method, the plugin will continue
to track.  The only way to cease tracking is to exec #stop.  Guaranteed.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/220#issuecomment-125430861>
> .
>


-- 
Snet from Gmail Mobile

**Comment by houmanka** [comment]
Thank you for your respond.

H.

**Comment by houmanka** [comment]
One last question. Sorry for that.
If user press the home button then double tap the home button and completely close the app, does your plugin still track the user, say in GeoFencing?

**Comment by christocracy** [comment]
Yes.  Geofences persist not only on close but device restart as well

On Tuesday, July 28, 2015, Houman Kargaran <notifications@github.com> wrote:

> One last question. Sorry for that.
> If user press the home button then double tap the home button and
> completely close the app, does your plugin still track the user, say in
> GeoFencing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/220#issuecomment-125517068>
> .
>


-- 
Snet from Gmail Mobile
