### ISSUE TITLE
Git install fails on Cordova 5.1 with shell.js: internal error

### ISSUE THREAD

**Issue by davidzof** [christocracy/cordova-plugin-background-geolocation#222]
For information Cordova 5.1 the git install fails with the following error:

shell.js: internal error
Error: EXDEV, cross-device link not permitted '/tmp/git/1438242999549/LICENSE'

a workaround is to clone locally and install from there:

$ git clone https://github.com/christocracy/cordova-plugin-background-geolocation.git
$ cordova plugin add ../cordova-plugin-background-geolocation/

This is fixed in the latest Cordova Branch, see here: https://issues.apache.org/jira/browse/CB-9212

**Comment by christocracy** [comment]
This version plugin has been deprecated a long time.

Please see the new improved version [here](https://github.com/transistorsoft/cordova-background-geolocation-lt)
