### ISSUE TITLE
Premium Version: repository 'https://github.com/christocracy/cordova-background-geolocatio n.git/' not found

### ISSUE THREAD

**Issue by albatrosproject** [christocracy/cordova-plugin-background-geolocation#225]
Hello Chris,
I'm using the premium version of the plugin,I cannot  access the repository, I wonder if the link is correct, this is a print sreen.
Thank you
![backgeo](https://cloud.githubusercontent.com/assets/13589643/9088504/34776f26-3b88-11e5-9270-54393da0da59.PNG)

**Comment by christocracy** [comment]
I converted my account to github org.  Check your email for the invite to
new team.  I've confirmed that it was sent 2 days ago.

On Wednesday, August 5, 2015, albatrosproject <notifications@github.com>
wrote:

> Hello Chris,
> I'm using the premium version of the plugin,I cannot  access the
> repository, I wonder if the link is correct, this is a print sreen.
> Thank you
> [image: backgeo]
> <https://cloud.githubusercontent.com/assets/13589643/9088504/34776f26-3b88-11e5-9270-54393da0da59.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/225>
> .
>


-- 
Snet form Gmail Mobile
