### ISSUE TITLE
Would it be possible to get documentation / help with Appery.io Plugin Install? 

### ISSUE THREAD

**Issue by abigdreamer** [christocracy/cordova-plugin-background-geolocation#226]
Would it be possible to get documentation / help with Appery.io Plugin Install? 
Does this plugin work with appery.io? Can we get it installed and tested with some sort of
demo account and then activate with payment?

**Comment by christocracy** [comment]
The free version won’t work.

The Premium Version
<http://transistorsoft.github.io/cordova-background-geolocation/> can.  The
Premium version has been decoupled from Cordova and is able to run in pure
native apps.

The Premium Version can be made to work with any kind of iOS / Android
mobile framework.

On Wed, Aug 5, 2015 at 11:48 AM, Mike Tallent <notifications@github.com>
wrote:

> Would it be possible to get documentation / help with Appery.io Plugin
> Install?
> Does this plugin work with appery.io? Can we get it installed and tested
> with some sort of
> demo account and then activate with payment?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/226>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
appery.io is Cordova-based.  It seems to be a cloud-based build-service,
like PhoneGapBuild with extra features.

It depends upon their build-service, whether they’re able to compile code /
accept private frameworks.  PGB doesn’t allow this, which is totally dumb.

On Wed, Aug 5, 2015 at 12:04 PM, Chris Scott <christocracy@gmail.com> wrote:

> The free version won’t work.
>
> The Premium Version
> <http://transistorsoft.github.io/cordova-background-geolocation/> can.
> The Premium version has been decoupled from Cordova and is able to run in
> pure native apps.
>
> The Premium Version can be made to work with any kind of iOS / Android
> mobile framework.
>
> On Wed, Aug 5, 2015 at 11:48 AM, Mike Tallent <notifications@github.com>
> wrote:
>
>> Would it be possible to get documentation / help with Appery.io Plugin
>> Install?
>> Does this plugin work with appery.io? Can we get it installed and tested
>> with some sort of
>> demo account and then activate with payment?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/226>
>> .
>>
>
>
>
> --
> Chris Scott
> Transistor Software <http://www.transistorsoft.com>
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
