### ISSUE TITLE
Android POSTing previous locations with new location

### ISSUE THREAD

**Issue by doorty** [christocracy/cordova-plugin-background-geolocation#227]
I'm testing on a Samsung Galaxy S5 in Genymotion. Whenever I set the GPS to a new location (far enough outside the stationary radius), I get multiple HTTP POSTs with all the previous locations. 

1) 1st location change: 1 HTTP POST
2) 2nd location change: 2 HTTP POST
3) 3rd location change: 3 HTTP POST

Here are the results after 3 location changes:

```javascript
{
      "location": {
        "bearing": "0.0",
        "longitude": "-18.508528333333334",
        "recorded_at": "2015-08-06T21:23Z",
        "latitude": "65.99044333333333",
        "speed": "0.0",
        "accuracy": "1.0",
        "altitude": "0.0"
      },
      "test": "test",
      "auth_token": "user_secret_auth_token",
      "id": 1
    },
    {
      "location": {
        "bearing": "0.0",
        "longitude": "-18.508528333333334",
        "recorded_at": "2015-08-06T21:23Z",
        "latitude": "65.99044333333333",
        "speed": "0.0",
        "accuracy": "1.0",
        "altitude": "0.0"
      },
      "test": "test",
      "auth_token": "user_secret_auth_token",
      "id": 2
    },
    {
      "location": {
        "bearing": "0.0",
        "longitude": "-18.511039999999998",
        "recorded_at": "2015-08-06T21:24Z",
        "latitude": "65.99184833333334",
        "speed": "0.0",
        "accuracy": "1.0",
        "altitude": "0.0"
      },
      "test": "test",
      "auth_token": "user_secret_auth_token",
      "id": 3
    },
    {
      "location": {
        "bearing": "0.0",
        "longitude": "-18.508528333333334",
        "recorded_at": "2015-08-06T21:23Z",
        "latitude": "65.99044333333333",
        "speed": "0.0",
        "accuracy": "1.0",
        "altitude": "0.0"
      },
      "test": "test",
      "auth_token": "user_secret_auth_token",
      "id": 4
    },
    {
      "location": {
        "bearing": "0.0",
        "longitude": "-18.511039999999998",
        "recorded_at": "2015-08-06T21:24Z",
        "latitude": "65.99184833333334",
        "speed": "0.0",
        "accuracy": "1.0",
        "altitude": "0.0"
      },
      "test": "test",
      "auth_token": "user_secret_auth_token",
      "id": 5
    },
    {
      "location": {
        "bearing": "0.0",
        "longitude": "-18.538741666666667",
        "recorded_at": "2015-08-06T21:25Z",
        "latitude": "66.00503666666667",
        "speed": "0.0",
        "accuracy": "1.0",
        "altitude": "262.929626"
      },
      "test": "test",
      "auth_token": "user_secret_auth_token",
      "id": 6
    }

**Comment by christocracy** [comment]
Is your server receiving and responding with http 200 to those POST?

Any response other than 200 will not remove the location from SQLite.  The
plugin will continue attempting to sync all recorded locations.

Once 200 is received, location is deleted from SQLite.

On Thursday, August 6, 2015, Brent Daugherty <notifications@github.com>
wrote:

> I'm testing on a Samsung Galaxy S5 in Genymotion. Whenever I set the GPS
> to a new location (far enough outside the stationary radius), I get
> multiple HTTP POSTs with all the previous locations.
>
> 1) 1st location change: 1 HTTP POST
> 2) 2nd location change: 2 HTTP POST
> 3) 3rd location change: 3 HTTP POST
>
> Here are the results after 3 location changes:
>
> {
>       "location": {
>         "bearing": "0.0",
>         "longitude": "-18.508528333333334",
>         "recorded_at": "2015-08-06T21:23Z",
>         "latitude": "65.99044333333333",
>         "speed": "0.0",
>         "accuracy": "1.0",
>         "altitude": "0.0"
>       },
>       "test": "test",
>       "auth_token": "user_secret_auth_token",
>       "id": 1
>     },
>     {
>       "location": {
>         "bearing": "0.0",
>         "longitude": "-18.508528333333334",
>         "recorded_at": "2015-08-06T21:23Z",
>         "latitude": "65.99044333333333",
>         "speed": "0.0",
>         "accuracy": "1.0",
>         "altitude": "0.0"
>       },
>       "test": "test",
>       "auth_token": "user_secret_auth_token",
>       "id": 2
>     },
>     {
>       "location": {
>         "bearing": "0.0",
>         "longitude": "-18.511039999999998",
>         "recorded_at": "2015-08-06T21:24Z",
>         "latitude": "65.99184833333334",
>         "speed": "0.0",
>         "accuracy": "1.0",
>         "altitude": "0.0"
>       },
>       "test": "test",
>       "auth_token": "user_secret_auth_token",
>       "id": 3
>     },
>     {
>       "location": {
>         "bearing": "0.0",
>         "longitude": "-18.508528333333334",
>         "recorded_at": "2015-08-06T21:23Z",
>         "latitude": "65.99044333333333",
>         "speed": "0.0",
>         "accuracy": "1.0",
>         "altitude": "0.0"
>       },
>       "test": "test",
>       "auth_token": "user_secret_auth_token",
>       "id": 4
>     },
>     {
>       "location": {
>         "bearing": "0.0",
>         "longitude": "-18.511039999999998",
>         "recorded_at": "2015-08-06T21:24Z",
>         "latitude": "65.99184833333334",
>         "speed": "0.0",
>         "accuracy": "1.0",
>         "altitude": "0.0"
>       },
>       "test": "test",
>       "auth_token": "user_secret_auth_token",
>       "id": 5
>     },
>     {
>       "location": {
>         "bearing": "0.0",
>         "longitude": "-18.538741666666667",
>         "recorded_at": "2015-08-06T21:25Z",
>         "latitude": "66.00503666666667",
>         "speed": "0.0",
>         "accuracy": "1.0",
>         "altitude": "262.929626"
>       },
>       "test": "test",
>       "auth_token": "user_secret_auth_token",
>       "id": 6
>     }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/227>
> .
>


-- 
Snet form Gmail Mobile

**Comment by doorty** [comment]
Oh, it's returning 201.

**Comment by doorty** [comment]
For the backend, you will need to be able to accept the following in HTTP POST and return code 200 if successful. I can also include any necessary headers.
```javascript
{
      "location": {
        "bearing": "0.0",
        "longitude": "-18.511039999999998",
        "recorded_at": "2015-08-06T21:24Z",
        "latitude": "65.99184833333334",
        "speed": "0.0",
        "accuracy": "1.0",
        "altitude": "0.0"
      },
      "extra_optional_param": "test",
      "auth_token": "user_secret_auth_token"
}

**Comment by christocracy** [comment]
The plugin *should have been* written to accept a 200-ish response but it's [clearly not](https://github.com/christocracy/cordova-plugin-background-geolocation/blob/master/src/android/LocationUpdateService.java#L693).
