### ISSUE TITLE
Only listen for entry/exit stationary mode

### ISSUE THREAD

**Issue by garrettlangley** [christocracy/cordova-plugin-background-geolocation#229]
We are only interested in getting background location when a person starts/stops moving. Location while moving isnt needed.

Is there a way to do this?

Thanks

**Comment by christocracy** [comment]
This can be done with [Premium Version](http://transistorsoft.github.io/cordova-background-geolocation/) with its `#onMotionChange` listener.

```
bgGeo.onMotionChange(function(isMoving, location, taskId) {
    if (isMoving) {
        console.log('Device has just started MOVING', location);
        bgGeo.changePace(false);  // <-- force back into stationary-state after movement detected.
    } else {
        console.log('Device has just STOPPED', location);
    }
    
    bgGeo.finish(taskId);
})
```

**Comment by garrettlangley** [comment]
thanks @christocracy testing out the free but def considering the premium
