### ISSUE TITLE
[android] Set headers, content type and cookies for the server request

### ISSUE THREAD

**Issue by 23tux** [christocracy/cordova-plugin-background-geolocation#23]
Hi,

I read about the limitations of android not calling the JS callback. So, I looked into your source code and found this inside the `src/android/LocationUpdateService.java`:

  DefaultHttpClient httpClient = new DefaultHttpClient();
  HttpPost request = new HttpPost(url);

```
DefaultHttpClient httpClient = new DefaultHttpClient();
HttpPost request = new HttpPost(url);

JSONObject location = new JSONObject();
location.put("latitude", l.getLatitude());
location.put("longitude", l.getLongitude());
location.put("accuracy", l.getAccuracy());
location.put("speed", l.getSpeed());
location.put("recorded_at", l.getRecordedAt());
params.put("location", location);

StringEntity se = new StringEntity(params.toString());
request.setEntity(se);
request.setHeader("Accept", "application/json");
request.setHeader("Content-type", "application/json");
Log.d(TAG, "Posting to " + request.getURI().toString());
HttpResponse response = httpClient.execute(request);
```

Here, the request method (`POST`), the content type (`application/json`) and the params are set to fixed values / a fixed structure. It would be awesome, if that could be more flexible.

The background is, I have to deal with an (rather old and weird) existing server api, that only accepts `Content-Type: application/x-www-form-urlencoded`, the content itself is therefore not json but in the form `field[subfield1]=somevalue&field[subfield2]=foobar` and it uses cookies for authentication.

So, is it possible, to integrate such a flexibility into your project? At a glance, the features would be
- setting a custom structure/format how data is passed to the server (passing a custom structure AND a format like json or form encoded to the android api)
- set custom headers
- add cookies for authentication

**Comment by christocracy** [comment]
FYI Android has been completely refactored
- No more in-plugin HTTP -- plugin now executes your Javascript callback, just like iOS
- Significantly improved battery performance

http://christocracy.github.io/cordova-background-geolocation/
