### ISSUE TITLE
update phonegapbuild repository plugin version ?

### ISSUE THREAD

**Issue by devteamshippeo** [christocracy/cordova-plugin-background-geolocation#230]
Hi Chris,

I suppose you administrate this plugin https://build.phonegap.com/plugins/1299
 on phonegap build repository ?

If I'm right ? Could you declare the both new version 0.3.6 and 0.3.7, please ?
If not, you can close the issue...

**Comment by christocracy** [comment]
I no longer update PGB since their account policy changed requiring me to sign up to a **paid account** in order to submit new plugin versions.

However, PGB now allow you to upload your own [private plugins](http://phonegap.com/blog/2014/12/09/phonegap-build-new-features/).
