### ISSUE TITLE
WP8 Keep alive

### ISSUE THREAD

**Issue by luigi37** [christocracy/cordova-plugin-background-geolocation#233]
Hi Chris, am I right in assuming that this plugin is keeping **WP8 apps** running in background indefinitely **EVEN WITHOUT movement**? Is that correct?
Thanks
Luigi

**Comment by christocracy** [comment]
I cannot say.  I didn’t make the WP8 plugin, it was contributed to the repo
via pull-request some time ago.  I wouldn’t be surprised if its performance
was sub-par compared to Android & iOS.

On Wed, Aug 19, 2015 at 8:15 AM, luigi37 <notifications@github.com> wrote:

> Hi Chris, am I right in assuming that this plugin is keeping *WP8 apps*
> running in background indefinitely *EVEN WITHOUT movement*? Is that
> correct?
> Thanks
> Luigi
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/233>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by luigi37** [comment]
Thanks Chris. After some tests I can confirm that IF THERE IS NO MOVEMENT:
1- The App DOES not get killed (meaning when I reopen it's the same I left, not a new launch)
2- The App gets frozen and no javascript task gets executed meantime (not sure about your callback function but I assume not, as there is no position change, BTW I've put zero at accuracy).
3- Background sound and vibration are NOT played (not sure if this is due to the lack of javascript execution or on the need of enabling a background sound mode like in iOS).
Just for everybody info...
