### ISSUE TITLE
Excessively slow on map markers rendering

### ISSUE THREAD

**Issue by e4r** [christocracy/cordova-plugin-background-geolocation#236]
Hello,

thanks for this fantastic plugin, it's definitely what I was looking for! However, I've experienced excessive slowness when I press "Stop" on the sample app, when the markers are rendered, the map is almost stuck.
This happens with few points and become worse with more points. I've tried on 3 mobiles: low, medium and medium-high profiled smartphones, but the issue appears in any case, with tiny differences.

Is it supposed to be this slow? Has anybody experienced this issue as well?

**Comment by christocracy** [comment]
What platform?

Have you tried the new SampleApp (Ionic based)?

https://github.com/transistorsoft/cordova-background-geolocation-SampleApp

**Comment by e4r** [comment]
Ok I tried that, it seems to locate me, but when I switch off the geolocation, it doesn't seem to have saved  any position, and consequently doesn't render any marker.

This happens both on iOS and Android. 

On iOS only I don't see the icon which generally means that you're being geolocated. Am I missing some plugin?
However, I can't replicate the above mentioned problem.

**Comment by christocracy** [comment]
There is no other required plugin.

What do you mean "when I switch OFF geolocation"??

On Friday, August 28, 2015, Leonardo Maria Miliacca <
notifications@github.com> wrote:

> Ok I tried that, it seems to locate me, but when I switch off the
> geolocation, it doesn't seem to have saved any position, and consequently
> doesn't render any marker.
>
> This happens both on iOS and Android.
>
> On iOS only I don't see the icon which generally means that you're being
> geolocated. Am I missing some plugin?
> However, I can't replicate the above mentioned problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/236#issuecomment-135665016>
> .
>


-- 
Snet form Gmail Mobile
