### ISSUE TITLE
Latest iOS premium version "Always" permission for Location is not available

### ISSUE THREAD

**Issue by KimberleeDArmstrong** [christocracy/cordova-plugin-background-geolocation#237]
I have created several app using this plugin and it has always worked great.  This is a great plugin and thank you.  Yesterday I created a new app which is a clone of an existing app.  The only difference between the 2 apps is the newest one has the newest version of Cordova and the newest version of this plugin.  The "Always" permission for Location is not on the newest app but is on its older clone.  The newer one is also not collecting coordinates when the app is in the background and the screen is off like the older one.

**Comment by christocracy** [comment]
Destroy platform.  Remove plugin, reinstall plugin.  Re add platform.
Rebuild

On Thursday, August 27, 2015, KimberleeDArmstrong <notifications@github.com>
wrote:

> I have created several app using this plugin and it has always worked
> great. This is a great plugin and thank you. Yesterday I created a new app
> which is a clone of an existing app. The only difference between the 2 apps
> is the newest one has the newest version of Cordova and the newest version
> of this plugin. The "Always" permission for Location is not on the newest
> app but is on its older clone. The newer one is also not collecting
> coordinates when the app is in the background and the screen is off like
> the older one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237>
> .
>


-- 
Snet form Gmail Mobile

**Comment by KimberleeDArmstrong** [comment]
I did that and I am still seeing the same thing?

Kimberlee Armstrong
Software Engineer
dataVoice International, Inc.
972-390-8808 X144
www.datavoiceint.com
On 08/27/2015 12:26 PM, Chris Scott wrote:
> Destroy platform. Remove plugin, reinstall plugin. Re add platform.
> Rebuild
>
> On Thursday, August 27, 2015, KimberleeDArmstrong 
> <notifications@github.com>
> wrote:
>
> > I have created several app using this plugin and it has always worked
> > great. This is a great plugin and thank you. Yesterday I created a 
> new app
> > which is a clone of an existing app. The only difference between the 
> 2 apps
> > is the newest one has the newest version of Cordova and the newest 
> version
> > of this plugin. The "Always" permission for Location is not on the 
> newest
> > app but is on its older clone. The newer one is also not collecting
> > coordinates when the app is in the background and the screen is off like
> > the older one.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237>
> > .
> >
>
>
> -- 
> Snet form Gmail Mobile
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237#issuecomment-135499833>.
>



Confidentiality Notice | This email and any included attachments may be privileged, confidential and/or otherwise protected from disclosure.  Access to this email by anyone other than the intended recipient is unauthorized.  If you believe you have received this email in error, please contact the sender immediately and delete all copies.  If you are not the intended recipient, you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by KimberleeDArmstrong** [comment]
Wait sorry, I did it in the wrong order.  Trying again.

Kimberlee Armstrong
Software Engineer
dataVoice International, Inc.
972-390-8808 X144
www.datavoiceint.com
On 08/27/2015 12:26 PM, Chris Scott wrote:
> Destroy platform. Remove plugin, reinstall plugin. Re add platform.
> Rebuild
>
> On Thursday, August 27, 2015, KimberleeDArmstrong 
> <notifications@github.com>
> wrote:
>
> > I have created several app using this plugin and it has always worked
> > great. This is a great plugin and thank you. Yesterday I created a 
> new app
> > which is a clone of an existing app. The only difference between the 
> 2 apps
> > is the newest one has the newest version of Cordova and the newest 
> version
> > of this plugin. The "Always" permission for Location is not on the 
> newest
> > app but is on its older clone. The newer one is also not collecting
> > coordinates when the app is in the background and the screen is off like
> > the older one.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237>
> > .
> >
>
>
> -- 
> Snet form Gmail Mobile
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237#issuecomment-135499833>.
>



Confidentiality Notice | This email and any included attachments may be privileged, confidential and/or otherwise protected from disclosure.  Access to this email by anyone other than the intended recipient is unauthorized.  If you believe you have received this email in error, please contact the sender immediately and delete all copies.  If you are not the intended recipient, you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by KimberleeDArmstrong** [comment]
Ok I did it in the right order. Still not seeing the "Always".  Any ideas?

Cordova-ios version 3.9.1
BackgroundGeolocation version 0.2.0

Kimberlee Armstrong
Software Engineer
dataVoice International, Inc.
972-390-8808 X144
www.datavoiceint.com
On 08/27/2015 03:00 PM, Kimberlee wrote:
> Wait sorry, I did it in the wrong order.  Trying again.
>
> Kimberlee Armstrong
> Software Engineer
> dataVoice International, Inc.
> 972-390-8808 X144
> www.datavoiceint.com
> On 08/27/2015 12:26 PM, Chris Scott wrote:
>> Destroy platform. Remove plugin, reinstall plugin. Re add platform.
>> Rebuild
>>
>> On Thursday, August 27, 2015, KimberleeDArmstrong 
>> <notifications@github.com>
>> wrote:
>>
>> > I have created several app using this plugin and it has always worked
>> > great. This is a great plugin and thank you. Yesterday I created a 
>> new app
>> > which is a clone of an existing app. The only difference between 
>> the 2 apps
>> > is the newest one has the newest version of Cordova and the newest 
>> version
>> > of this plugin. The "Always" permission for Location is not on the 
>> newest
>> > app but is on its older clone. The newer one is also not collecting
>> > coordinates when the app is in the background and the screen is off 
>> like
>> > the older one.
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > 
>> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237>
>> > .
>> >
>>
>>
>> -- 
>> Snet form Gmail Mobile
>>
>> —
>> Reply to this email directly or view it on GitHub 
>> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237#issuecomment-135499833>.
>>
>



Confidentiality Notice | This email and any included attachments may be privileged, confidential and/or otherwise protected from disclosure.  Access to this email by anyone other than the intended recipient is unauthorized.  If you believe you have received this email in error, please contact the sender immediately and delete all copies.  If you are not the intended recipient, you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by christocracy** [comment]
That's a really old version of plugin.  Are you installing that from GitHub?

On Thursday, August 27, 2015, KimberleeDArmstrong <notifications@github.com>
wrote:

> Ok I did it in the right order. Still not seeing the "Always". Any ideas?
>
> Cordova-ios version 3.9.1
> BackgroundGeolocation version 0.2.0
>
> Kimberlee Armstrong
> Software Engineer
> dataVoice International, Inc.
> 972-390-8808 X144
> www.datavoiceint.com
> On 08/27/2015 03:00 PM, Kimberlee wrote:
> > Wait sorry, I did it in the wrong order. Trying again.
> >
> > Kimberlee Armstrong
> > Software Engineer
> > dataVoice International, Inc.
> > 972-390-8808 X144
> > www.datavoiceint.com
> > On 08/27/2015 12:26 PM, Chris Scott wrote:
> >> Destroy platform. Remove plugin, reinstall plugin. Re add platform.
> >> Rebuild
> >>
> >> On Thursday, August 27, 2015, KimberleeDArmstrong
> >> <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> >> wrote:
> >>
> >> > I have created several app using this plugin and it has always worked
> >> > great. This is a great plugin and thank you. Yesterday I created a
> >> new app
> >> > which is a clone of an existing app. The only difference between
> >> the 2 apps
> >> > is the newest one has the newest version of Cordova and the newest
> >> version
> >> > of this plugin. The "Always" permission for Location is not on the
> >> newest
> >> > app but is on its older clone. The newer one is also not collecting
> >> > coordinates when the app is in the background and the screen is off
> >> like
> >> > the older one.
> >> >
> >> > —
> >> > Reply to this email directly or view it on GitHub
> >> >
> >> <
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237
> >
> >> > .
> >> >
> >>
> >>
> >> --
> >> Snet form Gmail Mobile
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237#issuecomment-135499833
> >.
> >>
> >
>
>
>
> Confidentiality Notice | This email and any included attachments may be
> privileged, confidential and/or otherwise protected from disclosure. Access
> to this email by anyone other than the intended recipient is unauthorized.
> If you believe you have received this email in error, please contact the
> sender immediately and delete all copies. If you are not the intended
> recipient, you are notified that disclosing, copying, distributing or
> taking any action in reliance on the contents of this information is
> strictly prohibited.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237#issuecomment-135537801>
> .
>


-- 
Snet form Gmail Mobile

**Comment by KimberleeDArmstrong** [comment]
Yes.

Kimberlee Armstrong
Software Engineer
dataVoice International, Inc.
972-390-8808 X144
www.datavoiceint.com
On 08/27/2015 03:06 PM, Chris Scott wrote:
> That's a really old version of plugin. Are you installing that from 
> GitHub?
>
> On Thursday, August 27, 2015, KimberleeDArmstrong 
> <notifications@github.com>
> wrote:
>
> > Ok I did it in the right order. Still not seeing the "Always". Any 
> ideas?
> >
> > Cordova-ios version 3.9.1
> > BackgroundGeolocation version 0.2.0
> >
> > Kimberlee Armstrong
> > Software Engineer
> > dataVoice International, Inc.
> > 972-390-8808 X144
> > www.datavoiceint.com
> > On 08/27/2015 03:00 PM, Kimberlee wrote:
> > > Wait sorry, I did it in the wrong order. Trying again.
> > >
> > > Kimberlee Armstrong
> > > Software Engineer
> > > dataVoice International, Inc.
> > > 972-390-8808 X144
> > > www.datavoiceint.com
> > > On 08/27/2015 12:26 PM, Chris Scott wrote:
> > >> Destroy platform. Remove plugin, reinstall plugin. Re add platform.
> > >> Rebuild
> > >>
> > >> On Thursday, August 27, 2015, KimberleeDArmstrong
> > >> <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > >> wrote:
> > >>
> > >> > I have created several app using this plugin and it has always 
> worked
> > >> > great. This is a great plugin and thank you. Yesterday I created a
> > >> new app
> > >> > which is a clone of an existing app. The only difference between
> > >> the 2 apps
> > >> > is the newest one has the newest version of Cordova and the newest
> > >> version
> > >> > of this plugin. The "Always" permission for Location is not on the
> > >> newest
> > >> > app but is on its older clone. The newer one is also not collecting
> > >> > coordinates when the app is in the background and the screen is off
> > >> like
> > >> > the older one.
> > >> >
> > >> > —
> > >> > Reply to this email directly or view it on GitHub
> > >> >
> > >> <
> > 
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237
> > >
> > >> > .
> > >> >
> > >>
> > >>
> > >> --
> > >> Snet form Gmail Mobile
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <
> > 
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237#issuecomment-135499833
> > >.
> > >>
> > >
> >
> >
> >
> > Confidentiality Notice | This email and any included attachments may be
> > privileged, confidential and/or otherwise protected from disclosure. 
> Access
> > to this email by anyone other than the intended recipient is 
> unauthorized.
> > If you believe you have received this email in error, please contact the
> > sender immediately and delete all copies. If you are not the intended
> > recipient, you are notified that disclosing, copying, distributing or
> > taking any action in reliance on the contents of this information is
> > strictly prohibited.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237#issuecomment-135537801>
> > .
> >
>
>
> -- 
> Snet form Gmail Mobile
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237#issuecomment-135538012>.
>



Confidentiality Notice | This email and any included attachments may be privileged, confidential and/or otherwise protected from disclosure.  Access to this email by anyone other than the intended recipient is unauthorized.  If you believe you have received this email in error, please contact the sender immediately and delete all copies.  If you are not the intended recipient, you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by KimberleeDArmstrong** [comment]
Ah.  no.  I am installing from transistorsoft.  Trying again.

Kimberlee Armstrong
Software Engineer
dataVoice International, Inc.
972-390-8808 X144
www.datavoiceint.com
On 08/27/2015 03:06 PM, Chris Scott wrote:
> That's a really old version of plugin. Are you installing that from 
> GitHub?
>
> On Thursday, August 27, 2015, KimberleeDArmstrong 
> <notifications@github.com>
> wrote:
>
> > Ok I did it in the right order. Still not seeing the "Always". Any 
> ideas?
> >
> > Cordova-ios version 3.9.1
> > BackgroundGeolocation version 0.2.0
> >
> > Kimberlee Armstrong
> > Software Engineer
> > dataVoice International, Inc.
> > 972-390-8808 X144
> > www.datavoiceint.com
> > On 08/27/2015 03:00 PM, Kimberlee wrote:
> > > Wait sorry, I did it in the wrong order. Trying again.
> > >
> > > Kimberlee Armstrong
> > > Software Engineer
> > > dataVoice International, Inc.
> > > 972-390-8808 X144
> > > www.datavoiceint.com
> > > On 08/27/2015 12:26 PM, Chris Scott wrote:
> > >> Destroy platform. Remove plugin, reinstall plugin. Re add platform.
> > >> Rebuild
> > >>
> > >> On Thursday, August 27, 2015, KimberleeDArmstrong
> > >> <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > >> wrote:
> > >>
> > >> > I have created several app using this plugin and it has always 
> worked
> > >> > great. This is a great plugin and thank you. Yesterday I created a
> > >> new app
> > >> > which is a clone of an existing app. The only difference between
> > >> the 2 apps
> > >> > is the newest one has the newest version of Cordova and the newest
> > >> version
> > >> > of this plugin. The "Always" permission for Location is not on the
> > >> newest
> > >> > app but is on its older clone. The newer one is also not collecting
> > >> > coordinates when the app is in the background and the screen is off
> > >> like
> > >> > the older one.
> > >> >
> > >> > —
> > >> > Reply to this email directly or view it on GitHub
> > >> >
> > >> <
> > 
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237
> > >
> > >> > .
> > >> >
> > >>
> > >>
> > >> --
> > >> Snet form Gmail Mobile
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <
> > 
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237#issuecomment-135499833
> > >.
> > >>
> > >
> >
> >
> >
> > Confidentiality Notice | This email and any included attachments may be
> > privileged, confidential and/or otherwise protected from disclosure. 
> Access
> > to this email by anyone other than the intended recipient is 
> unauthorized.
> > If you believe you have received this email in error, please contact the
> > sender immediately and delete all copies. If you are not the intended
> > recipient, you are notified that disclosing, copying, distributing or
> > taking any action in reliance on the contents of this information is
> > strictly prohibited.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237#issuecomment-135537801>
> > .
> >
>
>
> -- 
> Snet form Gmail Mobile
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237#issuecomment-135538012>.
>



Confidentiality Notice | This email and any included attachments may be privileged, confidential and/or otherwise protected from disclosure.  Access to this email by anyone other than the intended recipient is unauthorized.  If you believe you have received this email in error, please contact the sender immediately and delete all copies.  If you are not the intended recipient, you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by christocracy** [comment]
I recently released the Premium iOS version free.  Give it a try.

Here’s a link to the new SampleApp.  Follow the directions
https://github.com/transistorsoft/cordova-background-geolocation-SampleApp




On Thu, Aug 27, 2015 at 4:08 PM, KimberleeDArmstrong <
notifications@github.com> wrote:

> Ah. no. I am installing from transistorsoft. Trying again.
>
>
> Kimberlee Armstrong
> Software Engineer
> dataVoice International, Inc.
> 972-390-8808 X144
> www.datavoiceint.com
> On 08/27/2015 03:06 PM, Chris Scott wrote:
> > That's a really old version of plugin. Are you installing that from
> > GitHub?
> >
> > On Thursday, August 27, 2015, KimberleeDArmstrong
> > <notifications@github.com>
> > wrote:
> >
> > > Ok I did it in the right order. Still not seeing the "Always". Any
> > ideas?
> > >
> > > Cordova-ios version 3.9.1
> > > BackgroundGeolocation version 0.2.0
> > >
> > > Kimberlee Armstrong
> > > Software Engineer
> > > dataVoice International, Inc.
> > > 972-390-8808 X144
> > > www.datavoiceint.com
> > > On 08/27/2015 03:00 PM, Kimberlee wrote:
> > > > Wait sorry, I did it in the wrong order. Trying again.
> > > >
> > > > Kimberlee Armstrong
> > > > Software Engineer
> > > > dataVoice International, Inc.
> > > > 972-390-8808 X144
> > > > www.datavoiceint.com
> > > > On 08/27/2015 12:26 PM, Chris Scott wrote:
> > > >> Destroy platform. Remove plugin, reinstall plugin. Re add platform.
> > > >> Rebuild
> > > >>
> > > >> On Thursday, August 27, 2015, KimberleeDArmstrong
> > > >> <notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > > >> wrote:
> > > >>
> > > >> > I have created several app using this plugin and it has always
> > worked
> > > >> > great. This is a great plugin and thank you. Yesterday I created a
> > > >> new app
> > > >> > which is a clone of an existing app. The only difference between
> > > >> the 2 apps
> > > >> > is the newest one has the newest version of Cordova and the newest
> > > >> version
> > > >> > of this plugin. The "Always" permission for Location is not on the
> > > >> newest
> > > >> > app but is on its older clone. The newer one is also not
> collecting
> > > >> > coordinates when the app is in the background and the screen is
> off
> > > >> like
> > > >> > the older one.
> > > >> >
> > > >> > —
> > > >> > Reply to this email directly or view it on GitHub
> > > >> >
> > > >> <
> > >
> >
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237
> > > >
> > > >> > .
> > > >> >
> > > >>
> > > >>
> > > >> --
> > > >> Snet form Gmail Mobile
> > > >>
> > > >> —
> > > >> Reply to this email directly or view it on GitHub
> > > >> <
> > >
> >
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237#issuecomment-135499833
> > > >.
> > > >>
> > > >
> > >
> > >
> > >
> > > Confidentiality Notice | This email and any included attachments may be
> > > privileged, confidential and/or otherwise protected from disclosure.
> > Access
> > > to this email by anyone other than the intended recipient is
> > unauthorized.
> > > If you believe you have received this email in error, please contact
> the
> > > sender immediately and delete all copies. If you are not the intended
> > > recipient, you are notified that disclosing, copying, distributing or
> > > taking any action in reliance on the contents of this information is
> > > strictly prohibited.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > >
> > <
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237#issuecomment-135537801
> >
> > > .
> > >
> >
> >
> > --
> > Snet form Gmail Mobile
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237#issuecomment-135538012
> >.
> >
>
>
>
> Confidentiality Notice | This email and any included attachments may be
> privileged, confidential and/or otherwise protected from disclosure. Access
> to this email by anyone other than the intended recipient is unauthorized.
> If you believe you have received this email in error, please contact the
> sender immediately and delete all copies. If you are not the intended
> recipient, you are notified that disclosing, copying, distributing or
> taking any action in reliance on the contents of this information is
> strictly prohibited.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237#issuecomment-135538540>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
Wait, this is a question about the new Free **Premium iOS** version?

Post an issue there https://github.com/transistorsoft/cordova-background-geolocation-lt

**Comment by KimberleeDArmstrong** [comment]
Thanks!

Kimberlee Armstrong
Software Engineer
dataVoice International, Inc.
972-390-8808 X144
www.datavoiceint.com
On 08/27/2015 07:59 PM, Chris Scott wrote:
> I recently released the Premium iOS version free. Give it a try.
>
> Here’s a link to the new SampleApp. Follow the directions
> https://github.com/transistorsoft/cordova-background-geolocation-SampleApp
>
>
>
>
> On Thu, Aug 27, 2015 at 4:08 PM, KimberleeDArmstrong <
> notifications@github.com> wrote:
>
> > Ah. no. I am installing from transistorsoft. Trying again.
> >
> >
> > Kimberlee Armstrong
> > Software Engineer
> > dataVoice International, Inc.
> > 972-390-8808 X144
> > www.datavoiceint.com
> > On 08/27/2015 03:06 PM, Chris Scott wrote:
> > > That's a really old version of plugin. Are you installing that from
> > > GitHub?
> > >
> > > On Thursday, August 27, 2015, KimberleeDArmstrong
> > > <notifications@github.com>
> > > wrote:
> > >
> > > > Ok I did it in the right order. Still not seeing the "Always". Any
> > > ideas?
> > > >
> > > > Cordova-ios version 3.9.1
> > > > BackgroundGeolocation version 0.2.0
> > > >
> > > > Kimberlee Armstrong
> > > > Software Engineer
> > > > dataVoice International, Inc.
> > > > 972-390-8808 X144
> > > > www.datavoiceint.com
> > > > On 08/27/2015 03:00 PM, Kimberlee wrote:
> > > > > Wait sorry, I did it in the wrong order. Trying again.
> > > > >
> > > > > Kimberlee Armstrong
> > > > > Software Engineer
> > > > > dataVoice International, Inc.
> > > > > 972-390-8808 X144
> > > > > www.datavoiceint.com
> > > > > On 08/27/2015 12:26 PM, Chris Scott wrote:
> > > > >> Destroy platform. Remove plugin, reinstall plugin. Re add 
> platform.
> > > > >> Rebuild
> > > > >>
> > > > >> On Thursday, August 27, 2015, KimberleeDArmstrong
> > > > >> <notifications@github.com
> > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > > > >> wrote:
> > > > >>
> > > > >> > I have created several app using this plugin and it has always
> > > worked
> > > > >> > great. This is a great plugin and thank you. Yesterday I 
> created a
> > > > >> new app
> > > > >> > which is a clone of an existing app. The only difference 
> between
> > > > >> the 2 apps
> > > > >> > is the newest one has the newest version of Cordova and the 
> newest
> > > > >> version
> > > > >> > of this plugin. The "Always" permission for Location is not 
> on the
> > > > >> newest
> > > > >> > app but is on its older clone. The newer one is also not
> > collecting
> > > > >> > coordinates when the app is in the background and the screen is
> > off
> > > > >> like
> > > > >> > the older one.
> > > > >> >
> > > > >> > —
> > > > >> > Reply to this email directly or view it on GitHub
> > > > >> >
> > > > >> <
> > > >
> > >
> > 
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237
> > > > >
> > > > >> > .
> > > > >> >
> > > > >>
> > > > >>
> > > > >> --
> > > > >> Snet form Gmail Mobile
> > > > >>
> > > > >> —
> > > > >> Reply to this email directly or view it on GitHub
> > > > >> <
> > > >
> > >
> > 
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237#issuecomment-135499833
> > > > >.
> > > > >>
> > > > >
> > > >
> > > >
> > > >
> > > > Confidentiality Notice | This email and any included attachments 
> may be
> > > > privileged, confidential and/or otherwise protected from disclosure.
> > > Access
> > > > to this email by anyone other than the intended recipient is
> > > unauthorized.
> > > > If you believe you have received this email in error, please contact
> > the
> > > > sender immediately and delete all copies. If you are not the 
> intended
> > > > recipient, you are notified that disclosing, copying, 
> distributing or
> > > > taking any action in reliance on the contents of this information is
> > > > strictly prohibited.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > >
> > > <
> > 
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237#issuecomment-135537801
> > >
> > > > .
> > > >
> > >
> > >
> > > --
> > > Snet form Gmail Mobile
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237#issuecomment-135538012
> > >.
> > >
> >
> >
> >
> > Confidentiality Notice | This email and any included attachments may be
> > privileged, confidential and/or otherwise protected from disclosure. 
> Access
> > to this email by anyone other than the intended recipient is 
> unauthorized.
> > If you believe you have received this email in error, please contact the
> > sender immediately and delete all copies. If you are not the intended
> > recipient, you are notified that disclosing, copying, distributing or
> > taking any action in reliance on the contents of this information is
> > strictly prohibited.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237#issuecomment-135538540>
> > .
> >
>
>
>
> -- 
> Chris Scott
> Transistor Software <http://www.transistorsoft.com>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/237#issuecomment-135594788>.
>



Confidentiality Notice | This email and any included attachments may be privileged, confidential and/or otherwise protected from disclosure.  Access to this email by anyone other than the intended recipient is unauthorized.  If you believe you have received this email in error, please contact the sender immediately and delete all copies.  If you are not the intended recipient, you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.
