### ISSUE TITLE
Android searching geolocation icon always active

### ISSUE THREAD

**Issue by socrates3** [christocracy/cordova-plugin-background-geolocation#241]
The icon that appears on android (v5.1) when an app is trying to get the geolocation is always present when this plug in is started, even after the callback is called an finish() function is called

My android location system preferences are set to high accuracy (GPS + network)

Any idea on how to solve the issue?

**Comment by christocracy** [comment]
This project has been deprecated and move here.

https://github.com/transistorsoft/cordova-background-geolocation-lt

On Saturday, October 3, 2015, socrates3 <notifications@github.com> wrote:

> The icon that appears on android (v5.1) when an app is trying to get the
> geolocation is always present when this plug in is started, even after the
> callback is called an finish() function is called
>
> My android location system preferences are set to high accuracy (GPS +
> network)
>
> Any idea on how to solve the issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/241>
> .
>


-- 
Snet form Gmail Mobile

**Comment by socrates3** [comment]
I see, but how can I try if this issue appears also in the new premium version?
