### ISSUE TITLE
Factory Reset Geolocation is not working

### ISSUE THREAD

**Issue by freezyfridge** [christocracy/cordova-plugin-background-geolocation#244]
Hi, I using the SampleApp to test on the android. I faced an issue, where i have factory reset the android s5, open the sampleApp app, click locate and start the tracking, the tracking is not working(android setting is all in default mode, without google account).

Then i added google account to the android, the app is working. May i know why? Do users requires to setup google account on the phone then this background geolocation will only works?

**Comment by christocracy** [comment]
Plugin uses google play services location API.
