### ISSUE TITLE
Class not found error

### ISSUE THREAD

**Issue by mabdullah4014** [christocracy/cordova-plugin-background-geolocation#246]
Hello. I have installed the plugin but when i start my app I get into the failure call back of BackgroundGeolocation which is 

var failureFn = function(error) {
      console.log('BackgroundGeoLocation error');
    }

and the error variable contains "Class not found".. I dont know what this error is all about. I am using cordova 5.2.0 and testing on lollipop(Android API 22). Any help would be much appreciated.

**Comment by christocracy** [comment]
Show me the logs from adb logcat.

Is this your first time installing?  See README for installation
instructions related to Android.  There's a screenshot of the Android
package manager showing packages you need to to enable

On Wednesday, January 27, 2016, mabdullah4014 notifications@github.com
wrote:

> Hello. I have installed the plugin but when i start my app I get into the
> failure call back of BackgroundGeolocation which is
> 
> var failureFn = function(error) {
> console.log('BackgroundGeoLocation error');
> }
> 
> and the error variable contains "Class not found".. I dont know what this
> error is all about. I am using cordova 5.2.0 and testing on
> lollipop(Android API 22). Any help would be much appreciated.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/246
> .

## 

Snet form Gmail Mobile

**Comment by kingalione** [comment]
+1. Same behaviour here. On iOS everything works great but not on android

**Comment by christocracy** [comment]
This plugin has been deprecated for over a year.  It's no longer supported.  Plugin has moved [here](https://github.com/transistorsoft/cordova-background-geolocation-lt).

**Comment by balapkm** [comment]
i download below thing only it's not working android 5 (lolilop)
https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/1.6.2 

pls help me

**Comment by christocracy** [comment]
You are confused at commenting upon the wrong repo.  See the README and redirect to the "-lt" or "lite version" repo.

https://github.com/christocracy/cordova-plugin-background-geolocation

**Comment by christocracy** [comment]
Also, it makes me **angry** when people spam multiple issues about the same problem.  Do NOT spam the issues in your quest for help.  It will **hurt** your chances of support.
