### ISSUE TITLE
Not posting params

### ISSUE THREAD

**Issue by devmw** [christocracy/cordova-plugin-background-geolocation#247]
Hi!

Im using your 3.5 free version for both iOS and Android.

iOS works fine. Android sends a request to the url, but none of the parameters is send. Not even the location information.

Has something changed in Android?

If I inject a parameter in the url, the parameter is sent as a get. But I cant get the location anyway.

Any ideas? I used your demo code.

Kind regards,
Michael

**Comment by christocracy** [comment]
This plugin is deprecated for a year now and is no longer supported.  It has been completely rebuilt and moved to a new repo.  It is vastly improved, particularly Android.

See the README
https://github.com/christocracy/cordova-plugin-background-geolocation

However, only iOS is free now.  Android requires a paid license.
http://shop.transistorsoft.com/pages/cordova-background-geolocation-premium
