### ISSUE TITLE
background geolocation not working in kitkat 4.4.2

### ISSUE THREAD

**Issue by balapkm** [christocracy/cordova-plugin-background-geolocation#250]
Hi ,
I'm working with device tracking application..
so i use below sample app

**https://github.com/transistorsoft/cordova-background-geolocation-SampleApp**

it's working fine with android kitkat 4.4.4..same app not working in kitkat 4.4.2 .it's thorw error code as **1**

![screenshot_2016-05-30-11-09-01](https://cloud.githubusercontent.com/assets/5486829/15640470/f2135528-2655-11e6-93ad-cd99f9dd0321.jpg)
![screenshot_2016-05-30-11-09-10](https://cloud.githubusercontent.com/assets/5486829/15640471/f23108e8-2655-11e6-98dc-3689119531e7.jpg)

**Comment by christocracy** [comment]
You are commenting upon the wrong repo.  This repo is obsolete, see README for message and redirect.

https://github.com/christocracy/cordova-plugin-background-geolocation
