### ISSUE TITLE
Unable to start service

### ISSUE THREAD

**Issue by josegamboa** [christocracy/cordova-plugin-background-geolocation#251]
I am having this error on Android 6, it is working fine on Android 4 and 5.

Unable to start service com.transistorsoft.locationmanager.BackgroundGeolocationService@9a6f6dc with Intent { cmp=com.mobilementor.FCNSWUAT/com.transistorsoft.locationmanager.BackgroundGeolocationService (has extras) }: java.lang.SecurityException: Client must have ACCESS_FINE_LOCATION permission to request PRIORITY_HIGH_ACCURACY locations.

Manifest config:

```
 <uses-sdk android:minSdkVersion="14" android:targetSdkVersion="23" />
    <uses-permission android:name="android.permission.GET_TASKS" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="com.google.android.gms.permission.ACTIVITY_RECOGNITION" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
</manifest>
```

Thanks...

**Comment by albertmatyi** [comment]
As issue #245  states, this repository is no longer active. 

The new and improved version can be found [here](https://github.com/transistorsoft/cordova-background-geolocation-lt)

Cheers,
m

**Comment by christocracy** [comment]
Please see README for link to updated project.
