### ISSUE TITLE
IOS tracking with wifi turned off

### ISSUE THREAD

**Issue by sdkumar25** [christocracy/cordova-plugin-background-geolocation#252]
Hi chris,

We bought the plugin and Its working great but having some issues in IOS and we need your help on this.

With wifi turned off and turning on cellular data the tracking was not happening properly and we are getting notification that device is still on stationary region and aggressive tracking never engaged and we travelled more than 1 km but still device shows that it is in stationary region

Please help us on this to overcome this issue because we are tracking the drivers who carrying the loads so for us tracking is important one and we can't force the driver to turn on wifi

**Comment by christocracy** [comment]
This repo is dead
