### ISSUE TITLE
Permission Problem

### ISSUE THREAD

**Issue by Georadius** [christocracy/cordova-plugin-background-geolocation#253]
We have properly implemented the paid version of your cordova plugin.but we have a major issue specially with xiomi phones is that we need to enable the location and storage permission manually in the phones rather than automatically.

Kindly suggest me any solution for that phone or any updation required in the plugin for automatically update the location in these phones.

**Comment by christocracy** [comment]
This repo is obsolete.  Look at the readme.
https://github.com/christocracy/cordova-plugin-background-geolocation

**Comment by christocracy** [comment]
The premium repo is here:
https://github.com/transistorsoft/cordova-background-geolocation/issues
