### ISSUE TITLE
Geloaction didnt get latitude longitude after enabling location on android device

### ISSUE THREAD

**Issue by LoveenaSharma** [christocracy/cordova-plugin-background-geolocation#254]
My concern is that if device hasn't GPS on when app is installed but after a pop appears using this plugin cordova.plugins.locationAccuracy to automatically on your GPS.Now GPS is on but still I dont get Latitude Longitude.Gelocation plugin is installed and working well if GPS is on already at the time of app launching.

**Comment by christocracy** [comment]
This repo is no longer supported.  See the [README](https://github.com/christocracy/cordova-plugin-background-geolocation).  This plugin [has moved here](https://github.com/transistorsoft/cordova-background-geolocation-lt)
