### ISSUE TITLE
httpHeaders

### ISSUE THREAD

**Issue by kent2011981** [christocracy/cordova-plugin-background-geolocation#255]
## Your Environment

Plugin version: 2.2.5
Plugin configuration options:     
    desiredAccuracy: 0,
    stationaryRadius: 15,
    distanceFilter: 5,
    url: 'http://pushmobile.ru/ohranasave/blocation.php',
    httpHeaders: {'deviceID' : device.uuid, 'status' : 1},
    maxLocations: 1000,
    locationProvider: backgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,
    interval: 10000,
    fastestInterval: 100,
    activitiesInterval: 10000,
    notificationTitle: 'Сэйв',
    notificationText: 'Фоновый трекинг включен',
    notificationIconColor: '#FEDD1E',
    notificationIconLarge: 'mappointer_large',
    notificationIconSmall: 'mappointer_small',

## Context
Help me, plz!
Plugin does not sends to my php server these 'httpHeaders'

## There is my php request receiver code: 

   require_once("config.php");
   header('Access-Control-Allow-Origin: *');
   $data = file_get_contents('php://input');
   mysql_query("INSERT INTO os_test (`postdata`) VALUES ('$data')");

## What comes to the server in the database

![screenshot_287](https://cloud.githubusercontent.com/assets/18715452/22779063/2d1cd3ee-eef4-11e6-86b2-723c500a8935.png)

**Comment by christocracy** [comment]
Showing me a screenshot of your JSON from database is irrelevant evidence of missing http headers.

Why don't you look at the raw HTTP request in your server logs??

**Comment by christocracy** [comment]
And btw, this repo is **deprecated**.  It moved [here](https://github.com/transistorsoft/cordova-background-geolocation-lt)
