### ISSUE TITLE
Problem with UUID

### ISSUE THREAD

**Issue by lmchacon** [christocracy/cordova-plugin-background-geolocation#256]
Hello:

We are testing your PlugIn and everything is working fine except that we get a new UUID with every location update. 
None of those have any relation with the actual phone UUID.
They seem to be random generated.
Is this because it is the free version or we need to do something else on the phone or on the configuration?

Best regards,

Luis M. Chacón M.

**Comment by christocracy** [comment]
You're posting to the wrong repo (see the [README](https://github.com/christocracy/cordova-plugin-background-geolocation)).

You're probably looking for [cordova-background-geolocation-lt](https://github.com/transistorsoft/cordova-background-geolocation-lt)
