### ISSUE TITLE
App Crashes when comes to first line 

### ISSUE THREAD

**Issue by testvicoast** [christocracy/cordova-plugin-background-geolocation#257]
App Crashes when comes to 
 var bgGeo = window.BackgroundGeolocation;

Plz find the log :

d]
04-10 12:40:35.582 13581 13650 D TSLocationManager:   Gä¦n+Å  Settings loaded
04-10 12:40:35.596  2772  2839 D Kontrol:: CheckDeleteService: com.google.androi
d.googlequicksearchbox
04-10 12:40:35.602  2772  9519 D KONTROL : Launcher Servis +ºal-¦+ƒ-¦yor...
04-10 12:40:35.608  2772  9519 D Kontrol:: LauncherServicecom.google.android.goo
glequicksearchbox
04-10 12:40:35.721 13581 13650 D TSLocationManager: [c.t.l.data.sqlite.a onCreat
e] CREATE TABLE IF NOT EXISTS locations (id INTEGER PRIMARY KEY AUTOINCREMENT, u
uid TEXT NOT NULL DEFAULT '', timestamp TEXT, json TEXT, locked BOOLEAN);
04-10 12:40:35.724  1435  1444 I art     : Background sticky concurrent mark swe
ep GC freed 56298(3MB) AllocSpace objects, 45(900KB) LOS objects, 19% free, 20MB
/25MB, paused 6.331ms total 87.903ms
04-10 12:40:35.742 13581 13650 D TSLocationManager: [c.t.l.data.sqlite.a onCreat
e] CREATE TABLE IF NOT EXISTS geofences (id INTEGER PRIMARY KEY AUTOINCREMENT, i
dentifier TEXT NOT NULL UNIQUE, latitude DOUBLE NOT NULL, sin_latitude DOUBLE NO
T NULL, cos_latitude DOUBLE NOT NULL, longitude DOUBLE NOT NULL, sin_longitude D
OUBLE NOT NULL, cos_longitude DOUBLE NOT NULL, radius DOUBLE NOT NULL, notifyOnE
ntry BOOLEAN NOT NULL DEFAULT 0, notifyOnExit BOOLEAN NOT NULL DEFAULT 0, notify
OnDwell BOOLEAN NOT NULL DEFAULT 0, loiteringDelay INTEGER NOT NULL DEFAULT 0, e
xtras TEXT);
04-10 12:40:35.777  1435 13814 I PlaceInferenceEngine: [anon] Setup for configur
ation 105:[]
04-10 12:40:35.777  1435 13814 I PlaceInferenceEngine: [anon] Active modules aft
er start(): 0
04-10 12:40:35.806  1435 13021 W ctxmgr  : [AclManager]No 3 for (accnt=account#-
517948760#, com.google.android.googlequicksearchbox(10025):com.google.android.go
oglequicksearchbox, vrsn=10084000, 1, 3pPkg = null ,  3pMdlId = null). Was: 3 fo
r 6, account#-517948760#
04-10 12:40:35.839  1435 13021 W ctxmgr  : [PlacesProducer]Not handling added pr
oduction policy type=3
04-10 12:40:35.893  2772  9519 D KONTROL : Launcher Servis +ºal-¦+ƒ-¦yor...
04-10 12:40:35.896  2772  2839 D Kontrol:: CheckDeleteService: com.google.androi
d.googlequicksearchbox
04-10 12:40:35.896  2772  9519 D Kontrol:: LauncherServicecom.google.android.goo
glequicksearchbox
04-10 12:40:36.193  2772  9519 D KONTROL : Launcher Servis +ºal-¦+ƒ-¦yor...
04-10 12:40:36.194  2772  2839 D Kontrol:: CheckDeleteService: com.google.androi
d.googlequicksearchbox
04-10 12:40:36.194  2772  9519 D Kontrol:: LauncherServicecom.google.android.goo
glequicksearchbox
04-10 12:40:36.493  2772  9519 D KONTROL : Launcher Servis +ºal-¦+ƒ-¦yor...
04-10 12:40:36.494  2772  9519 D Kontrol:: LauncherServicecom.google.android.goo
glequicksearchbox
04-10 12:40:36.501  2772  2839 D Kontrol:: CheckDeleteService: com.google.androi
d.googlequicksearchbox
04-10 12:40:36.793  2772  9519 D KONTROL : Launcher Servis +ºal-¦+ƒ-¦yor...
04-10 12:40:36.795  2772  2839 D Kontrol:: CheckDeleteService: com.google.androi
d.googlequicksearchbox
04-10 12:40:36.795  2772  9519 D Kontrol:: LauncherServicecom.google.android.goo
glequicksearchbox
04-10 12:40:36.818 13581 13650 D TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO
 dbh]
04-10 12:40:36.818 13581 13650 D TSLocationManager:   G£à  Opened database
04-10 12:40:36.836 13581 13650 D TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO
 prune]
04-10 12:40:36.836 13581 13650 D TSLocationManager:   Gä¦n+Å  PRUNE -1 days
04-10 12:40:36.912 13581 13650 D TSLocationManager: [c.t.l.data.sqlite.GeofenceD
AO dbh]
04-10 12:40:36.912 13581 13650 D TSLocationManager:   G£à  Opened database
04-10 12:40:36.913  1435 12131 E AsyncOperation: serviceID=67, operation=Request
PlaceUpdates
04-10 12:40:36.913  1435 12131 E AsyncOperation: OperationException[Status{statu
sCode=Failed to bind to inner service, resolution=null}]
04-10 12:40:36.913  1435 12131 E AsyncOperation:        at amsg.a(:com.google.an
droid.gms:84)
04-10 12:40:36.913  1435 12131 E AsyncOperation:        at lin.run(:com.google.a
ndroid.gms:111)
04-10 12:40:36.913  1435 12131 E AsyncOperation:        at llt.run(:com.google.a
ndroid.gms:450)
04-10 12:40:36.913  1435 12131 E AsyncOperation:        at java.util.concurrent.
ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-10 12:40:36.913  1435 12131 E AsyncOperation:        at java.util.concurrent.
ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-10 12:40:36.913  1435 12131 E AsyncOperation:        at lqc.run(:com.google.a
ndroid.gms:17)
04-10 12:40:36.913  1435 12131 E AsyncOperation:        at java.lang.Thread.run(
Thread.java:818)
04-10 12:40:36.955 13581 13650 I TSLocationManager: [c.t.l.a.BackgroundGeolocati
on <init>]
04-10 12:40:36.955 13581 13650 I TSLocationManager:   =ƒö¦  Connecting to Google
PlayServices...
04-10 12:40:36.991  1435  1435 E ctxmgr  : [PlacesProducer]Failure requestPlaceU
pdates, priority=102, interval=360000, status=Status{statusCode=Failed to bind t
o inner service, resolution=null}
04-10 12:40:36.998 13581 13650 D TSLocationManager: $ configure()
04-10 12:40:37.005 13581 13581 I TSLocationManager: [c.t.l.a.BackgroundGeolocati
on onConnected]
04-10 12:40:37.005 13581 13581 I TSLocationManager:   G£à  Google Play Services:
 connected (version code:10298000)
04-10 12:40:37.009 13581 13650 D TSLocationManager: $ watchPosition()
04-10 12:40:37.019 13581 13826 E AndroidRuntime: FATAL EXCEPTION: pool-4-thread-
2
04-10 12:40:37.019 13581 13826 E AndroidRuntime: Process: com.transistorsoft.bac
kgroundgeolocation.ionic, PID: 13581
04-10 12:40:37.019 13581 13826 E AndroidRuntime: java.lang.NullPointerException:
 Attempt to invoke virtual method 'void com.transistorsoft.locationmanager.locat
ion.TSLocationManager.watchPosition(org.json.JSONObject)' on a null object refer
ence
04-10 12:40:37.019 13581 13826 E AndroidRuntime:        at com.transistorsoft.lo
cationmanager.adapter.BackgroundGeolocation$2.run(Unknown Source)
04-10 12:40:37.019 13581 13826 E AndroidRuntime:        at java.util.concurrent.
ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-10 12:40:37.019 13581 13826 E AndroidRuntime:        at java.util.concurrent.
ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-10 12:40:37.019 13581 13826 E AndroidRuntime:        at java.lang.Thread.run(
Thread.java:818)
04-10 12:40:37.024   556   567 W ActivityManager:   Force finishing activity com
.transistorsoft.backgroundgeolocation.ionic/.MainActivity
04-10 12:40:37.055 13581 13581 I TSLocationManager: CDVBackgroundGeolocation#onD
estoy
04-10 12:40:37.070   556 10800 I OpenGLRenderer: Initialized EGL, version 1.4
04-10 12:40:37.075   556 10800 I MaliEGL : [Mali]window_type=1, is_framebuffer=0
, errnum = 0
04-10 12:40:37.075   556 10800 I MaliEGL : [Mali]surface->num_buffers=4, surface
->num_frames=3, win_min_undequeued=1
04-10 12:40:37.075   556 10800 I MaliEGL : [Mali]max_allowed_dequeued_buffers=3
04-10 12:40:37.084 13581 13581 I TSLocationManager: [c.t.l.a.BackgroundGeolocati
on onActivityDestroy]
04-10 12:40:37.084 13581 13581 I TSLocationManager: GòöGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉG
òÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉ
GòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉ
04-10 12:40:37.084 13581 13581 I TSLocationManager: Gòæ MainActivity was destroy
ed
04-10 12:40:37.084 13581 13581 I TSLocationManager: GòáGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉG
òÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉ
GòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉGòÉ
04-10 12:40:37.084 13581 13581 I TSLocationManager: GòƒGöÇ stopOnTerminate: true

04-10 12:40:37.084 13581 13581 I TSLocationManager: GòƒGöÇ enabled: false
04-10 12:40:37.093  2772  9519 D KONTROL : Launcher Servis +ºal-¦+ƒ-¦yor...
04-10 12:40:37.097  2772  2839 D Kontrol:: CheckDeleteService: com.google.androi
d.googlequicksearchbox
04-10 12:40:37.105  2772  9519 D Kontrol:: LauncherServicecom.google.android.goo
glequicksearchbox
04-10 12:40:37.111  5926  5926 I MicroDetector: Keeping mic open: false
04-10 12:40:37.112  5926 12803 I DeviceStateChecker: DeviceStateChecker cancelle
d
04-10 12:40:37.112  5926 13341 I AudioController: internalShutdown
04-10 12:40:37.112  5926 13341 I MicrophoneInputStream: mic_close com.google.and
roid.apps.gsa.speech.audio.af@b286c04
04-10 12:40:37.113  5926 12611 E AudioRecord-JNI: Error -4 during AudioRecord na
tive read
04-10 12:40:37.114  5926  8392 I MicroRecognitionRunner: Stopping hotword detect
ion.
04-10 12:40:37.132   154 13808 D AudioMTKStreamIn: +setParameters() routing=0
04-10 12:40:37.132   154 13808 D AudioResourceManager: setUlInputDevice(), new_d
evice = 0x0
04-10 12:40:37.132   154 13808 D AudioMTKStreamIn: setParameters, device(0x0)
04-10 12:40:37.132   154 13808 D AudioMTKStreamIn: -setParameters()
04-10 12:40:37.132   154 13808 D AudioMTKStreamInManager: +Do_input_standby Clie
nt = 0xb8a29248
04-10 12:40:37.133   154 13808 D AudioMTKStreamInManager: Do_input_standby(), Cl
ient->mSourceType = 10, Client->mMemDataType = 2
04-10 12:40:37.133   154 13808 D AudioMTKStreamInManager: checkMemInUse Client =
 0xb8a29248
04-10 12:40:37.135 13581 13581 I TSLocationManager: [c.t.l.l.TSLocationManager s
topWatchPosition]
04-10 12:40:37.135 13581 13581 I TSLocationManager:   =ƒö¦  watchPosition: OFF
04-10 12:40:37.158 13581 13581 D TSLocationManager: [c.t.l.a.BackgroundGeolocati
on h]
04-10 12:40:37.158 13581 13581 D TSLocationManager:   =ƒö¦  Cleared callbacks
04-10 12:40:37.172 13581 13581 I TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO
 close]
04-10 12:40:37.172 13581 13581 I TSLocationManager:   G£à  Closed database
04-10 12:40:37.185 13581 13581 I TSLocationManager: [c.t.l.l.TSLocationManager s
topWatchPosition]
04-10 12:40:37.185 13581 13581 I TSLocationManager:   =ƒö¦  watchPosition: OFF
04-10 12:40:37.215 13581 13581 W cr_AwContents: WebView.destroy() called while W
ebView is still attached to window.
04-10 12:40:37.224   154 13808 D AudioMTKStreamInManager: +AudioMTkRecordThread(
)
04-10 12:40:37.224   154 13808 D AudioMTKStreamInManager: ClosePcmDumpFile
04-10 12:40:37.224   154 13808 D AudioMTKStreamInManager: threadLoop exit STANDB
Y_MEMIF_TYPE mMemType = 2
04-10 12:40:37.227   154 13808 D AudioMTKStreamInManager: -AudioMTkRecordThread(
)
04-10 12:40:37.227   154 13808 D AudioMTKStreamInManager: checkSourceInUse Clien
t = 0xb8a29248
04-10 12:40:37.227   154 13808 D AudioResourceManager: StopInputDevice(), mUlInp
utDevice = 0x80000004
04-10 12:40:37.228   154 13808 D AudioMTKStreamInManager: checkSourceInUse Clien
t = 0xb8a29248
04-10 12:40:37.228   154 13808 D AudioMTKStreamInManager: -Do_input_standby Clie
nt = 0xb8a29248
04-10 12:40:37.228   154 13808 D AudioMTKStreamInManager: ReleaseClient Client =
 0xb8a29248 clientid = 63 mAudioInput.size  = 1
04-10 12:40:37.228   154 13808 D AudioMTKStreamInManager: remove  mAudioInputclo
ient index = 0
04-10 12:40:37.228   154 13808 D AudioMTKStreamInManager: ReleaseClient mAudioIn
put.size = 0
04-10 12:40:37.228   154 13808 D AudioSPELayer: SPELayer::Stop
04-10 12:40:37.228   154 13808 D AudioSPELayer: SPELayer::Clear
04-10 12:40:37.228   154 13808 D AudioSPELayer: free mSphCtrlBuffer 0xb89062d0
04-10 12:40:37.228   154 13808 D AudioSPELayer: ~free mSphCtrlBuffer
04-10 12:40:37.228   154 13808 D AudioSPELayer: ~Clear
04-10 12:40:37.228   154 13808 D AudioSPELayer: SPELayer::Standby
04-10 12:40:37.228   154 13808 D AudioSPELayer: SPELayer::Clear
04-10 12:40:37.228   154 13808 D AudioSPELayer: ~Clear
04-10 12:40:37.229   154 13808 D AudioSPELayer: Standby --
04-10 12:40:37.233   154  1103 D AudioSPELayer: SPELayer::Standby
04-10 12:40:37.233   154  1103 D AudioSPELayer: SPELayer::Clear
04-10 12:40:37.233   154  1103 D AudioSPELayer: ~Clear
04-10 12:40:37.233   154  1103 D AudioSPELayer: Standby --
04-10 12:40:37.233   154  1103 D AudioSPELayer: ~SPELayer
04-10 12:40:37.233   154  1103 D AudioSPELayer: SPELayer::Clear
04-10 12:40:37.233   154  1103 D AudioSPELayer: ~Clear
04-10 12:40:37.233   154  1103 D AudioSPELayer: ~SPELayer --
04-10 12:40:37.233   154  1103 D AudioPreProcess: AudioPreProcess destructor
04-10 12:40:37.233   154  1103 D AudioPreProcess: ~AudioPreProcess--
04-10 12:40:37.233   154  1103 D AudioStreamAttribute: AudioStreamAttribute dest
ructor
04-10 12:40:37.245 13581 13581 W cr_AwContents: Application attempted to call on
 a destroyed WebView
04-10 12:40:37.245 13581 13581 W cr_AwContents: java.lang.Throwable
04-10 12:40:37.245 13581 13581 W cr_AwContents:         at org.chromium.android_
webview.AwContents.isDestroyed(AwContents.java:1229)
04-10 12:40:37.245 13581 13581 W cr_AwContents:         at org.chromium.android_
webview.AwContents.setNetworkAvailable(AwContents.java:2614)
04-10 12:40:37.245 13581 13581 W cr_AwContents:         at com.android.webview.c
hromium.WebViewChromium.setNetworkAvailable(WebViewChromium.java:431)
04-10 12:40:37.245 13581 13581 W cr_AwContents:         at android.webkit.WebVie
w.setNetworkAvailable(WebView.java:802)
04-10 12:40:37.245 13581 13581 W cr_AwContents:         at org.apache.cordova.en
gine.SystemWebViewEngine$1.setNetworkAvailable(SystemWebViewEngine.java:112)
04-10 12:40:37.245 13581 13581 W cr_AwContents:         at org.apache.cordova.Na
tiveToJsMessageQueue$OnlineEventsBridgeMode$2.run(NativeToJsMessageQueue.java:34
0)
04-10 12:40:37.245 13581 13581 W cr_AwContents:         at android.os.Handler.ha
ndleCallback(Handler.java:739)
04-10 12:40:37.245 13581 13581 W cr_AwContents:         at android.os.Handler.di
spatchMessage(Handler.java:95)
04-10 12:40:37.245 13581 13581 W cr_AwContents:         at android.os.Looper.loo
p(Looper.java:148)
04-10 12:40:37.245 13581 13581 W cr_AwContents:         at android.app.ActivityT
hread.main(ActivityThread.java:5417)
04-10 12:40:37.245 13581 13581 W cr_AwContents:         at java.lang.reflect.Met
hod.invoke(Native Method)
04-10 12:40:37.245 13581 13581 W cr_AwContents:         at com.android.internal.
os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-10 12:40:37.245 13581 13581 W cr_AwContents:         at com.android.internal.
os.ZygoteInit.main(ZygoteInit.java:616)
04-10 12:40:37.246 13581 13581 I chromium: [INFO:CONSOLE(0)] "Blink deferred a t
ask in order to make scrolling smoother. Your timer and network tasks should tak
e less than 50ms to run to avoid this. Please see https://developers.google.com/
web/tools/chrome-devtools/profile/evaluate-performance/rail and https://crbug.co
m/574343#c40 for more information.", source: file:///android_asset/www/Contact91
1.html (0)
04-10 12:40:37.247  5926 12634 I MicroRecognitionRunner: Detection finished
04-10 12:40:37.393  2772  9519 D KONTROL : Launcher Servis +ºal-¦+ƒ-¦yor...
04-10 12:40:37.395  2772  2839 D Kontrol:: CheckDeleteService: com.google.androi
d.googlequicksearchbox
04-10 12:40:37.396  2772  9519 D Kontrol:: LauncherServicecom.google.android.goo
glequicksearchbox
04-10 12:40:37.693  2772  9519 D KONTROL : Launcher Servis +ºal-¦+ƒ-¦yor...
04-10 12:40:37.695  2772  2839 D Kontrol:: CheckDeleteService: com.google.androi
d.googlequicksearchbox
04-10 12:40:37.697  2772  9519 D Kontrol:: LauncherServicecom.google.android.goo
glequicksearchbox
04-10 12:40:37.994  2772  2839 D Kontrol:: CheckDeleteService: com.google.androi
d.googlequicksearchbox
04-10 12:40:37.995  2772  9519 D KONTROL : Launcher Servis +ºal-¦+ƒ-¦yor...
04-10 12:40:37.997  2772  9519 D Kontrol:: LauncherServicecom.google.android.goo
glequicksearchbox
04-10 12:40:38.293  2772  9519 D KONTROL : Launcher Servis +ºal-¦+ƒ-¦yor...
04-10 12:40:38.294  2772  9519 D Kontrol:: LauncherServicecom.google.android.goo
glequicksearchbox
04-10 12:40:38.295  2772  2839 D Kontrol:: CheckDeleteService: com.google.androi
d.googlequicksearchbox
04-10 12:40:38.593  2772  9519 D KONTROL : Launcher Servis +ºal-¦+ƒ-¦yor...
04-10 12:40:38.595  2772  2839 D Kontrol:: CheckDeleteService: com.google.androi
d.googlequicksearchbox
04-10 12:40:38.596  2772  9519 D Kontrol:: LauncherServicecom.google.android.goo
glequicksearchbox
04-10 12:40:38.893  2772  9519 D KONTROL : Launcher Servis +ºal-¦+ƒ-¦yor...
04-10 12:40:38.902  2772  2839 D Kontrol:: CheckDeleteService: com.google.androi
d.googlequicksearchbox
04-10 12:40:38.905  2772  9519 D Kontrol:: LauncherServicecom.google.android.goo
glequicksearchbox
04-10 12:40:39.168  2772  9519 D KONTROL : Launcher Servis +ºal-¦+ƒ-¦yor...
04-10 12:40:39.171  2772  9519 D Kontrol:: LauncherServicecom.google.android.goo
glequicksearchbox
04-10 12:40:39.195  2772  2839 D Kontrol:: CheckDeleteService: com.google.androi
d.googlequicksearchbox
04-10 12:40:39.493  2772  9519 D KONTROL : Launcher Servis +ºal-¦+ƒ-¦yor...
04-10 12:40:39.495  2772  2839 D Kontrol:: CheckDeleteService: com.google.androi
d.googlequicksearchbox
04-10 12:40:39.496  2772  9519 D Kontrol:: LauncherServicecom.google.android.goo
glequicksearchbox
04-10 12:40:39.793  2772  9519 D KONTROL : Launcher Servis +ºal-¦+ƒ-¦yor...
04-10 12:40:39.796  2772  2839 D Kontrol:: CheckDeleteService: com.google.androi
d.googlequicksearchbox
04-10 12:40:39.798  2772  9519 D Kontrol:: LauncherServicecom.google.android.goo
glequicksearchbox
04-10 12:40:40.093  2772  9519 D KONTROL : Launcher Servis +ºal-¦+ƒ-¦yor...
04-10 12:40:40.095  2772  2839 D Kontrol:: CheckDeleteService: com.google.androi
d.googlequicksearchbox
04-10 12:40:40.095  2772  9519 D Kontrol:: LauncherServicecom.google.android.goo
glequicksearchbox

**Comment by christocracy** [comment]
This repo is abandoned.  See the README.
