### ISSUE TITLE
In veiclhe or bike when i am walking

### ISSUE THREAD

**Issue by danielpawel** [christocracy/cordova-plugin-background-geolocation#263]
I am using the premium version.

IOS is just fine! But when I use android, it show that I am on Veiclhe or Bike when i am actualy walking. 

How is that possible? I need to configure this? 

Cheers,
and congrats on the plugins, is really nice!

**Comment by christocracy** [comment]
This is not the correct repo.  This repo is dead.  See the [README](https://github.com/christocracy/cordova-plugin-background-geolocation)
