### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by aniket-kr-joshi** [christocracy/cordova-plugin-background-geolocation#264]
:compileDebugJava/platforms/android/src/org/apache/cordova/geolocation/Geolocation.java:28: error: cannot find symbol
import org.apache.cordova.PermissionHelper;
                         ^
  symbol:   class PermissionHelper
  location: package org.apache.cordova
/platforms/android/src/org/apache/cordova/geolocation/Geolocation.java:56: error: cannot find symbol
                PermissionHelper.requestPermissions(this, 0, permissions);
                ^
  symbol:   variable PermissionHelper
  location: class Geolocation
/platforms/android/src/org/apache/cordova/geolocation/Geolocation.java:87: error: cannot find symbol
            if(!PermissionHelper.hasPermission(this, p))
                ^
  symbol:   variable PermissionHelper
  location: class Geolocation
/platforms/android/src/org/apache/cordova/geolocation/Geolocation.java:102: error: cannot find symbol
        PermissionHelper.requestPermissions(this, requestCode, permissions);
        ^
  symbol:   variable PermissionHelper
  location: class Geolocation
/platforms/android/src/nl/xservices/plugins/GooglePlus.java:346: error: cannot find symbol
                            cordova.getActivity(), acct.getAccount(), true
                                                       ^
  symbol:   method getAccount()
  location: variable acct of type GoogleSignInAccount
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 errors
 FAILED

**Comment by christocracy** [comment]
This project has been dead for 3 years.

See the README for information.
