### ISSUE TITLE
Erro Isnstallation

### ISSUE THREAD

**Issue by renatovieiradesouza** [christocracy/cordova-plugin-background-geolocation#265]
Friends, when trying to install the plugin in my project, hide an installation, but with some error messages, can anyone help me?
Versão:
    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0
global packages:
    cordova (Cordova CLI) : 7.0.1
local packages:
    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.9.2
System:
    Node : v7.5.0
    npm  : 5.4.2
    OS   : Windows 7
Misc:
    backend : pro
Erro:
https://pastebin.com/LwSnRtPy

**Comment by christocracy** [comment]
Have you seen the README if this repo?

There’s an important message there

**Comment by renatovieiradesouza** [comment]
I read the README.  Without success in reading. Do you can help me?

**Comment by christocracy** [comment]
The [README](https://github.com/christocracy/cordova-plugin-background-geolocation/) doesn't make any sense to you?  Looks pretty clear that *this* repo is dead and you should direct yourself over to the other place linked there.

![](https://dl.dropboxusercontent.com/s/6js907kr9bzfwi9/Screenshot%202017-11-28%2018.42.38.png?dl=1)

**Comment by renatovieiradesouza** [comment]
I was here: https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/README.md

Thank you for help.
