### ISSUE TITLE
Could not get response(neither success nor failure) from beGeo.configure

### ISSUE THREAD

**Issue by gatang007** [christocracy/cordova-plugin-background-geolocation#268]
I have been using the following code to start the beGeo successfully on Android. However, when I tried to run it on iOS, I could get no response from the call.  The logging printed on console was like

***************
* console log
**************
configureBackgroundGeolocation cp 1
configureBackgroundGeolocation cp 2
configureBackgroundGeolocation cp 3
configureBackgroundGeolocation cp 6

***************
* code
**************
  configureBackgroundGeolocation() {
    console.log("configureBackgroundGeolocation cp 1");
    // 1. Get a reference to the plugin
    this.bgGeo = (<any>window).BackgroundGeolocation;

    console.log("configureBackgroundGeolocation cp 2");
    // 2. Listen to events
    this.bgGeo.on('location', this.onLocation.bind(this));
    this.bgGeo.on('motionchange', this.onMotionChange.bind(this));
    this.bgGeo.on('activitychange', this.onActivityChange.bind(this));
    this.bgGeo.on('geofence', this.onGeofence.bind(this));
    this.bgGeo.on('http', this.onHttpSuccess.bind(this), this.onHttpFailure.bind(this));
    this.bgGeo.on('heartbeat', this.onBgGeoHeartBeat.bind(this));

    console.log("configureBackgroundGeolocation cp 3");
    // 3. Configure it.
      this.bgGeo.configure({
      debug: true,
      desiredAccuracy: 100,
      distanceFilter: 10,
      heartbeatInterval: 60,
      preventSuspend: true
    }, (state) => {
      console.log("configureBackgroundGeolocation cp 4 - starting");
      // 4. Start the plugin.
      this.bgGeo.start();
      this.bgGeo.getState(function(state) {
        console.log(JSON.stringify(state));
      });
    }, (error) => {
      console.log("configureBackgroundGeolocation cp 5");
      console.log("failed to configure error", error);
    });
    console.log("configureBackgroundGeolocation cp 6");
  }

===========================

It looks like the beoGeo.configure was not unable to return "state" or "error".

Can you please shed light on this? Many thanks

**Comment by christocracy** [comment]
This repo is obsolete.  See [README](https://github.com/christocracy/cordova-plugin-background-geolocation)
