### ISSUE TITLE
Does the speed in returned  response is accurate when the accuracy is low?

### ISSUE THREAD

**Issue by Gurjit-ONEBCG** [christocracy/cordova-plugin-background-geolocation#271]
Hi, I am using this plugin in ionic 3 app.
I want to know that when the logged accuracy is low of location eg. _accuracy_ :500
Then, do the  _speed_  and _bearing_ parameter values are also wrong in response? 
or it does not depend on the location accuracy. 

Thanks

**Comment by christocracy** [comment]
Are you sure you’re using *this* plugin?

See the README; https://github.com/christocracy/cordova-plugin-background-geolocation

**Comment by Gurjit-ONEBCG** [comment]
> Are you sure you’re using _this_ plugin?
> 
> See the README; https://github.com/christocracy/cordova-plugin-background-geolocation

Sorry I have moved it on right place
