### ISSUE TITLE
Prolonged duration of app in background 

### ISSUE THREAD

**Issue by akshayakrsh** [christocracy/cordova-plugin-background-geolocation#3]
Hi,

I have 3 questions:
1. Does this work even when the app is foreground? Or do I need to use the org.apache.cordova.geolocation plugin for that?
2. And what about prolonged times i.e. say the user is stationary at a location for 3-4 hours or more (e.g. his home) with the app in background and wakes up in the morning starts moving...will the ajax call start firing automatically?
3. Does this also handle the scenarios such as gps signal loss, flight mode, disabled location services and disabled background app refresh? 

I urgently am looking for a solution for this, let me know if I can use this plugin for that. I have been able to solve the problem 3 myself but the problem 2 is making me go nuts!

**Comment by edparsons** [comment]
Hi Chris,
You mentioned you can't turn on aggressive tracking via the background-fetch or notification methods earlier in this thread.

Why is that and is there a way to say on an interval like every hour to boot up the gps and check if someones moved

Thanks

**Comment by christocracy** [comment]
Sime comments in this thread may be obsolete.

On Thursday, May 14, 2015, edparsons <notifications@github.com> wrote:

> Hi Chris,
> You mentioned you can't turn on aggressive tracking via the
> background-fetch or notification methods earlier in this thread.
>
> Why is that and is there a way to say on an interval like every hour to
> boot up the gps and check if someones moved
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/3#issuecomment-102241309>
> .
>


-- 
Snet from Gmail Mobile
