### ISSUE TITLE
Remove Background Tracking Enabled from notification bar

### ISSUE THREAD

**Issue by programming-kid** [christocracy/cordova-plugin-background-geolocation#34]
Hey @christocracy first of  amazing plugin :+1: , just got it working after suffering for 30 mins due to callback issue on Android,

Anyways what i wanted to ask is there any way i can remove Background Tracking Enabled from notification drawer in Android or customize it according my specific app .

Thanks

**Comment by christocracy** [comment]
Android has been refactored.
- plugin no longer handles http; calls js callback (just like ios)
- much improved battery efficiency.
- no more foreground service

http://christocracy.github.io/cordova-background-geolocation/
