### ISSUE TITLE
Can I use your plugin to send notification to user instead of send something to server?

### ISSUE THREAD

**Issue by stefaniebrunner** [christocracy/cordova-plugin-background-geolocation#35]
I have a question about to use your plugin on another approach. I don't have to send something to server when location change but to send a notification to the user and the user then should be able to start my app from the notification message.
Can you give me an answer if that is possible with your plugin and how I can achieve this? I'm doing this on Android. 
I really appreciate your help.

Thanks a lot.

**Comment by christocracy** [comment]
FYI Android has been completely refactored
- No more in-plugin HTTP -- plugin now executes your Javascript callback, just like iOS
- Significantly improved battery performance

http://christocracy.github.io/cordova-background-geolocation/
