### ISSUE TITLE
Add option to specify the date format posted to the server

### ISSUE THREAD

**Issue by mrthehud** [christocracy/cordova-plugin-background-geolocation#37]
Hey,

While writing an endpoint for this to post to (with Symfony), I noticed the date format seems a little odd - I'd like to be able to specify this, if possible.

Otherwise, what's the format here?

**Comment by christocracy** [comment]
Android has been refactored.
- plugin no longer handles http; calls js callback (just like ios)
- much improved battery efficiency.
- no more foreground service

http://christocracy.github.io/cordova-background-geolocation/

**Comment by mrthehud** [comment]
Thanks.
