### ISSUE TITLE
question: Multiple location requests at once

### ISSUE THREAD

**Issue by stefaniebrunner** [christocracy/cordova-plugin-background-geolocation#42]
Why do I receive on my server about 20 locations all at once? I was testing the plugin with one device and received always circa 20 requests from that only device.
Is that a configuration issue?

**Comment by christocracy** [comment]
FYI Android has been completely refactored
- No more in-plugin HTTP -- plugin now executes your Javascript callback, just like iOS
- Significantly improved battery performance

http://christocracy.github.io/cordova-background-geolocation/
