### ISSUE TITLE
Not Getting location by plugin success callback 

### ISSUE THREAD

**Issue by mspnitesh** [christocracy/cordova-plugin-background-geolocation#43]
Hello everyone,

First i would like to thanx for developing this plugin. but i have some issue i am able to get location why standard method but am not able to get location by plugin success callback.

It's urgent if anyone know this issue then please let me know

Thank you

**Comment by christocracy** [comment]
FYI Android has been completely refactored
- No more in-plugin HTTP -- plugin now executes your Javascript callback, just like iOS
- Significantly improved battery performance

http://christocracy.github.io/cordova-background-geolocation/

**Comment by craig-at-rsg** [comment]
So the free version is this one (in github) and the paid version has improvements that aren't open source?

If I have that right, I have my own app that uses a custom plugin already - if I bought your paid version, would I be able to use your source code to improve my app instead of using your plugin directly?

**Comment by christocracy** [comment]
> So the free version is this one (in github) and the paid version has
> improvements that aren't open source?
>
Correct.

> If I have that right, I have my own app that uses a custom plugin already
> - if I bought your paid version, would I be able to use your source code to
> improve my app instead of using your plugin directly?
>
“a custom plugin”?

Please email me directly.


-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by craig-at-rsg** [comment]
Hi Chris,

Our app needed to work a little differently than the earlier version of your plugin, so I wrote a plugin for location recording. 

Your new version sounds like it has some features which would be useful to us, but it wouldn't fit our app without a lot of rework. 


The new features I was interested in:
1. I haven't seen a good way to call javascript from Android when the app is in the background, and I had given up on this, but that would help simplify our app if it really works. 
2. Google Play location services - there are lots of examples online, but this is something we want to add, especially for the mode detection. 

So, I was wondering if paying for your app would give me access to and permission to use your source code in my app. 

Thanks,
Craig

**Comment by christocracy** [comment]
Please email me directly.  You can find my contact-info on my website in my
sig

On Wed, May 6, 2015 at 11:40 AM, craig-at-rsg <notifications@github.com>
wrote:

> Hi Chris,
>
> Our app needed to work a little differently than the earlier version of
> your plugin, so I wrote a plugin for location recording.
>
> Your new version sounds like it has some features which would be useful to
> us, but it wouldn't fit our app without a lot of rework.
>
>
> The new features I was interested in:
> 1. I haven't seen a good way to call javascript from Android when the app
> is in the background, and I had given up on this, but that would help
> simplify our app if it really works.
> 2. Google Play location services - there are lots of examples online, but
> this is something we want to add, especially for the mode detection.
>
> So, I was wondering if paying for your app would give me access to and
> permission to use your source code in my app.
>
> Thanks,
> Craig
>
>
>
>
>
> On May 6, 2015, at 11:19 AM, Chris Scott <notifications@github.com> wrote:
>
> > > So the free version is this one (in github) and the paid version has
> > > improvements that aren't open source?
> > >
> > Correct.
> >
> > > If I have that right, I have my own app that uses a custom plugin
> already
> > > - if I bought your paid version, would I be able to use your source
> code to
> > > improve my app instead of using your plugin directly?
> > >
> > “a custom plugin”?
> >
> > Please email me directly.
> >
> >
> > --
> > Chris Scott
> > Transistor Software <http://www.transistorsoft.com>
>
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/43#issuecomment-99517046>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
