### ISSUE TITLE
Also interested in foreground usage

### ISSUE THREAD

**Issue by comara** [christocracy/cordova-plugin-background-geolocation#45]
Closed issue #40 also asked this question. 

In my case I have only iOS and Android users, and I'd like to track their location with the same mechanism regardless of whether or not the app is in the background. My users may have the app running in the foreground intentionally because they believe it results in better tracking. I've heard of some users plugging in their phones and tapping the screen in an effort to keep the app in the foreground specifically for this purpose. 

Any ideas on how I can use the plugin in the foreground?

**Comment by jtomaszewski** [comment]
> to add a line in the README (unless I overlooked it) that the plugin will not log while in foreground

+1 for that. I realised it long time after using the plugin, lol!

**Comment by christocracy** [comment]
This repo is deprecated.

It has moved to
https://github.com/transistorsoft/cordova-background-geolocation-lt


On Mon, Sep 21, 2015 at 3:57 PM, Jacek Tomaszewski <notifications@github.com
> wrote:

> to add a line in the README (unless I overlooked it) that the plugin will
> not log while in foreground
>
> +1 for that. I realised it long time after using the plugin, lol!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/45#issuecomment-142092472>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
