### ISSUE TITLE
Enormous volume of location reports from one specific device

### ISSUE THREAD

**Issue by shedd** [christocracy/cordova-plugin-background-geolocation#47]
We recently encountered an issue where one of our beta users was sending through an enormous volume of location requests.  We saw nearly 14,000 such requests in a 60 minute period.  We were able to track down the user and get him to force close the app and that stopped the massive surge of requests.  Clearly, this was an issue both for his phone's performance and questionable for our API if this happened across a large userbase.

We're using a vanilla implementation of this plugin, based largely on the example in the README.

What would cause such a massive request surge?  We're using the same settings (accuracy 10, stationaryRadius 20, distanceFilter 30) that are in the README example.

It's possible (we're trying to confirm) that the user disabled the GPS on his device during the time in question.

Any suggestions on where we should look for the root cause of this issue?

Thanks so much.

**Comment by christocracy** [comment]
FYI Android has been completely refactored in Premium Version
- No more in-plugin HTTP -- plugin now calls your Javascript callback, just like iOS
- Significantly improved battery performance

http://christocracy.github.io/cordova-background-geolocation/
