### ISSUE TITLE
Please consider submitting to build.phonegap.com

### ISSUE THREAD

**Issue by codearachnid** [christocracy/cordova-plugin-background-geolocation#5]
Would love to use your plugin in the official build service repo. Please submit via https://build.phonegap.com/plugins for use within the community.

**Comment by appsdeveloper89** [comment]
This plugin is not working iam trying to use this in phonegap android its not working
what i have to give here
url: 'http://only.for.android.com/update_location.json',
authToken: 'user_secret_auth_token'

i dont know what to give here please create sample example plugin which work
and please help me what i have to give url and authToken

i want to impplement background geolocation which sends lattitude and longitude

**Comment by christocracy** [comment]
The plugin is working fine.  The problem, I suspect, is your lack of
experience with web-application development.

I’m afraid I’m not here to provide general “mobile/web application
development” support.

If you don’t understand this:

  url: 'http://only.for.android.com/update_location.json',
  authToken: ‘user_secret_auth_token'

Then you need to go google “token-based authentication”.  This is not
specific to my plugin — it’s general to any web application.


On Mon, Jan 26, 2015 at 11:27 AM, appsdeveloper89 <notifications@github.com>
wrote:

> This plugin is not working iam trying to use this in phonegap android its
> not working
> what i have to give here
> url: 'http://only.for.android.com/update_location.json',
> authToken: 'user_secret_auth_token'
>
> i dont know what to give here please create sample example plugin which
> work
> and please help me what i have to give url and authToken
>
> i want to impplement background geolocation which sends lattitude and
> longitude
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/5#issuecomment-71488624>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
PS @appsdeveloper89 Your choice to post on a **closed issue** having subject "Please consider submitting to build.phonegap.com" was very poor.

**Comment by appsdeveloper89** [comment]
Thanks for replying Chris Scott
what iam asking is url means here i need to send these locations to my
sever?
and auth token means how to get it?

i dont want to use php
i need to call internally through without using auth token we cant get it?

your plugin doesnt have clarity many of people suffers with this
they dont know how to use it

**Comment by christocracy** [comment]
What do you not understand about this
<https://github.com/christocracy/cordova-plugin-background-geolocation#android>
?

*"The plugin manages sync-ing GeoLocations to your server automatically,
using the configured url, params and headers”*

If you’re *not* using a server (running php, for example), then this plugin
is useless to you.

What is an auth-token?  It’s up to *your server *application to provide you
an auth-token after your user logs into your app and that’s beyond the
scope of my plugin.  My plugin doesn’t care if you supply one or not, it
merely provides a hook for you to plug the one YOUR server generated.
http://stackoverflow.com/questions/1592534/what-is-token-based-authentication



On Wed, Jan 28, 2015 at 11:44 AM, appsdeveloper89 <notifications@github.com>
wrote:

> Thanks for replying Chris Scott
> what iam asking is url means here i need to send these locations to my
> sever?
> and auth token means how to get it?
>
> i dont want to use php
> i need to call internally through without using auth token we cant get it?
>
> your plugin doesnt have clarity many of people suffers with this
> they dont know how to use it
>
> On Mon, Jan 26, 2015 at 10:13 PM, Chris Scott <notifications@github.com>
> wrote:
>
> > PS @appsdeveloper89 <https://github.com/appsdeveloper89> Your choice to
> > post on a *closed issue* having subject "Please consider submitting to
> > build.phonegap.com" was very poor.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/5#issuecomment-71491779>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/5#issuecomment-71868719>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
And Dammit:  quit posting on CLOSED issues which have nothing to do with your problem
