### ISSUE TITLE
Android: server side

### ISSUE THREAD

**Issue by YairHadari** [christocracy/cordova-plugin-background-geolocation#50]
Hi,

From JS I'm calling PHP file that are creating a text file with $_POST['location'] - only for tests.
The problem is that nothing is being passed to  $_POST['location'] .
The JS is:
        bgGeo.configure(callbackFn, failureFn, {
            url: 'http://MyServer.com/WriteBackgroundToDB.php', // <-- only required for Android; ios allows javascript callbacks for your http
            params: {                                               //  <-- Android ONLY:  HTTP POST params sent to your server when persisting locations.
                auth_token: 'user_secret_auth_token',
                foo: 'bar'
            },
            headers: {      // <-- Android ONLY:  Optional HTTP headers sent to your configured #url when persisting locations
                'X-Foo': 'BAR'
            },  
            desiredAccuracy: 10,
            stationaryRadius: 20,
            distanceFilter: 30,
            debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
            notificationTitle: 'Background tracking', // <-- android only, customize the title of the notification
            notificationText: 'ENABLED' // <-- android only, customize the text of the notification
        });

The PHP code is:
<?php
header('Access-Control-Allow-Origin: *');

$file = fopen('test.txt','w');
echo fwrite($file, 'Post location: ' . $_POST['location']);
$json = JSON_decode($_POST['location'], true);
echo fwrite($file, 'Last: ' . json_last_error()); 

echo fwrite($file, 'json: ' . $json); 
echo fwrite($file, 'count: ' . count($json)); 
foreach ($json as $trend)
{  
    echo fwrite($file, 'Lat: ' . $trend['Latitude'] ); 
    $Latitude = $trend['Latitude'];  
} 
fclose($file);  
?>

Can someone assist please?

**Comment by christocracy** [comment]
FYI Android has been completely refactored in Premium Version
- No more in-plugin HTTP -- plugin now executes your Javascript callback, just like iOS
- Significantly improved battery performance

http://christocracy.github.io/cordova-background-geolocation/

**Comment by piavgh** [comment]
Hi @georgetudor 
Suppose I want to send Android location to api.example.com/location_android, so what kind of request I have to handle? GET or POST?
Thank you!
