### ISSUE TITLE
Add plugin to Android project

### ISSUE THREAD

**Issue by predragmilutinovic** [christocracy/cordova-plugin-background-geolocation#51]
How to add the plugin into existing Android project, https://github.com/DevExpress/DevExtreme-ApplicationTemplate-Android?

**Comment by christocracy** [comment]
FYI Android has been completely refactored in Premium Version
- No more in-plugin HTTP -- plugin now executes your Javascript callback, just like iOS
- Significantly improved battery performance

http://christocracy.github.io/cordova-background-geolocation/
