### ISSUE TITLE
Android always update every 1 minute

### ISSUE THREAD

**Issue by keko123** [christocracy/cordova-plugin-background-geolocation#53]
Hello, I changed the values ​​of distanceFilter (values 1, 10,20,30) and stationaryRadius( values 1, 10, 20, 30).
Moving running (5 km/ h ) and bus (30 km/h in city and 70 km/h in road) always position is updated every 1 minute.
Somebody know why?

Thanks

PD.: thanks for your work!!!

**Comment by christocracy** [comment]
Android has been refactored.
- plugin no longer handles http; calls js callback (just like ios)
- much improved battery efficiency.
- no more foreground service

http://christocracy.github.io/cordova-background-geolocation/
