### ISSUE TITLE
Notification persistent & clickable

### ISSUE THREAD

**Issue by trcharlie** [christocracy/cordova-plugin-background-geolocation#58]
Hello!
First of all, great work!
What I am missing is a way to make the notification persistent on android (if the application itself is being closed, the notification is gone) and to open the app when the user taps on the notification.

Is there an easy way to implement those features?

regards,
charlie

**Comment by christocracy** [comment]
Android has been refactored.
- plugin no longer handles http; calls js callback (just like ios)
- much improved battery efficiency.
- no more foreground service (no more notification to click)

http://christocracy.github.io/cordova-background-geolocation/
