### ISSUE TITLE
Hello, I'm using ionic framework on Android platform

### ISSUE THREAD

**Issue by awesomejerry** [christocracy/cordova-plugin-background-geolocation#60]
Hi, I'm using the plugin to monitor user's position to determine if user is getting closed to a certain destination. However when I'm trying to send params to server, it seems that server cannot get those params. Here's part of my code:
{
   url: 'my Server php url',
   param: {
       lat: pos.getLat(),
       lng: pos.getLng()
   },
   header: {
      'Access-Control-Allow-Origin': '*',
      'Content-Type': 'application/json; charset=utf-8'
  },
  desiredAccuracy: 10,
  stationaryRadius: 20,
  distanceFilter: 30,
  notificationTitle: 'Navigating',
  notificationText: pos.getName(),
  activityType: 'AutomotiveNavigation',
  debug: true
}

php:
$lat = $_POST['lat'];
$lng = $_POST['lng'];
$file = 'location.txt';
$current = file_get_contents($file);
$current .= "\n" . $lat . $lng;
file_put_contents($file, $current);

Can you provide me with a working example of Android version?  Thank you very much!

**Comment by christocracy** [comment]
FYI, Android has been refactored in new Premium Version
- Significantly improved battery performance
- No more in-plugin HTTP -- plugin now calls your Javascript callback, just like iOS

http://christocracy.github.io/cordova-background-geolocation/
