### ISSUE TITLE
NotificationTitle Does not change

### ISSUE THREAD

**Issue by hakimny** [christocracy/cordova-plugin-background-geolocation#65]
Hi Chris,
Something I should bring to your attention, I have changed the notificationTitle on the config but for some reasons, it is always the default text that shows up ( Background tracking).
Thank you for looking into this

**Comment by christocracy** [comment]
Android has been refactored.
- plugin no longer handles http; calls js callback (just like ios)
- much improved battery efficiency.
- no more foreground service

http://christocracy.github.io/cordova-background-geolocation/
