### ISSUE TITLE
no call to the json url

### ISSUE THREAD

**Issue by slajar** [christocracy/cordova-plugin-background-geolocation#67]
I tried to use the background-geolocation plugin. Well, it doesn't work in terms of calling the url. I set up a php script that sends the entire $_REQUEST to an email adress.

The script is:
$content = implode(', ', array_map(function ($v, $k) { return $k . '=' . $v; }, $_REQUEST, array_keys($_REQUEST)));
mail("mail@mail.com", "request", $content);

I get an email but there is no content. That means to me that it is called but the push hasn't been done correctly.

Is there any particular thing I have to do on the server or in the app?
Is there anywhere a complete example?

**Comment by christocracy** [comment]
FYI Android has been completely refactored in Premium Version
- No more in-plugin HTTP -- plugin executes your Javascript callback just like iOS
- Significantly improved **battery performance**

http://christocracy.github.io/cordova-background-geolocation/
