### ISSUE TITLE
How to Tweek the Plugin to improve Device Battery Life

### ISSUE THREAD

**Issue by hakimny** [christocracy/cordova-plugin-background-geolocation#68]
Hi Chris,

How to Tweek the Plugin to improve Device Battery Life? I noticed that even though I am setting DistanceFilter to 100 m, but the fact that the plugin keeps monitoring changes see to drain battery very quickly.

FYI: I am ONLY testing on Android Devices. SDK 4.0.X, SDK 4.1.X, SDK 4.2.X & SDK 4.4

**Comment by christocracy** [comment]
Good news on **Battery Performance**:  I've refactored Android completely and released it as a Premium Version:

- Significantly improved battery performance
- No more in-plugin HTTP -- plugin executes your javascript callback, just like iOS

http://christocracy.github.io/cordova-background-geolocation/
