### ISSUE TITLE
Android logging of locations

### ISSUE THREAD

**Issue by darrenahunter** [christocracy/cordova-plugin-background-geolocation#69]
Hi Chris

Terrific plugin.
I understand the reasoning for the plugin logging the location directly to the server as you can’t guarantee the JS callback to still exist. I expect others like myself are after access to the geo points inside there JS apps. This can be done by retrieving the points from the server (that have been logged by your plugin).
Would it be possible to add config options to direct the android plugin to log the points to something local (ie. localstorage) and then the android app could pole this and collect points without the server.
This would help with network outages also.
OR could you call the JS callback but if that fails then log to localstorage or server – kind of best of both worlds.
Just not everyone has or wants to use a server.

Once again many thanks for your plugin
Darren

**Comment by christocracy** [comment]
Android has been refactored.
- plugin no longer handles http; calls js callback (just like ios)
- much improved battery efficiency.

http://christocracy.github.io/cordova-background-geolocation/

**Comment by darrenahunter** [comment]
hey Chris your premium plugin is taking credit card trans not over HTTPS

**Comment by christocracy** [comment]
It's via Stripe.  The request to Stripe is via http, which merely returns a
token.


On Tuesday, March 10, 2015, darrenahunter <notifications@github.com> wrote:

> hey Chris your premium plugin is taking credit card trans not over HTTPS
>
>
> > On 7 Mar 2015, at 10:42 pm, Chris Scott <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > Closed #69 <
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/69
> >.
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/69#event-247976247
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/69#issuecomment-78178434>
> .
>


-- 
Snet from Gmail Mobile

**Comment by christocracy** [comment]
Request to stripe is via https, rather

On Tuesday, March 10, 2015, Chris Scott <christocracy@gmail.com> wrote:

> It's via Stripe.  The request to Stripe is via http, which merely returns
> a token.
>
>
> On Tuesday, March 10, 2015, darrenahunter <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> hey Chris your premium plugin is taking credit card trans not over HTTPS
>>
>>
>> > On 7 Mar 2015, at 10:42 pm, Chris Scott <notifications@github.com>
>> wrote:
>> >
>> > Closed #69 <
>> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/69
>> >.
>> >
>> > —
>> > Reply to this email directly or view it on GitHub <
>> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/69#event-247976247
>> >.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/69#issuecomment-78178434>
>> .
>>
>
>
> --
> Snet from Gmail Mobile
>


-- 
Snet from Gmail Mobile

**Comment by darrenahunter** [comment]
understand but the page in not https so people will have concerns putting up a credit card I think

**Comment by christocracy** [comment]
Thanks, I'll see what I can do.

On Tuesday, March 10, 2015, darrenahunter <notifications@github.com> wrote:

> understand but the page in not https so people will have concerns putting
> up a credit card I think
>
>
> > On 11 Mar 2015, at 11:33 am, Chris Scott <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > It's via Stripe. The request to Stripe is via http, which merely returns
> a
> > token.
> >
> >
> > On Tuesday, March 10, 2015, darrenahunter <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > hey Chris your premium plugin is taking credit card trans not over
> HTTPS
> > >
> > >
> > > > On 7 Mar 2015, at 10:42 pm, Chris Scott <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > > >
> > > > Closed #69 <
> > >
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/69
> > > >.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub <
> > >
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/69#event-247976247
> > > >.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/69#issuecomment-78178434
> >
> > > .
> > >
> >
> >
> > --
> > Snet from Gmail Mobile
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/69#issuecomment-78178573
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/69#issuecomment-78178742>
> .
>


-- 
Snet from Gmail Mobile

**Comment by christocracy** [comment]
Looks like Heroku enables ssl for all apps.  I can probably change my URL
to https and voila.  Will do that once I return from vacation this weekend.
Thanks again.


On Tuesday, March 10, 2015, Chris Scott <christocracy@gmail.com> wrote:

> Thanks, I'll see what I can do.
>
> On Tuesday, March 10, 2015, darrenahunter <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> understand but the page in not https so people will have concerns putting
>> up a credit card I think
>>
>>
>> > On 11 Mar 2015, at 11:33 am, Chris Scott <notifications@github.com>
>> wrote:
>> >
>> > It's via Stripe. The request to Stripe is via http, which merely
>> returns a
>> > token.
>> >
>> >
>> > On Tuesday, March 10, 2015, darrenahunter <notifications@github.com>
>> wrote:
>> >
>> > > hey Chris your premium plugin is taking credit card trans not over
>> HTTPS
>> > >
>> > >
>> > > > On 7 Mar 2015, at 10:42 pm, Chris Scott <notifications@github.com
>> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>> > > >
>> > > > Closed #69 <
>> > >
>> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/69
>> > > >.
>> > > >
>> > > > —
>> > > > Reply to this email directly or view it on GitHub <
>> > >
>> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/69#event-247976247
>> > > >.
>> > > >
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <
>> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/69#issuecomment-78178434
>> >
>> > > .
>> > >
>> >
>> >
>> > --
>> > Snet from Gmail Mobile
>> > —
>> > Reply to this email directly or view it on GitHub <
>> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/69#issuecomment-78178573
>> >.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/69#issuecomment-78178742>
>> .
>>
>
>
> --
> Snet from Gmail Mobile
>


-- 
Snet from Gmail Mobile

**Comment by christocracy** [comment]
That should do it.

https://cedar-transistor.herokuapp.com/checkout/cordova-background-geolocation

On Tuesday, March 10, 2015, Chris Scott <christocracy@gmail.com> wrote:

> Looks like Heroku enables ssl for all apps.  I can probably change my URL
> to https and voila.  Will do that once I return from vacation this weekend.
> Thanks again.
>
>
> On Tuesday, March 10, 2015, Chris Scott <christocracy@gmail.com
> <javascript:_e(%7B%7D,'cvml','christocracy@gmail.com');>> wrote:
>
>> Thanks, I'll see what I can do.
>>
>> On Tuesday, March 10, 2015, darrenahunter <notifications@github.com>
>> wrote:
>>
>>> understand but the page in not https so people will have concerns
>>> putting up a credit card I think
>>>
>>>
>>> > On 11 Mar 2015, at 11:33 am, Chris Scott <notifications@github.com>
>>> wrote:
>>> >
>>> > It's via Stripe. The request to Stripe is via http, which merely
>>> returns a
>>> > token.
>>> >
>>> >
>>> > On Tuesday, March 10, 2015, darrenahunter <notifications@github.com>
>>> wrote:
>>> >
>>> > > hey Chris your premium plugin is taking credit card trans not over
>>> HTTPS
>>> > >
>>> > >
>>> > > > On 7 Mar 2015, at 10:42 pm, Chris Scott <notifications@github.com
>>> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>>> > > >
>>> > > > Closed #69 <
>>> > >
>>> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/69
>>> > > >.
>>> > > >
>>> > > > —
>>> > > > Reply to this email directly or view it on GitHub <
>>> > >
>>> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/69#event-247976247
>>> > > >.
>>> > > >
>>> > >
>>> > > —
>>> > > Reply to this email directly or view it on GitHub
>>> > > <
>>> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/69#issuecomment-78178434
>>> >
>>> > > .
>>> > >
>>> >
>>> >
>>> > --
>>> > Snet from Gmail Mobile
>>> > —
>>> > Reply to this email directly or view it on GitHub <
>>> https://github.com/christocracy/cordova-plugin-background-geolocation/issues/69#issuecomment-78178573
>>> >.
>>> >
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/69#issuecomment-78178742>
>>> .
>>>
>>
>>
>> --
>> Snet from Gmail Mobile
>>
>
>
> --
> Snet from Gmail Mobile
>


-- 
Snet from Gmail Mobile
