### ISSUE TITLE
Start background service at device boot

### ISSUE THREAD

**Issue by mikedumont** [christocracy/cordova-plugin-background-geolocation#7]
Hi christocracy,

I'm trying to build an cross-platform app (android, ios). The idea of the app is based on location awereness. I would like to receive location updates from te moment a devices boots. Is it somehow possible to make the plugins background service start on boot? 

If it's possible, can you give me an example of how to do it?

(i tried to do it with a broadcastreceiver, but somehow i don't get it to work..)

Thanks in advance!

**Comment by anaibol** [comment]
Hi, I would like to know if the service is started automatically on system startup on Android.
Thanks!
