### ISSUE TITLE
Android version compatibility

### ISSUE THREAD

**Issue by corklaassebos** [christocracy/cordova-plugin-background-geolocation#73]
Hi Chris,

Thanks for sharing this great plugin. Using it to track availability of voluntary firemen.

I am trying to make my app run on old Android devices (testing with a version 2.3.5, API lvl 10) and I noticed a dependency on API version 11 due to the use of Notification.Builder. The service crashes because of this. For reference, the crash message is:

```
java.lang.NoClassDefFoundError: android.app.Notification$Builder
at com.tenforwardconsulting.cordova.bgloc.LocationUpdateService.onStartCommand(LocationUpdateService.java:188)
```

I suggest indicating the minimum API level in the documentation. Is there a similar minimal iOS version?
Maybe you have some tips to avoid a crash on unsupported versions.

Thanks,

Cor

**Comment by christocracy** [comment]
Hi, pinging this closed thread to let you know I've refactored Android and released it as a Premium Version:
- Significantly improved battery performance.
- No more in-plugin HTTP -- plugin now executes your javascript callback, just like iOS.

http://christocracy.github.io/cordova-background-geolocation/
