### ISSUE TITLE
Android simple example

### ISSUE THREAD

**Issue by ibkhalid** [christocracy/cordova-plugin-background-geolocation#79]
Can you please share a simple example for what the server request needs to look like for Android ?

We have a PHP server script that needs to be called with some parameter
        GPS coordinates 
        Users GCM regid 

Many thanks.

**Comment by christocracy** [comment]
Android has been refactored.
- plugin no longer handles http; calls js callback (just like ios)
- much improved battery efficiency.
- no more foreground service

http://christocracy.github.io/cordova-background-geolocation/
