### ISSUE TITLE
Feature request: start background service after reboot and even if the program is killed

### ISSUE THREAD

**Issue by marradomenico** [christocracy/cordova-plugin-background-geolocation#83]
If the service is on going there is a way to start automatically the service after the reboot of the device?
If the service is on going there is a way to not stop it even if the main program is killed?

Have you implemented these features? (on Android)

**Comment by christocracy** [comment]
Android has been refactored.
- plugin no longer handles http; calls js callback (just like ios)
- much improved battery efficiency.
- no more foreground service

http://christocracy.github.io/cordova-background-geolocation/
