### ISSUE TITLE
Empty POST request on cordova 4.0.0 android 4.4.2

### ISSUE THREAD

**Issue by vitrus** [christocracy/cordova-plugin-background-geolocation#95]
I installed christocracy background-geolocation plugin in my Cordova 4.0.0 project and when I got it working my scripts on the web (php application) was receiving empty post requests from the app.

After some digging and testing I made some changes to the LocationUpdateService.java (basically changed the StringEntity to a UrlEncodedFormEntity. And got it all working. I am curious if other people with the same configuration are experiencing the same problems and if so, if anyone would be interested in my solution (or has a better solution).

**Comment by christocracy** [comment]
Android refactored in Premium Version
- No more in-plugin HTTP -- plugin calls your javascript callback just like iOS
- Significantly improved battery performance.

http://christocracy.github.io/cordova-background-geolocation/
