### ISSUE TITLE
PhoneGap Build callbackFn only called once (iOS 7.1.1)

### ISSUE THREAD

**Issue by dnmd** [christocracy/cordova-plugin-background-geolocation#97]
It might be that I'm missing something essential here, therefore apologies in advance :)

Using the exact example provided (readme.md) and building the application with PhoneGap Build, I noticed that the callbackFn is only called once when bgGeo.start() is initialized.

When the application is suspended to the background the callbackFn is not triggered at all. Which I verified with a counter (other suggestions are welcome but I suppose it should do the trick); incrementing for every time the callbackFn is called.
- Could PhoneGap Build be the cause for this behaviour? (Using the QR code for deployment)

```
$ phonegap create bggeo
$ phonegap add local plugin add https://github.com/christocracy/cordova-plugin-background-geolocation.git

bggeo/www/config.xml
(removed) <gap:plugin name="org.apache.cordova.geolocation" />
(added)   <gap:plugin name="org.transistorsoft.cordova.background-geolocation" version="0.3.2" />

bggeo/www/js/index.js
(added) var bgCount = 0;

        var callbackFn = function(location) {
                bgCount++;
        };

bggeo/www/index.html
(added) <button onclick="alert('callbackFn: ' + bgCount );">No. Times callbackFn</button>

$ phonegap remote build ios
```

And of course, regardless of the issue I encounter, many thanks for providing this plugin! :)

**Comment by gobisankar11** [comment]
callbackfn not fired ios 8

**Comment by christocracy** [comment]
Have tried the SampleApp?

On Saturday, April 25, 2015, gobisankar11 <notifications@github.com> wrote:

> callbackfn not fired ios 8
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/97#issuecomment-96190719>
> .
>


-- 
Snet from Gmail Mobile
