### ISSUE TITLE
Android : Update location over HTTPS

### ISSUE THREAD

**Issue by pko** [christocracy/cordova-plugin-background-geolocation#98]
Hi Chris,

Tanks for your plugin, i just begin with cordova and your work goes in a perfect way for me.

In my last try, i want to send location through https. It isn't working. Is it not permitted by your plugin or just a general limit of cordova ? 

Thx

**Comment by christocracy** [comment]
Android refactored in Premium Version.
- No more in-plugin HTTP -- calls Javascript callback just like iOS.
- Significantly improved battery performance.

http://christocracy.github.io/cordova-background-geolocation/
